### ISSUE TITLE
다음팟 플레이어 영상 광고 차단

### ISSUE THREAD

**Issue by chloelemaire** [List-KR/List-KR#1]
요즘 List KR만 적용 후 다음팟 플레이어에서 시청자가 많은 방송을 켜면
니베아 화장품 광고만 재생되는데

smr.tvpot.daum.net
vads-api.ad.daum.net
analytics.ad.daum.net
vads-api.daumkakao.com
play.kakao.com###mArticle > a.link_banner.\#live_tab\#promotion_banner:nth-child(3) > img.img_banner
play.kakao.com###mArticle > a.link_banner.\#live_tab\#promotion_banner:nth-child(3)
play.kakao.com###mArticle > a.link_banner.\#tvplus_tab\#promotion_banner:nth-child(4) > img.img_banner
play.kakao.com###mArticle > a.link_banner.\#tvplus_tab\#promotion_banner:nth-child(4)

위와같은 필터 적용시 나오지 않더군요

통합됐으면 좋겠습니다

**Comment by ptrkr** [comment]
안녕하세요, List-KR 필터에 관심을 가져 주셔서 감사합니다.

https://github.com/List-KR/List-KR/commit/1a4c5d885446038008980f6d9c527ebf47a989eb 에서 우선 대응 규칙을 추가한 상태이며 실제로 반영되기까지 약간의 시간이 소요될 수 있습니다. 대응 규칙의 정상 작동이 확인되는 경우 피드백을 남겨 주시면 감사하겠습니다.
