### ISSUE TITLE
List-KR은 Youslist 필터 모두 포함하나요?

### ISSUE THREAD

**Issue by mongmeow** [List-KR/List-KR#1]
지금 list-kr랑 youslist 병행 사용하고 있는데 list-kr이 youslist 필터 모두 포함하면 list-kr 만 켜서 쓰려고 합니다.

**Comment by ghost** [comment]
안녕하세요, List-KR이 YousList를 기반으로 제작된 것은 맞으나, YousList의 내용을 주기적으로 병합하거나 하지는 않기 때문에 필터 간 차이가 발생할 수밖에 없습니다. 타 필터의 사용 여부를 제가 결정할 수는 없기에 주로 방문하시는 웹 사이트 등지의 광고를 어느 필터가 더 잘 차단하고 있는지 등을 판단해 선택하시는 게 좋아 보입니다.

**Comment by ghost** [comment]
일정 기간 동안 활동이 없어 이슈 닫습니다.
