### ISSUE TITLE
뉴토끼 차단 필터 제공합니다.

### ISSUE THREAD

**Issue by sokolwalela** [List-KR/List-KR#10]
3초 후에 애드블록 감지 스크립트 동작하길래 그것도 막았습니다.

! 2019. 9. 11. https://newtoki24.net
newtoki24.net##.board-tail-banner
newtoki24.net##.basic-banner.row.row-10
newtoki24.net##+js(setTimeout-defuser.js, (), 3000)

**Comment by ghost** [comment]
https://github.com/List-KR/List-KR/commit/563cb9f283dcc227f5db08b7eb332107093a1611 커밋에서 일부 업데이트 하였습니다.

List-KR 필터에 관심을 가져 주셔서 감사합니다 :)
