### ISSUE TITLE
||ssl.pstatic.net/sstatic/sdyn*

### ISSUE THREAD

**Issue by Mo-norn** [List-KR/List-KR#104]
||ssl.pstatic.net/sstatic/sdyn* 

네이버 이미지 검색 불가

**Comment by ghost** [comment]
본 이슈를 언급한 커밋에서 각각 수정하였습니다. 반영 시까지 시간이 소요될 수 있으니 임시로 해당 규칙 제거한 후 이용 부탁드립니다. 이용에 불편을 드려 죄송합니다.
