### ISSUE TITLE
[AD] 카카오톡에서 광고가 계속 보여요.

### ISSUE THREAD

**Issue by ILIKECHICKENTOOMUCH** [List-KR/List-KR#106]
## 광고 제보
* **문제가 되는 URL**:   카카오톡 메신저 최신버전 9.0.6
* **URL에서 문제가 되는 요소**:  메신저내에서 상단 광고 노출
* **확인 가능한 스크린샷 (옵션)**:  
<img src=https://i.imgur.com/veIawbq.jpg>

메신저 이전 버전에서는 광고 차단이 잘 이루어지다, 9.0.6 버전업 되면서부터 차단이 안 되네요.

## 시스템 환경
* **사용 중인 기기**:  데스크탑 & 갤럭시 S20
* **사용 중인 브라우저**:  엣지 & 크롬 & 웨일
* **구독 중인 필터**:  List-KR

**Comment by ghost** [comment]
해당 이미지는 외부 요청이 아닌 카카오톡 내부에 직접 삽입되어 있어 필터링이 불가합니다.
