### ISSUE TITLE
daum.net incorrect blocking

### ISSUE THREAD

**Issue by Sergey-Lyapin** [List-KR/List-KR#107]
Numbers of search pages are blocked with List-KR, the problem is caused by this rule:
`||search1.daumcdn.net/search/statics/common/js/log*`

Original issue with screenshots:
https://github.com/AdguardTeam/AdguardFilters/issues/65966

**Comment by ghost** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/65966
