### ISSUE TITLE
||cafe.naver.com/static/js/*/common/bastat/ScriptBAStatLog*

### ISSUE THREAD

**Issue by Mo-norn** [List-KR/List-KR#109]
![11Screenshot 2020-10-22 at 21 32 17](https://user-images.githubusercontent.com/34658160/96873629-2c011480-14b0-11eb-8f14-66faea00af84.jpg)

||cafe.naver.com/static/js/*/common/bastat/ScriptBAStatLog*
네이버 내소식 안보이는 현상

그런데 대형 사이트 차단하실때는 조금 더 신중하게 해주시면 안되나요? 은근 스트레스입니다.  
네이버 다음등 대형 사이트들은 유기적으로 얽혀있어서 광범위하게 차단하면 안보이는곳에 문제가 발생하더라고요.
대형 사이트들은 딱 필요한 부분만 차단해주셨으면 좋겠습니다.

**Comment by ghost** [comment]
https://github.com/List-KR/List-KR/commit/bbfbcccefdfcedcecc678f725f2e6d8b2790819c 커밋에서 업데이트 하였습니다. 이용에 불편을 드려 죄송합니다.
