### ISSUE TITLE
onair.imbc.com 광고제거

### ISSUE THREAD

**Issue by himawarihome** [List-KR/List-KR#116]
MBC 온에어가 flash에서 변경되었습니다
||smrmembers-smr.smartmediarep.com/smc/smrmembers/$domain=~allvod.sbs.co.kr|~news.sbs.co.kr|~news.tvchosun.com|~play-tv.kakao.com|~programs.sbs.co.kr
여기서 onair.imbc.com 제외해주고 
||smrmembers-smr.smartmediarep.com/smc/smrmembers/*$redirect=noopmp4-1s,media,domain=onair.imbc.com
이렇게 하면 될거 같습니다
감사합니다

**Comment by jiyongwoo** [comment]
$redirect쓰면 안되나보군요

**Comment by seyoon20087** [comment]
issues에 넣지 마시고 pull request를 만들어주세요.
