### ISSUE TITLE
 m.comic.naver.com [Incorrect blocking]

### ISSUE THREAD

**Issue by zloyden** [List-KR/List-KR#119]
Hello!
The website `m.comic.naver.com/webtoon/weekday.nhn` becomes unresponsive on Samsung Internet (and Yandex Browser) when using the List-KR filter in Adguard.
It's caused by these rules:
```
m.comic.naver.com###migrationPopup
m.comic.naver.com##.bg
m.comic.naver.com##div.ly_dim
```

I added a temporary solution to our filters https://github.com/AdguardTeam/AdguardFilters/commit/01275f85fb155b854e9922a33af72b128eeaf12a, but it will be nice, if you resolve it directly. I offer to remove them from `List-KR`.

**Comment by ghost** [comment]
Hello! I've deployed a patch commit (https://github.com/List-KR/List-KR/commit/fa0c734daaa5c66f4a471d901699c0a0cf09cb12) for fix this problem. Thank you for your report!
