### ISSUE TITLE
네이버 상품검색시 AiTEMS 광고차단 불가

### ISSUE THREAD

**Issue by akranrkso** [List-KR/List-KR#12]
안드로이드폰에서 네이버 상품검색시에 AiTEMS 광고가 나옵니다.

발생되는 방식은 2종류로 나옵니다.

1) 네이버 검색창에서 상품검색시 종합검색창에서 상품들 바로 아래쪽 AiTEMS 광고 발생

----> m.search.naver.com###ct > section.sc.sp_nshop._prs_shp_tli._nshopping_guideview:nth-child(7) > div.api_subject_bx._au_reactive:nth-child(3)

----> m.search.naver.com###ct > section.sc.sp_nshop._prs_shp_lis._nshopping_guideview:nth-child(5) > div.api_subject_bx._au_reactive:nth-child(3)

2) 상품검색창 "쇼핑 더 보기" 로 클릭하여 상품목록 중 하나의 상품을 해당쇼핑몰에서

보고 난 후 페이지 뒤로가기로 상품목록으로 돌아오면 구경한 상품의 바로 아래쪽에

AiTEMS 광고가 발생

----> msearch.shopping.naver.com###_sr_lst_81935902202 > div.fem1Lz0-5c.android:last-child

**Comment by ghost** [comment]
안녕하세요, https://github.com/List-KR/List-KR/commit/3bc32492c965010eb8bcc8b45bb44254df265e81 커밋에서 일부 규칙을 업데이트 하였습니다. 필터 업데이트 후 실질 반영까지는 약 3~4시간 정도가 소요될 수 있으니 참고 부탁드립니다.

List-KR 필터 개발에 관심을 가져 주셔서 감사합니다 :)

**Comment by ghost** [comment]
추가 제보가 없어 해결된 것으로 판단하고 종결 처리합니다.
