### ISSUE TITLE
m.comic.naver.com 

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#120]
When i visit [m.comic.naver.com/webtoon/weekday.nhn](https://m.comic.naver.com/webtoon/weekday.nhn) on [org.mozilla.firefox_beta](https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta) and Firefox Windows, they display it like under pictures.
I think it is appeared by List-KR/List-KR@fa0c734daaa5c66f4a471d901699c0a0cf09cb12.
But List-KR/List-KR@bb3f88dad01ee027c0f845fda87a834f3bc9cb9, which was created by me, generated List-KR/List-KR#119.
So, i suggest under filter rules.
```
m.comic.naver.com##body>div#ly_dim>div.bg
m.comic.naver.com##body>div#ly_dim
```
![20201121_060022](https://user-images.githubusercontent.com/37463155/99869495-53d4bc80-2bc3-11eb-8ef6-35b398952932.jpg)
![jj](https://user-images.githubusercontent.com/37463155/99869573-1cb2db00-2bc4-11eb-84b5-3aeb9033e6fe.png)

**Comment by ghost** [comment]
Please see this issue.
@L4by @zloyden

**Comment by ghost** [comment]
AdguardTeam/AdguardFilters#68219

**Comment by zloyden** [comment]
According to [this issue](https://github.com/List-KR/List-KR/issues/119), can you check it on Samsung Internet browser via AdGuard  Content Blocker?
For me it doesn't help, I guess that we should unblock this image `ssl.pstatic.net/static/m/comic/im/promo/popup_cloud.png` https://github.com/AdguardTeam/AdguardFilters/commit/d358634e30d934a15efcfe6a740a917560f0ab3d.

**Comment by ghost** [comment]
> 
> 
> According to [this issue](https://github.com/List-KR/List-KR/issues/119), can you check it on Samsung Internet browser via AdGuard Content Blocker?
> For me it doesn't help, I guess that we should unblock this image `ssl.pstatic.net/static/m/comic/im/promo/popup_cloud.png` [AdguardTeam/AdguardFilters@d358634](https://github.com/AdguardTeam/AdguardFilters/commit/d358634e30d934a15efcfe6a740a917560f0ab3d).

OK. I checked it on  Samsung Internet browser via AdGuard Content Blocker.
I tried to block them as possible, but i could not block them.
Hmm... I suggest under code.
```
!#if (!adguard_ext_android_cb && !adguard_app_ios)
||ssl.pstatic.net/static/m/comic/im/promo/popup_cloud.png
m.comic.naver.com##body>div#ly_dim>div.bg
m.comic.naver.com##body>div#ly_dim
!#endif
```

**Comment by zloyden** [comment]
Thanks for your reply, I fixed it in AdGuard filters. The update should be available in 1-2 hours.
You can notice, that I left an exception `@@||ssl.pstatic.net/static/m/comic/im/promo/popup_cloud.png` for content blockers. It's a temporary solution until it is removed from `List-KR`.

**Comment by ghost** [comment]
https://github.com/List-KR/List-KR/commit/ee7b5903336f08d0f52714fbe8766e765fe104ef will fix this issue. Thank you for reporting!
