### ISSUE TITLE
tgd.kr 게시글 이미지 안뜨는 오류(?) 수정

### ISSUE THREAD

**Issue by NenkaLab** [List-KR/List-KR#127]
@@||upload.tgd.kr^
@@||cdn-assets.tgd.kr^
@@||placehold.it^

**Comment by ghost** [comment]
Hi, @NenkaLab.  Cloud you please give me reproducible URL?

**Comment by piquark6046** [comment]
It seems that your issue is related to https://github.com/AdguardTeam/AdguardFilters/issues/111644#issuecomment-1055500288.
