### ISSUE TITLE
orbi.kr [Incorrect blocking]

### ISSUE THREAD

**Issue by Alex-302** [List-KR/List-KR#13]
<details><summary>Screenshot:</summary> 

![image](https://user-images.githubusercontent.com/8361299/65605837-73b62380-dfb2-11e9-89d4-dfae0620c320.png)

 </details>

Caused by `orbi.kr##div#top_banner_area`

Possible fix `orbi.kr#$#.global-top { top: 0 !important; }`

**Comment by ghost** [comment]
Fixed at https://github.com/List-KR/List-KR/commit/39a9fcc1e65edc09096d4d891ca04ae0e06f97ec. Thanks for reporting!

**Comment by Alex-302** [comment]
@L4by 
ad is visible now
![image](https://user-images.githubusercontent.com/8361299/65684772-22b53680-e069-11e9-817a-e9430eef57aa.png)
can be blocked by `orbi.kr#$#div#top_banner_area { display: none !important; }` (`#$#` - to prevent incorrect blocking by content-blockers for iOS, which does not support `#$#` rules)

**Comment by ghost** [comment]
Added at https://github.com/List-KR/List-KR/commit/4f3f0fbb3c60cb89e2f3f4f19e45332ea1f9775b. If this issue still persists, please reopen this issue. thanks :)

**Comment by Alex-302** [comment]
Now is search bar and menu are hidden when you scroll the page:(
With current rule after scrolling down-up:

![image](https://user-images.githubusercontent.com/8361299/65715574-071c5100-e0a6-11e9-8ce8-e24cff05b9ef.png)

with the rule below:

![image](https://user-images.githubusercontent.com/8361299/65715527-f23fbd80-e0a5-11e9-942b-1b71bad8d409.png)

Better replace by this: `orbi.kr#$#div[class="global-top animate"] { top: 0 !important; }`
A padding at the top will disappear when you scroll the page.

I hope this is the final solution:)
