### ISSUE TITLE
[AD] 네이버 특정 까페에서만 나오는 광고

### ISSUE THREAD

**Issue by otobi** [List-KR/List-KR#133]
## 광고 제보
* **문제가 되는 URL**:  https://m.cafe.naver.com/ca-fe/web/cafes/28497937/articles/159862?fromList=true
* **URL에서 문제가 되는 요소**: 광고 노출
* **확인 가능한 스크린샷 (옵션)**: 

## 시스템 환경
* **사용 중인 기기**:  windows 10
* **사용 중인 브라우저**: 마소 엣지
* **구독 중인 필터**: lisk-kr

**Comment by otobi** [comment]
크롬 개발자모드에서 찾아보니 
////  <div data-v-272df92a="" class="banner_add bottom"><a href="https://cafe.naver.com/rainup/2398236"><span class="banner_inner"><img src="https://cafeptthumb-phinf.pstatic.net/MjAyMTAxMTVfMjU0/MDAxNjEwNzAwMjg4NDA4.Gc5ivyFhwtmGpAfdIXbqbiijWeSWrJxVjaYvqtC3K80g.HE_f3XR4l5K8Cm8WwWzY75rLpQfV-Alb7vhrHIkLRqUg.JPEG/KakaoTalk_20210115_115458796.jpg?type=f1480_240_banner" alt="매니저 등록 배너"></span></a></div>   ///

에서 광고가 나옵니다.

**Comment by ghost** [comment]
https://github.com/List-KR/List-KR/commit/ccf2d2c31ecf94ca93684511b7d07465a4eba9c5 커밋에서 업데이트 되었습니다.
