### ISSUE TITLE
[AD] 애니 365 PC 버전 사례 신고

### ISSUE THREAD

**Issue by 115dkk** [List-KR/List-KR#136]
## 광고 제보
* **문제가 되는 URL**: https://www.ani365.org/kr
* **URL에서 문제가 되는 요소**: (광고 노출/잘못된 차단 등..) 양 엎으로 광고 노출중
* **확인 가능한 스크린샷 (옵션)**: 
![image](https://user-images.githubusercontent.com/33408534/103161833-2d8de680-482b-11eb-9d5e-7d552db62564.png)

## 시스템 환경
* **사용 중인 기기**: 
![image](https://user-images.githubusercontent.com/33408534/103161837-557d4a00-482b-11eb-85cb-0d39d71167e7.png)

* **사용 중인 브라우저**: 
![image](https://user-images.githubusercontent.com/33408534/103161839-6332cf80-482b-11eb-816f-519f73eef3d3.png)

* **구독 중인 필터**:
![image](https://user-images.githubusercontent.com/33408534/103161867-c58bd000-482b-11eb-9700-e708fea72232.png)
![image](https://user-images.githubusercontent.com/33408534/103161876-d9cfcd00-482b-11eb-9d98-0445b98abff1.png)

**Comment by ghost** [comment]
It is already fixed by AdguardTeam/AdguardFilters@69dd425449e1748118102bbdccab21bedc61518a (AdguardTeam/AdguardFilters#69935).

**Comment by 115dkk** [comment]
해당 현상 여전히 반복되고 있습니다. List-KR 버전 2.0.3.44, 2020-12-28일 버전입니다.

원래대로라면 차단되어야 하는데 차단되지 않고 있다면, 광고 차단을 회피하는 코드가 숨어있는 거 아닌가 싶기도 합니다. 알못이라 자세히는 모르겠지만요.

**Comment by ghost** [comment]
해당 현상이 재현되지 않습니다. 필터를 업데이트하신 후 다시 시도해주시기 바랍니다.

**Comment by 115dkk** [comment]
![image](https://user-images.githubusercontent.com/33408534/103437509-d1342800-4c6b-11eb-9764-385dd48b0b5d.png)
그대로입니다.
![image](https://user-images.githubusercontent.com/33408534/103437521-e741e880-4c6b-11eb-839d-cc7d7ba8167b.png)
보다시피 필터도 업데이트 된 상태입니다. 재현을 위해 기존 파이어폭스에 비해 변경된 설정 일부를 가져와야 할까요?

**Comment by 115dkk** [comment]
파이어폭스가 순정에 대해 다음의 설정이 변경된 상태입니다. 참고로 엣지에서는 정상적으로 차단이 되는 것이 확인됩니다.
![image](https://user-images.githubusercontent.com/33408534/103437537-2839fd00-4c6c-11eb-947e-ccc96989d939.png)
![image](https://user-images.githubusercontent.com/33408534/103437544-3a1ba000-4c6c-11eb-9ab0-bf5f89662932.png)
![image](https://user-images.githubusercontent.com/33408534/103437550-4273db00-4c6c-11eb-9ef0-ff27e8bd171c.png)
![image](https://user-images.githubusercontent.com/33408534/103437554-4c95d980-4c6c-11eb-9e1f-ed5f150a9ac7.png)

만약 단순히 파이어폭스 설정으로 인해 문제가 되는 것이 확실하다면 이슈를 닫으셔도 될 것이라 생각합니다.

**Comment by ghost** [comment]
eSNI 적용 시 차단이 되지 않는 문제는 필터가 아닌 AdGuard 자체의 문제입니다. AdGuard 개발진에게 문의해주셔야 할 부분으로 보입니다.
