### ISSUE TITLE
w17.leadership14.site [Ads]

### ISSUE THREAD

**Issue by Alex-302** [List-KR/List-KR#14]
### Issue URL (Anti Adblock Script)
[https://w17.leadership14.site/bbs/board.php?bo_table=notice](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fw17.leadership14.site%2Fbbs%2Fboard.php%3Fbo_table%3Dnotice)
### Comment
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/AUQhQpa.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard version: | 3.2.1
Browser: | Chrome
Filters: | Filter unblocking search ads and self-promotion,<br>AdGuard Base,<br>List-KR

Not sure ads it or annoyance widget, but these elements are not shown on my end(I see request to kingjjal.com)

**Comment by ghost** [comment]
Fixed at https://github.com/List-KR/List-KR/commit/bc10f62ebd326b352ba1873e1b4e2a1fc2c855ed. Thanks for reporting!
