### ISSUE TITLE
Question: natch를 사용하면 필터링이 안됩니다

### ISSUE THREAD

**Issue by shms1000** [List-KR/List-KR#143]
## 시스템 환경 : 윈도우10 프로 64비트
* **사용 중인 기기**: PC
* **사용 중인 브라우저**: 크롬
* **구독 중인 필터**: ADGuard

중국 거주 중이라 Natch를 사용하는데 이거만 켰다하면
필터링이 안됩니다.

다른 vpn 프로그램은 켜도 필터링이 되던데 유독 이것만 안되네요

해결방법 아시는 분 계실까요?

**Comment by ghost** [comment]
안녕하세요, 필터링이 안 되는 문제는 보통 다음의 이유로 인해 발생합니다:

- ESNI 사용
- 데이터 세이버 사용
- 기타 연결 필터링에 방해가 되는 부가 기능의 사용

상기 문제는 Adguard 자체의 기술적 문제이므로 필터 단에서 해결할 수 없으며, Adguard 개발팀에 문의하는 것이 유일한 방법입니다.
