### ISSUE TITLE
에브리타임 앱 광고 미차단

### ISSUE THREAD

**Issue by joyfuI** [List-KR/List-KR#15]
안녕하세요. 안드로이드에서 애드가드를 사용하고 있습니다.
[에브리타임](https://play.google.com/store/apps/details?id=com.everytime.v2)이라는 대학생 앱이 있는데요.
게시판에 들어갈때 앱 하단에 광고가 나타나는데 현재 차단이 되어 있지 않습니다.

`||ad.everytime.kr^$app=com.everytime.v2`

일단 저는 요 필터를 추가해서 차단하고 있습니다.

**Comment by ghost** [comment]
안녕하세요. https://github.com/List-KR/List-KR/commit/4787146a61f29625c4723b68f1fc717416e48579 커밋에서 해당 규칙을 업데이트 하였습니다. 실 적용 시까지 약 3~4시간 정도가 소요될 수 있으니 참고 부탁드립니다.

List-KR 필터 개발에 관심을 가져 주셔서 감사합니다 :)
