### ISSUE TITLE
유투브 광고 차단이 되지 않습니다.

### ISSUE THREAD

**Issue by yujgewt** [List-KR/List-KR#17]
제목 그대로 유투브 광고 차단이 되질 않네요.

**Comment by ghost** [comment]
안녕하세요, YouTube 공식 애플리케이션의 광고 차단은 AdGuard 차단 방식의 기술적 한계로 [YouTube Vanced](https://vanced.app) 등 서드파티 애플리케이션을 통해 진행하여야 합니다. 본 필터의 문제가 아니기 때문에 본 이슈는 `invalid` 처리되는 점 양해 부탁드립니다.

List-KR 필터 개발에 관심을 가져 주셔서 감사합니다 :)
