### ISSUE TITLE
tgd.kr 차단 오류

### ISSUE THREAD

**Issue by asteriskyg** [List-KR/List-KR#179]
tgd.kr 에서 리스트 글이 하나 사라지는 오류가 있습니다.
`tgd.kr###article-list-category + div` `tgd.kr$$div[style="padding:0em 1em;"]` 필터를 해제하면 문제가 해결됩니다.

![image](https://user-images.githubusercontent.com/25531016/116802588-cf616f00-ab4e-11eb-8bfd-d4c032698d66.png)
(정상)

![image](https://user-images.githubusercontent.com/25531016/116802656-69291c00-ab4f-11eb-8d72-f9cc7b9a6044.png)
(필터 적용시)

**Comment by ghost** [comment]
#180 PR에서 해결되었습니다.
