### ISSUE TITLE
cafe.naver.com [Incorrect Blocking]

### ISSUE THREAD

**Issue by zloyden** [List-KR/List-KR#18]
On this site https://cafe.naver.com/inmacbook iframe didn't show up in Safari because of that rule `cafe.naver.com,m.etnews.com,ptware.net,snulife.com#$#* { -webkit-touch-callout: auto!important; -webkit-user-select: auto!important; -moz-user-select: auto!important;}`.
Original report https://github.com/AdguardTeam/AdguardFilters/issues/42350.
Possible fix is remove domain from that rule.
<details><summary>Screenshot:</summary>

![safari_kr](https://user-images.githubusercontent.com/33488229/66814608-90090880-ef3f-11e9-90de-3e080c449def.png)
</details><br/>

**Comment by ghost** [comment]
Fixed at https://github.com/List-KR/List-KR/commit/946f62d8a2c32ffc0e54edcae7527d5696805acb. Thanks for reporting!
