### ISSUE TITLE
[AD] 모바일 카카오톡 뉴스 등의 광고 차단이 이루어지지 않고 있습니다.

### ISSUE THREAD

**Issue by iamJason-Han** [List-KR/List-KR#183]
## 광고 제보
* **문제가 되는 URL**:  https://v.kakao.com/v/20210607203507870 (이뿐 아닌 모든 https://v.kakao.com/v/ 형태의 URL)
* **URL에서 문제가 되는 요소**: 광고 노출
* **확인 가능한 스크린샷 (옵션)**: 
![KakaoTalk_01](https://user-images.githubusercontent.com/48706968/121037085-227faf00-c7ea-11eb-9278-c78f45852c60.jpg)
상단에 보이는 배너광고
![KakaoTalk_02](https://user-images.githubusercontent.com/48706968/121037116-29a6bd00-c7ea-11eb-9263-07b9f41279b4.jpg)
본문 중간의 광고
![KakaoTalk_03](https://user-images.githubusercontent.com/48706968/121037262-44793180-c7ea-11eb-9fa6-91ff7a0d6f77.jpg)
본문 하단의 광고
![KakaoTalk_04](https://user-images.githubusercontent.com/48706968/121037282-4b07a900-c7ea-11eb-88b1-708d00523dac.jpg)
댓글창 아래의 배너광고
![KakaoTalk_05](https://user-images.githubusercontent.com/48706968/121037322-522eb700-c7ea-11eb-9e12-83348746fe26.jpg)
카카오톡 #에 들어갔을 때 상단에 뜨는 광고 (첫 번째 스크린샷과 같은 url 추청)

## 시스템 환경
* **사용 중인 기기**:  LG X5 (  LM-X510 )
* **사용 중인 브라우저**: 카카오톡 내의 웹뷰?
* **구독 중인 필터**: List-KR

**Comment by seyoon20087** [comment]
다음과 같은 규칙을 사용자 필터에 추가해보세요
```txt
||ad.daum.net^$important
```
제가 보기로는 상기 필터가 광고 차단이 잘 된다고 보고 있습니다.

**Comment by ghost** [comment]
안녕하세요, `v.kakao.com` 페이지의 광고를 차단하기 위한 규칙은 이미 필터에 삽입되어 있습니다. 그러나 카카오톡 웹뷰의 광고 차단이 Android 시스템 보안 정책 상 불가한 것으로 확인됩니다. 원하는 답변을 드리지 못해 죄송합니다.
