### ISSUE TITLE
나무위키뷰어 앱 파워링크 광고 차단

### ISSUE THREAD

**Issue by joyfuI** [List-KR/List-KR#19]
테스트해봤는데 여전히 차단이 안됩니다.
필터링 로그에는 `external.impression-neo.naver.com`라고만 뜨는 걸로 봐선(필터링에 걸리지 않음) 도메인을 통째로 차단해야할 듯 싶습니다.

_Originally posted by @joyfuI in https://github.com/List-KR/List-KR/issues/16#issuecomment-544077623_

**Comment by ghost** [comment]
안녕하세요. https://github.com/List-KR/List-KR/commit/95a18764180bf45caa0880ef12a8d22bdd272d4a 커밋에서 해당 규칙을 업데이트 하였습니다. 실 적용 시까지 약 3~4시간 정도가 소요될 수 있으니 참고 부탁드립니다.

List-KR 필터 개발에 관심을 가져 주셔서 감사합니다 :)
