### ISSUE TITLE
[Tracker] datadive 사용자 추적 트래커

### ISSUE THREAD

**Issue by miyu4u** [List-KR/List-KR#198]
## 광고 제보
* **문제가 되는 URL**: 

static.datadive.ai

* **URL에서 문제가 되는 요소**: (광고 노출/잘못된 차단 등..)

사용자 추적용 트래커 차단 룰 추가

* **확인 가능한 스크린샷 (옵션)**: 

## 시스템 환경
* **사용 중인 기기**: 
* macos
* **사용 중인 브라우저**: 
* chrome, safari,
* **구독 중인 필터**:
* list-KR

**Comment by ghost** [comment]
Hi. Cloud you please give me reproducible URL?

**Comment by miyu4u** [comment]
(.*?).datadive.ai

> Hi. Cloud you please give me reproducible URL?

---

maybe it could be `^((https?:)?\/\/)?static\.datadive\.ai(\/.*?)?$` (regex)

Sorry I'm not skillful for adguard filter syntax.

I'm using this only to prevent try to get tracker js file.

how to do i will contribute to filter list?

**Comment by ghost** [comment]
You can learn AdGuard filter syntax at the following resources.
- https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters
- https://github.com/adguardteam/scriptlets

Unfortunately, the maintainers of List-KR decided what List-KR no longer support blocking tracking, annoyances, etc.  ([Related Discussion](https://github.com/List-KR/List-KR/discussions/199))
Please contribute SpywareFilter of [AdguardTeam/AdguardFilters ](https://github.com/AdguardTeam/AdguardFilters).
