### ISSUE TITLE
blockMouseRight() 이슈

### ISSUE THREAD

**Issue by Mo-norn** [List-KR/List-KR#2]
cafe.naver.com$$script[tag-content="blockMouseRight();"]

카페 접속멤버와 일부 댓글들이 제대로 작동하지 않습니다.
애초에 tag-content 를 사용하면 blockMouseRight() 스크립트 전부 차단되는지라 다른 방법으로 부탁합니다.

**Comment by ghost** [comment]
테스트 커밋을 그냥 올려버렸네요. https://github.com/List-KR/List-KR/commit/b66d5d27f2ae521fe4517fbdb51818806c60c621 커밋에서 업데이트 하였습니다. Adguard 사용 중이신 경우 반영까지 시간이 소요될 수 있으니 약 3~4시간 정도 후에 재확인 부탁드립니다. 불편을 드려 죄송합니다.
