### ISSUE TITLE
Websites protected by Ad-Shield

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#202]
## Moved to https://github.com/List-KR/List-KR/issues/269 because List-KR has blocked Ad-Shield advertisement successfully.

**Comment by shadow-b1ock** [comment]
FYI, current AdGuard Extra (1.0.319) does not work on `ygosu.com` and `ppss.kr`. These websites are known to be self-sabotaging when adblock is detected, and current AdGuard Extra triggers it.

**Comment by piquark6046** [comment]
If you want to report the mentioned issue, please go to https://github.com/List-KR/List-KR-Script/issues/new/choose.

**Comment by piquark6046** [comment]
If you want to report a mentioned issue, please go to https://github.com/List-KR/List-KR-Script/issues/new/choose.

**Comment by seia-soto** [comment]
@piquark6046 I would like to import the rule from my PR on YousList to List-KR too. But I am still postponing it due to #234 because of its side-effect. May I get the schedule when to create PR or commit, so you can work in clean state?

- https://github.com/yous/YousList/pull/212

**Comment by piquark6046** [comment]
@seia-soto No problem. I will merge #234 soon.

**Comment by seia-soto** [comment]
Seems like replacing 'setInterval' function with true-function is preventing adshield to show ads without any layout shifts or content breaks unless the site uses 'setInterval'.

Tested on Ygosu and Tgd, PPSS. But on inven, there are elements failed to show properly when we prevent setInterval.

**Comment by seia-soto** [comment]
Not a complete solution to adshield as 'setInterval' and 'clearInterval' is easy to replace with iterations and AbortController.

**Comment by seia-soto** [comment]
Update on tgd.kr: seems like they removed adshield from their website.
