### ISSUE TITLE
사이트 내용 안보임

### ISSUE THREAD

**Issue by unknownpu** [List-KR/List-KR#203]
## 광고 제보
* **문제가 되는 URL**:  
사이트내 기사 클릭시 모든 기사 내용이 안보입니다.
예) https://www.chosun.com/international/international_general/2021/09/26/TT2HMMIQQVFNXFIV57H4RVJOCA/
chosun.com#?#div.raw-html > div iframe[src*="//adex.ednplus.com/"]:upward(5) 필터 해제시 정상적으로 보입니다.

* **URL에서 문제가 되는 요소**: 
기사내용이 안보입니다.

## 시스템 환경
* **사용 중인 기기**:  PC

**Comment by ghost** [comment]
https://github.com/List-KR/List-KR/commit/5041d0c5526c5bdc9accb4609e3ed04debb35278
It is already resolved.
Please update List-KR.
