### ISSUE TITLE
Blocking cxense.com in tn.com.ar breaks functionality

### ISSUE THREAD

**Issue by rndmUsr678** [List-KR/List-KR#208]
if you visit an article in the website, for example this one: https://tn.com.ar/deportes/futbol/2021/11/14/oscar-lopez-turitich-el-heroe-olvidado-perdio-la-pierna-a-causa-de-la-diabetes-y-hoy-lo-mantienen-sus-excompaneros-de-river/, at the bottom of the page, the images are broken, due to the rules that block _cxense.com_

Screenshot showing the broken images:

![Screen Shot 2021-11-14 at 07 29 27](https://user-images.githubusercontent.com/94295285/141680244-30e09d3d-c830-4cad-8677-79b2c659429b.png)

**Comment by ghost** [comment]
@rndmUsr678 
Cloud you please give me the list of subscribed filters?

**Comment by ghost** [comment]
Hello. I'm using AdGuard Base filter.

**Comment by ghost** [comment]
Only AdGuard Base? @rndmUsr678

**Comment by ghost** [comment]
Alongside List-KR. I only use AdGuard Base because I heard it already contains EasyList

**Comment by ghost** [comment]
Fetched. https://github.com/List-KR/List-KR/commit/bb02d7cf1fd6fcc185242053bbcb69c44878f802
