### ISSUE TITLE
AD: map.kakao.com 좌측 검색결과 리스트 중간중간 intrusive ad의 element hiding

### ISSUE THREAD

**Issue by inodez** [List-KR/List-KR#209]
### URL

http://kko.to/_sAkOISGe

### FILTERS

AdGuard 베이스필터
AdGuard 추적 보호 필터
AdGuard 실험 필터
List-KR
http://in0de.synology.me/pwn.txt
http://in0de.synology.me/own.txt

### Browser

Mozilla Firefox 95.0.2
Windows 10 21H2 (b19044.1415)

### Ad-Blocker

AdGuard for Windows 7.9 nightly 3

### Comment

먼저, List-kr에 map.kakao.com 관련된 필터는 아직 없는 듯 합니다.

카카오맵에서 임의의 POI를 검색하고 나면 결과 리스트가 왼쪽에 나타나는데요
중간중간에 배너가 들어갑니다.
이를 Element hide해보려고 했는데 잘 되지 않아서요.

https://i.imgur.com/ybRQ3es.png

이런 시도들을 해봤지만, 여전히 노출되고 있습니다.
map.kakao.com##a.link_ad
map.kakao.com##li.AdItem
kakao.com##li[class*="AdItem"]
kakao.com##a[class*="link_ad"]

무엇을 잘못했는지 못찾겠어서 도움을 요청드려 봅니다.
감사합니다.

**Comment by ghost** [comment]
Please add the following rule into user rules and reload the website:
```
map.kakao.com##ul[id="info.search.place.list"] > li.AdItem
```

**Comment by ghost** [comment]
@inodez

**Comment by inodez** [comment]
@piquark6046
도움을 주셔서 감사합니다.
하지만, 여전히 광고가 보이고 있습니다.
혹시 직접 테스트 해보실 때는 광고 제거가 잘 되셨었습니까?

**Comment by ghost** [comment]
Yes. Clear all cache and site data on Firefox with AdGuard for Windows 7.8.
Or, disable all 3rd-party adblockers and anti-rightclick extension.
@inodez 
<details>
<summary>Screenshot</summary>

![Screenshot from 2022-01-14 16-42-35](https://user-images.githubusercontent.com/37463155/149552468-551fbc33-4806-4f65-8976-c3e966e55e15.png)

</details>

---

If you want to prevent anti-rightclick scripts on a website, please enable AdGuard Annoyances filter.
[Contributions](https://github.com/AdguardTeam/AdguardFilters/pulls?q=is%3Apr+author%3Apiquark6046+anti-drag+OR+anti-rightclick+OR+copyright-notice)

**Comment by inodez** [comment]
https://giant.gfycat.com/ClutteredKindIndianhare.mp4

@piquark6046 분명히 제 환경에 문제가 있는 것이겠지만,
어떻게 해도 제대로 차단되지 않았습니다.
컴퓨터 리부팅, 브라우저 캐시 초기화, addon 비활성화 등 생각나는 모든 방법을 다 해보았습니다.
제가 사용하고 있는 Firefox 뿐 아니라, MS Edge 에서도 광고가 차단되지 않았습니다.

혹시 동적 자바스크립트에 의해 광고가 웹페이지 로드 후에 추가되는 것은 아닐까 추측했는데
올려주셨던 스크린샷에서 광고가 잘 차단된 것을 보니
어떻게 해야할 지 전혀 모르겠습니다.

**Comment by ghost** [comment]
@inodez 
Cloud you please re-install AdGuad for Windows using [Official AdGuard Uninstaller](https://cdn.adguard.com/public/Adguard/tools/Uninstall_Utility.zip)?

**Comment by inodez** [comment]
@piquark6046 다시 AdGuard를 인스톨한 후 문제가 해결되었습니다. 이럴수가...
정말 감사합니다. :)
