### ISSUE TITLE
뉴스형식 광고 차단

### ISSUE THREAD

**Issue by hyunbridge** [List-KR/List-KR#21]
![스크린샷](https://user-images.githubusercontent.com/51025374/68393114-a9a01780-01ae-11ea-9278-76948d6eb776.png)
위 스크린샷처럼 뉴스속보 형식으로 뜨는 광고 입니다.

uBlock Origin v1.23.0 @ Microsoft Edge BETA 79.0.309.14에서 아래 필터가 정상 작동함을 확인 하였습니다.
```
||www.mediacategory.com/servlet/adNewsflashContentsBox
```

**Comment by ghost** [comment]
https://github.com/List-KR/List-KR/commit/8ed0b23fbfac23673a869a5731b11415eeac6349 커밋에서 업데이트 되었습니다. AdGuard를 사용하시는 경우 실질 적용까지 약 3~4시간 정도 소요될 수 있으니 참고 부탁드립니다.

List-KR 필터 개발에 관심을 가져 주셔서 감사합니다 :)
