### ISSUE TITLE
AD: 디씨인사이드 앱 내 파워링크 광고 차단

### ISSUE THREAD

**Issue by woofingcough** [List-KR/List-KR#211]
### URL

https://m.dcinside.com

### FILTERS

NSABlocklist
Lightswitch05 - Ads & Tracking
NextDNS Ads & Trackers Blocklist
Steven Black
YousList

### Browser

(Other)

### Ad-Blocker

(Other)

### Comment

NextDNS를 통해 디시인사이드 앱에서 광고차단을 하려고 하는데 파워링크 광고들이 계속 표시됩니다.

**Comment by woofingcough** [comment]
죄송합니다. 정확하지 않은 정보를 드렸네요. 애드블록으로는 iOS 애드가드 DNS 필터링을 사용중입니다.

**Comment by ghost** [comment]
The advertisement is transferred via `https://app.dcinside.com/api/_ad_search_link2.php`. 
However, On iOS, All web request including iOS app are filtered through DNS filtering module; therefore, AdGuard cannot block it on iOS App.

<details>
<summary>Screenshot</summary>

![Screenshot from 2022-01-18 04-58-44](https://user-images.githubusercontent.com/37463155/149873699-d3031dd2-0a20-4af4-92e2-9246b2915e5f.png)

![Screenshot](https://user-images.githubusercontent.com/37463155/149873404-315ce3c9-eb84-417f-89da-d9933f5240ae.png)
https://adguard.com/en/adguard-ios/overview.html

</details>

If you want to block them, please use web browser such as Firefox or Safari.
