### ISSUE TITLE
AD: 마나토끼

### ISSUE THREAD

**Issue by 115dkk** [List-KR/List-KR#212]
### URL

https://manatoki120.net/

### FILTERS

![화면 캡처 2022-01-20 174208](https://user-images.githubusercontent.com/33408534/150303564-58a8c202-e8a4-4d47-8f2c-8323e50c86ae.png)
![화면 캡처 2022-01-20 174222](https://user-images.githubusercontent.com/33408534/150303571-3db87ac5-26e4-49f2-b8bd-5133a3d931e2.png)

### Browser

Microsoft Edge

### Ad-Blocker

AdGuard for Windows

### Comment

![화면 캡처 2022-01-20 174317](https://user-images.githubusercontent.com/33408534/150303713-44e11c43-3ab3-40b2-aa2b-cefa3a9dc7be.png)

부탁드립니다.

**Comment by ghost** [comment]
The rules blocking the advertisements already exists.
Please the following methods:
1. Update subscribed filters.
2. Clear cache and site data of your browser.
3. Enable HTTPS filtering of AdGuard.
4. Reinstall AdGuard using [Official AdGaurd Uninstaller](https://cdn.adguard.com/public/Adguard/tools/Uninstall_Utility.zip). 

<details>
<summary>Screenshot</summary>

![Screenshot](https://user-images.githubusercontent.com/37463155/150305857-522b1518-62bf-4ba0-94f1-d9800cc23a5c.png)


</details>

**Comment by 115dkk** [comment]
> The rules blocking the advertisements already exists.

확인했습니다. 노트북 환경으로 인한 절전모드 오류로 보입니다. 다시 절전-절전해제를 하니 정상작동합니다.
