### ISSUE TITLE
AD: namu.wiki

### ISSUE THREAD

**Issue by green1052** [List-KR/List-KR#213]
### URL

namu.wiki

### FILTERS

list-kr

### Browser

Google Chrome

### Ad-Blocker

AdGuard for Android

### Comment

![Screenshot_20220121-154617_Kiwi Browser](https://user-images.githubusercontent.com/34261355/150480055-a0e146d6-0df8-4b86-b84c-6b836b98f5bf.jpg)

문서 하단 광고가 제거되지 않습니다.

**Comment by ghost** [comment]
Merged into #210
