### ISSUE TITLE
sbs 라이브 화면이 안나옵니다

### ISSUE THREAD

**Issue by himawarihome** [List-KR/List-KR#214]
### URL

https://www.sbs.co.kr/ko/live/S01

### FILTERS

uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList
EasyPrivacy
Online Malicious URL Blocklist
Peter Lowe’s Ad and tracking server list

### Browser

Mozilla Firefox, Google Chrome

### Ad-Blocker

uBlock Origin

### Comment

list-kr을 제외하면 정상 작동합니다

**Comment by ghost** [comment]
~~Unable to connect.~~

**Comment by ghost** [comment]
Please test the following rules:
```
@@||adservice.sbs.co.kr/NetInsight/vast/$xmlhttprequest
||advod.sbs.co.kr^
||advod.sbs.co.kr^$redirect=noopmp4-1s,media
```

**Comment by himawarihome** [comment]
> Please test the following rules:
> 
> ```
> @@||adservice.sbs.co.kr/NetInsight/vast/$xmlhttprequest
> ||advod.sbs.co.kr^
> ||advod.sbs.co.kr^$redirect=noopmp4-1s,media
> ```

안되는거 같습니다

**Comment by ghost** [comment]
This website rejects VPN or proxy connection.

**Comment by piquark6046** [comment]
@jiyongwoo 
Can I access your desktop remotely?
If you want to communicate privately, please email `piquark6046@protonmail.com` ([PGP-encryption supported](https://keys.openpgp.org/vks/v1/by-fingerprint/FE57A8DEDF68D3A6400DF26E0E5C8ADF00DDAE40)) with `Support #214` subject.

**Comment by himawarihome** [comment]
현재 됩니다
