### ISSUE TITLE
나무위키 하단 광고가 다시 나옵니다

### ISSUE THREAD

**Issue by tjtnsgns** [List-KR/List-KR#215]
### URL

namu.wiki

### FILTERS

list-kr

### Browser

Google Chrome

### Ad-Blocker

AdGuard for Android

### Comment

![Screenshot_20220129-232622_Kiwi Browser](https://user-images.githubusercontent.com/28147257/151664973-137bf8a7-7be9-4851-98e9-a6a284962385.jpg)

1월 29일 기준으로 다시 하단 광고가 다시 나오기 시작했습니다

**Comment by ghost** [comment]
Merged to https://github.com/List-KR/List-KR-Script/issues/1.
