### ISSUE TITLE
Annoyances: 나무위키 나무뉴스가 제거가 되지 않습니다.

### ISSUE THREAD

**Issue by tjtnsgns** [List-KR/List-KR#219]
### URL

https://namu.wiki/w/%EA%B9%80%EC%84%A0%ED%83%9C(%EC%87%BC%ED%8A%B8%ED%8A%B8%EB%9E%99)

### FILTERS

list-kr
youslist
HyunGuard

### Browser

Mozilla Firefox

### Ad-Blocker

AdGuard for Windows

### Comment

나무위키의 나무뉴스를 차단해도 하루가 지나면 다시 나타납니다, 
![K-001](https://user-images.githubusercontent.com/28147257/153112953-dd56b45e-184a-4916-ad4e-d299c7b899de.jpg)
특히나 차단을 시켜보면 뒤에 있는 값이 자꾸 변경되면서 차단이 되지 않습니다. 
![K-002](https://user-images.githubusercontent.com/28147257/153113087-5f4846fc-9d32-46e8-bc15-4ae8fcdb8dc6.jpg)
하단의 파워링크가 비슷한 느낌인 듯합니다.

**Comment by piquark6046** [comment]
Your issue is related to https://github.com/AdguardTeam/AdguardFilters/pull/108961.

**Comment by chan4chan** [comment]
보기 싫은 사람은 옵션인지 설정에서 끄면 되는데 왜 광고 차단을 꺼야지 나무뉴스를 볼 수 있게 만드나요?

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/219#issuecomment-1033766853
@chan4chan 

It will be hidden when you enable only AdGuard Annoyances filter (Not List-KR or AdGuard Base) .
If you want to show with AdGuard Annoyances filter, please add the following rules into your user rules:
```
@@||namu.wiki/i/*?type=news&title=$domain=namu.wiki
namu.wiki#@?#aside > div[id][class]:matches-attr("/data-v-/"):has(> a[href="https://namu.news/"])
namu.wiki#@?##app > div[id][class]:matches-attr("/data-v-/") > div > div:has(> a[href="https://namu.news/"])
```

**Comment by chan4chan** [comment]
감사합니다.
방해 요소 필터랑 YousList를 끄고 해결하였습니다.

**Comment by loveseoul9900** [comment]
나무뉴스 사이드바를 전체 차단하는 Tapermonkey(Violentmonkey) 스크립트입니다.

https://github.com/List-KR/HideNamuSideBar

모바일: https://greasyfork.org/ko/scripts/497290-namuside

**Comment by piquark6046** [comment]
@loveseoul9900 
이미 있습니다. 근데 버그가 좀 있지만요.
https://github.com/List-KR/HideNamuSideBar

**Comment by loveseoul9900** [comment]
> @loveseoul9900 이미 있습니다. 근데 버그가 좀 있지만요. https://github.com/List-KR/HideNamuSideBar

두시간동안 뻘짓했네요; 이걸로 다른곳에 링크 공유해야겠습니다
