### ISSUE TITLE
안녕하세요 혹시 갤럭시 스토어 팝업 광고도 adguard로 차단이 가능한가요?

### ISSUE THREAD

**Issue by cjh980402** [List-KR/List-KR#22]
갤럭시 스토어에 들어가면 뜨는 팝업 광고도 차단이 되는지 궁금해서 문의드려봅니다. 만약 차단이 가능하다면 필터 규칙을 어떻게 작성해야하나요?

**Comment by ghost** [comment]
안녕하세요, 해당 광고를 불러오는 주소를 차단하면 가능할 것으로 보입니다. 자세한 내용 파악을 위해 AdGuard 필터링 로그를 함께 첨부해주시면 감사하겠습니다.

**Comment by cjh980402** [comment]
> 안녕하세요, 해당 광고를 불러오는 주소를 차단하면 가능할 것으로 보입니다. 자세한 내용 파악을 위해 AdGuard 필터링 로그를 함께 첨부해주시면 감사하겠습니다.

그나저나 로그 다 삭제한 다음 갤럭시 스토어에만 들어갔는데도 로그가 너무 많이 뜨네요....일단 혹시 몰라서 다 캡처했습니다. 차단이 안 된 목록 중에 후보가 있을것 같습니다.

![KakaoTalk_20200630_100545698](https://user-images.githubusercontent.com/23624124/86071100-59692300-bab9-11ea-8160-d56cabcac6b6.png)

![KakaoTalk_20200630_100545698_01](https://user-images.githubusercontent.com/23624124/86071096-55d59c00-bab9-11ea-8754-f63c45dd86c7.jpg)
