### ISSUE TITLE
번개장터 검색 결과가 뜨지 않습니다

### ISSUE THREAD

**Issue by AndyH0ng** [List-KR/List-KR#221]
### URL

https://m.bunjang.co.kr/search/products?q=ㅇㅇㅇ

### FILTERS

List-KR
NoriDev: https://github.com/NoriDev/NoriDev-AdBlock-Filter
(List-KR만 해제시 정상 작동합니다)

### Browser

Apple Safari

### Ad-Blocker

AdGuard for Mac, AdGuard DNS

**Comment by piquark6046** [comment]
@AndyH0ng 
Did you mean this element?
<details>
<summary>Screenshot</summary>

![Screensh111ot](https://user-images.githubusercontent.com/98787049/153320368-cb14447f-f15e-4379-8d98-5839fa7a0438.png)



</details>

**Comment by AndyH0ng** [comment]
네
