### ISSUE TITLE
AB: Chrome stopped working on inven.co.kr with uBlock Origin

### ISSUE THREAD

**Issue by ffxivvillein** [List-KR/List-KR#222]
### URL

https://www.inven.co.kr/board/powerbbs.php?query=write

### FILTERS

https://github.com/List-KR/List-KR/raw/master/filter.txt

### Browser

Google Chrome

### Ad-Blocker

uBlock Origin

### Comment

크롬이 멈추면서 열려있는 모든 탭의 사용이 불가능해지며 점유율이 상승합니다.

크롬 프로세스중 점유율이 상승한 프로세스를 강제 종료하면 uBlock Origin이 종료되면서 다시 정상 작동합니다.

`inven.co.kr` 사이트에서 글 작성시 발생하는 현상이나 프리징이 걸려 특정 로그를 얻어 낼 수 없습니다.

**Comment by ffxivvillein** [comment]
추가로 게시글 열때도 동일한 증상이 발생합니다

**Comment by piquark6046** [comment]
Please remove List-KR on your uBlock Origin.

**Comment by piquark6046** [comment]
Or, Add the following rules into your user rules:
```
@@/:\/\/([a-z]|[0-9])+\.inven\.co\.kr\/([A-Z]|[a-z]|[0-9]|_)+\./$object,image,media,other
@@/:\/\/([a-z]|[0-9])+\.inven\.co\.kr\/([A-Z]|[a-z]|[0-9]|_)+\/([A-Z]|[a-z]|[0-9]|_)+\./$object,image,media,other
@@/:\/\/ppss\.kr\/([A-Z]|[a-z]|[0-9]|_)+/$object,image,media,other
@@/:\/\/ppss\.kr\/([A-Z]|[a-z]|[0-9]|_)+\/([A-Z]|[a-z]|[0-9]|_)+/$object,image,media,other
@@/:\/\/ygosu\.com\/([A-Z]|[a-z]|[0-9]|_)+/$object,image,media,other
@@/:\/\/ygosu\.com\/([A-Z]|[a-z]|[0-9]|_)+\/([A-Z]|[a-z]|[0-9]|_)+/$object,image,media,other
```

**Comment by piquark6046** [comment]
Related: https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1979

**Comment by piquark6046** [comment]
@ffxivvillein Has your issue been resolved?
