### ISSUE TITLE
AB: 1412.rest

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#227]
### URL

https://1412.rest/romance1/6920542

### FILTERS

Ad Blocking:
AdGuard Base,
AdGuard Mobile Ads

Privacy:
AdGuard Tracking Protection

Language-specific:
List-KR

### Browser

Samsung Internet

### Ad-Blocker

AdGuard Content Blocker

### Comment
<details>
<summary>Screenshots</summary>

![Screenshots_2022-02-24-15-13-33](https://user-images.githubusercontent.com/100195064/155469332-e1401f9f-dce3-4959-8c48-31891fd416b8.png)
![Screenshots_2022-02-24-15-12-40](https://user-images.githubusercontent.com/100195064/155469343-0b04aaa2-095a-4c72-97fc-4a77ed26bbbf.png)

</details>

This site Anti Adblock Script
Fix is adguard android
But dont fix samsung internet adguard content blocker

**Comment by piquark6046** [comment]
@9JI0oFWdNImpT0 
Can you update the subscribed filters?

**Comment by ghost** [comment]
@piquark6046 
of course, i can try update

<details>
<summary>Screenshot</summary>

![Screenshots_2022-02-24-17-45-29](https://user-images.githubusercontent.com/100195064/155490155-76bf13bf-6d70-4dbf-81e4-1d6f100c858d.png)
![Screenshots_2022-02-24-17-45-48](https://user-images.githubusercontent.com/100195064/155490169-ff43e09c-8c9d-48e9-8a19-02eff75db4bd.png)

</details>

But, dont fix
Could it be a Samsung Internet problem?

**Comment by piquark6046** [comment]
@9JI0oFWdNImpT0 
Can you add the following rule into your user rules and reload the website?
```
||1412.rest/addons/*/adblockDetector.js
```

Or, transfer to [AdGuard for Android](https://adguard.com/en/adguard-android/overview.html).

**Comment by ghost** [comment]
@piquark6046 
I add user rules
And reboot phone
Reload site, but dont fix.

Instead of a content blocker, 
AdGuard Android works just fine.
thank you

**Comment by ghost** [comment]
@piquark6046 
I find Samsung Internet Content Blocker Solution

```
@@||adblockanalytics.com^$domain=1412.rest
1412.rest##.adsbygoogle
```

Samsung Internet can't block anti-adblock .js scripts
but, This anti-adblock script tests connection to https://adblockanalytics.com to determine whether to use ad blocker.
With the above rules, on Samsung Internet
can bypass anti-adblock.
And now anti-adblock doesn't work even if you hide ad blank space

**Comment by piquark6046** [comment]
@9JI0oFWdNImpT0 Pushed.
