### ISSUE TITLE
AD: gall.dcinside.com

### ISSUE THREAD

**Issue by green1052** [List-KR/List-KR#229]
### URL

https://gall.dcinside.com

### FILTERS

adguard filters

list-kr 
youslist

### Browser

(Other)

### Ad-Blocker

AdGuard for Windows

### Comment

![image](https://user-images.githubusercontent.com/34261355/157443129-3962a736-f706-4e3a-a0f0-6024647fa1ae.png)

갤러리 글 목록에서 AD 항목이 숨겨지지 않습니다

**Comment by piquark6046** [comment]
@green1052 Can you provide the URL?

**Comment by green1052** [comment]
https://gall.dcinside.com/mgallery/board/lists/?id=vpngate @piquark6046
