### ISSUE TITLE
v live 앱 업데이트 후 광고 추가

### ISSUE THREAD

**Issue by joyfuI** [List-KR/List-KR#23]
최근 [v라이브](https://play.google.com/store/apps/details?id=com.naver.vapp) 앱이 업데이트 되면서 피드에 광고가 추가되었습니다.

필터링 로그를 확인해보니까 gfp.veta.naver.com가 광고 도메인으로 추정됩니다.

`||gfp.veta.naver.com^$app=com.naver.vapp`

일단 저는 저 필터로 차단해놓은 상태인데 잘 차단되는 것 같습니다.

**Comment by joyfuI** [comment]
아 기존 필터를 살펴보니까 이미 있네요.

`||gfp.veta.naver.com/adcall^`

근데 https라서 안드로이드에선 작동하지 않고 도메인 전체를 차단해야지 필터가 작동합니다.

**Comment by ghost** [comment]
https://github.com/List-KR/List-KR/commit/897b133071ae0b69b9df4b67703d7a1584d0af21 커밋에서 업데이트 하였습니다. AdGuard의 경우 실질 반영까지 몇 시간 정도 소요될 수 있으니 참고 부탁드립니다.

List-KR 필터 개발에 관심을 가져 주셔서 감사합니다.
