### ISSUE TITLE
Leftover: https://m.naver.com/aside/

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#239]
### URL

https://m.naver.com/aside/

### FILTERS

List-KR

### Browser

Microsoft Edge

### Ad-Blocker

AdGuard Browser Extension, AdGuard for Windows, AdGuard for Android

### Comment

When you turn on list kr, a blank space is created.
||blocked by ssl.pstatic.net/tveta/libs/ rule
https://ssl.pstatic.net/tveta/libs/ssp/ssp.web.sdk.js
If this whitelist , the blank space disappears. 

<details>
<summary>Screenshots</summary>

![68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f4e5642723031632e706e67](https://user-images.githubusercontent.com/101787143/158745914-cdaae2e5-f60a-4b0d-9d98-a7d538382c9b.png)
![68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f3649374659394b2e706e67](https://user-images.githubusercontent.com/101787143/158745918-28c9c478-0946-4f06-a58f-7eba99fe8ff0.png)

</details>

**Comment by piquark6046** [comment]
~~@88Va2wFDcYd1CT~~
~~Cannot reproduce.~~
~~Please update the subscribed filters.~~

<details>
<summary>Screenshot</summary>

![Screenshot1](https://user-images.githubusercontent.com/98787049/158759932-9144f5ba-89b2-47bd-99bf-e5e0a6084b2c.png)

</details>

**Comment by ghost** [comment]
@piquark6046 
It still is. 

<details>
<summary>Screenshots</summary>

![1](https://user-images.githubusercontent.com/101787143/158762791-a3dbac64-41a5-4b50-b597-5bc524317db1.png)
![2](https://user-images.githubusercontent.com/101787143/158762801-99833493-b8d1-4cfc-a41c-99d8165f9d24.png)

</details>

**Comment by piquark6046** [comment]
Fetched.

**Comment by ghost** [comment]
@piquark6046 
I found a way to reproduce it.
If you connect directly to https://m.naver.com/aside/
not reproduced, but
First, connect to https://m.naver.com
Pressing the hamburger menu reproduces the symptoms. 

<details>
<summary>Screenshot</summary>

![3](https://user-images.githubusercontent.com/101787143/158764103-e6844a98-6edb-4059-9821-2327fd0bc808.png)

</details>

**Comment by piquark6046** [comment]
@88Va2wFDcYd1CT 
I cloud reproduce it, so I fetched.
Please wait until the fetch is downloaded automatically.
