### ISSUE TITLE
sbs allclip 동영상 재생 문제

### ISSUE THREAD

**Issue by joyfuI** [List-KR/List-KR#24]
![Screenshot0](https://user-images.githubusercontent.com/1342862/71324135-9bb81300-251e-11ea-8e40-7f3f44ffc4f0.png)
http://allclip.sbs.co.kr/end.html?clipid=S01_446568027

sbs allclip 사이트에서 동영상 재생이 안 되는 문제가 있습니다.
List-KR의 문제가 아니라 Adguard 베이스 필터의 문제이긴 한데 List-KR에서 차단 해제하는 필터를 추가할 필요가 있어 보입니다.
*****
기존 필터를 살펴보니 이미 비슷한 필터가 있네요.

`@@||ad.smartmediarep.com/NetInsight/$domain=allvod.sbs.co.kr|news.sbs.co.kr|programs.sbs.co.kr`

도메인이 allvod.sbs.co.kr에서 allclip.sbs.co.kr로 바뀐 건지
아니면 그냥 allclip.sbs.co.kr이 추가된 건지 모르겠지만
암튼 allclip.sbs.co.kr 도메인에 대해서 추가하면 될 듯합니다.

**Comment by ghost** [comment]
안녕하세요, 해당 규칙이 https://github.com/List-KR/List-KR/commit/4a44e1c7f6923a9df8be701198c49d815546f8ed 커밋에서 업데이트 되었습니다. AdGuard 환경에서는 실제 반영까지 최대 24시간 정도 소요될 수 있으니 참고 부탁드립니다. 고맙습니다.
