### ISSUE TITLE
IC: inven.co.kr

### ISSUE THREAD

**Issue by DavidLee3835** [List-KR/List-KR#245]
### URL

https://www.inven.co.kr/

### FILTERS

List-KR

### Browser

Google Chrome

### Ad-Blocker

AdGuard Browser Extension

### Comment

<img width="867" alt="image" src="https://user-images.githubusercontent.com/99162643/159197335-295a75ed-9c24-4986-b04a-56d9c3df0cee.png">

Images in the center box are not loaded except the first image.
The images should be shown when mouse cursor hovering the button on right side.

**Comment by DavidLee3835** [comment]
https://github.com/List-KR/List-KR/blob/88deefcf5f7e5853454d8874fcd2b1fb4a97292b/filters/general_extension.txt#L1

I think this filter causes the problem.

**Comment by piquark6046** [comment]
Then, you cannot block ad-shield advertisement unless maintainers of List-KR find other solution.

**Comment by seia-soto** [comment]
Consider only applying the cosmetic filter that won't break the site feature.

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/commit/432222764618ee6bc14dfde08862fae3ac2b81f9
