### ISSUE TITLE
IC: gigglehd.com incorrect blocking

### ISSUE THREAD

**Issue by amdradeonhd6950** [List-KR/List-KR#248]
### URL

https://gigglehd.com/gg/

### FILTERS

List-KR

### Browser

Google Chrome

### Ad-Blocker

AdGuard for Android

### Comment

There's incorrect blocking issue on https://gigglehd.com/gg/.
![Screenshot_20220322-105051](https://user-images.githubusercontent.com/82917025/159391318-5ffe8f6d-36aa-4444-b3bd-c89b37e0bf7c.png)
The main banner pictures are not ads.
![Screenshot_20220322-105044](https://user-images.githubusercontent.com/82917025/159391323-113ea3b7-5772-4f61-a8cb-e84b6ec09dc7.png)
When I turn on AdBlock for Android, the main banner pictures are blocked, which should not blocked.

**Comment by amdradeonhd6950** [comment]
maybe the code "gigglehd.com##.widget_banner_skin > ul.banner_list" is causing this issue.

**Comment by seia-soto** [comment]
I'll try to rollback the incorrect rule. Please, wait for investigation.

<details><summary>Logger output</summary>

```
+1
/generate_204$image
--
gigglehd.com
3
image
https://clients1.google.com/generate_204
```
```
+1
||cse.google.com/adsense/search/async-ads.js^
--
gigglehd.com
3
script
https://cse.google.com/adsense/search/async-ads.js
```
```
+0
##div[style~="!important;"] > .nw_box > div:not(class):not(id) > table[cellspacing="0"][class]
gigglehd.com
dom
https://gigglehd.com/gg/
```
```
+0
##div.widget_banner_skin
gigglehd.com
dom
https://gigglehd.com/gg/
```
```
+0
##div#container>div.section>div.xe-widget-wrapper>div>div.nw_box
gigglehd.com
dom
https://gigglehd.com/gg/
```
```
+0
##.widget_banner_skin > ul.banner_list
gigglehd.com
dom
https://gigglehd.com/gg/
```
```
+0
##.widget_banner_skin
gigglehd.com
dom
https://gigglehd.com/gg/
```
```
+0
google-analytics.com/analytics.js
<<
gigglehd.com
3
script
https://www.google-analytics.com/analytics.js
```
```
+0
||google-analytics.com/analytics.js$script,redirect-rule=google-analytics.com/analytics.js
--
gigglehd.com
3
script
https://www.google-analytics.com/analytics.js
```
```
+0
||google-analytics.com/analytics.js$script,redirect-rule=google-analytics_analytics.js,domain=~banki.ru|~olx.*
--
gigglehd.com
3
script
https://www.google-analytics.com/analytics.js
```
```
+0
||google-analytics.com^
--
gigglehd.com
3
script
https://www.google-analytics.com/analytics.js
```
```
+0
https://gigglehd.com/gg/
```
</details>

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/113454
