### ISSUE TITLE
AB: ppss.kr

### ISSUE THREAD

**Issue by green1052** [List-KR/List-KR#265]
### URL

ppss.kr

### FILTERS

list-kr

### Browser

(Other)

### Ad-Blocker

AdGuard for Android

### Comment

faild to load images error

https://docs.ad-shield.io/ec9bccd7-3af8-4fc6-b63d-fdea204124f8

**Comment by green1052** [comment]
i think better then ad shield filer rules make private

**Comment by seia-soto** [comment]
Will check on laptop LOL

![image](https://user-images.githubusercontent.com/30369714/160074161-acba5d1e-a207-4a73-9169-a060efc7164e.png)

**Comment by green1052** [comment]
> 

disable u r adblock

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/265#issuecomment-1078582195
I think that it is impossible to make List-KR private because any rule can be exposed by using network traffic monitor or visiting [FiltersRegistry](https://github.com/AdguardTeam/FiltersRegistry/commits/master).

**Comment by seia-soto** [comment]
> [#265 (comment)](https://github.com/List-KR/List-KR/issues/265#issuecomment-1078582195) I think it is impossible to make List-KR private because any rule can be exposed by using network traffic monitor or visiting [FiltersRegistry](https://github.com/AdguardTeam/FiltersRegistry/commits/master).

I sent you updated filter using encrypted mail. Please, update the filter at your own risk to be monitored.

**Comment by seia-soto** [comment]
Patching won't take long but distribution to end-users would take some time.
