### ISSUE TITLE
Websites protected by Ad-Shield

### ISSUE THREAD

**Issue by piquark6046** [List-KR/List-KR#269]
## Moved to #277 because List-KR has blocked Ad-Shield advertisement successfully.

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/274#issuecomment-1088638252
@seia-soto  @JobcenterTycoon

What about unblocking the element mentioned in Ad-Shield script?
<details>
<summary>Screenshot</summary>

![Screenshot from 2022-04-05 13-41-15](https://user-images.githubusercontent.com/98787049/161767689-c3c0c358-7205-45be-b85b-5ab768d02577.png)

</details>

https://www.ad-shield.team/solution/recovery

**Comment by JobcenterTycoon** [comment]
When it works why not

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/269#issuecomment-1088799498

> They check easylist filter

I know.
However, maintainers of List-KR can push a patch when Ad-Shield advertisement is not blocked.

**Comment by piquark6046** [comment]
Oh, I was wrong. Hold on a sec...

**Comment by piquark6046** [comment]
@JobcenterTycoon 
It seems that your suggested rules do not work at [inven.co.kr](https://www.inven.co.kr/webzine/news/?news=269783) on Microsoft Edge with AdGuard Browser Extension.
Cloud you please check this?

**Comment by JobcenterTycoon** [comment]
@piquark6046 i tested a bit with adguard and i see `inven.co.kr##div[class^="ad-"]` in ListKR flags

**Comment by piquark6046** [comment]
Thank you for your contribution.

**Comment by JobcenterTycoon** [comment]
@piquark6046 
The filter `||coupang.com/?src*addtag=*&placementid&campaignid*&subid=*&impressionid&campaigntype*&subparam=$document,domain=ppss.kr|ygosu.com|tgd.kr|inven.co.kr|loawa.com` not works for `loawa.com`

does replacing the current URL to `coupang.com/*addtag=*&pageType*&placementid*&impressionid&campaigntype` works for you?

**Comment by seia-soto** [comment]
`loawa.com` has difference from existing adshield installed websites. Most of rules may not work in future that currently applied specially for adshield.

**Comment by JobcenterTycoon** [comment]
Does adcrap can control the parameter from `coupang.com` ? I try to add rules which can’t be controlled by adcrap

**Comment by seia-soto** [comment]
No, it can't control the parameter of `coupang.com`. However, the crap can take the control because they seems like proxying the site.

I don't know well but the filter: `||coupang.com/*addtag=*&pageType*&placementid*&impressionid&campaigntype,domain=ppss.kr|ygosu.com|tgd.kr|inven.co.kr|loawa.com` is not working on my side.

**Comment by JobcenterTycoon** [comment]
You did a mistake in the filter, `||coupang.com/*addtag=*&pageType*&placementid*&impressionid&campaigntype$popup,3p` works fine for me (tested on uBO). The redirection way for me is:

`https://loawa.com/ZuYwUdi-fPXaNPlWIGyNE420bd297eba852e3.pptx` (adcrap) ->

`http://api.linkmine.co.kr/ck.html?app_code=4fNEkEu5g6&sid=38303` (tracking)->

`https://link.coupang.com/re/AFFHOME?lptag=AF7400138&traceid=V0-180-0000000000000000&subId=757S138436&subParam=6OT0648164925271638303Z403332487_CPR` (advertiser)->

`https://www.coupang.com/...` (advertiser)

**Comment by JobcenterTycoon** [comment]
@piquark6046 are `​api.linkmine.co.kr` and `nefing.com` pure tracker domains? Because i want to report it to other lists and i want to be sure

**Comment by piquark6046** [comment]
@JobcenterTycoon Are they related to Ad-Shield advertisement?
If not, please open an issue with a blank issue.

**Comment by JobcenterTycoon** [comment]
Yes i get redirected through it

**Comment by piquark6046** [comment]
@JobcenterTycoon No. They are advertisement domains.

**Comment by piquark6046** [comment]
Confirmed at ygosu.com
