### ISSUE TITLE
안드로이드 카카오페이 앱의 투자 탭 접속 오류

### ISSUE THREAD

**Issue by joyfuI** [List-KR/List-KR#27]
안드로이드 [카카오페이 앱](https://play.google.com/store/apps/details?id=com.kakaopay.app)이 최근 업데이트 이후로 투자 탭에 들어갔을 때
> 네트워크 연결 상태가 좋지 않습니다.
> 잠시 후 다시 시도해 주세요.

라면서 앱이 꺼집니다.

필터링 로그를 살펴보니 webid.ad.daum.net, stat.tiara.kakao.com 이 두 가지 주소를 차단했을 때 저 메시지가 뜨네요.
`@@||webid.ad.daum.net^`
`@@||stat.tiara.kakao.com^`
임시로 저 필터를 추가하니 이 현상이 사라졌습니다.

참고로 webid.ad.daum.net은 `||ad.daum.net^`의 의해, stat.tiara.kakao.com은 `||stat.tiara.kakao.com^`의 의해 차단되고 있습니다.

**Comment by ghost** [comment]
https://github.com/List-KR/List-KR/commit/a62fa421c09720cf8b21859900c406b10bebdc1a 커밋에서 업데이트하였습니다. 필터 개발에 참여해 주셔서 감사합니다 :)
