### ISSUE TITLE
IC: ygosu.com

### ISSUE THREAD

**Issue by DavidLee3835** [List-KR/List-KR#270]
### URL

https://ygosu.com/

### FILTERS

List-KR

### Browser

Google Chrome

### Ad-Blocker

AdGuard Browser Extension

### Comment

AdGuard Off
<img width="803" alt="image" src="https://user-images.githubusercontent.com/99162643/160313391-bc1db10b-4da0-4948-b2f0-9bbff35fc433.png">

AdGuard On
<img width="817" alt="image" src="https://user-images.githubusercontent.com/99162643/160313371-4cf70084-b9b2-4c98-8a37-ae28b4d44fdb.png">

<img width="657" alt="image" src="https://user-images.githubusercontent.com/99162643/160313434-8b0e52ce-ae6b-491d-946c-2c940c44cbed.png">
<img width="678" alt="image" src="https://user-images.githubusercontent.com/99162643/160313452-af7e39f7-39e5-402d-96cb-786bf8b840c7.png">

After I updated the filter this morning, the section below the website is broken.
https://github.com/List-KR/List-KR/blob/master/filters-AG/general_extension.txt#L1
I think this filter makes the scripts on the website stop working.

**Comment by DavidLee3835** [comment]
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/99162643/160313957-7d0699dc-f564-4fc4-bfd4-96fc7dd639d8.png">

I'm on testing with Chrome secret tab, All of the images are gone.
This filter should be removed asap.

**Comment by seia-soto** [comment]
I am sure that the error that images failed to be loaded is because of adshield, and the delay created before actual propagation to the end-user can affect your browser.

You can temporarily resolve the issue using following rules in case of AdGuard:

```css
op.gg,etoland.co.kr,sports.donga.com,mlbpark.donga.com,ppss.kr,ygosu.com,inven.co.kr,tgd.kr#@#//scriptlet("abort-current-inline-script", "document.currentScript")
op.gg,etoland.co.kr,sports.donga.com,mlbpark.donga.com,ppss.kr,ygosu.com,inven.co.kr,tgd.kr$@$ad-shield-inventory[tag-content="ad-shield-ads"]
```

(ref: https://github.com/List-KR/List-KR/commit/494739bb17aa0bc4cc6af9a3a8861d48891efe75)

**Comment by seia-soto** [comment]
@DavidLee3835 , also, please visit [here](https://github.com/List-KR/List-KR/issues/269#issue-1182547377) to trust List-KR rules, so that every rules can work.

- If the link above doesn't work: https://github.com/List-KR/List-KR/issues/269#issue-1182547377

**Comment by DavidLee3835** [comment]
<img width="720" alt="image" src="https://user-images.githubusercontent.com/99162643/160353694-6e77011b-dcc9-4104-be97-a2d2672637e0.png">
<img width="710" alt="image" src="https://user-images.githubusercontent.com/99162643/160353660-7d068f58-97fc-488d-b436-c421a7222f6d.png">

@seia-soto Thank you for the suggestion.
However, even I disabled List-KR in AdGuard filter lists and added new one in Custom filter section,
images of ygosu.com aren't shown like below.

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/99162643/160354139-43553586-56a8-4889-a450-86978d50910b.png">

Can you please try reproducing this?
It occurs when the page is refreshed.

**Comment by piquark6046** [comment]
Confirmed.

**Comment by piquark6046** [comment]
It seems that I need to use `$$` rule that can use on only Firefox, AdGuard for Windows, AdGuard for Mac and Android.
I will figure out the way I can block Ad-Shield and fix this issue with other rule.

**Comment by DavidLee3835** [comment]
<img width="990" alt="image" src="https://user-images.githubusercontent.com/99162643/160511601-734034b6-b2fc-4ea2-a745-ce277da6c886.png">
<img width="999" alt="image" src="https://user-images.githubusercontent.com/99162643/160511628-e2713817-e94f-4ea4-a5d8-fb062ca1e4e5.png">

I think this filter was too risky to be merged, the comment section is also not shown.

https://ygosu.com/community/yeobgi/1924796
https://ygosu.com/community/yeobgi/1925165

Users who use List-KR filter are already suffering from these problems.

**Comment by seia-soto** [comment]
Unfortunately, AdShield can make any component on the site its hostage. I am sorry about that but it's unable to expect what they'll break.

**Comment by DavidLee3835** [comment]
That's a shame, but I think preventing users from having an uncomfortable experience is more important.
Do you think it takes long time to resolve those problems with another filter?
If so, this filter should be reverted asap to prevent the uncomfortable experience to user.

**Comment by piquark6046** [comment]
@DavidLee3835 Okay. I will revert the changes that does not affect user experiment of other website for now.

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/269
