### ISSUE TITLE
IC: inven.co.kr, tgd.kr

### ISSUE THREAD

**Issue by DavidLee3835** [List-KR/List-KR#274]
## Ad-Shield advertisement issue is merged into https://github.com/List-KR/List-KR/issues/269.

---

### URL

https://inven.co.kr

### FILTERS

List-KR

### Browser

Google Chrome

### Ad-Blocker

AdGuard Browser Extension

### Comment

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/99162643/161463668-7e132a3d-b521-4986-91e5-1b9bcd219fa2.png">

inven.co.kr images are gone, like ygosu.com and ppss.kr before.
https://github.com/List-KR/List-KR/issues/270

**Comment by DavidLee3835** [comment]
https://tgd.kr/s/naseongkim/63024553

AdGuard Off
<img width="894" alt="image" src="https://user-images.githubusercontent.com/99162643/161473297-9c8e2c28-71cb-4e02-bcff-d17c1e4f7a97.png">

AdGuard On
<img width="898" alt="image" src="https://user-images.githubusercontent.com/99162643/161473316-b787af30-4063-4ae5-b3fb-4dd136a8bcd4.png">

tgd.kr also has the same problem.

**Comment by seia-soto** [comment]
Confirmed. It may take time to work as every contributors isn't full time worker.

**Comment by piquark6046** [comment]
Ad-Shield advertisement issue is merged into https://github.com/List-KR/List-KR/issues/269.

**Comment by JobcenterTycoon** [comment]
@piquark6046 adcrap only place ads if a adblocker got detected so a way can be to fool the script thinking no adblocker is active. A filter i added to uBO:

```
*$script,redirect-rule=noopjs,domain=ppss.kr|ygosu.com|tgd.kr|inven.co.kr
*$image,redirect-rule=1x1.gif,domain=ppss.kr|ygosu.com|tgd.kr|inven.co.kr
*$xhr,redirect-rule=noopjs,domain=ppss.kr|ygosu.com|tgd.kr|inven.co.kr
@@*$ghide,domain=ppss.kr|ygosu.com|tgd.kr|inven.co.kr
```
