### ISSUE TITLE
Websites protected by Ad-Shield

### ISSUE THREAD

**Issue by piquark6046** [List-KR/List-KR#277]
## https://github.com/List-KR/microShield/blob/main/README.ko.md

**Comment by piquark6046** [comment]
@seia-soto Administrators of loawa.com added Ad-Shield.
https://github.com/AdguardTeam/AdguardFilters/issues/114791

**Comment by seia-soto** [comment]
> @seia-soto Administrators of loawa.com added Ad-Shield. [AdguardTeam/AdguardFilters#114791](https://github.com/AdguardTeam/AdguardFilters/issues/114791)

I found another method that can be applied globally. May I get the list of the sites that use adshield?

* I am also searching

### Currently found sites

```
loawa.com,ppss.kr,inven.co.kr,tgd.kr,ygosu.com
```

**Comment by piquark6046** [comment]
@JobcenterTycoon
I found that Ad-Shield advertisement on ppss.kr is updated.
I will push a patch for that.

**Comment by piquark6046** [comment]
Reverted.

**Comment by JobcenterTycoon** [comment]
@piquark6046 its because Adguard base override the exception filter with `||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,redirect=googlesyndication.com/adsbygoogle.js,domain=ppss.kr,important`

@Alex-302 @Yuki2718

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardFilters/pull/115163

**Comment by piquark6046** [comment]
@gaeulbyul @seia-soto @green1052 
Can you verify that Ad-Shield advertisement is hidden by List-KR?

**Comment by green1052** [comment]
inven.co.kr - hide
ppss.kr - hide
loawa.com - not hide
tgd.kr - hide
ygosu.com - hide

ungoogled Chromium 100.0.4896.75, list-kr 06.01.46

**Comment by green1052** [comment]
@piquark6046

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/277#issuecomment-1096645134
Can you share a screenshot on loawa.com?

**Comment by gaeulbyul** [comment]
Environment:

* Chrome: v100.0.4896.88
* AdGuard: v4.0.161
* List-KR: v2022.412.2

Result:

* ppss.kr: OK
* loawa.com: ~~OK~~ Failed
* ygosu.com: OK
* m.ygosu.com: OK

But,

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/830515/162959908-fe1653de-27e2-41f4-b30c-dbaede4936b6.png)

</details>

~~Is revealing `<ad-shield-inventory>` and `<ad-shield-ads>`  intended? or they didn't load ads correctly for some reason?~~

Nevermind. after several refresh, adshield detects the adblock. (but ads are not shown on my PC.)

**Comment by green1052** [comment]
<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/34261355/162960654-c4ea8df3-0bd8-4d09-b9cb-c246ffa98be8.png)

</details>
@piquark6046

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/277#issuecomment-1096648310

> but ads are not shown on my PC.

Is there any website notification (`alert`) or hidden image?

**Comment by gaeulbyul** [comment]
> [#277 (comment)](https://github.com/List-KR/List-KR/issues/277#issuecomment-1096648310)
> 
> > but ads are not shown on my PC.
> 
> Is there any website notification (`alert`) or hidden image?

Yes, "Failed to load images. (AdBlock Exception)"

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/277#issuecomment-1096655979

I cannot reproduce your issue on Microsoft Edge and Mozilla Firefox with AdGuard Browser Extension.
~~Is AdGuard Base filter enabled?~~
Filters List:
<details>
<summary>Screenshot</summary>

![Screenshot from 2022-04-12 12-32-00](https://user-images.githubusercontent.com/98787049/162963104-d1413ed9-fe49-4c87-aba4-76a559ebd6ed.png)

</details>
Stealth Mode: Off

**Comment by gaeulbyul** [comment]
[#277 (comment)](https://github.com/List-KR/List-KR/issues/277#issuecomment-1096655979)

Yes, AdGuard Base filter & List-KR. two filters.

(I never turned "stealth mode" to on)

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/277#issuecomment-1096650899
This issue can be reproduced on AdGuard for Windows (Not AdGuard Browser Extension).

**Comment by JobcenterTycoon** [comment]
@piquark6046 i confirm adcrap ads are back now

https://github.com/uBlockOrigin/uAssets/commit/d6cfe3ae3c68e3eeea2b2ae5010a2948533c000a

**Comment by piquark6046** [comment]
@JobcenterTycoon Your patch pushed to uAssets does not work on loawa.com.

**Comment by JobcenterTycoon** [comment]
Ok updated

**Comment by lunamoth** [comment]
와우 인벤 유저 정보 게시판 아래 링크로 접속하면 애드쉴드 광고가 나오더군요. 혹시 차단 지원 가능하다면 부탁드리겠습니다.

KST 2022년 4월 13일 오후 11:11 현재 

https://www.inven.co.kr/board/wow/1896

<details>
<summary>Screenshot</summary>

![화면 캡처 2022-04-13 231035](https://user-images.githubusercontent.com/99085/163200049-0fd68218-226d-4e9b-a83e-9df0a11b259b.jpg)

</details>

**Comment by piquark6046** [comment]
@lunamoth 
Please update your configuration with referring to https://github.com/List-KR/List-KR/issues/236#issuecomment-1086910452.

**Comment by seia-soto** [comment]
Note that new form of ads by adsield can be blocked only with `iframe` tag.

```css
loawa.com##ins[aria-label="Advertisement"]
loawa.com,ygosu.com,inven.co.kr,ppss.kr##iframe[src*="ad"]
```

I don't know if there is any side effect yet because I can applying a lot of filters at the time.

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/277#issuecomment-1100894460
Your suggested rule does not apply to the websites because of `@@$ghide,domain=ppss.kr|ygosu.com|tgd.kr|inven.co.kr|loawa.com` and `@@$generichide,domain=ppss.kr|ygosu.com|tgd.kr|inven.co.kr|loawa.com`.

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/pull/298

**Comment by JobcenterTycoon** [comment]
Ad shield is back on `loawa.com`

**Comment by piquark6046** [comment]
@JobcenterTycoon Also, please check `ppss.kr`.

**Comment by JobcenterTycoon** [comment]
`ppss.kr` works fine with uBlock Origin but `loawa.com` not. On `loawa.com` adcrap even appears with completely disabled adblocker.

Im updated loawa now with the filter suggested in the slack chat

**Comment by JobcenterTycoon** [comment]
@piquark6046 what about the regex now? The regex need a update to cover the new ad shield URLs

The latest version from uBO: ` /\/[0-9a-zA-Z\/\_?]{14,}\.(?!png|jpg|gif|jpeg|html|htm|txt|php|com|kr|net|svg)/$document,popup,inline-script,1p,domain=ppss.kr|ygosu.com|tgd.kr|inven.co.kr|loawa.com|feedclick.net`

**Comment by JobcenterTycoon** [comment]
@piquark6046 

`||coupang.com/?*addtag=*&pageType*&placementid*&impressionid&campaigntype$document` need a update to block the latest redirect, the site removed the `?` https://github.com/uBlockOrigin/uAssets/commit/336b2d7caed27d6d86d42232b1c79a0e3471ee92 (will remove if the filter in List KR get updated its just to fix it quickly)

For the regex above its important to only cover `document` and `popup` no other requests to avoid detection and just to block the redirect

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/pull/347
https://github.com/List-KR/List-KR/pull/348
https://github.com/List-KR/List-KR/pull/349

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/pull/351

**Comment by seia-soto** [comment]
## For anyone who're experiencing the problem even you updated to the latest version
> ### 최신 버전으로 업데이트했음에도 불구하고 문제를 겪고 계시는 분들께

Open Developer tools on the problematic website first via CTRL+SHIFT+I or OPTION+CMD+I.
Choose the language and paste the content on the link to the developer tools 'Console' pane.
To continue, just press Enter key on the developer tools console.

> 문제인 웹 사이트에서 CTRL+SHIFT+I나 OPTION+CMD+I를 통해 개발자 도구를 열어주세요.
> 언어를 선택하고 개발자 도구의 '콘솔' 패널에 링크의 내용을 붙여넣어주세요.
> 이제 계속하시려면 콘솔에서 엔터 키를 눌러주세요.

- English: https://gist.githubusercontent.com/seia-soto/f3e22dbf893701e548a1f5ec5691ac97/raw/2e8dae19f2d99c9545f821d553a339e5b8b04673/scrap.js
- Korean (한국어): https://gist.githubusercontent.com/seia-soto/f3e22dbf893701e548a1f5ec5691ac97/raw/2e8dae19f2d99c9545f821d553a339e5b8b04673/scrap.ko.js

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/30369714/169525553-3c467233-eb31-4353-8379-7286941b54a7.png)

</details>

**Comment by green1052** [comment]
ppss.kr Failed to load images. (AdBlock Exception)

adguard pc, ungoogled chromium 101.0.4951.67

list-kr - 2022.520.1

script (expired in 1 day): https://pastebin.mozilla.org/t3HHqfdA#

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/277#issuecomment-1132913820
Confirmed.

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/277#issuecomment-1132913820
~~It seems that it is caused by Stealth Mode of AdGuard for Windows.~~

**Comment by seia-soto** [comment]
I found that it's related to the following commit on uAssets: https://github.com/uBlockOrigin/uAssets/commit/6d46c69050f6465d87ac23c0aed251c4ff092fbb

We need to sync with them.

**Comment by seia-soto** [comment]
Not reproduced on uBO, only AG.

**Comment by JobcenterTycoon** [comment]
Why? I added many filter to List-KR thats why i removed the filter from quick

**Comment by seia-soto** [comment]
Ah, I thought that you removed it from uAssets because it's not used anymore. Thanks for noticing me.

**Comment by seia-soto** [comment]
@piquark6046 Found problematic: `/\/[0-9a-zA-Z\/\_?]{14,}\.(?!png|jpg|gif|jpeg|html|htm|txt|php|com|kr|net|svg|[a-zA-Z0-9\/]{5,})/$document,popup,~third-party,domain=ppss.kr|ygosu.com|tgd.kr|inven.co.kr|loawa.com|feedclick.net`

<details>
<summary>Details</summary>

상태
HTML 구성요소 제거

소스 URL
https://www.inven.co.kr/

애플리케이션
Safari (com.apple.Safari)

규칙
/\/[0-9a-zA-Z\/\_?]{14,}\.(?!png|jpg|gif|jpeg|html|htm|txt|php|com|kr|net|svg|[a-zA-Z0-9\/]{5,})/$document,popup,~third-party,domain=ppss.kr|ygosu.com|tgd.kr|inven.co.kr|loawa.com|feedclick.net (List-KR)

데이터 유형
기타

HTML 구성요소
<link rel="stylesheet" type="text/css" href="https://www.inven.co.kr/webzine/lib/style/dist/commu_style.css?v=220516aa">

연결 ID
1003713

요청 ID
605691

</details>

**Comment by piquark6046** [comment]
@seia-soto Done.

**Comment by seia-soto** [comment]
#361

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/commit/3f02b707a978ec905ed3cf3b2cbfb62f94bef976

**Comment by piquark6046** [comment]
### Complaints of loawa.com visitors
<details>
<summary>Screenshots</summary>

![Screenshot 로스트아크 인벤 공홈 전투정보실과 MGX를 사용해주셔서 감사합니다  - 로스트아크 인벤 자유 게시판](https://user-images.githubusercontent.com/98787049/169664531-0c223658-835e-4606-bc65-1b5306427f48.png)
![Screenshot 로스트아크 인벤 모험가분들을 비꼬는 글을 작성해서 죄송합니다  - 로스트아크 인벤 자유 게시판](https://user-images.githubusercontent.com/98787049/169664543-f393cc81-b947-476d-ae23-7f76d459e723.png)



</details>


<details>
<summary>URLs</summary>

https://www.inven.co.kr/board/lostark/4811/4880553
https://www.inven.co.kr/board/lostark/4811/4880778
https://www.inven.co.kr/board/webzine/4811/4880441
https://www.inven.co.kr/board/lostark/4821/87652

https://www.dogdrip.net/406280572
https://www.dogdrip.net/406296749
https://www.dogdrip.net/406275120
https://www.dogdrip.net/406288178
https://www.dogdrip.net/406291198

</details>

**Comment by JobcenterTycoon** [comment]
I reported the `###im_box` issue already and it got fixed in https://github.com/easylist/easylist/commit/3bd09b072850ac66703e408a5a60b0fd2ad7f524

**Comment by Seohare** [comment]
사진 처럼 애드 쉴드의 광고가 차단 되지 않습니다.

사이트는 https://loawa.com/ 입니다. 몇 초 기다린 후에 광고가 나옵니다. 애드 쉴드의 광고는 잘 차단이 되지 않는 것 같습니다. 스크립트 또는 필터를 개선해주세요.

![Uploading Screenshot_20220605-212656_Samsung Internet.png…]()

**Comment by green1052** [comment]
Ad-Shield Update Log

https://docs.ad-shield.io/update-notes

**Comment by JobcenterTycoon** [comment]
Last entry: 2.4.2022

**Comment by Seohare** [comment]
List-KR 필터에 ||jsdelivr.net^ 규칙을 넣어주세요. 애드쉴드의 분석 도메인 입니다.

**Comment by green1052** [comment]
> List-KR 필터에 ||jsdelivr.net^ 규칙을 넣어주세요. 애드쉴드의 분석 도메인 입니다.

~~jsdelivr.net는 cdn 사이트입니다.
차단시 사이트가 꺠질 위험이 있어 추가하기 어렵습니다.~~

**Comment by seia-soto** [comment]
동일하게 해당 도메인은 많은 웹 사이트의 정적 자산을 배포하고 있는 도메인으로 차단 시에는 많은 웹 사이트가 깨질 수 있어 차단이 불가능한 점 안내드립니다. 특정 도메인에 한해서 추가는 가능하나 AdGuard의 DNS 필터링 기능에서 와해되어 타 웹 사이트까지 영향을 끼칠 수도 있습니다.

**Comment by green1052** [comment]
> 동일하게 해당 도메인은 많은 웹 사이트의 정적 자산을 배포하고 있는 도메인으로 차단 시에는 많은 웹 사이트가 깨질 수 있어 차단이 불가능한 점 안내드립니다. 특정 도메인에 한해서 추가는 가능하나 AdGuard의 DNS 필터링 기능에서 와해되어 타 웹 사이트까지 영향을 끼칠 수도 있습니다.

![image](https://user-images.githubusercontent.com/34261355/172147252-12e6b334-bc19-49a8-b154-3783e9e1b968.png)

**Comment by green1052** [comment]
<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/34261355/172147378-393a9c59-31e1-4f20-8a83-f236f5c4b6d7.png)

</details>

**Comment by seia-soto** [comment]
DNS 필터링의 경우 서브도메인까지 차단되므로 전혀 차단할 이유가 없습니다.

**Comment by Seohare** [comment]
네, 알겠습니다.

**Comment by gaeulbyul** [comment]
애드쉴드의 트래킹 스크립트를 차단하고 싶으시다면 jsdelivr.net 도메인을 막지 말구 [스크립트 주소를 직접 지정해서 차단](https://github.com/uBlockOrigin/uAssets/issues/9717#issuecomment-1094195224)하면 되지 않을까요. (seia-soto님 말씀하셨다시피) 도메인을 막는다면 자칫 사이트 기능 자체에 영향을 줄 수 있습니다.

(가령, [로아와](https://loawa.com)의 경우 jsdelivr에서 Vue.js 등 애드쉴드와 무관한 JS/CSS도 가져와서 쓰고 있습니다.)

다만 트래킹 스크립트를 막는다고 해서 애드쉴드의 광고를 지우는 효과는 없긴 합니다. (List-KR은 광고차단에 중점을 두는 필터이구, 트래킹 관련은 프라이버시 관련 별도의 필터에서 다루는 걸로 알고있습니다.)

**Comment by Seohare** [comment]
혹시 애드가드 자바 스크립트 작성 규칙이랑 웹 요소 차단 규칙 작성 방법 알려주실 분 계신가요? 예시 규칙도 알려주세요. 
 사진에 노란색으로 밑 줄 친 부분을 제가 직접 차단하고 싶고, 애드 쉴드의 광고 차단 방법에 대해 연구해 볼려고 그러는 겁니다.

<details>
<summary>Details</summary>

![화면 캡처](https://user-images.githubusercontent.com/99063049/172330566-8c36a442-b29d-4115-97dc-6d9ff2bce298.png)

</details>

**Comment by piquark6046** [comment]
@KARINA76756 https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters
https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#scriptlets
https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-redirects.md

**Comment by gaeulbyul** [comment]
여기 이슈트래커는 애드쉴드 측에서 자주 모니터링하고 있습니다. 만악 광고차단 방법을 공개적으로 밝힌다면 금방 막힐거에요.
그리구 노란색 표시한 부분은 (google 어쩌고를 제외하면) 광고표시와는 무관한 걸로 보입니다..

**Comment by Seohare** [comment]
인벤 사이트에서 광고가 다시 노출 됩니다. 필터 수정 바랍니다.

<details>
<summary>Screenshots</summary>

![d](https://user-images.githubusercontent.com/99063049/173022562-35d4c968-0c79-441a-8045-4ba6a506c629.png)


</details>

**Comment by seia-soto** [comment]
> 인벤 사이트에서 광고가 다시 노출 됩니다. 필터 수정 바랍니다.
> 

AdGuard에서는 아직 Shadow DOM 내부 요소에 대한 직접적인 차단이 제공되지 않는 경우가 있어 당분간은 개체 속성값(id, class 등)이 변경되면 그 때마다 차단을 해야 할 수 있는 점 참고부탁드립니다. 일단은 지금처럼 알려주시면 계속해서 수정은 할 예정입니다. 대개는 AdGuard 요소 차단기를 사용하여 직접 차단이 가능합니다. List-KR에 기여해주셔서 감사합니다.

**Comment by rock5684** [comment]
<details>
<summary>Screenshots</summary>

![84CB1911-4E5E-40CD-A71E-0FFAD195BD0A](https://user-images.githubusercontent.com/104014662/173083433-97e487e6-8c4f-4bde-9ae6-5f8807fcddf5.png)

</details>

모바일 트게더의 경우 옛날부터 갑자기 애드쉴드 광고 자체는 성공적으로 막혔는데 대신 저렇게 빈 광고박스가 사라지지 않긴 합니다.

**Comment by seia-soto** [comment]
@rock5684 

> 모바일 트게더의 경우 옛날부터 갑자기 애드쉴드 광고 자체는 성공적으로 막혔는데 대신 저렇게 빈 광고박스가 사라지지 않긴 합니다.

macOS Safari와 iOS Safari 모두에서 문제를 재현할 수 없습니다. AdGuard 앱에서 필터 업데이트를 한 번만 부탁드립니다.

<details>
<summary>Screenshots</summary>

![IMG_0363C0F8CFBA-1](https://user-images.githubusercontent.com/30369714/173086443-47f60939-b575-40df-8081-d844fa9535e6.jpeg)

</details>

**Comment by seia-soto** [comment]
## Blocking AdShield with UserScript, 유저스크립트로 애드쉴드 차단하기

- https://github.com/list-kr/microshield

<details>
<summary>English</summary>

We're providing microShield to mitigate AdShield in faster term. The speed of shipping ad blocker rules is slower since the available strategies are limited to existing functionalities of ad blockers.

In this comment, I am suggesting the way to inject our microShield script.

> Note that the script is not merged to upstream, yet!

<table>
<tr>
	<td>Source
	<td>Level
	<td>Link
<tr>
	<td>List-KR/microShield
	<td>Active
	<td>https://github.com/List-KR/microShield/raw/main/microShield.user.js
<tr>
	<td>seia-soto/filter-kr
	<td>Experimental
	<td>https://github.com/seia-soto/filter-kr/raw/master/scripts/adshield.user.js
</table>

### Platform Support

For browsers, I recommend Violentmonkey which is maintained actively and fully driven by the community.

<table>
<tr>
	<td>Platform
	<td>Name
	<td>Transparency
	<td>Link
<tr>
	<td>Browser
	<td>Violentmonkey
	<td>Community
	<td>https://violentmonkey.github.io/
<tr>
	<td>Browser, Firefox-specific
	<td>Greasemonkey
	<td>Community
	<td>https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/
<tr>
	<td>Browser, Safari-specific
	<td>UserScripts
	<td>Community
	<td>https://itunes.apple.com/us/app/userscripts/id1463298887
<tr>
	<td>Windows
	<td>AdGuard for Windows
	<td>Private
	<td>https://adguard.com/en/adguard-windows/overview.html
<tr>
	<td>macOS
	<td>AdGuard for macOS
	<td>Private
	<td>https://adguard.com/en/adguard-mac/overview.html
<tr>
	<td>Android
	<td>AdGuard for Android
	<td>Private
	<td>https://adguard.com/en/adguard-android/overview.html
<tr>
	<td>Browser
	<td>Tampermonkey
	<td>Private
	<td>https://www.tampermonkey.net/
</table>

</details>

<details>
<summary>한국어</summary>

저희는 AdShield를 더 빨리 완화시키기 위해 microShield를 제공합니다. 광고 차단기 규칙이 전달되는 속도는 사용할 수 있는 전략이 광고 차단기의 기존 기능에 한정되기 때문에 더 느립니다.

이 댓글에서 저희의 microShield 스크립트를 주입할 수 있는 방법을 보여드리고 있습니다.

<table>
<tr>
	<td>출처
	<td>수준
	<td>링크
<tr>
	<td>List-KR/microShield
	<td>활성
	<td>https://github.com/List-KR/microShield/raw/main/microShield.user.js
<tr>
	<td>seia-soto/filter-kr
	<td>실험적
	<td>https://github.com/seia-soto/filter-kr/raw/master/scripts/adshield.user.js
</table>

### 플랫폼 지원

브라우저에서는 커뮤니티에 의해 운영되며 활발하게 유지보수되고 있는 Violentmonkey를 추천합니다.

<table>
<tr>
	<td>플랫폼
	<td>이름
	<td>투명성
	<td>링크
<tr>
	<td>Browser
	<td>Violentmonkey
	<td>공개
	<td>https://violentmonkey.github.io/
<tr>
	<td>Browser, Firefox-specific
	<td>Greasemonkey
	<td>공개
	<td>https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/
<tr>
	<td>Browser, Safari-specific
	<td>UserScripts
	<td>공개
	<td>https://itunes.apple.com/us/app/userscripts/id1463298887
<tr>
	<td>Windows
	<td>AdGuard for Windows
	<td>사유
	<td>https://adguard.com/en/adguard-windows/overview.html
<tr>
	<td>macOS
	<td>AdGuard for macOS
	<td>사유
	<td>https://adguard.com/en/adguard-mac/overview.html
<tr>
	<td>Android
	<td>AdGuard for Android
	<td>사유
	<td>https://adguard.com/en/adguard-android/overview.html
<tr>
	<td>Browser
	<td>Tampermonkey
	<td>사유
	<td>https://www.tampermonkey.net/
</table>

</details>

**Comment by Seohare** [comment]
> ## Blocking AdShield with UserScript, 유저스크립트로 애드쉴드 차단하기
> * https://github.com/list-kr/microshield
> 
> 영어
> 한국어

adshield-analytics-verification 스크립트 제거 규칙도 넣어주시면 좋을 것 같습니다.

<details>
<summary>Screenshots</summary>

![d](https://user-images.githubusercontent.com/99063049/173169010-fdf1d813-acb6-40c0-93fc-b9a846c643ef.png)

</details>

**Comment by seia-soto** [comment]
@NoName926 

> 
> adshield-analytics-verification 스크립트 제거 규칙도 넣어주시면 좋을 것 같습니다.
>

아래 코드를 사용하여 광고 차단기를 끈 상태로 해당 meta 태그의 사용 여부를 확인했으나 액세스 흔적이 없었습니다. 단, 조만간 트래킹도 완전히 차단할 수 있도록 하겠습니다.

<details>
<summary>Details</summary>

```js
  unsafeWindow.HTMLMetaElement.prototype.getAttribute = new Proxy(
    unsafeWindow.HTMLMetaElement.prototype.getAttribute,
    {
      apply(target, thisArg, argsList) {
        const [key] = argsList
        const original = Reflect.apply(target, thisArg, argsList)
        
        console.log(key, original)
        
        return original
      }
    }
  )
  
  unsafeWindow.HTMLMetaElement.prototype.getAttributeNS = new Proxy(
    unsafeWindow.HTMLMetaElement.prototype.getAttributeNS,
    {
      apply(target, thisArg, argsList) {
        const [ns, key] = argsList
        const original = Reflect.apply(target, thisArg, argsList)
        
        console.log(ns, key, original)
        
        return original
      }
    }
  )
```

</details>

**Comment by seia-soto** [comment]
Next update on scripts and filter rules are in pending state. I'll start validating and reversing their infrastructure when the `500` error fixed. We go as they go. I am monitoring changes regularly.

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/30369714/173238992-f3d42a82-ce05-4752-b8e8-06a4683be784.png)

</details>

**Comment by Seohare** [comment]
마이크로쉴드를  다운 받았더니 아래  사진처럼 뜹니다. 오진인가요?
![a](https://user-images.githubusercontent.com/99063049/173309423-9aa2c4d8-748c-4d80-bb26-e26cff877fe9.png)
?

**Comment by green1052** [comment]
오진이며 잘못된 방법으로 설치하셨습니다.

**Comment by green1052** [comment]
https://github.com/List-KR/microShield#how-to-install
