### ISSUE TITLE
AB: www.inven.co.kr

### ISSUE THREAD

**Issue by green1052** [List-KR/List-KR#278]
### URL

https://www.inven.co.kr/

### FILTERS

list-kr

### Browser

(Other)

### Ad-Blocker

AdGuard for Windows

### Comment

![image](https://user-images.githubusercontent.com/34261355/161963085-f5569000-fda5-4150-aa5b-8ef557c641ee.png)

version
![image](https://user-images.githubusercontent.com/34261355/161963161-05aae518-ec24-4670-bfad-289fe56eef5a.png)

**Comment by piquark6046** [comment]
Duplicate of #277
