### ISSUE TITLE
에브리타임 앱 광고 차단

### ISSUE THREAD

**Issue by novn123** [List-KR/List-KR#28]
||ad.everytime.kr^ 를 추가하면 게시판 하단 광고는 사라집니다

다만 메인 페이지 광고는 어떻게 해야 사라지는지를 모르겠네요.. 혹시 차단가능하다면 필터 업데이트해주시면 감사하겠습니다

![Screenshot_20200319-024343_Everytime~01](https://user-images.githubusercontent.com/62351198/76990899-09dc6c80-698c-11ea-8342-9b7e6a500427.jpg)

**Comment by ghost** [comment]
안녕하세요, `||ad.everytime.kr^` 규칙은 이미 [정의되어 있습니다.](https://github.com/List-KR/List-KR/blob/master/filter.txt#L526)

메인 페이지 광고의 경우 로그 등 구체적인 정보가 있어야 차단이 가능한데, 해당 광고 시청 시 발생하는 로그를 AdGuard 메인 앱 -> 필터링 로그에서 확인하여 첨부해주시면 감사하겠습니다.

**Comment by novn123** [comment]
![Screenshot_20200330-152034_AdGuard~01](https://user-images.githubusercontent.com/62351198/77881622-54b68800-729a-11ea-8ae9-3b99e0f65c5f.jpg)
![Screenshot_20200330-152121_AdGuard~01](https://user-images.githubusercontent.com/62351198/77881625-56804b80-729a-11ea-8150-2ffd07d628a9.jpg)
![Screenshot_20200330-152154_AdGuard~01](https://user-images.githubusercontent.com/62351198/77881627-5718e200-729a-11ea-9bfe-122624da6292.jpg)


https://everytime.kr/page/adredirect?url=https%3A%2F%2Fwww.hsd.co.kr%2Fevent%2Fevent_view%2F478

https://ad.everytime.kr/adClick?adToken=G1dHQX5dpoU7ZV2XyvVfK5Juxf8mu0eVV80LrxXSoJps0OtIfschAsQQTQwl9OhxKgiNzTaszaEDnlTk81x%2BN%2BfsTCDJmnMEbepJSiPkvfoW3ZcB%2BwcIPwDUfHA%2Fwy6t9d1gLOMGG8UjABPVJxcQFuQ0%2FloSJbo%2Fi0Y5tfS34yj%2B%2BxM1FSiUr8eHePM2hBxPmrPgSb6nV13ASoAouA0UZyFK6TQuyD56lhds99rirtOd0eyJ2L6TF%2Fvsohxo%2FdgM


규칙에 ad.everytime.kr은 있는데 DNS 필터?에 따로 사용자 규칙을 등록해야 제대로 차단이 되는 거 같습니다 이건 어쩔 수 없는 건가요?

**Comment by ghost** [comment]
안녕하세요, 답변이 늦어져 죄송합니다.

첨부해주신 사진을 봤을 때 `ad.everytime.kr`로의 요청은 DNS를 통해 이루어지는 것으로 보입니다. 본 필터는 DNS 단의 요청에 관여하는 부분이 존재하지 않기 때문에 말씀해주신 것처럼 사용자 지정 DNS 필터를 사용하여야 해결이 가능한 문제로 보입니다. 또한 AD redirect 페이지에 관해서는 https://github.com/List-KR/List-KR/commit/9b5b315dd00b4c85b7dbcd040c73cb9e195eab18 커밋에서 패치를 배포하였습니다. 추후 동일한 문제가 발생할 시 이슈를 등록해 주시면 확인해보도록 하겠습니다.
