### ISSUE TITLE
tgd.kr 광고 차단

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [List-KR/List-KR#29]
광고 자체는 차단이 되나, 광고 영역이 남아있어 아래 내용이 추가되는게 좋을 것 같습니다.

```
tgd.kr###main-content > div.frame > div:nth-child(2):NOT(#article-list)
tgd.kr###article-list > div:nth-child(3)
```
* `:NOT(#article-list)`를 붙이지 않으면, 다른 페이지에서 게시글 리스트가 날아갑니다.

**Comment by ghost** [comment]
https://github.com/List-KR/List-KR/commit/36982fea4f0b6bf730d657849ff19964b4ef8edd 커밋에서 반영되었습니다.
