### ISSUE TITLE
rp5.ru - adblock detection

### ISSUE THREAD

**Issue by BlazDT** [List-KR/List-KR#3]
https://rp5.ru/%D0%9F%D0%BE%D0%B3%D0%BE%D0%B4%D0%B0_%D0%B2_%D0%91%D0%B0%D0%BB%D1%82%D0%B5,_%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D0%B0

Following rule causes adblock detection:
##ins.adsbygoogle[data-ad-client]:not([data-matched-content-ui-type])

Screenshot in first post:
https://github.com/AdguardTeam/AdguardFilters/issues/35046

**Comment by ghost** [comment]
Fixed at https://github.com/List-KR/List-KR/commit/f85ba6424f375218c706d82091cfa97a60be45e7. Thanks for the report!
