### ISSUE TITLE
피들리 내용이 안보이는 문제

### ISSUE THREAD

**Issue by joyfuI** [List-KR/List-KR#3]
파이어폭스에서 uBlock Origin을 사용하고 있습니다.

[피들리](https://feedly.com/)라는 RSS 구독 사이트에서 본문이 숨겨져서 보이지 않는 문제가 있습니다.

로그를 살펴보니
> feedly.com##div.list-entries>div:not([data-inlineentryid]):not([data-uninlineentryid])

라는 필터가 원인으로 보입니다.

**Comment by ptrkr** [comment]
안녕하세요, https://github.com/List-KR/List-KR/commit/f9c25dda85da4701aed5fdfb725757cf07778fc3 에서 업데이트 하였습니다. 또 다른 문제가 있다면 언제든지 제보 부탁드립니다. 감사합니다 :)
