### ISSUE TITLE
트게더 (tgd.kr) 글 보관함 필터링 오류

### ISSUE THREAD

**Issue by asteriskyg** [List-KR/List-KR#30]
`tgd.kr###main-content > div.frame > div:nth-child(2):NOT(#article-list)`
해당 필터가 https://tgd.kr/member/mylist (글 보관함)의 리스트를 날려버립니다.

**Comment by ghost** [comment]
#29 이슈에서 제안되어 추가하였으나 문제가 발생하여 https://github.com/List-KR/List-KR/commit/f7d0e3767be35ca2af283fff1ba450923c97c280 커밋에서 제거하였습니다.
