### ISSUE TITLE
tgd.kr 필터 추가 요청

### ISSUE THREAD

**Issue by asteriskyg** [List-KR/List-KR#31]
`tgd.kr###article-list > div:nth-of-type(3)`
`tgd.kr###article-list-category + div`
`tgd.kr###main-menu > div:last-child`
`tgd.kr$$div[style="padding:0em 1em;"]`

![image](https://user-images.githubusercontent.com/25531016/78472095-3ad0e580-7771-11ea-866e-c5e8514b16b5.png)
![image](https://user-images.githubusercontent.com/25531016/78472117-6b188400-7771-11ea-8937-727bae21a0a8.png)
빨간색 박스 부분에 관여하는 필터입니다.

**Comment by ghost** [comment]
https://github.com/List-KR/List-KR/commit/52491dd2fc2317e69e6c7be486a74bf8dec9f3c1 커밋에서 반영되었습니다.
