### ISSUE TITLE
(데스크탑) 네이버tv, 카카오tv 광고차단 실패

### ISSUE THREAD

**Issue by tmddlfdl23** [List-KR/List-KR#33]
네이버 tv는 탑100 같은 방송사에서 광고를 관리하는 동영상이 아닌 
네이버에서 관리하는 동영상의 경우 차단이 안되는 문제가 발생합니다.

가령 네이버tv 메인의 지금 뜨는 영상 같은 경우입니다.
https://tv.naver.com/v/13242040

카카오tv(다음)은 모든 동영상이 아예 재생되지 않습니다.
광고차단에 의한 동영상자체의 차단으로 보입니다.
https://tv.kakao.com/channel/2653171/cliplink/407966152

**Comment by ghost** [comment]
안녕하세요, 네이버TV 메인의 동영상은 제 환경에서 정상적으로 차단되는 것으로 보입니다.
![Ss9p_20200408092230](https://user-images.githubusercontent.com/27128153/78731371-85717e00-797a-11ea-8ebd-2374a78cc6d8.png)

카카오TV의 경우 특정 URL에서 정상적인 광고 데이터를 받아오지 못하면 차단하는 방식인데, 이는 내부 서버의 구조와 관련된 문제라 혼자서 해결이 어려운 문제입니다. 로그 등 상태를 충분히 파악할 만한 정보가 있다면 본 이슈에 추가적으로 기재해주시면 감사하겠습니다.
