### ISSUE TITLE
IC: 다수의 사이트

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#335]
### URL

해피머니
1. 기프트몰 우측 영역은 문상으로 기프트 코드 등을 사는 영역이라 차단하면 안됩니다.
2. 추천제휴상품: 동일 이슈
3. 해피캐시로 이용할 수 있는 주요 쇼핑몰: 동일 이슈
![happymoney](https://user-images.githubusercontent.com/105501966/168420856-87293b3b-24ae-4aa4-b87e-b8e2ce3988dd.png)
![happymoney](https://user-images.githubusercontent.com/105501966/168420920-97851b0d-3a57-454e-830c-671f6107ee9d.png)

아카라이브
사이드바에서 나무뉴스 영역이랑 나무위키 인기검색어 영역이 차단됩니다.

디시인사이드
leftbanner 영역 공백이 차단이 안되고 있습니다. 해당 클래스는 전부 광고 영역으로 보입니다.
![dcinside](https://user-images.githubusercontent.com/105501966/168420785-3461dc7c-70a0-43ef-99c6-9168c1b2f2ea.png)

### FILTERS

List-KR v2022.514.4

### Browser

Google Chrome

### Operating System

Microsoft Windows 10, (Other)

### Ad-Blocker

uBlock Origin

**Comment by ghost** [comment]
@piquark6046 디시인사이드가 v2022.514.7에서도 해당 영역이 공백으로 나오는데 확인 부탁드립니다.
(uBO 1.42.4 / Chrome 101)

**Comment by piquark6046** [comment]
@rlfehd7915 
Did you sign in?

**Comment by ghost** [comment]
> @rlfehd7915 Did you sign in?

@piquark6046 네, 근데 로그아웃 상태에서도 동일하게 공백으로 뜹니다.
![image](https://user-images.githubusercontent.com/105501966/168422792-daea97bb-c5c2-453d-a137-0afb759a6fbb.png)
코드 상에서는 leftbanner가 차단되지 않고 남아있는 걸로 보입니다.

**Comment by ghost** [comment]
아카라이브 사이드바의 나무뉴스 영역은 [SPONSORED 콘텐츠](https://arca.live/b/request/42520167)이므로 차단을 해제할 이유가 없습니다.

**Comment by ghost** [comment]
> 아카라이브 사이드바의 나무뉴스 영역은 [SPONSORED 콘텐츠](https://arca.live/b/request/42520167)이므로 차단을 해제할 이유가 없습니다.

편의기능이 아니라는 게 아카라이브 쪽 편의기능이 아니라는 말이지 SPONSORED 콘텐츠라는 말은 아니지 않을까요? 동일한 이유에서 나무위키 인기검색어 숨김도 제공되지 않고 있고 컨텐츠도 리워드 이런 게 아니라 뉴스라서요. (단 나무위키에서는 나무뉴스를 숨길 수 있어요)
아카라이브랑 나무뉴스 운영사가 동일한데 이걸 광고로 봐야 하는지는 모르겠습니다. 대부분의 기사인 연합뉴스도 (한국)국가기간통신사고요.
사이트 운영자 쪽에서도 이런 요지의 말을 했던 걸로 알고 있습니다.

![image](https://user-images.githubusercontent.com/105501966/168435074-ca2dc7a4-a11e-4d76-841a-774248a80c76.png)

**Comment by ghost** [comment]
커뮤니티 사이트인 아카라이브와 뉴스 사이트인 나무뉴스가 어떤 관계가 있을까요? 나무위키에서야 숨김 기능을 별도로 제공하고 있지만 아카라이브는 편의성 콘텐츠가 아니라는 이유로 숨김 기능이 제공되고 있지 않습니다.

과거부터 지금까지 List-KR 필터는 광고뿐 아니라 스폰서 콘텐츠 또한 차단하는 데 중점을 두어왔습니다. 운영사만 같을 뿐 전혀 관련이 없는 두 서비스를 사이드바에 붙여놓는 것을 스폰서 콘텐츠가 아니라고 보기는 어렵다는 것이 개인적인 의견입니다.

**Comment by ghost** [comment]
나무위키 실검 사이드바의 경우 운영사인 umanle S.R.L.이 인수 공지에 나무위키 커뮤니티(당시 가칭)를 개설하겠다는 입장을 밝혔기에 Incorrect Blocking으로 간주될 여지가 있지만, 나무뉴스의 경우는 이렇다할 이유가 없습니다.

**Comment by ghost** [comment]
해당 사이드바에서 표출되는 나무뉴스 내용을 봤을 때, sponsored 기사보다는 정보 전달형 기사로 보입니다.
나뮤뉴스 사이트에서 adsense 광고를 띄우긴 하지만 사이트에 영리성이 있다고 스폰서드 콘텐츠로 띄우는 건 과도한 해석이라고 느껴집니다. (아카라이브 콘텐츠가 아니라고 스폰서드로 보는 것도 마찬가지고요)
동일한 이유에서 디시인사이드도 디시뉴스를 제공하고요. 아마 나무위키 운영사 쪽에서 디시인사이드를 참고한 것으로 보입니다.

스폰서드형 컨텐츠는 #332 나 아래 같은 경우가 해당되고 이런 경우에는 해당되지 않는다고 생각합니다.
![image](https://user-images.githubusercontent.com/105501966/168453331-be3a01b1-b5a5-4d87-99db-528f088f54e7.png)

**Comment by seia-soto** [comment]
제가 Umale SRL 사에서 운영하는 서비스를 거의 이용하지 않아 정황 파악에는 어려움이 있을 수 있으나 말씀하신 잘못 차단되었다고 주장하시는 개체가 아래 사진과 같다면 저는 다음의 이유를 들어 차단이 정당하다고 생각합니다.

1. 서비스는 서비스 별로 봅니다.
운영사가 같고 다름을 떠나서 두 웹 사이트는 사용 목적이 직접적으로 연관되는 웹 사이트가 아닙니다.

2. 웹 사이트의 추천으로 표시되는 경우는 실제 기사를 보여주기 위함인지 그 의도를 정확히 파악할 수가 없고 '편의기능'이 아니라는 점에서 유추하는 경우 광고로 간주할 수 있습니다.
나무위키 운영사인 Umale SRL은 광고를 게제하기 시작한 시점부터 자사 서비스를 통해 수익성을 개선하겠다고 밝힌 점이 있습니다. 이에 따라 자사 서비스의 사용 유도 광고라고 저는 판단할 수 있다고 봅니다.

3. 광고는 광고입니다.
AdGuard와 uBO 등 여러 광고 차단기에서도 **유용한 광고 필터**는 따로 제공되고 있습니다. 이 유용한 광고 필터는 검색엔진 등이 추천하는 컨텐츠 등 직/간접적으로 도움을 주는 광고를 허용하는 필터입니다. 말씀하신 아래 객체는 1번 근거에 의하여 커뮤니티인 나무라이브의 사용 목적을 크게 벗어나는 개체로 광고라고 판단됩니다. 광고가 도움을 주느냐는 또 다른 문제이며 특히 유용한 광고 필터가 따로 존재하는 것처럼 저희는 사용자에게 모든 광고를 차단할 것인지 유용한 광고는 남길 것인지 선택권을 줄 필요가 있다고 생각합니다.

![image](https://user-images.githubusercontent.com/30369714/168477720-eaf01529-2351-4905-a5fd-8990334ce65b.png)
