### ISSUE TITLE
103.204.13.68 rule is vaild?

### ISSUE THREAD

**Issue by green1052** [List-KR/List-KR#339]
[specific_ELEMHIDE.txt#L454](https://github.com/List-KR/List-KR/blob/master/filters-share/specific_ELEMHIDE.txt#L454)
[specific_ELEMHIDE.txt#L455](https://github.com/List-KR/List-KR/blob/master/filters-share/specific_ELEMHIDE.txt#L455)

103.204.13.68 redirect naver.com

**Comment by green1052** [comment]
umm i found illegal webtoon site 

http://103.204.13.68:8901/
http://www.11toon41.com/

![image](https://user-images.githubusercontent.com/34261355/168469421-7a370dbe-d67a-4e1d-b423-5cb63d696233.png)

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/112517

**Comment by green1052** [comment]
👌
