### ISSUE TITLE
iMBC 온에어 광고차단

### ISSUE THREAD

**Issue by himawarihome** [List-KR/List-KR#35]
지금 필터의
||smrmembers-smr.smartmediarep.com/smc/smrmembers/$domain=~allvod.sbs.co.kr|~news.sbs.co.kr|~news.tvchosun.com|~onair.imbc.com|~play-tv.kakao.com|~programs.sbs.co.kr
에서 ~onair.imbc.com 제거해주세요
그래야
http://onair.imbc.com/
에서 동영상 광고가 제거됩니다.

**Comment by ghost** [comment]
안녕하세요. 해당 규칙은 iMBC 온에어에서 동영상이 제대로 재생되지 않는 문제를 해결하고자, 실 테스트 과정에서 AdGuard 기본 기능으로 동영상 광고가 스킵되는 것을 확인한 이후 삽입한 것으로 기억합니다.

현재 개인적인 사정으로 당장 테스트가 어려워 추후 확인 및 수정할 수 있도록 하겠습니다. 필터 개발에 참여해 주셔서 감사합니다 :)

**Comment by ghost** [comment]
https://github.com/List-KR/List-KR/commit/d573a4cc5b9494101aa171d9ad3c8ee81fbff446 커밋에서 업데이트 하였습니다. 제보해 주셔서 감사합니다.
