### ISSUE TITLE
IB: toomics.com

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#354]
### URL

https://www.toomics.com/

### FILTERS

List-KR

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

**Comment by green1052** [comment]
problematic rule : ||thumb.toomics.com/upload/banner

**Comment by ghost** [comment]
@piquark6046
`specific_ELEMHIDE.txt` 내 `toomics.com##img[src*="://thumb.toomics.com/upload/banner/"]`
이것도 있어서 문제가 발생하는 것 같습니다. 그리고 배너 차단할 거면 `##.header__banner`, `##.close-floating`, 그리고 `##.fluid-banner`도 차단하는 게 좋을 것 같네요.

**Comment by piquark6046** [comment]
Done.
