### ISSUE TITLE
AD: toomics.com

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#355]
### URL

https://www.toomics.com/

### FILTERS

List-KR

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Comment

![image](https://user-images.githubusercontent.com/105501966/169633952-fa0c5d6b-9c1d-4d96-894b-a07f919bb6ed.png)
`##.header__banner`, `##.close-floating`

![image](https://user-images.githubusercontent.com/105501966/169633968-c2d760ec-b5dd-46cf-b8ec-02e30aefe1d1.png)
`##.fluid-banner`

광고 영역인지는 모르겠지만 어쨌든 이미지는 차단되어 있으니 영역도 차단해야 된다고 생각합니다.

**Comment by ghost** [comment]
@piquark6046 `##.close-floating`도 차단해주시면 안되나요? 화면 우측 하단에 있습니다.
![image](https://user-images.githubusercontent.com/105501966/169634792-81f077fc-0a7b-4bcb-8646-72ef1add0a5b.png)

![image](https://user-images.githubusercontent.com/105501966/169634846-892b4474-5dba-49a6-a51e-d3013578d77e.png)
그리고 상단에 있는 margin도 삭제가 가능할까요?

**Comment by piquark6046** [comment]
Done.
