### ISSUE TITLE
AD: edaily.co.kr

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#356]
### URL

https://www.edaily.co.kr/
https://www.edaily.co.kr/news/read?newsId=01433366632331216&mediaCodeNo=257
https://m.edaily.co.kr/news/read?newsId=01433366632331216&mediaCodeNo=257

### FILTERS

List-KR

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Comment

PC
1.
![image](https://user-images.githubusercontent.com/105501966/169637924-49521000-3fac-4303-bf33-11026935b857.png)
2.
![image](https://user-images.githubusercontent.com/105501966/169637964-a3671acb-6fa3-4c6a-a812-b22f30cc4aa2.png)
3. 사이드바 영역에 광고 공간 많아요
모바일
1.
![image](https://user-images.githubusercontent.com/105501966/169638335-66671571-ef70-4e4a-9ed2-38bfdc108830.png)
2. (아래에도 광고 공간 많아요)
![image](https://user-images.githubusercontent.com/105501966/169638349-7499abb9-7f1c-4bfc-b1f9-de849fc40db7.png)

**Comment by ghost** [comment]
@piquark6046 혹시 PC에서 뜨는 팝업도 차단해주실 수 있나요
`https://www.edaily.co.kr/popup/viewpopup.html?v=*`

**Comment by piquark6046** [comment]
Done.
