### ISSUE TITLE
디시 공식앱에서 

### ISSUE THREAD

**Issue by azhysil** [List-KR/List-KR#36]
디시 공식앱을 사용하다보면 계속 로딩하는 표시만 뜨고 로딩하지 않는 상황이 발생하는데 해결방법을 알고 계신다면 알려주시면 감사하겠습니다

**Comment by ghost** [comment]
안녕하세요. 갤럭시 노트 9 (SM-N960NK)에서 해당 문제를 재현할 수 없습니다. 아마 AdGuard 자체의 문제로 추정되는데, 그렇다면 안드로이드 애플리케이션 버그 리포트를 작성하셔야 해결이 가능한 문제로 보입니다.
