### ISSUE TITLE
아프리카tv 애드벌룬 광고 제보

### ISSUE THREAD

**Issue by bobblun** [List-KR/List-KR#37]
||adballoon.afreecatv.com/api*^

아프리카tv 설치형 프로그램 애드벌룬 광고 차단 주소입니다
추가해주시면 감사하겠습니다

**Comment by ghost** [comment]
https://github.com/List-KR/List-KR/commit/f10b61451071bc76ef1b7741ddccf438212ec597 커밋에서 해결되었습니다.
