### ISSUE TITLE
삼성닷컴 페이지에서 제품구매 불가

### ISSUE THREAD

**Issue by Jungmac** [List-KR/List-KR#38]
adguard 보호 작동중일때 삼성닷컴내 제품구매 페이지에서 제품구매 버튼이 아예 동작하지 않습니다.

브라우저나 플랫폼(Mac, Windows, 모바일) 상관없이 벌어지는 현상 같으며 

일단 애드가드 보호를 일시정지 시키면 정상적으로 구매 절차가 진행되긴합니다.

확인 좀 부탁드리겠습니다.

**Comment by ghost** [comment]
안녕하세요, 확인은 해보겠으나 어떤 페이지에서 해당 증상이 나타나는지 로그와 함께 기술해 주시면 감사하겠습니다.
