### ISSUE TITLE
AD: coupang.com

### ISSUE THREAD

**Issue by green1052** [List-KR/List-KR#381]
### URL

l

### FILTERS

list-kr

### Browser

Google Chrome

### Operating System

Microsoft Windows 11

### Ad-Blocker

uBlock Origin

### Comment

||coupang.com/*&addtag=*ptag=*&redirect=landing&traceid=*&placementid=*&impressionid=&campaigntype=$document

해당 규칙으로 인해 쿠팡 단축 URL 클릭시 차단됩니다.

**Comment by piquark6046** [comment]
Please email me the URL you visited and the original URL.

**Comment by green1052** [comment]
sent

**Comment by piquark6046** [comment]
https://partners.coupang.com/
https://github.com/List-KR/List-KR/issues/269#issuecomment-1090298189
