### ISSUE TITLE
AD: namu.wiki (UAIA)

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#384]
### URL

https://namu.wiki/w/%EB%82%98%EB%AC%B4%EC%9C%84%ED%82%A4:%EB%8C%80%EB%AC%B8

### FILTERS

List-KR

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Comment

나무뉴스 차단

**Comment by piquark6046** [comment]
Please enable AdGuard Annoyances.
