### ISSUE TITLE
AD: inven.co.kr

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#385]
### URL

https://www.inven.co.kr/

### FILTERS

List-KR

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Comment

인벤 사전예약, 브랜드 파트너 섹션

**Comment by ghost** [comment]
@piquark6046 저 부분은 Ad-Shield 아니고 단순 사이드바 섹션입니다.
![image](https://user-images.githubusercontent.com/105501966/171827920-182853e3-2c75-43ac-9b9e-211b3e1df188.png)

**Comment by piquark6046** [comment]
A rule blocking the section can be used for detecting an adblock user.

**Comment by seia-soto** [comment]
@rlfehd7915 해당 영역을 차단하면 애드쉴드에서 차단을 감지하게 되는 점 때문에 지금은 차단이 불가능합니다. 이후에 더 나은 해결책이 있다면 그 때 다시 차단하겠습니다. 더 좋은 차단 환경을 위해 노력해주셔서 감사합니다.
