### ISSUE TITLE
애드쉴드 광고차단 안 됨

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#388]
### URL

https://loawa.com/

### FILTERS

List-KR 

### Browser

Samsung Internet

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment

<details>
<summary>Screenshot</summary>

![Screenshot_20220605-212656_Samsung Internet](https://user-images.githubusercontent.com/99063049/172050693-27b1568a-18f0-4794-b68d-896c66cfd5ed.png)

</details>

사진 처럼 애드 쉴드의 광고가 차단 되지 않습니다.

사이트는 https://loawa.com/ 입니다. 몇 초 기다린 후에 광고가 나옵니다. 애드 쉴드의 광고는 잘 차단이 되지 않는 것 같습니다. 스크립트 또는 필터를 개선해주세요.

**Comment by piquark6046** [comment]
Duplicate of #277

**Comment by Seohare** [comment]
문제 해결되었나요?

**Comment by seia-soto** [comment]
문제는 해결되지 않았으나 관리 및 문제 추적의 편의 상 AdShield와 관련된 모든 문제를 #277 에서 다룰 예정입니다. AdShield와 관련해서는 새로운 이슈를 생성하지 말아주시고 #277 에 남겨주세요.

**Comment by KARINA76756** [comment]
네
