### ISSUE TITLE
Ad-Shield not blocking ads

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#389]
### URL

https://loawa.com/

### FILTERS

List-KR

### Browser

Samsung Internet

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment

Ads in AdShield are not blocked as in the picture. The site is https://loawa.com/. After waiting a few seconds, the ad appears. Ad Shield doesn't seem to block ads well. Please improve the script or filter.

![Screenshot_20220605-212656_Samsung Internet](https://user-images.githubusercontent.com/99063049/172051429-dd24cf12-fd20-48f6-888a-ec5bae864b15.png)

**Comment by seia-soto** [comment]
Duplicate of #277 . We're handling all things related to AdShield on #277 .
