### ISSUE TITLE
(후방주의) hiyobi.me 모바일 광고 차단

### ISSUE THREAD

**Issue by 115dkk** [List-KR/List-KR#39]
이전에는 어차피 모바일로 애드가드 키면 들어갈 수 없었지만, 지금은 시대가 좋아져서 애드가드 VPN으로 애드가드를 킨 채 진입 가능합니다.

그런데 광고는 사라지지 않는군요. 조치가 필요합니다.

![Screenshot_20200811-232457_Chrome.jpg](https://user-images.githubusercontent.com/33408534/89909995-a4cf2f00-dc2a-11ea-95e8-73004802ec64.jpg)

문제의 광고들은 위쪽에 있습니다. 매우 거슬립니다...

![Screenshot_20200811-233409_AdGuard.jpg](https://user-images.githubusercontent.com/33408534/89910598-65eda900-dc2b-11ea-8c3a-29f92002fce1.jpg)

아마 광고 관련 요청은 이렇게 통과되는 것으로 추정됩니다. 헛다리일수도 있지만요.

**Comment by ghost** [comment]
안녕하세요, 말씀주신 환경에서 시도해 봤으나 문제를 재현할 수 없습니다. 프록시 요청을 통해 AdGuard를 사용 중이신 경우 VPN 방식으로 변경해보시기 바랍니다.

**Comment by 115dkk** [comment]
> 안녕하세요, 말씀주신 환경에서 시도해 봤으나 문제를 재현할 수 없습니다. 프록시 요청을 통해 AdGuard를 사용 중이신 경우 VPN 방식으로 변경해보시기 바랍니다.

이미 VPN 방식입니다. 정확히 말하면 애드가드 VPN이 SOCK5 프록시로 돌고, Adguard는 이를 프록시 서버로 인식하게 만드는 겁니다.

**Comment by 115dkk** [comment]
필터 뭐 꼈는지 등을 알려줘야 할까요?

**Comment by ghost** [comment]
![Screenshot_20200814-081424_Brave.jpg](https://user-images.githubusercontent.com/27128153/90196217-3e066d00-de06-11ea-98f1-fa0d45a242e6.jpg)

List-KR, AdGuard 베이스/트래킹/소셜/방해 요소 필터를 활성화하고 방문한 사진입니다. 상단에 광고가 노출되지 않습니다.

![Screenshot_20200814-081544_AdGuard.jpg](https://user-images.githubusercontent.com/27128153/90196360-7f971800-de06-11ea-9319-08ca5e1f6fe1.jpg)

https://github.com/List-KR/List-KR/commit/b31dfc3518ebdf8de64d1925961368c22949728d 커밋에서 광고 파일이 위치한 디렉터리 자체의 요청을 차단하였기 때문에 필터링 로그에도 차단되었다는 로그가 남습니다.

말씀주신 대로 어떤 필터를 사용하시는지, 사용 중이신 브라우저 및 OS가 어떻게 되는지 기술해 주셔야 할 것 같습니다.

**Comment by 115dkk** [comment]
Adguard 베이스 필터, 모바일 광고 필터, 추적 보호 필터, 방해 요소 필터, DNS 필터
adblock warning removal list
List-KR

을 씁니다.

브라우저는 chrome, OS는 안드로이드 9 입니다.

**Comment by 115dkk** [comment]
잠만, 지금은 차단 됩니다. 어떻게 해결된 건지는 모르겠지만 갑자기 이래서 조금 당황스럽군요.

**Comment by ghost** [comment]
해결된 것으로 보고 닫습니다. 추후 다시 발생하는 경우 새 이슈를 오픈해주세요.
