### ISSUE TITLE
필터 사용시 구글 수정된 검색창이 띄지 않습니다.

### ISSUE THREAD

**Issue by tjtnsgns** [List-KR/List-KR#4]
![Screenshot_20190408-213035_Firefox Beta](https://user-images.githubusercontent.com/28147257/55725160-9ea8bd00-59fc-11e9-9093-870ba44b7479.jpg)
![Screenshot_20190408-213252_Samsung Internet](https://user-images.githubusercontent.com/28147257/55725167-a4060780-59fc-11e9-8d18-fe9f2467c101.jpg)
 위와 같이 필터를 활성화 하면 잘못된 검색어릉 자동으로 변경해주는 데 그것이 띄지 않습니다.

**Comment by ptrkr** [comment]
https://github.com/List-KR/List-KR/commit/a73fa54fb2e2873f1de4302ac356997afab14a30 에서 해결하였습니다. 제보 감사드립니다.
