### ISSUE TITLE
http://en.btbit.org/

### ISSUE THREAD

**Issue by ChiftKey** [List-KR/List-KR#4]
qiqivv.com:4433

**Comment by ghost** [comment]
안녕하세요, 해당 도메인에서 어떠한 부분 (차단되지 않은 광고, 안티 애드블록 스크립트 등)이 문제가 되는지 알려주셔야 검토가 가능합니다. 실험 환경에서 접속 시에는 별다른 광고가 표시되지 않는 것으로 보입니다.

**Comment by ChiftKey** [comment]
안녕하세요^^ 수고많으십니다 ㅎㅎ
list-kr 잘 사용하고있습니다

제가 너무 대충 적었네요..

![2019-07-07_23-02-12](https://user-images.githubusercontent.com/40620901/60769629-2fcb2500-a10d-11e9-865e-c22107a04d91.png)

캡쳐를 보시면.. 
`(광고에 수위가 높아.. 모자이크 처리했습니다..)`

http://en.btbit.org/

사이트 접속 시, 검색창 하단의 광고
오른쪽 아래의 팝업광고(?)가 차단이 되지 않아보였습니다.

![2019-07-07_23-06-00](https://user-images.githubusercontent.com/40620901/60769553-21303e00-a10c-11e9-9089-8844d86544e0.png)

제가 ublock origin의 My-filters 기능을 이용해서
`qiqivv.com:4433`
위의 주소를 리스트에  추가 시키고 나서

![2019-07-07_23-07-49](https://user-images.githubusercontent.com/40620901/60769554-25f4f200-a10c-11e9-8f9d-d1f1bfb90969.png)

언급드린 광고들이 차단되었습니다.

따라서.. 해당 주소를 필터리스트에 추가를 요청드렸습니다

수고하세요!!

**Comment by ghost** [comment]
https://github.com/List-KR/List-KR/commit/ae39326c1c526ab973e67b1307d67da8bbd453dc 커밋에서 업데이트 하였습니다. 반영 시까지 일정 시간이 소요될 수 있으니 2~3시간 정도 후에 확인 부탁드립니다.

**Comment by ChiftKey** [comment]
빠른 피드백 감사합니다^^
프로젝트 관리해주셔서 감사해요

**Comment by PlavorSeol** [comment]
애초에 해당 사이트가 비정상적인 것으로 의심됩니다만...

**Comment by ghost** [comment]
7일 이상 활동이 없는 이슈이며 해결되었다고 판단되어 닫기 처리합니다. 추후 문제 발생 시 언제든지 새 이슈를 통해 다시 제보해주시면 검토 후 해결토록 하겠습니다. List-KR 필터 개발에 관심을 가져 주셔서 감사합니다.
