### ISSUE TITLE
IC: inven.co.kr

### ISSUE THREAD

**Issue by DavidLee3835** [List-KR/List-KR#409]
### URL

https://www.inven.co.kr/

### FILTERS

List-KR

### Browser

Google Chrome

### Operating System

Apple macOS

### Ad-Blocker

AdGuard Browser Extension

### Comment

<img width="1589" alt="image" src="https://user-images.githubusercontent.com/99162643/173333402-c48f8da4-abf0-46b1-a151-708299c23f2d.png">

This message appears and images are not shown since yesterday when AdGuard is activated.
Can you check the filter and re-produce it?

**Comment by piquark6046** [comment]
@DavidLee3835 It seems that Ad-Shield on inven.co.kr rejects the webpage loading if a visitor uses an adblocker.

**Comment by DavidLee3835** [comment]
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/99162643/173477726-c2d9c978-23df-4fc4-960a-2b5e20f60641.png">

When I activate uBO only, the problem doesn't reproduced.

```
inven.co.kr#@#div.right-menu
loawa.com#@#div[id$="_v"]
loawa.com#@#div[id$="_v2"]
loawa.com#@#main div[class*="p-0 m-0 mb-2 d-none d-md-block text-center"]
```

I searched how to create own filter in AdGuard and tried the filter above.
Somehow the message not appears and images are shown normally, but the ads also appear.

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/409#issuecomment-1154636136
@DavidLee3835
This is how Ad-Shield works.
If Ad-Shield detects an adblocker, It pop-ups the notification and hides the images and comments.

For now, I remove the mentioned rules.
If you want to remove Ad-Shield advertisement, please use [microShield](https://github.com/List-KR/microShield).

**Comment by JobcenterTycoon** [comment]
@piquark6046 why you removed all the useful filters https://github.com/List-KR/List-KR/commit/9f73fe8d7320b551808e47fe5611ccaa806c86b5 https://github.com/List-KR/List-KR/commit/e91530ec49c96dd58a7a5860e4d95dee79d17b35 ?? I get no adshield with the redirect and whitelist filter

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/409#issuecomment-1155547506
Oh, I thought that the filters affects anti-adblock of Ad-Shield, and I forgot to revert the changes.
I revert that.
