### ISSUE TITLE
(제안) 애드쉴드/나무위키 필터를 별도 파일로 분리하면 어떨까요?

### ISSUE THREAD

**Issue by gaeulbyul** [List-KR/List-KR#411]
현황
=====
현재 List-KR에서 애드쉴드와 나무위키의 파워링크 광고를 차단하고자 많은 노력을 하고 있고, 이들 웹 사이트 역시 이를 그냥 두지 않고 지속적으로 우회하고 있습니다. 그런데, 일단 우회를 하고나면 단순히 광고가 다시 나타나는 정도가 아니라 이미지가 사라지거나, 페이지의 내용이 사라지거나, 로딩속도 저하등의 현상이 자주 발생하다보니 오히려 광고보다 더 불편하게 되는 부작용이 발생하고 있습니다. 이 때 유저 입장에선 문제가 있는 필터만 골라서 끄는 방법이 없기 때문에 응급조치를 위해...
* 나무위키에서 애드블락을 해제 (이러면 구글광고 등 잘 막던 광고도 놓치게 됨)
* List-KR 필터를 비활성화 (이러면 다른 한국어 웹사이트도 전부 영향 받음)

하는 경우가 생깁니다.

제안
=====
List-KR의 필터 중 **특히 오작동이 자주 발생하는 필터만 별도의 파일로 분리**하는 방안은 어떨까요? 이렇게하여 오작동 발생시 응급조치로써 **유저에게 하여금 문제있는 필터만 개별적으로 끌 수 있는 방법**이 생기게 됩니다.

방안 1
-----
기존 필터에서 오작동이 잦았던 필터를 다음과 같이 둘로 나눕니다.
* List-KR (기존 필터에서 오작동 발생이 잦았던 부분이 없는 버전)
* List-KR Advanced (가칭) (애드쉴드와 나무위키 등 오작동이 많았던 버전. 유저는 웹 사이트 문제 발생시 응급조치로 이 필터만 끌 수 있도록.)

방안 2
-----
위와 비슷하나 애드쉴드와 나무위키를 별개로 분리하여 셋으로 나눕니다. 파일이 많아지긴 하나 유저 입장에선 나무위키나 애드쉴드 둘 중 한가지만 끌 방법이 생기게 됩니다.
* List-KR
* List-KR for Ad-Shield
* List-KR for NamuWiki

**Comment by piquark6046** [comment]
https://github.com/List-KR/NamuLink
https://github.com/List-KR/microShield

**Comment by green1052** [comment]
i think better suggestion 1 than 2
 like list-kr experimental

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/236
