### ISSUE TITLE
11st mobile app ad

### ISSUE THREAD

**Issue by green1052** [List-KR/List-KR#413]
like..
![Screenshot_20220615-231402_11st](https://user-images.githubusercontent.com/34261355/173849267-ea3cd0a7-867f-40f4-b6a7-52d83ca55f90.jpg)

![Screenshot_20220615-231420_11st](https://user-images.githubusercontent.com/34261355/173849283-228886f3-7ddc-4058-b31d-a5cfe41d512d.jpg)

we need research to block ad

**Comment by piquark6046** [comment]
@green1052 Did you mean [11st](https://play.google.com/store/apps/details?id=com.elevenst)?
If so, It can be difficult to block them if the app does not accept the certificate of AdGuard.

**Comment by seia-soto** [comment]
From iOS with Proxyman iOS version, it seems like they didn't impl SSL pinning.

Below is found entries:

<details>
<summary>Tracker</summary>

`GET https://11st.kr/html/common/googleAd/ifrm_ga.html?param=prdNo:97490606;ldispCtgrNo:1001324;mdispCtgrNo:1002030&mobileYn=Y&ref=sellerProductDetailView`

<img width="375" alt="image" src="https://user-images.githubusercontent.com/30369714/173866861-17ca8f15-fb47-4b91-bbe8-1f7f22907077.png">

</details>

<details>
<summary>Ad (1)</summary>

`GET https://ds.11st.co.kr/NetInsight/text/11st/11st_mobile/mobile_product@NM_text?category=1007545`

<img width="375" alt="image" src="https://user-images.githubusercontent.com/30369714/173867794-e6bae254-008d-4f76-a372-9dadc49e8774.png">

</details>

**Comment by green1052** [comment]
> @green1052 Did you mean [11st](https://play.google.com/store/apps/details?id=com.elevenst)? If so, It can be difficult to block them if the app does not accept the certificate of AdGuard.

yes
![image](https://user-images.githubusercontent.com/34261355/173867239-1fce349a-5a18-4bd2-b0d9-30304ba4e06e.png)

**Comment by green1052** [comment]
more ad @piquark6046 

<details>
<summary>Screenshots</summary>

![Screenshot_20220616-013537_11st](https://user-images.githubusercontent.com/34261355/173879926-42051604-0c57-4ede-98c9-4023ac6001e3.jpg)
![Screenshot_20220616-013555_11st](https://user-images.githubusercontent.com/34261355/173879941-0b3779d6-e032-4450-8cf0-8f67b1001cfa.jpg)

</details>

**Comment by Seohare** [comment]
@piquark6046 

차단이 잘못 된 것 같습니다.
||action.adoffice.11st.co.kr^ 이 규칙을 필터에서 제거 하면 해결될 것 같네요.

<details>
<summary>Screenshots</summary>

![2](https://user-images.githubusercontent.com/99063049/176910162-4f1414b0-88cc-4c8e-9701-37f9bd39d164.png)
![1](https://user-images.githubusercontent.com/99063049/176910167-9099cae3-269a-4273-8604-605dbfe923ea.png)

![3](https://user-images.githubusercontent.com/99063049/176910150-b9d5b718-533e-4025-b6ad-65216c4b6ca9.png)

</details>

**Comment by piquark6046** [comment]
@NoName926 What is the element that you clicked?

**Comment by green1052** [comment]
> @NoName926 What is the element that you clicked?

<details>
<summary>Screenshots</summary>

![Screenshot_20220701-235609_11st](https://user-images.githubusercontent.com/34261355/176918988-9e88b49f-f667-4e34-b7ae-67ff143f01c3.jpg)

</details>

this rule break image

**Comment by green1052** [comment]
and many images..

**Comment by green1052** [comment]
<details>
<summary>Screenshots</summary>

![Screenshot_20220701-235704_11st](https://user-images.githubusercontent.com/34261355/176919172-fce1d62f-884e-47a5-a4ca-c2a64ab4310d.jpg)
![Screenshot_20220701-235709_11st](https://user-images.githubusercontent.com/34261355/176919179-5ee17b73-b51c-40ec-8696-6655b7eb796b.jpg)

</details>

**Comment by piquark6046** [comment]
@green1052 Please test this:
```
@@/^https:\/\/cdn\.011st\.com\/11dims/resize/[0-9]{3,4}x[0-9]{3,4}\//
```

**Comment by Seohare** [comment]
> @NoName926 What is the element that you clicked?

@piquark6046 

검색 창에 cpu를 검색하고 나오는 상품들을 클릭하면 저렇게 뜹니다.

<details>
<summary>Screenshots</summary>

![Screenshot_20220702-092324_11st.png](https://user-images.githubusercontent.com/99063049/176979694-c5523705-4606-47e2-bb1a-b30cfb630db2.png)

</details>

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/413#issuecomment-1172796149
@NoName926 The element is an advertisement.
If you want to hide them, please give me a URL that you visited with 11st app.

**Comment by Seohare** [comment]
@piquark6046 

11번가 앱에서 URL공유 기능을 못 찾아서 URL을 알려주는 게 어렵습니다. 
 11번가 앱에서 검색 창에 아무거나 검색하고 아래에 나오는 상품들을 누르면 제가 보낸 사진 처럼 나옵니다. 한번 테스트 해보시는 걸 추천합니다.

**Comment by green1052** [comment]
![Screenshot_20220702-125040_11st](https://user-images.githubusercontent.com/34261355/176985530-c046b69a-9737-4562-9568-0f4c921ef1b5.jpg)

icon broken

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/413#issuecomment-1172827268
@green1052 
App or a website opened with a web browser?

**Comment by green1052** [comment]
app
