### ISSUE TITLE
추가 제보가 없어 종결 처리합니다. 문제가 계속 나타난다면 언제든지 새 이슈로 제보 부탁드립니다.

### ISSUE THREAD

**Issue by githardnewB** [List-KR/List-KR#416]
추가 제보가 없어 종결 처리합니다. 문제가 계속 나타난다면 언제든지 새 이슈로 제보 부탁드립니다.

_Originally posted by @ghost in https://github.com/List-KR/List-KR/issues/8#issuecomment-543698862_

안녕하세요, 당시 애드가드랑 github를 잘 몰라서 이게 전체 공개로 오픈되는지를 몰랐습니다. 당시 제보할때 개인 정보를 모르고 그대로 다 노출한 스샷이라 혹시 해당 스레드를 삭제해주실 수 있는지 여쭙고 싶습니다

**Comment by piquark6046** [comment]
Deleted.

**Comment by githardnewB** [comment]
감사합니다
