### ISSUE TITLE
Naver App

### ISSUE THREAD

**Issue by piquark6046** [List-KR/List-KR#419]
![Screenshot_20220618-134441_NAVER.png](https://user-images.githubusercontent.com/99063049/174423120-c9f607d2-4ce6-43ed-98fd-faa49a16d0a4.png)

네이버 앱 실행 후에 노출되는 광고가 차단되지 않습니다.  이 문제도 해결해 주시면 좋을 것 같습니다.

_Originally posted by @NoName926 in https://github.com/List-KR/List-KR/issues/418#issuecomment-1159361013_

**Comment by piquark6046** [comment]
@NoName926
Did you enable HTTPS filtering for the app?

**Comment by Seohare** [comment]
@piquark6046  
HTTPS 필터링을 활성화하면 광고는 차단 되지만 사진 처럼 네이버 앱이 제대로 작동하지 않습니다. 그래서 HTTPS 필터링을 끌 수 밖에 없었습니다.
![Screenshot_20220618-202010_NAVER](https://user-images.githubusercontent.com/99063049/174435377-6e929e46-f326-40f7-bb0c-7565d0cddd6e.png)
![Screenshot_20220618-202020_NAVER](https://user-images.githubusercontent.com/99063049/174435379-6fb77b2d-f223-4747-bada-9834167fd1a6.png)
![Screenshot_20220618-201957_NAVER](https://user-images.githubusercontent.com/99063049/174435380-b7672d04-b8f1-4352-8093-78cfd8e7d3e9.png)

**Comment by piquark6046** [comment]
Then, any adblocker cannot inject an adblocking script into the app except rooting your android.

**Comment by Seohare** [comment]
@piquark6046 네, 알겠습니다.

**Comment by piquark6046** [comment]
Please use a browser instead.
