### ISSUE TITLE
[AD] 마루마루 광고

### ISSUE THREAD

**Issue by 115dkk** [List-KR/List-KR#42]
## 광고 제보
* **문제가 되는 URL**: https://marumaru.sale/
* **URL에서 문제가 되는 요소**: 온갖 광고
* **확인 가능한 스크린샷 (옵션)**: ![Screenshot_20200829-183647_Chrome.jpg](https://user-images.githubusercontent.com/33408534/91633880-cc920580-ea26-11ea-97d2-acdefed9d40a.jpg)

## 시스템 환경
* **사용 중인 기기**: SM-J415N
* **사용 중인 브라우저**: 모바일 chrome
* **구독 중인 필터**: 애드가드 기본 및 모바일, 추적 보호, 방해요소, DNS 필터 + Adblock Warning Removal List + List KR

추가로, 해당 사이트는 이전부터 fuckadblock 스크립트를 사용하는 것으로 악명높았던 사이트입니다. 이런 문제가 없는지 확인해주시면 감사하겠습니다.

**Comment by ghost** [comment]
https://github.com/List-KR/List-KR/commit/86d5e59c6d590a330faf4f08cfa26aa261a181c6 커밋에서 업데이트 하였습니다.
