### ISSUE TITLE
IG Downloader app ad

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#426]
### URL

https://play.google.com/store/apps/details?id=instasaver.instagram.video.downloader.photo&hl=ko

### FILTERS

List-KR

### Browser

Microsoft Edge

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment

IG Downloader 앱의 광고가 차단 되지 않습니다.

![1](https://user-images.githubusercontent.com/99063049/174747401-4770e749-90bf-45e3-ade5-37e0a833df7d.png)
![2](https://user-images.githubusercontent.com/99063049/174747408-59a7ad93-3053-4377-8cb1-ff961965a361.png)

**Comment by Seohare** [comment]
@piquark6046 
필터를 업데이트 했습니다. 그런데 앱을 실행하고 앱  화면에 나오는 광고는 차단이 되었는 데 팝업 광고는 여전히 차단 되지 않습니다
![1](https://user-images.githubusercontent.com/99063049/174760350-54d1eb90-ef37-475b-bb2a-63adf98800b5.png)
.

**Comment by piquark6046** [comment]
Please clear data of the app.

**Comment by Seohare** [comment]
@piquark6046 
데이터를 지웠습니다. 링크를 입력하고 다운로드 버튼을 누르면 여전히 광고가 나옵니다. 한번 테스트 해보세요.

**Comment by piquark6046** [comment]
Please give an example URL because I don't have any Facebook ID.

**Comment by Seohare** [comment]
@piquark6046 

예제 URL: https://www.instagram.com/p/CctvrLIJkQu/?igshid=YmMyMTA2M2Y=
광고가 항상 뜨는 것은 아니지만 어떤 경우에는 뜹니다. 

![1](https://user-images.githubusercontent.com/99063049/174774810-9b8b3a66-df00-41a8-a320-58aed98105ee.png)

**Comment by piquark6046** [comment]
Cannot reproduce with List-KR 2022.621.1.
Please update filters.

**Comment by Seohare** [comment]
@piquark6046 

필터는 최신 버전으로 업데이트 했으나  광고는 계속 나옵니다. 

![Screenshot_20220622-162925_AdGuard.png](https://user-images.githubusercontent.com/99063049/174970428-59964a18-d929-4a5d-a823-761f379fd910.png
)https://user-images.githubusercontent.com/99063049/174970488-3de570d4-c041-4d9c-b6f7-41cce6010633.mp4

**Comment by piquark6046** [comment]
Did you enable DNS filtering?

**Comment by Seohare** [comment]
@piquark6046 

네, 설정했습니다.

**Comment by Seohare** [comment]
@piquark6046 
필터를 최신 버전(2022.622.5)으로 업그레이드 하니깐 이제 광고가 안 뜨는 것 같습니다.
