### ISSUE TITLE
IC:  www.danawa.com

### ISSUE THREAD

**Issue by green1052** [List-KR/List-KR#428]
### URL

https://www.danawa.com/

### FILTERS

list-kr

### Browser

Google Chrome

### Operating System

Microsoft Windows 11

### Ad-Blocker

uBlock Origin

### Comment

![image](https://user-images.githubusercontent.com/34261355/175777698-5a2de15f-37e8-42a9-b3c9-47210c1c7b8d.png)
![image](https://user-images.githubusercontent.com/34261355/175777702-b5127805-3a38-4e8b-8711-95cc8e687578.png)

**Comment by piquark6046** [comment]
@green1052 
Please read [this web document](https://help.danawa.com/bizCenter/index.php?depth1=2).
It is a marketing of danawa.

**Comment by green1052** [comment]
@piquark6046 
then how about remove all

![image](https://user-images.githubusercontent.com/34261355/175778964-d068dfee-b2f0-46fe-83fa-c1c7864b0d2c.png)
