### ISSUE TITLE
[AD] 마루마루 남아있는 광고

### ISSUE THREAD

**Issue by 115dkk** [List-KR/List-KR#43]
## 광고 제보
* **문제가 되는 URL**: https://marumaru.sale/bbs/cmoic/19998/137002
* **URL에서 문제가 되는 요소**: 하단에 광고바 노출 - 오로지 만화를 표시하는 페이지까지 가야 나타납니다.
* **확인 가능한 스크린샷 (옵션)**: ![20200831_215032.jpg](https://user-images.githubusercontent.com/33408534/91721629-0b18f300-ebd4-11ea-9ce2-5430a7c6b1c9.jpg)

**Comment by ghost** [comment]
윈도우 10 파이어폭스 Nightly 환경에서 재현할 수 없습니다. 문제가 되는 배너의 이미지 URL을 첨부해주시면 감사하겠습니다.

**Comment by 115dkk** [comment]
이미지 링크: https://i.imgur.com/dg44mfY.gif

이미지 클릭 시 가는 링크: http://bit.ly/38a4ETn

**Comment by ghost** [comment]
우선 https://github.com/List-KR/List-KR/commit/7aba99804821da942f32b66391c56dffb922de96 커밋에서 픽스하였습니다.

이미 대응 규칙이 추가되어 있는 관계로 이미지 차단만 실시하였으며, 동일한 문제가 발생하는 경우 다시 제보 부탁드립니다.
