### ISSUE TITLE
AD: clien.net

### ISSUE THREAD

**Issue by green1052** [List-KR/List-KR#432]
### URL

https://m.clien.net/service/board/cm_andro/13273958

### FILTERS

.

### Browser

Google Chrome

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment

in comment 

![Screenshot_20220702-143009_Kiwi Browser](https://user-images.githubusercontent.com/34261355/176987889-2e01cee5-50ab-4e08-b4d7-87e2a0a27bba.jpg)

**Comment by piquark6046** [comment]
Found. But, I think that the original URL is replaced with an advertisement URL.

**Comment by piquark6046** [comment]
It can be recovered with a pure JS rule.

**Comment by green1052** [comment]
![Screenshot_20220702-143646_Kiwi Browser](https://user-images.githubusercontent.com/34261355/176988071-30df2f33-cc83-460f-a157-47849351ce5c.jpg)

**Comment by green1052** [comment]
ok

**Comment by piquark6046** [comment]
@green1052 
Done. But, uBlock Origin dose not support a pure JS rule.

**Comment by green1052** [comment]
ok
