### ISSUE TITLE
IC: 웃긴대학 모바일 제목 짤림

### ISSUE THREAD

**Issue by asrahi** [List-KR/List-KR#434]
### URL

http://m.humoruniv.com/board/read.html?table=pds&st=day&pg=0&number=1162453

### FILTERS

List-KR

### Browser

Google Chrome, Samsung Internet

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows, AdGuard for Android

## 증상
![image](https://user-images.githubusercontent.com/5344149/177030327-d2cde903-8845-4072-bda5-adfc1e058ead.png)
웃긴대학 상단 제목이 광고와 함께 짤립니다.

## 광고중지 화면
![image](https://user-images.githubusercontent.com/5344149/177030348-023dd846-041d-4101-8f24-8a6e863da651.png)

## 문제필터
script + div:not([id]) + div[id] div[id] > table

![image](https://user-images.githubusercontent.com/5344149/177030401-39bbebd4-5b07-49c5-905b-e196a0a932c1.png)

![image](https://user-images.githubusercontent.com/5344149/177030394-792d4b78-d59d-424c-8252-b7e36634151f.png)

**Comment by piquark6046** [comment]
@asrahi 
Where?
<details>
<summary>Screenshot</summary>

![Screenshot from 2022-07-03 08-16-23](https://user-images.githubusercontent.com/98787049/177031285-16a8a364-c12b-4c76-803a-b2df5290b4d1.png)

</details>

**Comment by asrahi** [comment]
Oops! Sorry, It seems to have been updated on the humoruniv.
Thank you

**Comment by seia-soto** [comment]
@asrahi I don't see any errors too. Please, close if your issue resolved. :)

**Comment by asrahi** [comment]
http://m.humoruniv.com/board/read.html?table=pds&st=day&pg=0&number=1167672

![image](https://user-images.githubusercontent.com/5344149/180926798-851bc52d-edb3-455d-a7fd-6d64c870cf29.png)

웃긴대학 오늘의 베스트 글에서 상단 제목줄이 다시 짤리네요

**Comment by asrahi** [comment]
![image](https://user-images.githubusercontent.com/5344149/180926888-5e5e30ba-0c17-45df-baca-2a1997b93fdd.png)

해당 필터 끄면 잘 나옵니다

**Comment by piquark6046** [comment]
Cannot reproduce.
<details>
<summary>Screenshot</summary>

![Screenshot from 2022-07-26 05-14-54](https://user-images.githubusercontent.com/98787049/180928681-5478cde0-aa7d-4f26-9a0a-880b52b6f4c5.png)

</details>

**Comment by piquark6046** [comment]
@asrahi

**Comment by piquark6046** [comment]
Ah... I cannot find the targeted element anymore.

CC: @seia-soto

**Comment by asrahi** [comment]
thanks
