### ISSUE TITLE
Play store app ad

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#435]
### URL

Goole play store app

### FILTERS

List-KR

### Browser

(Other)

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment

구글 플레이 스토어에 들어가서 앱 검색을 하면 사진 처럼 광고가 노출 됩니다.

![Screenshot_20220706-125802_Google Play Store](https://user-images.githubusercontent.com/99063049/177465770-691e0f56-f535-4994-9d5b-0386c19d9e01.png)

**Comment by piquark6046** [comment]
The advertisement may be filtered if your android device is rooted.

If you want to use an ad-free unofficial Google Play Store, please use Aurora Store[^1][^2].

[^1]: https://auroraoss.com/
[^2]: https://gitlab.com/AuroraOSS/AuroraStore
