### ISSUE TITLE
'Asked' app ad

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#437]
### URL

Asked app

### FILTERS

List-KR

### Browser

(Other)

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment

Asked 앱에 광고 흑적이 남아 있습니다.

![Screenshot_20220708-173504_Asked](https://user-images.githubusercontent.com/99063049/177952983-83088897-b873-498b-98c5-d52a3ebbbc22.png)

**Comment by piquark6046** [comment]
Unlike a website or in-app web browser, an advertisement in an app can be filtered by modifying/blocking a network/web request.

**Comment by piquark6046** [comment]
Please use a web browser instead of the app.
