### ISSUE TITLE
[AD] 네이트온 신규 광고 차단관련

### ISSUE THREAD

**Issue by a77ila2000** [List-KR/List-KR#44]
## 광고 제보
* **문제가 되는 URL**:  네이트온 메신지 광고
* **URL에서 문제가 되는 요소**: (광고 노출/잘못된 차단 등..)
* **확인 가능한 스크린샷 (옵션)**: 
![20200901_091015](https://user-images.githubusercontent.com/70551075/91780637-118a8780-ec33-11ea-824d-27dd6e6f5d61.png)

## 시스템 환경
* **사용 중인 기기**:  데스크탑
* **사용 중인 브라우저**: 크롬
* **구독 중인 필터**:
List-KR

**Comment by ghost** [comment]
사용하지 않는 프로그램인 관계로 AdGuard 내부 필터링 로그가 있어야 파악이 가능할 것 같습니다.

설정 -> 광고 차단 -> 필터링 로그 열기 접근 후 로그 첨부 부탁드립니다.

**Comment by a77ila2000** [comment]
필터링 로그에 네이트온이 안들어가서

첨부해도 의미가 없을꺼 같습니다.ㅠ



2020-09-02 오후 7:48에 Laby 이(가) 쓴 글:
