### ISSUE TITLE
[NSFW] AD: illegal sites ad

### ISSUE THREAD

**Issue by green1052** [List-KR/List-KR#444]
### URL

AD:
https://torrentsee118.com/
https://www.tfreeca22.top/home.php
https://www.torrentreel96.top/home.php
https://torrentview63.com/
https://torrentmobile57.com/
https://torrentjuju6.com/
https://torrentsir62.com/
https://torrentrj44.com/
https://torrentj67.com/
https://torrentsome46.com/
https://torrentmode2.com/
https://ktxtorrent48.com/
https://torrentbot40.com/
https://www.torrentq2.com/
https://torrentwiz45.com/
https://torrentbam31.com/
https://torrentlee36.com/
https://torrentgram42.com/
https://torrenttt32.com/
https://torpang19.com/
https://wtwt143.com/
https://www.race73.xyz/
https://mkmk26.link/%EC%9B%B9%ED%88%B0
https://fxfx133.com/
https://namedtoon92.com/
https://realtoon400.link/%EC%9B%B9%ED%88%B0
https://manamoa21.com/
https://www.redsun21.me/
https://www.jinyi22.me/
https://www.xcity21.me/
https://yagong40.com/
https://www.sexzoa20.me/
https://yadongpan31.org/
https://jogaeparty70.com/
https://www.nobra14.me/
https://www.sexnori21.me/
https://jgmoa25.com/
https://www.starking10.me/
https://www.sorabam14.me/
https://www.miindo18.me/
https://redvi37.com/
https://www.pok-ddal17.live/
https://www.dayisoo11.me/
https://www.dojun7.com/
https://bame51.net/
https://www.sexgate13.me/
https://yaburi16.com/
https://ddrblr37.com/
https://a17.koreanz.xyz/
https://www.tvgook87.com/
https://k40.qooqootv.fun/
https://k05.dandm.tv/home
http://tvnara65.net/
https://t20.tvusan.net/
https://tazotv47.com/
https://v14.sonagitv.tv/
https://v33.tvpong.net/
https://v18.free-tv.xyz/
https://www.opgirls68.com/main/
https://www.casa21.me/
https://yt702.org/

AD ,IB:
www.zoazoa7.me

### FILTERS

1

### Browser

Google Chrome

### Operating System

Microsoft Windows 11

### Ad-Blocker

uBlock Origin

### Comment

:(

**Comment by piquark6046** [comment]
@green1052 
What is an element hidden incorrectly on zoazoa7.me?

**Comment by green1052** [comment]
![image](https://user-images.githubusercontent.com/34261355/179395628-9fa36c23-366e-4c0f-9296-0ea1c3383707.png)
![image](https://user-images.githubusercontent.com/34261355/179395642-a7eb49af-a079-46e2-a4d1-7dc725ac130b.png)
