### ISSUE TITLE
tgd.kr and panel survey ads

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#447]
### URL

https://tgd.kr/s/kasushilollol/34411578
https://hunnek.tistory.com/258

### FILTERS

List-KR

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![tgd ad](https://user-images.githubusercontent.com/99063049/180432231-b03f4d85-fc12-4987-884e-e9b34b09a118.png)

![ad](https://user-images.githubusercontent.com/99063049/180432242-34476cfe-db6f-47e0-87e1-55edc8cd78bd.png)

**Comment by piquark6046** [comment]
@NoName926 Can you see any Ad-Shield advertisement on tgd.kr without [microShield](https://github.com/List-KR/microShield)?

CC: @seia-soto

**Comment by Seohare** [comment]
> @NoName926 [microShield](https://github.com/List-KR/microShield)없이 tgd.kr 에서 Ad-Shield 광고를 볼 수 있습니까?
> 
> CC : @seia 소토

@piquark6046  트게더에 애드쉴드 광고가 있나요? 마이크로쉴드를 끄고 트게더에 들어가 봤지만 애드쉴드 광고는 안 보이네요.

**Comment by seia-soto** [comment]
> @NoName926 Can you see any Ad-Shield advertisement on tgd.kr without [microShield](https://github.com/List-KR/microShield)?
> 
> CC: @seia-soto

How about `a[href^="https://www.panel.co.kr/user/join/etcpath"]` or similar, I don't see it's related to AdShield.

**Comment by seia-soto** [comment]
For `tgd.kr`, `#header-top-notice>*` won't break any site layout.

**Comment by seia-soto** [comment]
Note that the source is `AD` variable:

<details>

```html

<script type="text/javascript">var AD = [{"content":"\uc0dd\uc77c \ucd95\ud558\ud574 \ube14\ub9c1! \uc81c\ubc1c \uc6b0\ub9ac\uc640 \uc624\ub798 \uac19\uc774 \uc788\uc5b4\uc918!","link":"https:\/\/www.twitch.tv\/blinge1"},{"content":"\ud83d\udc3f\uc804\ubc29\uc1a1\uad6d PD \ud588\ub358\ubd84 \uc608\ub2a5\uc370\ud47c\ub2e4\ud83d\udc3f","link":"https:\/\/www.twitch.tv\/amond223"},{"content":"20\uc2dc \uacf5\ud3ec\uac8c\uc784 \uba74\uc5ed \uc5c6\ub294 \uc2a4\uba38\uac00 \uacf5\uac9c \ud569\ub2c8\ub2e4. ( \uc8fc\uc758 : \ube44\uba85\uc9c0\ub974\uba74 \uc18c\ub9ac\uac00 \uc0ac\ub77c\uc9d0 )","link":"https:\/\/www.twitch.tv\/bun__hong"},{"content":"\ud22c\ub35c\ub300\ub294 \uc5d0\uc774\ud399\uc2a4 \uc2e0\uc785 \uc5ec\uc2a4 \uc1a1\uc774 \ubcf4\ub7ec\uc624\uc138\uc694","link":"https:\/\/www.twitch.tv\/ssongg22"},{"content":"\ud83c\udf387\uc77c\ucc28 \ub274\ube44, \uc778\uc0ac \ub4dc\ub9ac\uc635\ub2c8\ub2e4.\ud83c\udf38","link":"https:\/\/www.twitch.tv\/chae_yuhnnn"},{"content":"\uc624\ub298\uc740 '\ubf48\uac00\uc774\uc988' \ud569\ub2c8\ub2f9.\ud83c\udfc1","link":"https:\/\/www.twitch.tv\/gamsemi"},{"content":"\ub0a8\ucea0\uc758 \uace0\ud488\uaca9 \uc131\uc778 \uc57c\ub514\uc624","link":"https:\/\/www.twitch.tv\/nge0811"},{"content":"[v] \ubc84\uce04\uc5bc \uc544\uc774\ub3cc\uc774 \ub418\uace0\uc2f6\uc5b4\uc694 !","link":"https:\/\/www.twitch.tv\/ddd0760"}];</script>

```

</details>

**Comment by piquark6046** [comment]
@seia-soto 
Do you agree that Ad-Shield is removed from inven.co.kr and tgd.kr entirely?

**Comment by seia-soto** [comment]
> @seia-soto Do you agree that Ad-Shield is removed from inven.co.kr and tgd.kr entirely?

Yes, via DNS.

**Comment by piquark6046** [comment]
CC: @JobcenterTycoon

**Comment by seia-soto** [comment]
I am not monitored actively these days but seems like they're removing it to shine their original content.

**Comment by seia-soto** [comment]
We still need some monitors but it's ok for now.
