### ISSUE TITLE
AB: aternos.org site anti adblock

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#456]
### URL

https://aternos.org/server/

### FILTERS

List-KR

Adblock Warning Removal List

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![1](https://user-images.githubusercontent.com/99063049/181428384-a0efdf00-f5be-4db1-8799-1a3a5a4e69a6.png)

로그인 후 서버 생성을 누르면 사진처럼 나옵니다.

**Comment by piquark6046** [comment]
The website is an international website.
