### ISSUE TITLE
AD: sites AD

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#458]
### URL

- [x] https://www.kinds.or.kr
- [x] https://cadgraphics.co.kr/index.php
- [x] https://e-healthnews.com/
- [x] http://www.fmtv.co.kr/news/
- [x] https://www.ggjil.com/
- [x] http://www.ohmytaxinews.com/
- [x] http://www.pohangnews.co.kr/
- [x] http://www.technoa.co.kr/
- [x] https://sports.chosun.com/
- [x] http://www.ignnews.kr/
- [x] http://www.gapyeongnow.kr/
- [x] http://www.nursenews.co.kr/main/main.asp
- [x] http://www.bgchang.co.kr/
- [x] http://www.gyeryongilbo.com/
- [x] http://www.kcilbo.com/coding/main.aspx
- [x] http://www.police112.co.kr/
- [x] http://www.goseong114.com/
- [x] http://www.namwon.net/
- [x] http://www.djmail.co.kr/
- [x] http://www.dailymedipharm.com/
- [x] http://www.db-times.com/
- [x] http://dongbujungang.co.kr/default/index.php
- [x] http://www.mediapen.com/
- [x] http://www.miraetv.net/
- [x] http://www.sjtoday.kr/
- [x] https://www.smartfn.co.kr/
- [x] http://www.esuwon.net/
- [x] http://snaptime.edaily.co.kr/
- [x] http://www.susailbo.com/
- [x] https://shindonga.donga.com/
- [x] http://www.ajl.co.kr/
- [x] https://www.anewsa.com/
- [x] http://www.areyou.co.kr/
- [x] http://www.hn-morning.com/
- [x] http://www.ibjnews.kr/
- [x] http://www.daebusinmun.com/
- [x] http://www.xn--z92b13l12bmi.com/
- [x] http://www.kpja.kr/main/index.html
- [x] http://www.yonhapnewsi.com/n_news/main/index.html
- [x] https://woman.donga.com/
- [x] http://www.yhinews.com/
- [x] http://www.ycehn.net/
- [x] http://www.osannews.net/
- [x] http://www.kjc24.co.kr/
- [x] http://www.k-today.com/
- [x] http://www.ybcmediagroup.com/
- [x] http://www.ourtoday.co.kr/
- [x] http://www.wonjutoday.co.kr/
- [ ] http://www.ombudsmannews.com/default/index.php
- [x] http://www.usnews.co.kr/
- [x] http://www.cfnews.kr/coding/main.aspx

### FILTERS

List-KR

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

**Comment by piquark6046** [comment]
**No changes**:
 - http://www.mediapen.com/ - No advertisement found. But, self-promotions are found. 
 - https://shindonga.donga.com/ - No advertisement found. 
 - http://www.fmtv.co.kr/news/ - Unable to connect.
 - http://snaptime.edaily.co.kr/ - No advertisement found.
 - https://woman.donga.com/ - No advertisement found.
 - http://www.kjc24.co.kr/ - Design of the website is broken on Firefox.

**Comment by green1052** [comment]
<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/34261355/182013029-d6952906-3690-487e-8445-d161bf6b7cea.png)

</details>
@piquark6046

**Comment by Seohare** [comment]
https://github.com/List-KR/List-KR/issues/458#issuecomment-1200346552

<details>
<summary>Screenshot</summary>

![1](https://user-images.githubusercontent.com/99063049/182014391-445e3c84-a840-4b41-ba96-e558537b18a9.png)

</details>
@piquark6046

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/458#issuecomment-1200364116
So, I meant that the banners are self-promotions.

**Comment by Seohare** [comment]
> [#458 (comment)](https://github.com/List-KR/List-KR/issues/458#issuecomment-1200364116) So, I meant that the banners are self-promotions.

Skip it if you think it's not an advertisement
