### ISSUE TITLE
AB: meeco.kr, 1412.rest

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#461]
### URL

https://meeco.kr/free/35700998
https://1412.rest/romance/17150638

### FILTERS

Ad Blocking:
AdGuard Base,
AdGuard Mobile Ads

Privacy:
AdGuard Tracking Protection

Language-specific:
List-KR

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

in ios safari adguard List-KR
https://github.com/List-KR/List-KR/blob/master/filters-AG/contentblocker.txt
Filter not working?

In ios safari adguard,
You cannot bypass anti adblock.
https://meeco.kr/free/35700998
https://1412.rest/romance/17150638

But in Android Samsung Internet adguard content blocker
You can bypass anti adblock.

Also, after bypassing anti adblock on Samsung Internet
Can you remove the remaining empty space?

1412.rest##.adsbygoogle

For me, this rule works with anti adblock bypass and
All works for empty space removal, 
but Does this rule work for others?
I don't know if this is the correct rule.

**Comment by piquark6046** [comment]
@88Va2wFDcYd1CT 
Did you mean AdGuard for Safari?

**Comment by ghost** [comment]
@piquark6046 
I am using AdGuard app and Safari on my iPhone.
non mac safari

**Comment by piquark6046** [comment]
Then, please enable [advanced protection](https://kb.adguard.com/en/ios/overview#advanced-protection-1).
Also, you need to enable List-KR and update filters.

**Comment by ghost** [comment]
@piquark6046 
I enabled Advanced Protection, but it's the same.
It could be a problem with my phone.

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/461#issuecomment-1200404060
Please wait 2-3 minutes after your configuration is changed.

**Comment by ghost** [comment]
on my iphone safari
It still doesn't work.

However, if you manually add user rules,
working.
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=1412.rest
1412.rest##.adsbygoogle

Is it a bug in the ios addguard?

**Comment by piquark6046** [comment]
@88Va2wFDcYd1CT 
Please test the following rule:
```
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$redirect=googlesyndication-adsbygoogle
```

**Comment by ghost** [comment]
@piquark6046 
It doesn't work.

**Comment by ghost** [comment]
@piquark6046 
Thank you for your hard work.

https://meeco.kr/free/35700998
also on this site
for safari using ios adguard
Can you add an anti adblock rule?

**Comment by piquark6046** [comment]
@88Va2wFDcYd1CT 
Already added at July 28 [^1].

[^1]: https://github.com/List-KR/List-KR/commit/ba8a452560952ddc71df9cf9803f90f9cb957b11

**Comment by ghost** [comment]
@piquark6046 
However
Like the 1412.rest site
https://meeco.kr/free/35700998
Also
Not working in safari using ios adguard.

**Comment by piquark6046** [comment]
But, by enabling advanced protection, AdGuard for iOS Pro can inject a scriptlet rule into a website.
https://kb.adguard.com/en/ios/overview#advanced-protection-1

**Comment by ghost** [comment]
But it doesn't seem to work.
I'll contact adguard.

**Comment by piquark6046** [comment]
@88Va2wFDcYd1CT 
Did you enable Safari extension of AdGuard?
https://kb.adguard.com/en/ios/safari-web-extension#install

**Comment by seia-soto** [comment]
@piquark6046 for Apple platforms, UserScript uses are highly limited. Script won't be injected or won't be ran at proper time. I can also reproduce on AG Pro.

**Comment by seia-soto** [comment]
@88Va2wFDcYd1CT 

- meeco.kr##div[style*="absolute"]:not([class]):not([id])

Video: https://user-images.githubusercontent.com/30369714/182092215-b3cc4a13-445e-4e3d-92be-25169125cb6b.MOV

**Comment by ghost** [comment]
> @88Va2wFDcYd1CT Did you enable Safari extension of AdGuard? https://kb.adguard.com/en/ios/safari-web-extension#install

I have enabled extensions for advanced protection, but the scriptlet rules don't seem to work well.

**Comment by ghost** [comment]
> @88Va2wFDcYd1CT
> 
> * meeco.kr##div[style*="absolute"]:not([class]):not([id])
> 
> Video: https://user-images.githubusercontent.com/30369714/182092215-b3cc4a13-445e-4e3d-92be-25169125cb6b.MOV

The rule you gave me works for me.
thank you

**Comment by piquark6046** [comment]
@88Va2wFDcYd1CT @seia-soto 
A similar bug was already reported.
 - https://github.com/AdguardTeam/AdguardForiOS/issues/2027
