### ISSUE TITLE
AB: svrforum.com

### ISSUE THREAD

**Issue by green1052** [List-KR/List-KR#465]
### URL

https://svrforum.com

### FILTERS

list-kr

### Browser

Google Chrome

### Operating System

Android

### Ad-Blocker

AdGuard for Android

**Comment by piquark6046** [comment]
@green1052 
Can you provide a detail URL?

**Comment by green1052** [comment]
![Screenshot_20220805-160953_Kiwi Browser](https://user-images.githubusercontent.com/34261355/183022171-d7117580-825f-45f1-a107-1d13aad341a8.jpg)

**Comment by green1052** [comment]
![Screenshot_20220805-160959_Kiwi Browser](https://user-images.githubusercontent.com/34261355/183022204-c935b405-f2e0-4434-987e-61a62b55a13b.jpg)

just wait a min

**Comment by green1052** [comment]
http://blockadblock.com
