### ISSUE TITLE
[AD] 네이버 카페 글 내용 내의 배너 광고

### ISSUE THREAD

**Issue by resetart** [List-KR/List-KR#47]
## 광고 제보
* **문제가 되는 URL**:  https://m.cafe.naver.com/ca-fe/web/cafes/14358379/articles/1714370?fromList=true
* **URL에서 문제가 되는 요소**: (광고 노출/잘못된 차단 등..)  게시글 내부의 배너 광고 노출
* **확인 가능한 스크린샷 (옵션)**: 
![image](https://user-images.githubusercontent.com/62340550/92120712-5d584f00-ee34-11ea-9229-9d1d58deca6d.png)

웹 브라우저 상에선 혼자 찾아보고 아래 내용을 사용자 규칙에 추가하여 배너 광고가 안 나오게 되었는데,
안드로이드 모바일 환경에서는 아래 규칙에 사용되지 않습니다.
PC에서도 모바일 웹페이지로 네이버 카페에 들어가면 광고가 출력 됩니다.
##div[class="ArticleFormBanner bottom"]

## 시스템 환경
* **사용 중인 기기**: 
* **사용 중인 브라우저**: 
* **구독 중인 필터**:

**Comment by resetart** [comment]
||cafeptthumb-phinf.pstatic.net^

위 문구를 사용하니 모바일 브라우저로 접속시엔 배너가 차단 되네요. 
다만 빈 공백이 크게 생기네요.
그리고 네이버 카페 어플 내에선 차단이 되지 않네요..

**Comment by ghost** [comment]
https://github.com/List-KR/List-KR/commit/df8065bb1e5abe2f0cfcfa0a58d7c719215649e4 커밋에서 업데이트 하였습니다. 단 네이버 카페 앱의 경우 AdGuard의 자체 제약사항으로 인해 필터링이 어렵습니다.
