### ISSUE TITLE
AB: JTBC

### ISSUE THREAD

**Issue by hankju84** [List-KR/List-KR#472]
### URL

https://tv.jtbc.co.kr/replay/pr10010687/pm10046946/ep20010324/view

### FILTERS

AdGuard Base Filter
AdGuard URL Tracking Filter
AdGuard Tracking Protection Filter
Legtimate URL Shortener
AdGuard Social Media Filter
AdGuard Annoyances Filter
List-KR

All filters are latest version.

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![image](https://user-images.githubusercontent.com/73779442/184657961-9d489542-3cb3-42d8-abd6-dae6c4011ad2.png)

**Comment by Seohare** [comment]
@piquark6046  이거 아직도 안 됩니다.

![1](https://user-images.githubusercontent.com/99063049/184782703-2f5037a4-7f1b-4219-9b46-5a6498101e89.png)
![2](https://user-images.githubusercontent.com/99063049/184782706-49703b3a-d663-4f2e-91de-494d4c216454.png)

**Comment by piquark6046** [comment]
@NoName926 Please update your filters.

**Comment by Seohare** [comment]
> @NoName926 Please update your filters.


@piquark6046  filter is the latest version.

**Comment by piquark6046** [comment]
@NoName926 Please describe all subscribed filters.

**Comment by Seohare** [comment]
@piquark6046 
EasyPrivacy
Fanboy's Annoyances
Peter Lowe's Blocklist
Adblock Warning Removal List
Online Malicious URL Blocklist
Fanboy's Enhanced Tracking List
Fanboy's Anti-Facebook List
List-KR
NoCoin Filter List
YousList
AdGuard 방해 요소 필터
AdGuard URL 추적 필터
AdGuard 베이스 필터
AdGuard 추적 보호 필터
AdGuard 팝업 필터
https://secure.fanboy.co.nz/r/fanboy-ultimate.txt
https://malware-filter.gitlab.io/malware-filter/tracking-filter-vivaldi.txt

**Comment by piquark6046** [comment]
Your issue is caused by AdGuard filters compiler.
Please wait until it is fixed.

**Comment by piquark6046** [comment]
@NoName926 Please update your filters.
It is resolved.

**Comment by Seohare** [comment]
> @NoName926 Please update your filters.
> It is resolved.

@piquark6046 이제 되네요. 감사합니다.
