### ISSUE TITLE
feedclick.net ad-shield

### ISSUE THREAD

**Issue by NoName926** [List-KR/List-KR#474]
### URL

https://feedclick.net/

### FILTERS

List-KR
microShield

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![118](https://user-images.githubusercontent.com/99063049/185784275-ecd298dc-4c69-48e9-bee1-fd28f99ef698.png)

:(

**Comment by piquark6046** [comment]
@NoName926 
What's wrong?
I cannot find any Ad-Shield advertisement with microShield.
