### ISSUE TITLE
is it typo?

### ISSUE THREAD

**Issue by green1052** [List-KR/List-KR#475]
https://github.com/List-KR/List-KR/blob/master/filters-share/specific_URL.txt#L201

**Comment by green1052** [comment]
||appdata.hungryapp.co.kr//event/
                                              ^ double slash

**Comment by piquark6046** [comment]
Nope.
<details>
<summary>Screenshot</summary>

![Screenshot from 2022-08-22 17-28-25](https://user-images.githubusercontent.com/98787049/185982822-631005f7-1ba5-4c9a-a035-8b334f29c8d3.png)

https://github.com/List-KR/List-KR/commit/81fdcfa0862783a0ba07bfd5ba87a7b6007c9a9c

</details>

**Comment by green1052** [comment]
ok
