### ISSUE TITLE
[Bug?] 나무위키 검색 불능

### ISSUE THREAD

**Issue by 115dkk** [List-KR/List-KR#48]
## 광고 제보
* **문제가 되는 URL**: https://namu.wiki/%EB%82%98%EB%AC%B4%EC%9C%84%ED%82%A4:%EB%8C%80%EB%AC%B8
* **URL에서 문제가 되는 요소**: (광고 노출/잘못된 차단 등..) 검색바가 저래 깨져서 검색이 불가능합니다. 애드가드나 List-KR 및 YousList를 끄면 검색 기능이 정상 작동하는 것이 확인됩니다.
* **확인 가능한 스크린샷 (옵션)**: ![Screenshot_20200904-184340_Chrome.jpg](https://user-images.githubusercontent.com/33408534/92226155-40c52100-eedf-11ea-9351-38b6640c4a80.jpg)

**Comment by 115dkk** [comment]
광고 라벨은 다른 것으로 대체해주세요. 그리고 똑같은 문제가 발생한 YousList의 이슈 참고바랍니다.

https://github.com/yous/YousList/issues/140

**Comment by ghost** [comment]
https://github.com/List-KR/List-KR/commit/1f3ec488d7b09ea8480c97bcab8fa6ac3f6dc14c 커밋에서 해결하였습니다. 실제 반영시까지 일정 시간이 소요될 수 있으니 이용에 지속적으로 문제가 있는 경우 잠시 List-KR 필터의 `namu.wiki##div[id^="chika"]` 규칙을 해제하고 이용 부탁드립니다. 이용에 불편을 드려 죄송합니다.
