### ISSUE TITLE
singingdalong.blogspot.com Anti-AdBlock

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#484]
### URL

http://singingdalong.blogspot.com/2018/04/MAX-Antivirus-Full-Version-Ransim-test.html

### FILTERS

List-KR

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![1](https://user-images.githubusercontent.com/99063049/188096244-0829f807-d479-4069-8a6b-e0bbb0a75cf4.png)

**Comment by Seohare** [comment]
@piquark6046 안티 애드블록 스크립트를 차단한 건가요? 아니면 메시지만 차단한 건가요?

**Comment by piquark6046** [comment]
I blocked only the message because there is no negative effect when a visitor uses an adblocker.
Do you want to block anti-adblock script entirely?
@NoName926

**Comment by Seohare** [comment]
@piquark6046  I want to block anti-adblock script 

Thanks
