### ISSUE TITLE
IC: List-KR이 단국대학교 강의 사이트 수강을 차단합니다!

### ISSUE THREAD

**Issue by 115dkk** [List-KR/List-KR#485]
### URL

https://canvas.dankook.ac.kr/courses/39012/external_tools/8

(단, 단국대학교 학생만 진입 가능)

### FILTERS

![image](https://user-images.githubusercontent.com/33408534/188115860-cb7acdf1-bc1b-45ca-b376-c92c3aed368f.png)
![image](https://user-images.githubusercontent.com/33408534/188115930-d29eece3-0eea-4fc7-beef-8cce1f0bcc40.png)

이상이 제가 사용하는 필터의 전부입니다.

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

URL은 확인할 수 없을 것이므로, 주요 사진은 다음과 같습니다.

![화면 캡처 2022-09-02 173829](https://user-images.githubusercontent.com/33408534/188115995-653a1c2a-087a-454b-8148-bac595847204.png)
로딩이 비정상적으로 길어짐
![화면 캡처 2022-09-02 173921](https://user-images.githubusercontent.com/33408534/188116000-fe1d65db-3a0c-440b-9ceb-9924b38e46dc.png)
이후 로딩 실패

간단한 트러블 슈팅(List-KR만 해제시 정상 작동, List-KR을 키면 작동 안함)을 통해 List-KR이 문제인 것을 파악하여 여기에 게시하는 것입니다.

**Comment by piquark6046** [comment]
Please email me via `piquark6046@proton.me` ([OpenPGP encryption supported](https://keys.openpgp.org/vks/v1/by-fingerprint/FE57A8DEDF68D3A6400DF26E0E5C8ADF00DDAE40)).

**Comment by piquark6046** [comment]
@115dkk Because I don't have any Dankook University account.
