### ISSUE TITLE
www.cuonet.com ad

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#488]
### URL

https://www.cuonet.com/

https://www.cuonet.com/bbs/board.php?bo_table=community2&wr_id=8165882

### FILTERS

List-KR

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![17](https://user-images.githubusercontent.com/99063049/188298552-baec6fdd-626a-41c8-8a9f-7c7605bf8d08.png)

![1](https://user-images.githubusercontent.com/99063049/188298545-f7f7de7b-8df9-410e-9adb-6888806b6577.png)

**Comment by piquark6046** [comment]
@NoName926 
I think that the highlighted element is not an advertisement or self-promotion as the following screenshot:

<details>
<summary>Screenshot</summary>

![Screensh2323](https://user-images.githubusercontent.com/98787049/188302961-3cc3484d-8de1-4c77-a197-10bc199fb767.png)

</details>

**Comment by Seohare** [comment]
@piquark6046  그럼 광고라고 생각하시는 것만 차단해주세요.
