### ISSUE TITLE
cafe.naver.com ad

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#489]
### URL

https://cafe.naver.com/steamindiegame/7500717

### FILTERS

List-KR

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![1](https://user-images.githubusercontent.com/99063049/188311124-61a5aee2-3461-4312-9ab2-3dd54268641f.png)

이 게시글 뿐만 아니라 이 카페에 있는 모든 게시글에 광고가 있습니다. 
혹시 이 광고도 차단이 가능한가요?

**Comment by piquark6046** [comment]
Do you have any android device?

**Comment by Seohare** [comment]
@piquark6046 No

**Comment by piquark6046** [comment]
iOS?

**Comment by Seohare** [comment]
@piquark6046 NO, I use my computer.

**Comment by Seohare** [comment]
Right now I am using a computer, but my phone is using Android.

**Comment by Seohare** [comment]
@piquark6046  아직 광고가 차단 되지 않았습니다.

**Comment by piquark6046** [comment]
Please update your filters.
@NoName926 

<details>
<summary>Screenshot</summary>

![Screenshot from 2022-09-05 09-20-40](https://user-images.githubusercontent.com/98787049/188415405-a12ce35e-6ef8-4375-856a-7eb37d1b83ce.png)


</details>

**Comment by Seohare** [comment]
@piquark6046  필터를 최신 버전으로 업데이트 했습니다. 그런데 (다른 게시글) 게시글을 누르면 광고가 나오지만 새로 고침을 하면 광고가 사라집니다. 이건 버그인가요? 제 컴퓨터 문제인가요?

**Comment by Seohare** [comment]
게시글을 클릭 했을 때
![3](https://user-images.githubusercontent.com/99063049/188431910-566371a1-f6e9-4596-97b6-e07b276526cf.png)

새로고침 후 
![4](https://user-images.githubusercontent.com/99063049/188432033-f53937ed-51b4-47ee-84a7-335809d4fb55.png)

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/489#issuecomment-1236838653
It seems that it is a bug.
