### ISSUE TITLE
[AD]

### ISSUE THREAD

**Issue by CodeGenerater** [List-KR/List-KR#49]
## 광고 제보
* **문제가 되는 URL**: https://namu.wiki/
* **URL에서 문제가 되는 요소**: 검색창이 사라짐 (잘못된 차단) namu.wiki##div[id^="chika"]
* **확인 가능한 스크린샷 (옵션)**: 
![2020-09-05_9-37-12](https://user-images.githubusercontent.com/6629344/92293063-8de6d880-ef5b-11ea-85c3-4cba362755f6.png)

## 시스템 환경
* **사용 중인 기기**: PC
* **사용 중인 브라우저**: Chrome
* **구독 중인 필터**: List-KR

**Comment by ghost** [comment]
Duplicate of #48, #50
