### ISSUE TITLE
AB: Anti-AdBlock sites

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#492]
### URL

https://betterpostings.blogspot.com/2022/08/making-anti-adblock-pop-up-on-blogspot.html

https://1412.rest/cboard/140223

### FILTERS

List-KR

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![1](https://user-images.githubusercontent.com/99063049/188564181-fdbb311b-421c-41d7-80cc-c9ab69b8b817.png)

Please block anti-adblock scripts.

**Comment by piquark6046** [comment]
@NoName926 
Did you login?

**Comment by Seohare** [comment]
@piquark6046 no

**Comment by seia-soto** [comment]
uBlock Origin filters already addressed this problem.

- https://github.com/uBlockOrigin/uAssets/issues/11541
- https://github.com/uBlockOrigin/uAssets/blob/ac7d15df96e8830ed7202c5bd61c14c29562b274/filters/filters-2021.txt#L2813-L2815

**Comment by seia-soto** [comment]
Seems like above rules do not work on AG macOS.

**Comment by piquark6046** [comment]
Please wait...

**Comment by piquark6046** [comment]
I cannot reproduce.
Can you reload the website?

<details>
<summary>Screenshot</summary>

![Screenshot from 2022-09-06 09-51-51](https://user-images.githubusercontent.com/98787049/188604957-20b4d365-79da-4452-b820-3f6238d057bc.png)

</details>

**Comment by seia-soto** [comment]
I can reproduce:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/30369714/188605363-cc38aa95-1221-4101-be6d-fd3c8957c1c5.png)

</details>

**Comment by piquark6046** [comment]
@seia-soto 
Can you give me list of the subscribed filters?

**Comment by seia-soto** [comment]
> @seia-soto Can you give me list of the subscribed filters?

- uBO filters (badware risks, annoyances, quick fixes, resource abuses)
- block outsider intrusion into lan
- list-kr
- filter-kr (with all uselesses)
- AdGuard filters (base, mobile, tracking, url tracking, social media, annoyances, russian)
- legitimate url shortner
- Fanboy's filters (enhanced tracking, anti-fb)
- adblock warning removal list
- web annoyances ultralist
- i don't care cookies
- Easylist (cookies, privacy)
- online malicious url blocklist
- nocoin

**Comment by piquark6046** [comment]
?????

<details>
<summary>Screenshot</summary>

![Screenshot from 2022-09-06 12-35-54](https://user-images.githubusercontent.com/98787049/188636916-c88dc882-2e02-4c6e-9683-84589937563e.png)



</details>

**Comment by seia-soto** [comment]
I don't know about Edge, but never worked on Safari.

**Comment by piquark6046** [comment]
@NoName926 
Can I access your computer remotely, or can you export your configuration?

**Comment by Seohare** [comment]
@piquark6046  No remote access.   How do I export my configuration?

**Comment by Seohare** [comment]
@piquark6046  엣지 브라우저에서 추적 차단을 엄격으로 바꿔 보시고 테스트 해보세요. 추적 차단이 원인일 수 있습니다.

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/492#issuecomment-1238125029
AdGuard settings > general > Export settings

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/492#issuecomment-1238128540
Great. I can reproduce now.

**Comment by piquark6046** [comment]
I cannot resolve it unless you disable tracking protection feature of your browser.
Please disable it because you have AdGuard premium.
