### ISSUE TITLE
Android 포도알 app ad

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#495]
### URL

App

### FILTERS

List-KR

### Browser

(Other)

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment

![KakaoTalk_20220907_214845543](https://user-images.githubusercontent.com/99063049/188882376-06896453-9b76-4282-8217-a4b2fed4c05c.png)

![Screenshot_20220907-213942](https://user-images.githubusercontent.com/99063049/188881478-86931a25-958a-47ff-8562-1c23c1309537.png)

광고 시청을 누르면 애드블록에 의해 광고 송출이 안 되는 게 맞습니다.  앱이라서 광고 차단이 될지는 모르겠습니다.

**Comment by ghost** [comment]
안녕하세요. 해당 광고는 안드로이드 보안 정책 상 차단이 불가능합니다. 감사합니다.
