### ISSUE TITLE
lifere.tistory.com Anti-AdBlock

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#496]
### URL

https://lifere.tistory.com/28

### FILTERS

AdGuard Base
EasyPrivacy,
Peter Lowe's Blocklist,
Fanboy's Enhanced Tracking List,
Fanboy's Anti-Facebook List,
AdGuard URL Tracking,
AdGuard Tracking Protection
Fanboy's Annoyances,
Adblock Warning Removal List,
AdGuard Annoyances
Online Malicious URL Blocklist,
NoCoin Filter List
List-KR

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![1](https://user-images.githubusercontent.com/99063049/189115397-ff460cbd-c4da-42f1-a66f-db89be70e28d.png)

**Comment by piquark6046** [comment]
@NoName926 
Please upload your AdGuard configuration at here or email me with it. 
I cannot reproduce it.

**Comment by piquark6046** [comment]
Did you report the following issue?
- https://github.com/AdguardTeam/AdguardFilters/issues/129202

**Comment by Seohare** [comment]
@piquark6046  Yes

**Comment by piquark6046** [comment]
Do you use other 3rd-party browser extension?
@NoName926 

I cannot reproduce even if I import your subscribed filters and enable strict tracking protection of Microsoft Edge.

**Comment by Seohare** [comment]
확장 프로그램이랑 추적 방지, 사용자 필터를 끄고 다시 키니깐 문제가 해결 됐습니다. 
애드가드 nightly 버전을 사용 중이라서 버그가 많네요.
