### ISSUE TITLE
IC: I'm getting an error. old version.

### ISSUE THREAD

**Issue by oklokl** [List-KR/List-KR#499]
### URL

https://github.com/List-KR/List-KR/raw/master/filter.txt

### FILTERS

https://github.com/List-KR/List-KR/raw/master/filter.txt

### Browser

Mozilla Firefox

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Comment

![2](https://user-images.githubusercontent.com/1571600/189402044-fbe843fc-5f0e-4794-bedd-b19dc313fd3c.png)

I'm getting an error.

https://github.com/List-KR/List-KR/raw/master/filter.txt

**Comment by oklokl** [comment]
My mistake..
https://github.com/List-KR/List-KR/raw/master/filter-uBO.txt
this is it..

**Comment by piquark6046** [comment]
It seems that an general filter in EasyList interferes your List-KR update.
Please click `Purge all cache` and update all filter lists.

And, delete all List-KR filters list in your custom section.

**Comment by oklokl** [comment]
![3](https://user-images.githubusercontent.com/1571600/189408362-de5026eb-1003-4eb0-94bb-1134bb4d8706.png)
So I deleted it, but it still is.

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/499#issuecomment-1242246737
Copy & paste the following filter into `My filters`:
```adblock
@@/adservice.$domain=github.com|githubusercontent.com
```
Or, create new Firefox profile.

Also, please delete the highlighted filter, and use `KOR: List-KR` in `Regions, languages` section.

---

If you want to read more information about List-KR, please read [this doc](https://velog.io/@piquark6046/List-KR-adblocker)[^1].

[^1]: Written in Korean language.
