### ISSUE TITLE
https://www.naver.com/ [Incorrect blocking]

### ISSUE THREAD

**Issue by Alex-302** [List-KR/List-KR#5]
Shopping corner, right under of the add right side, is not the advertisement but one of function of portal web.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/6D3bNBe.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/ZymFRQT.jpg)
</details>

**Comment by ghost** [comment]
Fixed at https://github.com/List-KR/List-KR/commit/5a8a55f7f4c8e72c96cfd8e325ae2fa8abb0a954. Thanks for reporting!
