### ISSUE TITLE
||ssl.pstatic.net/tveta^ 제거 부탁합니다.

### ISSUE THREAD

**Issue by Mo-norn** [List-KR/List-KR#5]
||ssl.pstatic.net/tveta^ 이걸 차단함으로써 네이버에 다른 것들이 여러 문제가 발생합니다.

일단 2개 발견했는데 하나는 대충 넘어가서 어디서 발견했는지 못 찾겠고

하나는 네이버 메인

![Screenshot 2019-04-13 at 07 10 58](https://user-images.githubusercontent.com/34658160/56069328-8d293180-5dbd-11e9-9ce7-f1777f9f56dd.jpg)

ssl.pstatic.net/tveta/libs/assets/js/pc/main/min/pc.veta.core.min.js차단으로 
탭 클릭시 안넘어갑니다.

그 외 하나도 발견했는데 어디였는지 잊어먹어서.. 이거 말고도 ssl.pstatic.net/tveta가 다양하게 사용하고 있던 거 같아 문제가 여럿 있을 거라 생각하여 조금 더 좁게 차단해주셨으면 합니다.

감사합니다.

**Comment by ptrkr** [comment]
https://github.com/List-KR/List-KR/commit/e9c77d882297381ca4d8f71b3481ef6e49a714b8 커밋에서 `m.cafe.naver.com` 도메인에만 적용되도록 업데이트 하였습니다. 실제 적용되기까지 일정 시간이 소요될 수 있으나 적용 후에도 문제가 발생하는 경우 다시 피드백 남겨주시면 검토하겠습니다. 감사합니다.
