### ISSUE TITLE
AD: Naver Knowledge Notification Pop-up

### ISSUE THREAD

**Issue by oklokl** [List-KR/List-KR#500]
### URL

https://kin.naver.com/qna/detail.naver?d1id=1&dirId=10201&docId=427984439&mode=answer

### FILTERS

https://github.com/List-KR/List-KR/raw/master/filter-uBO.txt

### Browser

Mozilla Firefox

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Comment

![44](https://user-images.githubusercontent.com/1571600/189411018-24e21ce0-faea-43f6-8224-540830c68c6c.png)
I am a Naver intellectual.
A pop-up appears. keep coming out.
It keeps coming out every time you give an answer indefinitely.
So I told the Naver operator. To block this
You must save it as a cookie. is a new window
If you delete cookies when closing, it will continue to appear indefinitely.

I've tried blocking but it's not perfect.
So my suggestion.. Please make a blocking of Naver intellectuals. Far from intellectuals, they keep running on trivial things.
Very annoying.

네이버 지식인 입니다.
팝업이 뜨는대. 계속 나옵니다.
무한대로 답변을 달때 마다 계속 나옵니다.
그래서 네이버 운영자에게 말했지만.  이것을 차단 하기 위해서는
쿠키로 저장을 해야 합니다. 새로운 창 형태 이며
닫을때 쿠키 삭제를 하면 계속 무한대로 나옵니다.

내가 해봤던 차단 하지만 완벽 하진 않습니다.
그래서 나의 건의.. 네이버 지식인 차단도 만들어 주세요. 지식인에서 먼가 사소한 것들을 계속 뛰웁니다.
매우 짜증 나게 합니다.
```adblock
kin.naver.com##li.c-callout__item:nth-of-type(3)
kin.naver.com##li.c-callout__item:nth-of-type(2)
kin.naver.com##li.c-callout__item:nth-of-type(1)
kin.naver.com##._profileTooltip.callout--profile-tooltip.c-callout
```

intervertebral my message. If you block it incorrectly, the webpage scrolling on the right disappears.
추간 나의 메시지. 차단을 잘못 하면 우측에 웹페이지 스크롤이 사라집니다.

**Comment by piquark6046** [comment]
Currently, I cannot access a Naver account.
Can I access your computer remotely?

**Comment by oklokl** [comment]
https://kin.naver.com/qna/detail.nhn?d1id=1&dirId=1060114&docId=388147571&qb=6rCc67Cc7KSRIOuEpOydtOuyhCDslYTsnbTrlJTroZwg66Gc6re47J24&enc=utf8&section=kin.qna&rank=11&search_sort=0&spq=0
https://www.ipclub.co.kr/
Bypass login attempt with Korean IP is possible.
You can log in through this.
I. Remote access is difficult due to the exposure of personal information. Sorry.

But this is what happens when you reply.
It's impossible to just connect.
You must have a Korean user account.
Signing up for Naver in Korea is more difficult than you think.

하지만 이것은 답변을 달 경우 발생 합니다.
그냥 접속 한것으로 불가능 합니다.
한국의 사용자 계정이 있어야 합니다.
한국 네이버 가입은 생각 보다 까다롭습니다.
https://m.blog.naver.com/myfairry/150098147421

**Comment by piquark6046** [comment]
Then, Can I get a screenshot of Firefox's inspector?

**Comment by oklokl** [comment]
[test2.txt](https://github.com/List-KR/List-KR/files/9538060/test2.txt)

I don't know if this is correct.
이게 맞는지 모르겠습니다.

**Comment by piquark6046** [comment]
Please test the following filters:
```adblock
kin.naver.com#$#div#ticketCreationLayer[data-store-id="ticketCreationLayer"] { display: none !important }
kin.naver.com#$#body { overflow: auto !important; }
```

**Comment by oklokl** [comment]
wow 
감사 합니다 한번에 차단 하였습니다.
나는 평생 걸렸습니다 ㅎㅎㅎ
Thank you, blocked at once.
I've had it all my life haha
:)
^^/
