### ISSUE TITLE
AD: Naver Knowledge Notification Pop-up 2 mini reminder

### ISSUE THREAD

**Issue by oklokl** [List-KR/List-KR#501]
### URL

https://kin.naver.com/qna/detail.naver?d1id=1&dirId=10603&docId=427986990&mode=answer

### FILTERS

https://github.com/List-KR/List-KR/raw/master/filter-uBO.txt

### Browser

Mozilla Firefox

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Comment

답변 너무 감사 드립니다. 나는 욕심을 내어 보겠습니다.
바쁘신대 죄송 합니다

작은 팝업 입니다. 하지만 나는 매끄럽게 차단을 할수 없습니다.
내가 스포이드 기능을 제거 하면 잘 안되네요.

Thank you so much for your reply. I'll try to be greedy.
I'm sorry you're busy

It's a small pop-up. But I can't block smoothly.
If I remove the eyedropper function, it doesn't work.
![55](https://user-images.githubusercontent.com/1571600/189432507-c73a5df5-71b8-4998-9d3c-e430aadae803.png)

[test3.txt](https://github.com/List-KR/List-KR/files/9538303/test3.txt)
get screenshot of Firefox inspector

```
! 2020. 6. 22. https://kin.naver.com
kin.naver.com##li.c-callout__item:nth-of-type(3)
kin.naver.com##li.c-callout__item:nth-of-type(2)
kin.naver.com##li.c-callout__item:nth-of-type(1)
kin.naver.com##._profileTooltip.callout--profile-tooltip.c-callout
```
내가 차단 한거 것 입니다. 작동은 합니다.
하지만. 매끄럽지 않습니다.
나는 마우스로 빈 웹페이지를 클릭 해야 합니다.

That's what I blocked. It works.
However. It is not smooth.
I need to click on a blank webpage with the mouse.

이것은 쓸모 없는 알림이며
사용자는 이것을 피해서 마우스로 화면을 클릭 해야 글을 쓸수 있습니다.
나는 매우 불편합니다.
정리 하자면 마우스로 화면을 클릭 해야 글을 쓸수 있습니다.
이 미니 팝업 때문에 말이죠.

This is a useless notification
Users must avoid this and click the screen with the mouse to write.
I am very uncomfortable.
To summarize, you have to click the screen with the mouse to write.
Because of this mini popup.

**Comment by piquark6046** [comment]
Please try the following filters:
```adblock
kin.naver.com##+js(ra, style, .callout--profile-tooltip._profileTooltip, stay)
kin.naver.com##.callout--profile-tooltip._profileTooltip
```

**Comment by oklokl** [comment]
wow good
Thank you so much.
Works fine.
sorry. Please continue.
Well applied.
Stay healthy, Hwa-ting!

wow good
너무 감사 드립니다.
잘 작동 합니다.
죄송 해요. 계속 부탁 드려서.
잘 적용 하였습니다.
건강 하세요 화팅.!
