### ISSUE TITLE
www.coupang.com ad

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#504]
### URL

https://www.coupang.com/vp/products/111559792?vendorItemId=3824294564&isAddedCart=

### FILTERS

List-KR

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![17](https://user-images.githubusercontent.com/99063049/189562433-0cc80746-12a7-4084-9b8c-c0736f80a85e.png)

**Comment by piquark6046** [comment]
Where?

**Comment by Seohare** [comment]
![1](https://user-images.githubusercontent.com/99063049/189593277-b3af06af-1f72-4025-9319-62c073a6d11e.png)

원래는 광고가 있었는데 다시 보니깐 사라졌네요. 버그가 심한 것 같습니다.

**Comment by piquark6046** [comment]
Then, please downgrade AdGuard for Windows to stable channel.
