### ISSUE TITLE
IC: dvdprime.com

### ISSUE THREAD

**Issue by agabob** [List-KR/List-KR#506]
### URL

https://dvdprime.com/g2/bbs/board.php?bo_table=movienews&wr_id=34019

### FILTERS

List-KR

### Browser

Mozilla Firefox, Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Comment

Filter is blocking the content of the post.

**Comment by piquark6046** [comment]
@agabob Can you attach some screenshot?

**Comment by agabob** [comment]
![With List-KR](https://user-images.githubusercontent.com/11524657/189975751-223d60c5-1d82-4d01-9543-0876f9c6b6b5.png)
With List-KR


![Without List-KR](https://user-images.githubusercontent.com/11524657/189975811-78723d67-f590-48a5-96df-5af2d4723fd4.png)
Without List-KR

**Comment by piquark6046** [comment]
@agabob 
It is a bug of uBlock Origin.
You can use AdGuard Browser Extension instead of uBO.
Or, disable the related filter by adding the following filter into `My filters`:
```adblock
dvdprime.com#@?##view_warning .relative:has(ins.adsbygoogle):not([class*="_content"])
```

**Comment by piquark6046** [comment]
- https://github.com/uBlockOrigin/uBlock-issues/issues/2262
