### ISSUE TITLE
IC: https://gigglehd.com/gg/

### ISSUE THREAD

**Issue by dofuuz** [List-KR/List-KR#507]
### URL

https://gigglehd.com/gg/

### FILTERS

List-KR

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Comment

List-KR is blocking main contents banner of https://gigglehd.com/gg/ .
Disabling List-KR fixes the issue.

**Comment by piquark6046** [comment]
@dofuuz 
It is a bug of uBlock Origin.
You can use AdGuard Browser Extension instead of uBO.
Or, disable the related filter by adding the following filter into `My filters`:
```adblock
gigglehd.com#@?#div[style~="!important;"] > .nw_box > div:not(class):not(id) > table[cellspacing="0"][class]:not(:has(a[href*="//gigglehd.com/gg/"]))
```

- https://github.com/uBlockOrigin/uBlock-issues/issues/2262
