### ISSUE TITLE
카카오톡 app Incorrect Blocking

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#508]
### URL

info.ad.daum.net (app)

### FILTERS

List-KR DNS

### Browser

(Other)

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment

![KakaoTalk_20220914_221234752_02](https://user-images.githubusercontent.com/99063049/190344922-23daca08-1ff9-42e5-95aa-10aac82002f6.png)
![KakaoTalk_20220914_221234752_01](https://user-images.githubusercontent.com/99063049/190344925-4e3ddeff-8a73-4499-b81f-7527c934ebd8.png)
![KakaoTalk_20220914_221234752](https://user-images.githubusercontent.com/99063049/190344931-6c83e22b-39c5-4a93-84fe-1b8099248055.png)

**Comment by piquark6046** [comment]
@NoName926 If you allow the request, you will see Bizboard of Kakao that is displayed on friends and chatting section.

**Comment by Seohare** [comment]
@piquark6046    @@||info.ad.daum.net^ 규칙을 넣는 건 어떤가요?

**Comment by piquark6046** [comment]
It just provides information about Kakao Advertisement and a switch that can turn on/off personalized advertisement for web browser.

**Comment by Seohare** [comment]
@piquark6046 Okay.
