### ISSUE TITLE
noonnu.cc Anti-AdBlock

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#510]
### URL

https://noonnu.cc/

### FILTERS

list-kr

### Browser

Microsoft Edge, Samsung Internet

### Operating System

Microsoft Windows 11, Android

### Ad-Blocker

AdGuard for Windows, AdGuard for Android

### Comment

![KakaoTalk_20220919_084759876](https://user-images.githubusercontent.com/99063049/190933351-d9acf649-2e89-4132-85a3-19a39ace2286.png)

스크립트를 차단해 주세요.

**Comment by piquark6046** [comment]
Please disable
