### ISSUE TITLE
Redefine contents blocked by List-KR policy

### ISSUE THREAD

**Issue by piquark6046** [List-KR/List-KR#512]
From #335, #344 and #345, maintainers of List-KR have to redefine policy of List-KR.
_Actually, it is reminded by @green1052._

Also, maintainers of List-KR have to maintain List-KR as List-KR can be included in uBO, AdGuard and AdGuard Korean filter like EasyList-AdGuard Base filter relationship.

---

New List-KR policy, I thought, is as follows:

List-KR blocks advertisement and anti-adblock on Korean-language websites and applications.
The advertisement means a content:
   - defined in advertisement catalog of a website or application
   - containing an advertisement label in the content (e.g., `AD`, `ad`, `광고`)
   - promoting a product or service that are not related to the actual content that a visitor wants to read/use on the website.

**Comment by green1052** [comment]
i glad to hear that

**Comment by piquark6046** [comment]
@seia-soto @green1052 @Raiden-Ei 
What do you think about this?

**Comment by seia-soto** [comment]
I agree.

**Comment by green1052** [comment]
🤔

**Comment by green1052** [comment]
@piquark6046 #357 
how to do?
block all?

**Comment by piquark6046** [comment]
@green1052 
If you mean the app notification, List-KR does not block it.
