### ISSUE TITLE
ADU: Korean Naver intellectual roulette pop-up notification 

### ISSUE THREAD

**Issue by oklokl** [List-KR/List-KR#513]
### URL

https://kin.naver.com/

### FILTERS

KOR: List-KR

### Browser

Mozilla Firefox

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Comment

![1](https://user-images.githubusercontent.com/1571600/192166878-d029456a-5a66-4067-aee0-c4aa94ab273b.png)
#500 

```
! 네이버 곧 지식iN 룰렛 이벤트가 종료됩니다. 매우 짜증 나는 무한대 팝업 차단
kin.naver.com#$#div#rouletteEndAlertLayer { display: none !important }
```
[1.txt](https://github.com/List-KR/List-KR/files/9641880/1.txt)

(I succeeded in blocking)

Thank you, developer.
I applied what you taught me.
Works fine.
I upload it because I want to share it.
I want to brag, so I try to upload it. and the purpose of information sharing.

:)

**Comment by piquark6046** [comment]
@oklokl 
```adblock
kin.naver.com#$##rouletteEndAlertLayer { display: none !important; }
```

**Comment by oklokl** [comment]
thank you.
:)
