### ISSUE TITLE
ADU: Participated in Naver intellectual pop-up event. related

### ISSUE THREAD

**Issue by oklokl** [List-KR/List-KR#514]
### URL

https://kin.naver.com/

### FILTERS

KOR: List-KR

### Browser

Mozilla Firefox

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Comment

[1.txt](https://github.com/List-KR/List-KR/files/9650951/1.txt)
! 네이버 지식인 팝업 10주간 달성하면 최대 4만원의 선물!
kin.naver.com#$##eventPopupLayer2022SeasonThree { display: none !important; }

![1](https://user-images.githubusercontent.com/1571600/192417544-70dea458-fec7-4a4d-b734-1630a3015031.png)
#513

thank you. I added one today.
These ads are difficult to block in the usual way.
:)
I'm using it the way you told me.

**Comment by piquark6046** [comment]
??????????
