### ISSUE TITLE
AD: Chrome YouTube Ad Blocker.. New..

### ISSUE THREAD

**Issue by oklokl** [List-KR/List-KR#515]
### URL

https://youtu.be/pNYf1bJq6H8

### FILTERS

KOR: List-KR
[ublock-백업_2022-09-27_17.15.45.txt](https://github.com/List-KR/List-KR/files/9653332/ublock-._2022-09-27_17.15.45.txt)

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Comment

![1](https://user-images.githubusercontent.com/1571600/192472037-f6eaf3f1-2795-4367-a61f-85d4dcadea86.png)
[1.txt](https://github.com/List-KR/List-KR/files/9653344/1.txt)
YouTube ads are not intermittently blocked.
Last time I thought it was my mistake.
Looking back today, I'm not mistaken.
Recently. YouTube ads are not blocked.

**Comment by piquark6046** [comment]
@JobcenterTycoon @mapx-
Please take a look.
