### ISSUE TITLE
ADU: Naver blog notice popup.. block failed

### ISSUE THREAD

**Issue by oklokl** [List-KR/List-KR#516]
### URL

https://blog.naver.com/vnfmstjfxkd

### FILTERS

[ublock-백업_2022-09-27_18.48.23.txt](https://github.com/List-KR/List-KR/files/9654247/ublock-._2022-09-27_18.48.23.txt)

### Browser

Mozilla Firefox

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Comment

![2](https://user-images.githubusercontent.com/1571600/192494182-1b582184-9417-48db-8155-1a2f1a0bb2b2.png)

[1.txt](https://github.com/List-KR/List-KR/files/9654250/1.txt)

! 네이버 블러그 공지 팝업
kin.naver.com#$##personalNoticeLayer { display: none !important; }
(I tried like this, but it doesn't block.)

I tried to block it, but it failed.
I need help.
Sorry to keep posting.
thank you.

**Comment by piquark6046** [comment]
I need more data.
Please allow me to access your computer remotely.

**Comment by oklokl** [comment]
[2.txt](https://github.com/List-KR/List-KR/files/9654442/2.txt)
Sorry for not being able to connect remotely.
This is like all the top and bottom sources.
Thank you so much for being busy.


```
blog.naver.com#$##personalNoticeLayer { display: none !important; }
blog.naver.com#$#body { overflow: auto !important; }
```
My additional message PM 08:17
Success.
thank you
It works fine when I apply what you made in the past.
:)
