### ISSUE TITLE
Leftover: clien.net

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#518]
### URL

https://www.clien.net/service/
https://www.clien.net/service/group/allinfo

### FILTERS

List-KR

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

**Comment by ghost** [comment]
@piquark6046 not fixed. (v2022.928.0)

**Comment by piquark6046** [comment]
@rlfehd7915 
It works on AdGuard platform.
Please hold on... I am rewriting filters for uBO.

**Comment by piquark6046** [comment]
Done.
