### ISSUE TITLE
AD: search.naver.com

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#519]
### URL

https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=0&ie=utf8&query=가방
https://m.search.naver.com/search.naver?sm=mtp_hty.top&where=m&query=가방

### FILTERS

List-KR

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Comment

파워상품

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/commit/82e492800d1d56d5cb9cc160ee1971d1df55b008
