### ISSUE TITLE
AD: lolesports.com

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#522]
### URL

https://lolesports.com/

### FILTERS

List-KR

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Comment

sponsor logo

**Comment by piquark6046** [comment]
It is an international website.
You can see an advertisement logo placed there by visiting the following website:
 - https://lolesports.com/zh-TW
 - https://lolesports.com/th-TH
 - https://lolesports.com/en-SG
 - https://lolesports.com/de-DE
 
Please report it at https://github.com/uBlockOrigin/uAssets and https://reports.adguard.com/ko/new_issue.html.
