### ISSUE TITLE
ADU: Request to block banner set by Naver Cafe Manager

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#524]
### URL

https://cafe.naver.com/steamindiegame/7927658

### FILTERS

List-KR

### Browser

Microsoft Edge, Samsung Internet

### Operating System

Microsoft Windows 11, Android

### Ad-Blocker

AdGuard for Windows, AdGuard for Android

### Comment

![image](https://user-images.githubusercontent.com/99063049/193763909-838b637d-5da3-49f7-a651-2527ecc2fa18.png)

https://github.com/List-KR/List-KR/issues/489#issuecomment-1236838653

새로고침을 해야 광고가 사라집니다. 새로고침을 안 하면 광고가 그대로 보입니다.
버그 같은데 일반 버그 였으면 지금은 해결 되어야 합니다. 
애드가드 업데이트 후에도 여전히 네이버 카페 광고가 보입니다.  
수정 부탁드립니다. (필터는 최신 버전입니다.)

**Comment by piquark6046** [comment]
It cannot fixed by a rule.
Will be handed with https://github.com/List-KR/AdBlock4Cafe.

**Comment by Seohare** [comment]
> It cannot fixed by a rule. Will be handed with https://github.com/List-KR/AdBlock4Cafe.

@piquark6046  https://github.com/List-KR/AdBlock4Cafe 여기에 문제를 생성하면 되나요?

**Comment by piquark6046** [comment]
Nope.

**Comment by piquark6046** [comment]
An internal discussion is in progress in the slack.
https://listauthorschat.slack.com/archives/C010N14G4TF/p1664877049597139

**Comment by piquark6046** [comment]
@NoName926 Resolved by List-KR filter.
You don't have to install any userscript to hide the advertisement. Just update List-KR filter.

**Comment by Seohare** [comment]
@piquark6046  모바일은 적용이 안 되나요?

**Comment by piquark6046** [comment]
@NoName926 Resolved. But you need to use a web browser instead of Naver Cafe application.

**Comment by Seohare** [comment]
> @NoName926 Resolved. But you need to use a web browser instead of Naver Cafe application.

Okay. Thank you.

**Comment by Seohare** [comment]
![Screenshot_20221009_204924_Samsung Internet.png](https://user-images.githubusercontent.com/99063049/194755264-980a64ca-0733-4513-ac6f-738517c8c36b.png)

@piquark6046 필터는 최신 버전입니다. 모바일은 광고가 계속 보이는 것 같은데 저만 이런건가요?
현재 게시글 광고는 차단되지 않았고,
카페 첫 화면에 있는 광고는 잘 차단되네요.

**Comment by piquark6046** [comment]
Please see domain status of your browser.
You need to visit https://m.cafe.naver.com instead of that domain to block the advertisement.
@NoName926

**Comment by Seohare** [comment]
https://m.cafe.naver.com로 들어가도 광고가 그대로 보입니다.  HTTPS 필터링은 활성화가 된 상태입니다.
@piquark6046 

![Screenshot_20221010_073917_Samsung Internet.png](https://user-images.githubusercontent.com/99063049/194782950-b8ba4ff8-7971-4227-8cee-7293b1122e62.png)

**Comment by piquark6046** [comment]
@NoName926 Fixed.
