### ISSUE TITLE
쿠팡 배너

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#525]
### URL

https://m.coupang.com/vm/products/6245470132?itemId=12631385666

### FILTERS

List-KR

### Browser

Samsung Internet

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment

![Screenshot_20221007_191800_Samsung Internet](https://user-images.githubusercontent.com/99063049/194531678-2b249eb5-ebc9-4fb6-b50b-d749eaf04630.png)

**Comment by piquark6046** [comment]
Please enable AdGuard Popup filter or AdGuard Annoyance filter.
