### ISSUE TITLE
AD: noonoo.tv

### ISSUE THREAD

**Issue by himawarihome** [List-KR/List-KR#527]
### URL

https://noonoo.tv/drama/19295

### FILTERS

adguard dns
list-kr

### Browser

Google Chrome

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment

noonoo-images.studiouniversal.net/banner/ -> images.nstatic.org/banner/

**Comment by piquark6046** [comment]
It returns HTTP 404 error.
