### ISSUE TITLE
www.itworld.co.kr

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#541]
### URL

https://www.itworld.co.kr/news/259336

### FILTERS

List-KR

### Browser

Samsung Internet

### Operating System

Android

### Ad-Blocker

AdGuard for Android

**Comment by piquark6046** [comment]
@NoName926 
Did you mean the element like the following screenshot?
<details>
<summary>Screenshot</summary>

![Scree23](https://user-images.githubusercontent.com/98787049/195703781-aedd9216-2432-465c-bb45-74bd7fc30546.png)

</details>

**Comment by Seohare** [comment]
> @NoName926 
> Did you mean the element like the following screenshot?
> <details>
> <summary>Screenshot</summary>
> 
> ![Scree23](https://user-images.githubusercontent.com/98787049/195703781-aedd9216-2432-465c-bb45-74bd7fc30546.png)
> 
> </details>

Yes

**Comment by piquark6046** [comment]
It seems that the element is related to its publisher because IT WORLD and CIO Korea are being operated by a same cooperation.
Do you agree with me? @NoName926

**Comment by Seohare** [comment]
> It seems that the element is related to its publisher because IT WORLD and CIO Korea are being operated by a same cooperation.
> Do you agree with me? @NoName926 

@piquark6046 Yes

**Comment by piquark6046** [comment]
Okay. I will block the `sponsored` advertisement with List-KR and the element with Adguard annoyances filter.
