### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#542]
https://github.com/List-KR/List-KR/commit/b47b6cf8b88d483403ab675c3e1b67b81112237a 

@@||korail.com^$stealth 규칙 말고 @@||korail.com^$stealth=dpi 규칙도 적용이 됩니다.
@@$stealth=dpi 규칙을 사용하면 'DPI로부터 보호 기능' 만 비활성화 됩니다.
@@||korail.com^$stealth=dpi라고 규칙을 작성하는 건 어떤 가요?
'DPI로부터 보호 기능' 때문에 작동이 안 되는 사이트는 @@$stealth=dpi  규칙을 사용하는 게 더 좋다고 생각합니다.

**Comment by piquark6046** [comment]
The `$stealth` modifier cannot be applied on AdGuard for Android yet.
그 `$stealth` 수정자는 아직 AdGuard for Android에서 적용될 수 없습니다.

 - https://github.com/AdguardTeam/AdguardForAndroid/issues/4168

**Comment by Seohare** [comment]
> The `$stealth` modifier cannot be applied on AdGuard for Android yet.
> 그 `$stealth` 수정자는 아직 AdGuard for Android에서 적용될 수 없습니다.
> 
>  - https://github.com/AdguardTeam/AdguardForAndroid/issues/4168

그렇군요. 알겠습니다.
