### ISSUE TITLE
boannews.com site bug

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#544]
![image_2022-10-17_20-09-43](https://user-images.githubusercontent.com/99063049/196162832-4e0f026b-87b5-4117-b9ed-de096785ed14.png)

https://www.boannews.com/media/view.asp?idx=110742

사진 처럼 안전하지 않음 이라고 뜨고 광고도 차단이 안 됩니다. 어떨 때는 정상적으로 연결이 되고 광고도 차단이 됩니다.
왜 이런지 알 수 있을까요? 애드가드 https 필터링 때문에 발생한 문제 인가요?

**Comment by piquark6046** [comment]
Please try re-install your Adguard for Windows by using AdGuard official uninstaller[^1].
AdGuard 공식 설치 제거기로 Windows용 AdGuard를 재설치해보세요[^1].

그래도 해결이 안되시면, nProtect 같은 금융 플러그인을 설치하셨나요?
Nevertheless, if it is not resolved, have you installed a banking plugin like nProtect?

[^1]: https://cdn.adguard.com/distr/windows/Uninstall_Utility.zip

**Comment by Seohare** [comment]
> Please try re-install your Adguard for Windows by using AdGuard official uninstaller[1](#user-content-fn-1-9f49950f3e3f4e975ea217567c8620e4). AdGuard 공식 설치 제거기로 Windows용 AdGuard를 재설치해보세요[1](#user-content-fn-1-9f49950f3e3f4e975ea217567c8620e4).
> 
> 그래도 해결이 안되시면, nProtect 같은 금융 플러그인을 설치하셨나요? Nevertheless, if it is not resolved, have you installed a banking plugin like nProtect?
> 
> ## Footnotes
> 1. https://cdn.adguard.com/distr/windows/Uninstall_Utility.zip [↩](#user-content-fnref-1-9f49950f3e3f4e975ea217567c8620e4) [↩2](#user-content-fnref-1-2-9f49950f3e3f4e975ea217567c8620e4)

네, 시도해보겠습니다.
