### ISSUE TITLE
ADU: m.blog.naver.com

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#548]
### URL

https://m.blog.naver.com/need97/221973462238

### FILTERS

List-KR

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![image](https://user-images.githubusercontent.com/99063049/196427678-8284c41c-a5f7-4541-98f8-8522a332ebfe.png)

**Comment by piquark6046** [comment]
Even if the element is an advertisement, the element is published by the same author who is author of the article you requested.

**Comment by piquark6046** [comment]
@NoName926 Do you agree with me?

**Comment by Seohare** [comment]
> @NoName926 Do you agree with me?

Yes
