### ISSUE TITLE
AD: dpg.danawa.com

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#549]
### URL

https://dpg.danawa.com/bbs/view?boardSeq=28&listSeq=2224328&past=Y

### FILTERS

List-KR

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![image](https://user-images.githubusercontent.com/99063049/196427902-d0685774-3f2d-423a-ba71-02847599ba10.png)

![image](https://user-images.githubusercontent.com/99063049/196427925-07e665b2-ff3c-4186-89c9-9ec7f2fc6070.png)

**Comment by piquark6046** [comment]
The second element is not an advertisement.
https://img.danawa.com/help/pdf/ServiceProposal_danawa.pdf

**Comment by Seohare** [comment]
> The second element is not an advertisement.
> https://img.danawa.com/help/pdf/ServiceProposal_danawa.pdf

Okay
