### ISSUE TITLE
IC: clien.net

### ISSUE THREAD

**Issue by egk1234** [List-KR/List-KR#550]
### URL

https://www.clien.net/service/board/news/17644496?od=T31&po=0&category=0&groupCd=allinfo

### FILTERS

List-KR uBO

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Comment

The comment section at the bottom of the article is not showing while blocking the ads.

**Comment by piquark6046** [comment]
@kegang0619 I cannot reproduce it. Please update your filters.

**Comment by egk1234** [comment]
> @kegang0619 I cannot reproduce it. Please update your filters.

I updated my filter, and it works well. Thanks

**Comment by piquark6046** [comment]
@kegang0619 Can you write a post in clien.net even if your uBO is enabled?
