### ISSUE TITLE
AB: topjung.tistory.com

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#554]
### URL

https://topjung.tistory.com/entry/%ED%94%84%EB%A6%AC%EB%AF%B8%EC%96%B4-%EA%B8%B0%EC%B4%88-%E2%91%A3-%ED%83%80%EC%9D%B4%ED%95%91-%EC%9E%90%EB%A7%89%ED%9A%A8%EA%B3%BC

### FILTERS

list-kr

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![image](https://user-images.githubusercontent.com/99063049/197331310-79ac8505-4d47-45c8-9f38-087c654610a2.png)

**Comment by piquark6046** [comment]
Unable to reproduce.
Please describe the subscribed filters and privacy configuration of your Microsoft Edge.

**Comment by Seohare** [comment]
> Unable to reproduce. Please describe the subscribed filters and privacy configuration of your Microsoft Edge.
@piquark6046 

subscribed filters:
![image](https://user-images.githubusercontent.com/99063049/197334846-b61b25cf-4922-464d-8c91-b2f49da20afb.png)
![image](https://user-images.githubusercontent.com/99063049/197334845-5db89559-5d7e-4ea3-981f-63ad07d43ea4.png)
![image](https://user-images.githubusercontent.com/99063049/197334848-48be79e1-5c8d-469a-b2f9-60eb87fd902b.png)

![image](https://user-images.githubusercontent.com/99063049/197334866-0221d113-0d7d-4812-9523-f282cbb4b9c8.png)

**Comment by piquark6046** [comment]
Unable to reproduce.

**Comment by green1052** [comment]
i did reproduce in firefox
but adblocker isnt problom

**Comment by seia-soto** [comment]
Chromium (Arc) with uBO didn't reproduce.

**Comment by Seohare** [comment]
사용자 필터에 문제가 있는 것 같네요. 확인해 보겠습니다.

**Comment by green1052** [comment]
선생님... 그냥 전부 꺼보신 다음에 해보시면 되지 않습니까...
