### ISSUE TITLE
IC: encar.com

### ISSUE THREAD

**Issue by rog103** [List-KR/List-KR#557]
### URL

http://www.encar.com/dc/dc_carsearchlist.do?carType=kor

### FILTERS

KOR: List-KR

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Comment

![2022-10-28 00 12 27](https://user-images.githubusercontent.com/116824890/198329667-794c98ff-bf85-4b82-a073-ad6ec896bf36.png)

Main page is showing with white blank when use filter(KOR: List-KR)

**Comment by piquark6046** [comment]
@rog103 Cannot reproduce. Please check other adblocker or filter list.

**Comment by piquark6046** [comment]
Caused by EasyPrivacy. https://github.com/uBlockOrigin/uAssets/issues/15437
