### ISSUE TITLE
IC: clien.net

### ISSUE THREAD

**Issue by karlkkh** [List-KR/List-KR#559]
### URL

clien.net

### FILTERS

clien.net##.aside > div[class*="_"][class^="side_"]

### Browser

Google Chrome, Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

uBlock Origin

### Comment

`clien.net##.aside > div[class*="_"][class^="side_"]`
This filter hides 'side_account' class after logon. The hidden class includes some of important functions of the website.

`clien.net##.aside > div[class*="_"][class^="side_p"]`
This will solve the problem.

**Comment by piquark6046** [comment]
@karlkkh Can you send a screenshot of devtool inspector?
If you want to send it privately, please email `filters@adguard.com` or `piquark6046@proton.me`.

**Comment by piquark6046** [comment]
@karlkkh Please test List-KR uBO 2022.1029.0.

**Comment by karlkkh** [comment]
![image](https://user-images.githubusercontent.com/116953560/198835675-1d3f47b8-f3ce-40af-b25d-fd51f475cdc4.png)
I can see the right pane with the updated list. Thanks.
