### ISSUE TITLE
how about make bromite filter?

### ISSUE THREAD

**Issue by green1052** [List-KR/List-KR#560]
https://www.bromite.org/custom-filters

https://github.com/xarantolus/filtrite

**Comment by piquark6046** [comment]
List-KR contains some cosmetic rules, scriptlet rules and `$redirect` rules.
But, subresource_filter_tools, Bromite adblock filter generator, does not support `$redirect`, CSS rule, `$domain`, extended CSS, etc.
https://github.com/vpngall/filter/actions/runs/3351938895

**Comment by green1052** [comment]
https://github.com/vpngall/filter/blob/main/lists/korean_extended.txt#L48

**Comment by green1052** [comment]
ok
