### ISSUE TITLE
pandora.tv

### ISSUE THREAD

**Issue by piquark6046** [List-KR/List-KR#572]
http://www.pandora.tv/company/notice/view/1/1178

**Comment by piquark6046** [comment]
~~https://github.com/List-KR/List-KR/commit/4357054c5820b5064f077f24e8c0ae4713c45efe~~

**Comment by krystian3w** [comment]
`<del>` looks bad on links with `<tt>`/`<code>`.


---

Demo to future tests:

```html
<a href="./List-KR/List-KR/commit/4357054c5820b5064f077f24e8c0ae4713c45efe"><code><del>4357054</del></code></a>
```

~~https://github.com/List-KR/List-KR/commit/4357054c5820b5064f077f24e8c0ae4713c45efe~~ vs <a href="./List-KR/List-KR/commit/4357054c5820b5064f077f24e8c0ae4713c45efe"><code><del>4357054</del></code></a> (looks better but without pop-up).

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/commit/f1e74822755ad662e0df0d7ef562a9f72295afb7
