### ISSUE TITLE
AD: www.wassada.com

### ISSUE THREAD

**Issue by green1052** [List-KR/List-KR#574]
### URL

https://www.wassada.com/bbs_detail.php?bbs_num=569410&tb=board_freetalk&id=&num=&pg=

### FILTERS

list-kr

### Browser

Mozilla Firefox

### Operating System

Microsoft Windows 11

### Ad-Blocker

uBlock Origin

**Comment by piquark6046** [comment]
@green1052 Please take a look your ProtonMail inbox.

**Comment by green1052** [comment]
replied
