### ISSUE TITLE
IC: xetown.com

### ISSUE THREAD

**Issue by Lastorder-DC** [List-KR/List-KR#576]
### URL

https://xetown.com/

### FILTERS

||xetown.com/|$xmlhttprequest

### Browser

Google Chrome

### Operating System

Microsoft Windows 11

### Ad-Blocker

uBlock Origin

### Comment

AJAX is used widely at rhymix(Comment, Write, etc)

It's nonsense to block all xhr.
Please stop adding rules like this. XHR is not bad thing.

**Comment by piquark6046** [comment]
@Lastorder-DC The filter does not block all XMLHttprequests. [^1]
The main purpose that I added the filter is to block the advertisement request.
Also, I can see only the advertisement request as the following screenshot when I do not log in.

<details>
<summary>Screenshot</summary>

![Screenshot from 2022-12-20 08-57-46](https://user-images.githubusercontent.com/98787049/208626207-9137c91d-4ecb-41a9-83c8-6c1560bb36b5.png)

</details>

[^1]: https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#special-characters

---

By the way, when do you get an error using List-KR filters list as [YJPost's said](https://xetown.com/topics/1731660)? [^2]
Please note that disabling List-KR filters list causes many unblocked advertisements on Korean-language websites. [^3]

[^2]: Also, Incorrect blocking on NamuWiki was occurred by Umanle S.R.L.
To learn more, please read [this series](https://velog.io/@piquark6046/series/namuwiki).
[^3]: https://github.com/List-KR/List-KR/issues/285

**Comment by Lastorder-DC** [comment]
You have to login to check. And, I have confirmed that List-KR is blocking normal request

**Comment by piquark6046** [comment]
@Lastorder-DC Okay. I created as `고키와인간` nickname.
Where do you get an error using List-KR filters list?

**Comment by Lastorder-DC** [comment]
Try to write at any board.

**Comment by piquark6046** [comment]
Resolved.
It is hidden by `xetown.com,m.mt.co.kr##[class^="ad"]`.

**Comment by piquark6046** [comment]
@Lastorder-DC 
Information: The patch will be available in up to 4 hours if you use AdGuard-complied List-KR that is added in AdGuard products by default.
If you want to resolve right now and uses AdGuard, please add the following filters into user rules:
```adblock
||xetown.com/|$xmlhttprequest,badfilter
```
After 4 hours, please remove that.
