### ISSUE TITLE
korean illegal sites - Ad, nsfw

### ISSUE THREAD

**Issue by green1052** [List-KR/List-KR#579]
- [x] https://torrenttt55.com/
- [x] https://torrentnx6.com/
- [ ] https://torrentsir86.com/
- [x] https://torrentten03.com/
- [ ] https://torrentzota7.com/
- [ ] https://torrentmobile79.com/
- [x] https://torrenttip50.com/
- [x] https://www.torrentcar24.com/
- [ ] https://www.torrentcall9.com/
- [ ] https://www.torrentcool22.com/
- [ ] https://torrentj84.com/
- [x] https://torrenttop27.com/
- [x] https://torrent-who26.me/
- [x] https://www.etorrent11.com/
- [x] https://torpang36.com/
- [ ] https://link-top11.com/
- [ ] https://link-mac8.com/
- [x] https://linkrand4.com/
- [x] https://www.skytoon72.com/
- [x] https://www.allall57.com/
- [x] https://wtbox30.xyz/
- [x] https://tvbox27.xyz/
- [x] https://ydbox13.com/
- [x] https://nightyd7.com/
- [x] https://wftoon56.com/
- [x] https://mingk7.com/
- [x] http://new.1004girl.com/
- [ ] https://funbe190.com (navbar)
- [ ] https://www.hodu285.net (navbar)
- [ ] https://torrentwiz51.com/
- [ ] https://인생도박9.com/
- [ ] https://aniweek.com/
- [ ] https://kormovie.com/ (different)
- [ ] https://m32.kormovie.com/ (different)
- [ ] https://a.kormovie.com/ (different)

#444

**Comment by piquark6046** [comment]
@green1052 Where is an advertisement on https://www.skytoon72.com/?
I can see only some leftovers.

**Comment by piquark6046** [comment]
@green1052 The advertisements of https://torpang36.com/ are already blocked in List-KR filter.

https://github.com/List-KR/List-KR/blob/1972d563332b5df1ae796ed6ed552cddee35c71d/filters-share/specific_URL.txt#L694-L696

**Comment by piquark6046** [comment]
The link-mac8.com issue will be resolved when the following issue is resolved:
 - https://github.com/AdguardTeam/ExtendedCss/issues/157

**Comment by green1052** [comment]
> @green1052 The advertisements of https://torpang36.com/ are already blocked in List-KR filter.
> 
> https://github.com/List-KR/List-KR/blob/1972d563332b5df1ae796ed6ed552cddee35c71d/filters-share/specific_URL.txt#L694-L696

![image](https://user-images.githubusercontent.com/34261355/209193811-50a9d4e2-f4fb-4b85-9583-0904c51d3b60.png)

check mobile version

**Comment by piquark6046** [comment]
The link-top11.com issue will be resolved when the following issue is resolved:
 - https://github.com/AdguardTeam/ExtendedCss/issues/157

**Comment by green1052** [comment]
@piquark6046 

torrentnx6.com banner broken

with adblocker
![image](https://user-images.githubusercontent.com/34261355/210229071-c0a03c65-fb7a-4f81-a6dc-4b4dd8f67023.png)

without adblocker
![image](https://user-images.githubusercontent.com/34261355/210229087-14ee9847-2b63-41f7-b314-cfc1d5a9f663.png)

**Comment by piquark6046** [comment]
https://etoland.co.kr/bbs/board.php?bo_table=etohumor06&wr_id=347477

**Comment by MyKareee** [comment]
Please add this site too: https://torrentgram53.com/
