### ISSUE TITLE
IC: daisomall.co.kr

### ISSUE THREAD

**Issue by green1052** [List-KR/List-KR#582]
### URL

https://www.daisomall.co.kr/

### FILTERS

list-kr

### Browser

Mozilla Firefox

### Operating System

Microsoft Windows 11

### Ad-Blocker

uBlock Origin

### Comment

```
daisomall.co.kr##.wing_banners
daisomall.co.kr##.table_goods_info_adcoupon
daisomall.co.kr##.forbizSlider
daisomall.co.kr##.header_top
daisomall.co.kr##a[href^="/banner.link.php?"]
||image.daisomall.co.kr/data/daiso_data/images/banner/
```

```
||image.daisomall.co.kr/data/daiso_data/images/banner/
```
로그인 화면 보험 광고 뿐만이 아닌 메인화면 베너도 같이 차단합니다.

그 외 나머지 규칙들은 광고가 아닌 자체 광고임으로 차단하지 않는것이 좋아 보입니다.

**Comment by piquark6046** [comment]
> 그 외 나머지 규칙들은 광고가 아닌 자체 광고임으로 차단하지 않는것이 좋아 보입니다.

https://github.com/List-KR/List-KR/issues/512 ??

**Comment by green1052** [comment]
![image](https://user-images.githubusercontent.com/34261355/210178352-59dfcff1-b38b-4429-83e2-53f3b0255323.png)

**Comment by piquark6046** [comment]
@green1052 The advertisement in [its login page](https://www.daisomall.co.kr/member/login.php?url=) does not have any advertisement label.
But, Advertisements in its homepage exist under a `a[href^="/banner.link.php"]` element like the advertisement in its login page.

**Comment by green1052** [comment]
![Screenshot_20230102_203318_Bromite](https://user-images.githubusercontent.com/34261355/210225974-aad488e1-b6a1-44c9-8634-807570d5d964.jpg)

**Comment by green1052** [comment]
list-kr 2023.0102.
