### ISSUE TITLE
IC: dailymotion.com

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#589]
### URL

https://www.dailymotion.com/video/x72n8fz

### FILTERS

Ad Blocking:
AdGuard Base

Privacy:
AdGuard Tracking Protection,
AdGuard URL Tracking,
Peter Lowe's Blocklist,
Fanboy's Anti-Facebook List

Annoyances:
AdGuard Annoyances,
Adblock Warning Removal List

Security:
NoCoin Filter List

Language-specific:
List-KR

Custom filters: https://malware-filter.gitlab.io/malware-filter/tracking-filter.txt,  https://secure.fanboy.co.nz/r/fanboy-ultimate.txt

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![스크린샷_20230107_032047](https://user-images.githubusercontent.com/99063049/211134461-a3011ebe-c132-47b0-a707-0e8a109bd5b2.png)

**Comment by piquark6046** [comment]
Contents in this website does not use Korean language mainly.
Also, It is not caused by List-KR filter.

**Comment by piquark6046** [comment]
@NoName926 
It seems that it is caused by https://malware-filter.gitlab.io/malware-filter/tracking-filter.txt.
Please remove the filter.
