### ISSUE TITLE
Issue with Investing.com

### ISSUE THREAD

**Issue by DrKita** [List-KR/List-KR#592]
Thankyou for your nice adblock list. I have a error while using List-KR when access at investing.com's some pages.
![화면 캡처 2023-01-12 110457](https://user-images.githubusercontent.com/17443139/211958519-69bf2524-6b60-43f3-93ee-382dfef8da42.jpg)

When I turned off List-KR, webpage is working correctly, so i think this problem happens with List-KR Filter. This error occurs at following pages: https://www.investing.com/indices/indices-futures, https://www.investing.com/indices/major-indices this pages. Thankyou for reading my issue.

**Comment by piquark6046** [comment]
@DrKita 
Are you use AdGuard or uBlock Origin?
Also, your filters list is required.
