### ISSUE TITLE
Discord 서버 개설에 대한 의견을 받습니다.

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#593]
이미 Slack 채널이 있기는 하나 해당 채널은 List-KR뿐만 아니라 모든 필터를 총망라하는 채널이고, 무엇보다 영어이기 때문에(...) 한국어 웹사이트의 광고 차단을 목표로 하는 본 필터의 소통 창구로 활용되기에는 다소 적합하지 않은 면이 있습니다.

Discord가 게이머를 위한 메신저인 것은 사실이나, [Server Verification](https://discord.com/verification) 제도 등 다른 커뮤니티에 대한 지원 제도도 있어 목적에 맞게 사용하면 큰 문제는 없을 것이라 판단됩니다.

이에 Organization 및 Repository 소유자로서 필터 기여자 분들과 다른 사용자분들의 의견을 구하고자 이슈를 개설하게 되었습니다. 자유롭게 의견 개진 부탁드립니다.

의견 수렴 종료 기간은 현재로써는 딱히 정해두진 않았으며, 객관적으로 보기에 충분한 양의 총의가 모였다고 판단되면 종료할 계획입니다. 감사합니다.

**Comment by piquark6046** [comment]
저는 Discord를 안 사용합니다.[^1]
https://tosdr.org/en/service/536

[^1]: I don't use Discord.

**Comment by green1052** [comment]
반대합니다

**Comment by piquark6046** [comment]
사실, Discord 서버를 생성했을 때, 많은 이가 참여할거라는 보장이 없습니다.
만약 홍보를 한다면, 많은 이들이 관심을 가질 AdGuard나 uBlock Origin 관련 이슈에 고정적인 초대 URL를 첨부하는 것이 나은 선택지 인 것 같습니다.

<details><summary>English</summary>

In fact, there are no guarantees that many peoples get involved, when a Discord server is created.
If a promotion is performed, it seems that attaching a fixed invitation URL into an issue related to AdGuard or uBlock Origin that can interests is a better option.

</details>

Examples:
 - https://gall.dcinside.com/mgallery/board/view/?id=sff&no=561913&page=1
 - https://pgr21.com/humor/0?page=1&divpage=82&no=462836
 - https://www.fmkorea.com/5033788773
 - https://www.fmkorea.com/5027629912
 - https://www.dogdrip.net/432963090

**Comment by piquark6046** [comment]
아니면, 가능하다면, AdGuard 이나 uBlock Origin 한국어 Discord 서버로 만드는게 어떤가요?

<details><summary>English</summary>

Or, If possible, What about creating an AdGuard or uBlock Origin Korean-language Discord server?

**Comment by seia-soto** [comment]
List-KR의 커뮤니티 활동을 반대합니다. GitHub는 현재 이슈 트래커로 충분한 역할을 하고 있으며 다른 사람들이 받아들이기에 저희의 기준을 스스로 설명할 만큼 충분히 성숙하지 못하였습니다.

**Comment by ghost** [comment]
List-KR 액세스 권한이 있는 모든 멤버가 반대 의사를 표명하였으므로 실효성이 없다고 판단되어 wontfix로 종결 처리하겠습니다. 소중한 의견 감사합니다.
