### ISSUE TITLE
AD: 금융인증서 인증 화면

### ISSUE THREAD

**Issue by gaeulbyul** [List-KR/List-KR#594]
### URL

* https://gov.kr
* https://www.nhis.or.kr
* https://hometax.go.kr
* 기타 금융인증서 인증을 사용하는 국내 웹사이트

### FILTERS

* List-KR (Version: 2023.0116.7 )
* AdGuard Base filter
* AdGuard Tracking Protection filter
* AdGuard Social Media filter

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 10

### Ad-Blocker

AdGuard Browser Extension

### Comment

제가 금융인증서로 웹사이트에 로그인을 하는 도중에 광고를 발견했는데요, 이런 광고도 List-KR에서 차단대상으로 보시나요?

스크린샷
=====

![금융인증서 로그인 화면. 이름, 핸드폰번호, 생년월일을 묻는 칸이 있고 그 아래에 배너광고가 있다.](https://user-images.githubusercontent.com/830515/212679625-b8b740bd-13c2-4d5d-8089-307bdc4d37ab.png)

![금융인증서 비밀번호 입력 화면. 숫자패드 상단에 "경품 이벤트 참여" 버튼이 있다"](https://user-images.githubusercontent.com/830515/212679654-d01e9b2d-6ecd-4842-a03c-c1f95f8f6885.png)

필터
=====

```adblock
! 광고 1 (배너광고 이미지 차단)
||4user.yeskey.or.kr/bnr-img^$image
```

**Comment by piquark6046** [comment]
> 제가 금융인증서로 웹사이트에 로그인을 하는 도중에 광고를 발견했는데요, 이런 광고도 List-KR에서 차단대상으로 보시나요?

광고로 보기는 하는데요. 보안이 강력히 요구되는 웹 페이지가 아닌가요?
일단, 확인은 해보겠습니다.

PS. ProtonMail을 확인해주세요.

**Comment by gaeulbyul** [comment]
네, 메일 기다리겠습니다.

**Comment by piquark6046** [comment]
경품 이벤트 참여 버튼의 숨기기(`##`)는 AdGuard Browser Extension과 uBlock Origin에서 안됩니다. 

---

2022년 12월 25일에 현재 GitHub 닉네임 + ProtonMail으로 된 메일 주소로 보낸 메일이 있습니다.

**Comment by gaeulbyul** [comment]
아, 당시 보냈던 메일은 확인했습니다.
버튼 숨기는 필터는... 이건 제가 잘못 썼네요. 제대로 작동하지 않습니다...
(개발자도구 갖고 잘 살펴보니 해당 버튼은 `<iframe>` 안에 있는데, 그 iframe문서의 주소는 `about:blank`로 나타나네요... 이런 경우는 본 적이 없어서 어찌 해야 모르겠습니다... 😅)

**Comment by piquark6046** [comment]
이런 경우는 유저스크립트로 손봐야 할 것 같습니다.
https://sdk.yeskey.or.kr/v1/fincert-ui.js 가 그 이벤트 참여 버튼을 포함한 금융 인증서 로그인 UI을 만드는 것으로 보입니다.

**Comment by gaeulbyul** [comment]
개인적으로 자주 사용하는 사이트가 아니다보니 유저스크립트를 더 만들정도까진 아닐거 같기두 하네요... 으음, 달리 수요가 더 있지 않은 이상 나중으로 미뤄도 되지 않을까 싶긴 합니다...

**Comment by gaeulbyul** [comment]
필터 업데이트가 된 걸 확인했으니 이 이슈는 닫아도 될거같아요.
