### ISSUE TITLE
Google invaild search result

### ISSUE THREAD

**Issue by piquark6046** [List-KR/List-KR#598]
- https://gigglehd.com/gg/bbs/13666041
 - https://www.dogdrip.net/460145467

**Comment by green1052** [comment]
해당 규칙은 List-KR이 아니라 Adguard나 ublock쪽에 등록하는게 좋아보이는데 어떻게 생각하시나요?

**Comment by green1052** [comment]
심지어 해당 규칙과 유사한 규칙이 `uBlock filters – Badware risks`에 등록되어 있네요

``` 
/^https?:\/\/((?!www)[a-z]+|\d{2,4})?\.?[-0-9a-z]{5,}\.[a-z]{2,6}\/(?:[0-9a-z]{6,8}\/)?\/?\?u=[0-9a-z]{7}&o=[0-9a-z]{7}/$document,match-case,domain=buzz|com|de|fun|guru|info|life|live|mobi|online|pw|site|skin|space|top|us|xyz
```

**Comment by piquark6046** [comment]
@green1052 👀
https://github.com/uBlockOrigin/uAssets/issues/16596#issuecomment-1416205847
