### ISSUE TITLE
AD: pushoong.com

### ISSUE THREAD

**Issue by liberaldev** [List-KR/List-KR#599]
### URL

https://pushoong.com/ask/7256110570

### FILTERS

애드가드 베이스 필터, List-KR

### Browser

Google Chrome

### Operating System

Microsoft Windows 11, Android

### Ad-Blocker

AdGuard for Windows, AdGuard for Android

### Comment

애드가드를 써도 해당 URL에 대한 상단 배너가 깔끔하게 제거되지 않는 문제가 있어 이에 따른 추가적인 조치가 필요합니다.

**Comment by piquark6046** [comment]
해결했어요.
패치는 AdGuard가 컴파일한 필터를 사용하신다면, 최대 4시간안에 사용하실 수 있습니다.
최대 4시간이 지난 후에 Windows에서는 AdGuard 트레이 메뉴에 있는 `필터 업데이트 확인...`을 클릭하여 다운로드하실 수 있으며, Android에서는 AdGuard 홈에 있는 `업데이트 확인`을 터치해서 다운로드하실 수 있습니다.
