### ISSUE TITLE
sms-receive.net [Anti Adblock Script]

### ISSUE THREAD

**Issue by Alex-302** [List-KR/List-KR#6]
AdGuard
Filters: Base, Annoyances(fixes this issue when List-KR is not enabled), List-KR

Screenshot:
<details>

![image](https://user-images.githubusercontent.com/8361299/60963084-85275200-a318-11e9-85e9-5350b5f20125.png)

</details>

Possible fix: `sms-receive.net#@#ins.adsbygoogle[data-ad-client]:not([data-matched-content-ui-type])`

**Comment by ghost** [comment]
Fixed at https://github.com/List-KR/List-KR/commit/e6bca0dd583e0ecddec5fad35fb77da5ebeb2255. Thanks for reporting!
