### ISSUE TITLE
AD: m.fmkorea.com 광고 자리 여백

### ISSUE THREAD

**Issue by relaxedbrownie** [List-KR/List-KR#609]
### URL

m.fmkorea.com

### FILTERS

https://filters.adtidy.org/ios/filters/2_optimized.txt

https://raw.githubusercontent.com/List-KR/List-KR/master/filter.txt

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

광고가 지워진 흔적이 여백으로 남아요. 체크 표시해뒀어요.
![IMG_3778](https://github.com/List-KR/List-KR/assets/126370491/37084f8a-53c3-4184-b664-757f99638c6a)

**Comment by piquark6046** [comment]
Android에서는 안보이는데, 혹시 아래 규칙을 AdGuard 설정 탭 -> 고급 모드를 스위치를 켜고 고급 설정 -> 콘텐츠 차단기에서 추가하실 수 있나요?
```adblock
m.fmkorea.com##iframe[src*="//loader.fmkorea.com/_loader/loader.php"]
```

**Comment by relaxedbrownie** [comment]
아무 글이나 눌러서 들어가면 하단 여백이 사라지는데 메인 화면에 있는 하단 여백은 안 사라지네요. m.fmkorea.com 접속하면 바로 뜨는 화면이에요.
![EC56A52A-80E7-4926-B2C0-84799E60D0FF](https://user-images.githubusercontent.com/126370491/221393858-2b0cbfb1-6077-4da6-ba18-55331cd2d2b7.jpeg)

**Comment by piquark6046** [comment]
이전에 알려드린 규칙을 제거하시고 아래 규칙을 새로 테스트해주세요:

```adblock
m.fmkorea.com##iframe[src*="//loader.fmkorea.com/"][src*="_loader/"]
```

**Comment by relaxedbrownie** [comment]
해결됐어요. 타 사이트에서도 같은 현상을 발견했는데 여기서 이어서 여쭤봐도 될까요? 아니면 글을 새로 쓸까요?
https://m.ppomppu.co.kr/new/bbs_list.php?id=ppomppu 뽐뿌게시판뿐만 아니라 다른 게시판에서도 여백이 보여요.
![IMG_3779](https://github.com/List-KR/List-KR/assets/126370491/edb32253-54c4-494a-9602-d4e72bc2ccd3)

**Comment by piquark6046** [comment]
아마 기본 규칙(웹 요청을 차단하는 규칙)으로 차단된 요소를 자동으로 숨겨지게 하는 규칙도 같이 실행하는 기능은 AdGuard for iOS에는 없는 것 같네요. 테스트해보시겠어요?
```adblock
m.ppomppu.co.kr##ul[class^="bbsList"] > div[style*="clear: both;"].sect0
```

**Comment by relaxedbrownie** [comment]
이것도 해결됐어요. 감사합니다!

**Comment by piquark6046** [comment]
두 규칙이 List-KR 필터에 적용되었으니, 자동 업데이트를 고려했을 때 4일 후(AdGuard 기본 값)에 기본값으로 적용될 예정입니다.
그 이후에는 두 규칙을 사용자 규칙에서 제거하셔도 무방합니다.

**Comment by relaxedbrownie** [comment]
감사합니다. 그럼 수고하세요!
