### ISSUE TITLE
EBS 영상 플레이어에 있는 추적 코드 제거 요청

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#614]
URL: https://mid.ebs.co.kr/course/view?courseId=10209920 

아무 영상 클릭해서 재생하고, F12를 눌러서 보면 아래 사진 처럼 추적 스크립트가 있습니다.
추적 스크립트 제거 가능한가요?

![1](https://user-images.githubusercontent.com/99063049/222030706-10eed25e-0fb3-4e37-a160-0c07d41f4564.png)

**Comment by piquark6046** [comment]
AdGuard 추적 보호 필터에 추가했어요.
