### ISSUE TITLE
IC: m.sports.naver.com

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#615]
### URL

https://m.sports.naver.com/video/1034654

### FILTERS

https://github.com/List-KR/List-KR/raw/master/filter.txt

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

Video playback is not possible when using an ad blocker or VPN environment.
Please check again.

**Comment by piquark6046** [comment]
@swbaek81 Can you provide little information:
1. Did you enable Advanced Protection feature of AdGuard for iOS?
2. Please list all subscribed filters.

**Comment by piquark6046** [comment]
Because I don't have an Apple device and check with another, the processing can be delayed.

**Comment by swbaek81** [comment]
I only use LIST KR. (= Safari & DNS)
https://github.com/List-KR/List-KR/raw/master/filter.txt
https://adguardteam.github.io/HostlistsRegistry/assets/filter_25.txt

However, the same NG occurs even if List Kr is Off and Adguard Base Filter is On.

Therefore, when a Naver Sports video is played, I would like LIST KR to turn off the ad blocking function (= to be able to watch the video after watching the advertisement)

![Advanced Protection](https://user-images.githubusercontent.com/15683789/222455803-75d150ff-791e-4217-868a-f7e573c0efda.png)
![dns](https://user-images.githubusercontent.com/15683789/222455810-ce8ed648-308d-4b4f-9abd-d9d9b08420dd.png)
![safari](https://user-images.githubusercontent.com/15683789/222455816-86c4db03-77d8-475c-a4a3-667f1ea44e08.png)
