### ISSUE TITLE
AD: torrentdia93.com

### ISSUE THREAD

**Issue by bestplayerbotphone** [List-KR/List-KR#617]
### URL

`torrentdia93.com/bbs/board.php?bo_table=torrent_movieko`

### FILTERS

List-KR

### Browser

Brave

### Operating System

Microsoft Windows 11

### Ad-Blocker

uBlock Origin

### Comment

![image](https://user-images.githubusercontent.com/121412413/222905755-bdc65094-0c91-4076-9c0c-3c96d26cc09a.png)

**Comment by bestplayerbotphone** [comment]
Proposed fix:
```
torrentdia93.com,torrentdia94.com,torrentdia95.com,torrentdia96.com,torrentdia97.com,torrentdia98.com,torrentdia99.com,torrentdia100.com,torrentdia101.com,torrentdia102.com,torrentdia103.com,torrentdia104.com,torrentdia105.com,torrentdia106.com,torrentdia107.com##tbody > tr:nth-of-type(1), tr:nth-of-type(2), tr:nth-of-type(3)
```

**Comment by bestplayerbotphone** [comment]
Hey @piquark6046 I am still seeing ads in `torrentdia93.com` after updating the lists

**Comment by piquark6046** [comment]
Fixed.
