### ISSUE TITLE
meeco.kr

### ISSUE THREAD

**Issue by piquark6046** [List-KR/List-KR#619]
The administrator of meeco.kr updates their website to make adblocker an incorrect blocking.

**Comment by seia-soto** [comment]
Tried to check on latest, but couldn't see any incorrect blocking. Can you share?

**Comment by piquark6046** [comment]
I had added the related commits (https://github.com/List-KR/List-KR/commit/555070c7ac6116e798d1db85d994fb1ab5181bda https://github.com/List-KR/List-KR/commit/0a88d1ca2bc37088b4e51676bd91c7fb5e448718).
However, I removed the rules after 3 days because the rules hided summaries of BBSes in https://meeco.kr. https://github.com/List-KR/List-KR/commit/405d2b411f6ab807e9cfbe27d086df6b32826bf5

**Comment by piquark6046** [comment]
A strange anti-adblock script is found on only AdGuard for Android.

**Comment by piquark6046** [comment]
It is just a bug related to the removed extCSS rules.
