### ISSUE TITLE
Rename filename of List-KR filter

### ISSUE THREAD

**Issue by piquark6046** [List-KR/List-KR#621]
## Summary
 - List-KR for AdGuard will be renamed to `https://cdn.jsdelivr.net/gh/List-KR/List-KR@master/filter-AdGuard.txt`
 - List-KR for uBlock Origin will be renamed to `https://cdn.jsdelivr.net/gh/List-KR/List-KR@master/filter-uBlockOrigin.txt`

## The changes
- The filename of List-KR for AdGuard in this repo will be changed to `/filter-AdGuard.txt`.
- The filename of List-KR for uBlock Origin in this repo will be changed to `/filter-uBlockOrigin.txt`.
- The cache existing in jsDelivr network will be purged automatically with [List-KR/jsdelivr-purge](https://github.com/List-KR/jsdelivr-purge) if there is an update.

### Negative effect
 - Users should reinstall List-KR filter, if they install the filter via a URL address.

### Positive effects
 - Accelerate response time and download speed.
 - Traffic transmitted to GitHub server will be reduced.

### Timeline

Date and Time | Event | Status  | Related Issues
------------- | ----- | ------- | --------------
 Mar 15, 2023 | Submit and apply a request changing List-KR filter list's `contentURL` and removing `cdnURL` in uBlock Origin | Resolved | https://github.com/uBlockOrigin/uBlock-issues/issues/2546
 Mar 15, 2023 | Submit and apply request changing List-KR filter's URL | Resolved | https://github.com/AdguardTeam/FiltersRegistry/issues/759
 April 07, 2023 | Remove the old versions | Resolved | None

**Comment by piquark6046** [comment]
@seia-soto @green1052 @JobcenterTycoon @Raiden-Ei

**Comment by seia-soto** [comment]
Can't we just change the CDN host only? If so, the only negative effect will not be occur and we can stay safe.

**Comment by piquark6046** [comment]
Yes. We can change CDN host only.
However, It can make a user focuses on the supporting adblock platforms.
