### ISSUE TITLE
ADU: cafe.naver.com/steamindiegame

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#622]
### URL

https://cafe.naver.com/steamindiegame

### FILTERS

list-kr

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![image](https://user-images.githubusercontent.com/99063049/223684636-f7b27f93-fa22-4a9c-96dc-40d71bed66e3.png)

**Comment by Seohare** [comment]
@piquark6046  필터 업데이트 했습니다. 
아직 광고가 나옵니다.

**Comment by piquark6046** [comment]
AdGuard 브라우저 확장에서는 잘 되는데요.
한번 AdGuard for Windows으로 테스트해볼께요.

**Comment by piquark6046** [comment]
AdGuard for Windows에 List-KR, AdGuard 베이스 필터와 AdGuard 추적보호 필터를 사용할 때의 결과가 아래 사진과 같습니다:

<details><summary>스크린샷</summary>

![Screenshot from 2023-03-09 08-43-01](https://user-images.githubusercontent.com/98787049/223967680-8fb5f370-008f-4f44-b5ab-faf3d9999974.png)

</details>

한번 Microsoft Edge의 캐시를 삭제해보시겠어요?

**Comment by Seohare** [comment]
@piquark6046 

![ad1](https://user-images.githubusercontent.com/99063049/224679461-7eba3998-7383-466f-a55f-8a93df6af1c1.png)

![ad2](https://user-images.githubusercontent.com/99063049/224679468-3793c2a5-4df5-43b7-b512-450f14711092.png)

캐시 삭제 해봤고 혹시 몰라서 몇 일 기다려봤습니다. 그런데 아직도 광고가 노출됩니다.

**Comment by piquark6046** [comment]
확인해보는 중입니다.

**Comment by piquark6046** [comment]
@NoName926 혹시 List-KR 단독으로만 시도해보시겠어요?
