### ISSUE TITLE
IC: grip.show

### ISSUE THREAD

**Issue by relaxedbrownie** [List-KR/List-KR#625]
### URL

https://www.grip.show/

### FILTERS

AdGuard 베이스 필터
AdGuard 모바일 광고 필터
AdGuard 방해 요소 필터
List-KR

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

혹시 AdGuard 베이스 필터도 여기에 제보해도 되나요?
![5095B167-40E6-4C39-A35C-226C4C4E28B8](https://user-images.githubusercontent.com/126370491/224012842-dd5090e6-d9b2-4078-9aac-cc37d24cbf8c.jpeg)

---------------------

![57A13E9D-DB0D-4622-BDA5-1C4413D482EB](https://user-images.githubusercontent.com/126370491/224012882-777b1855-fe75-4af9-be5f-b23206547bfe.jpeg)

해당 쇼핑몰의 자체 배너라서 광고라고 보기는 어려운 거 같은데 저 부분이 삭제되면서 페이지가 이상하게 나타나네요.

**Comment by piquark6046** [comment]
AdguardFilters에 패치했습니다.
최대 1시간 이후에 필터 업데이트를 수동으로 다운로드하실 수 있습니다.
