### ISSUE TITLE
AD: nsfw sites

### ISSUE THREAD

**Issue by green1052** [List-KR/List-KR#626]
### URL

https://kr1.hasha.in/
https://save-1.net/
https://booktoki220.com/

### FILTERS

1

### Browser

Mozilla Firefox

### Operating System

Microsoft Windows 11

### Ad-Blocker

uBlock Origin

### Comment

![image](https://user-images.githubusercontent.com/34261355/224054918-57edd1fd-b5e0-493a-8e49-5c69493183a0.png)

booktoki

**Comment by piquark6046** [comment]
:thinking: 

<details><summary>Screenshots</summary>

![Screens434_001](https://user-images.githubusercontent.com/98787049/224292028-6e60d975-dde8-4fce-8e87-275884eff405.png)

![Scr434](https://user-images.githubusercontent.com/98787049/224292005-aefc98d7-86f8-4ab5-88d4-eb85a667432f.png)

![Screenshot from 2023-03-10 10-30-56](https://user-images.githubusercontent.com/98787049/224293283-15a3e004-2286-4cea-b192-da334ffb8d51.png)

</details>
