### ISSUE TITLE
AD: yatv.net (NSFW)

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#628]
### URL

yatv.net/한국야동/야동/5c2d0-AI예쁜게-최고야

### FILTERS

List-KR

### Browser

Mozilla Firefox

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Comment

![image](https://user-images.githubusercontent.com/96731476/224209571-d102d44f-38f7-40e2-8bcb-865c4bd3ccd8.png)

**Comment by ghost** [comment]
@piquark6046 
![image](https://user-images.githubusercontent.com/96731476/226290925-d7dcb6a5-dce7-4ab0-871a-1d49109ab21c.png)
this is still there

**Comment by ghost** [comment]
hey @piquark6046 the list [here](https://cdn.jsdelivr.net/gh/List-KR/List-KR@master/filters-share/specific_ELEMHIDE.txt) did not get updated so I am still seeing the ad

**Comment by piquark6046** [comment]
Purged. Please update your filters.
