### ISSUE TITLE
egloos.com

### ISSUE THREAD

**Issue by piquark6046** [List-KR/List-KR#629]
http://ebc.egloos.com/8780

**Comment by green1052** [comment]
2023년 6월 16일 기준으로 서비스 종료했읍니다.

https://egloosbackup.egloos.com/

**Comment by piquark6046** [comment]
오. 관련 처리를 했는데 안 닫았네요.
https://github.com/AdguardTeam/AdguardFilters/commit/aa6b272c7400bcb8b5f9e5cc88edcb804340b475
