### ISSUE TITLE
AD: 애드쉴드 광고 차단 안 됨

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#632]
### URL

https://ygosu.com/

### FILTERS

List-KR

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

마이크로 쉴드 스크립트 버전은 3.0.1 입니다.

![1](https://user-images.githubusercontent.com/99063049/225266649-76e9b861-a5bc-4443-9c26-03a756ba902d.png)

![2](https://user-images.githubusercontent.com/99063049/225266662-5d2bdf8b-c517-49df-9212-48a0bc816cba.png)

**Comment by piquark6046** [comment]
~~microShield 버전을 알 수 있을까요? 3.0.1이여야 합니다.~~

최신 버전에서 재구현이 확인되었습니다.
다음 Issue로 병합 합니다: https://github.com/List-KR/microShield/issues/17

**Comment by piquark6046** [comment]
@NoName926 microShield 3.1.0 버전에서 해결되었습니다.
업데이트해주세요.
