### ISSUE TITLE
Quasarzone coupang ad

### ISSUE THREAD

**Issue by piquark6046** [List-KR/List-KR#638]
### Discussed in https://github.com/orgs/List-KR/discussions/32

<div type='discussions-op-text'>

<sup>Originally posted by **craftingmod** March 20, 2023</sup>
![2023-03-21_01-15-39_msedge](https://user-images.githubusercontent.com/9389278/226402612-f2cd1850-e647-4912-98ba-de27b574916f.png)

`quasarzone.com##.price-compare-srch` should be enough to hide.</div>

**Comment by piquark6046** [comment]
@craftingmod It seems that the advertisement attached in the screenshot appears on the following URL:
https://quasarzone.com/bbs/qb_saleinfo

However, I cannot see that. Can you check that the advertisement appears even if you log out from the website?

**Comment by craftingmod** [comment]
For example: https://quasarzone.com/bbs/qb_saleinfo?_method=post&type=&page=1&category=&popularity=&kind=subject&keyword=A750&sort=num%2C+reply&direction=DESC

It is only appeared when searching something of that category.

**Comment by piquark6046** [comment]
Resolved.
