### ISSUE TITLE
AD leftover: m.ruliweb.com

### ISSUE THREAD

**Issue by craftingmod** [List-KR/List-KR#639]
### URL

https://m.ruliweb.com/
https://m.ruliweb.com/community/board/300143

### FILTERS

AdGuard Base Filter
AdGuard Prevent Tracking Filter
AdGuard Chinese/Japan Filter
List-KR (last updated: 2023/03/21 - 06:01:00)

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

Go to top button with "fixed_ad" dom ID.

I thought that button was for going to top but.. 

(Without filter)
![2023-03-21_11-22-24_msedge](https://user-images.githubusercontent.com/9389278/226504388-727cfe06-b8be-42b9-87d7-6ae5787bb090.png)

(With filter - too large top button)

![2023-03-21_11-24-09_msedge](https://user-images.githubusercontent.com/9389278/226504591-e8cde59b-0082-4763-ba31-26182907aac6.png)

It looks like just ad wrapper.

`m.ruliweb.com###fixed_ad` should be enough.

**Comment by piquark6046** [comment]
In fact, The element was hidden by List-KR filter.
However, Because of the URL attached in the following commit's message, I changed it.
https://github.com/List-KR/List-KR/commit/679391693998171271c76c0b2460b6af074af46e

**Comment by craftingmod** [comment]
![2023-03-21_12-20-06_msedge](https://user-images.githubusercontent.com/9389278/226510282-64d451ef-78b9-4178-b24f-87c32d46d1d7.png)

Would you like to check again this element that should be hidden..?

`fixed_ad_wrapper` should be completly hidden for hiding I think.

If go to top button with `100% width` + `50px height` was intended design, I will close issue.

**Comment by piquark6046** [comment]
In a real mobile device and the current status, I think that the element fits screen size of the mobile device.

Did you mean the following commit?
https://github.com/List-KR/List-KR/commit/694d7ddda109fde58f26f8b319b791f7f0d2a5e5

**Comment by craftingmod** [comment]
Yeah that element fits screen size.

I think that button is intented feature so I'll close issue.
