### ISSUE TITLE
[AD] ||namu.news/api/articles/cached^ 문제

### ISSUE THREAD

**Issue by green1052** [List-KR/List-KR#64]
## 광고 제보
* **문제가 되는 URL**: 
* **URL에서 문제가 되는 요소**: (광고 노출/잘못된 차단 등..)
* **확인 가능한 스크린샷 (옵션)**: 

## 시스템 환경
* **사용 중인 기기**: 
* **사용 중인 브라우저**: 
* **구독 중인 필터**:

![Screenshot_20200923-175859_Firefox](https://user-images.githubusercontent.com/34261355/93990793-87af8380-fdc6-11ea-9803-5a6745b01d6e.jpg)

||namu.news/api/articles/cached^
해당 규칙으로 인해 나무위키 뉴스가 안보입니다.

**Comment by ghost** [comment]
Duplicate of #54
