### ISSUE TITLE
AD: m.ruliweb.com

### ISSUE THREAD

**Issue by craftingmod** [List-KR/List-KR#640]
### URL

https://m.ruliweb.com/community/board/300143/read/60817760

### FILTERS

List-KR Version 2023.0320.6

### Browser

Microsoft Edge

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment

![2023-03-21_17-50-01_chrome](https://user-images.githubusercontent.com/9389278/226556902-05c52042-a8ff-4b95-81fa-784339087905.png)

Pure 100% advertisement of their v-tuber content.

 This could be removed with `m.ruliweb.com##.board_main > .row > .row` rule.

**Comment by craftingmod** [comment]
Rule fix: `m.ruliweb.com##.board_main > .row` to `m.ruliweb.com##.board_main > .row > .row`

source_url is erased :(

**Comment by craftingmod** [comment]
# Update

 ![2023-03-21_18-49-22_chrome](https://user-images.githubusercontent.com/9389278/226570428-c514c139-6ada-442e-9ba8-451f828519cd.png)

## Filter rule
`m.ruliweb.com##.board_main > .row > .row`
`m.ruliweb.com##.board_main > .row > .border_box`

**Comment by piquark6046** [comment]
Did you login?

**Comment by craftingmod** [comment]
> Did you login?

Yes! It looks like they are working on to add that advertisement~

Could you see that .border_box/.row DOM in mobile?

**Comment by piquark6046** [comment]
Nope. It seems that the element does not appear when a visitor do not log in.

**Comment by craftingmod** [comment]
# Link
https://m.ruliweb.com/community/board/300143/read/60818771?

# Without any filter
Ignore red X marking part
![2023-03-21_19-12-21_msedge](https://user-images.githubusercontent.com/9389278/226575727-e24dfae9-f9f3-4afc-8328-552ef983757d.png)

![2023-03-21_19-13-03_msedge](https://user-images.githubusercontent.com/9389278/226575896-31b8e1f2-b9b2-4eb8-a3b3-cb40d74de6df.png)

# Conclusion
It is also appeared in no-login state.
Looks like randomly rendered with AD/VTuber AD?

**Comment by piquark6046** [comment]
Resolved.

**Comment by craftingmod** [comment]
https://m.ruliweb.com/community/board/300143/read/60818094

![2023-03-21_19-24-08_msedge](https://user-images.githubusercontent.com/9389278/226578497-5b60122d-7ea5-45e7-91c5-d7a5f48ab7c1.png)

If you are affordable, would you please check rule to not hide `.source_url` DOM..?

Not important :)
