### ISSUE TITLE
IC: gmarket.co.kr

### ISSUE THREAD

**Issue by relaxedbrownie** [List-KR/List-KR#641]
### URL

https://www.gmarket.co.kr/

### FILTERS

AdGuard 베이스 필터
AdGuard 방해 요소 필터
List-KR

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard Browser Extension, AdGuard for iOS/iOS Pro

### Comment

G마켓의 자체 행사 배너인데(외부 광고 아님) 사라지고 하얗게 뜹니다. 다른 필터는 놔두고 List-KR만 끄면 정상적으로 볼 수 있네요.

**Comment by piquark6046** [comment]
@relaxedbrownie 
이 Issue는 아래 Issue하고 비슷한데 맞나요?
https://github.com/List-KR/List-KR/issues/563#issuecomment-1320088924

**Comment by relaxedbrownie** [comment]
네 맞아요. 완전 같은 이슈네요. 위에 옥션 글도 같은 맥락이에요.

**Comment by piquark6046** [comment]
Duplicate of #563
