### ISSUE TITLE
AD: https://m.tv.nate.com

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#643]
### URL

https://m.tv.nate.com/clip/4685640?ref=mnewsvrk

### FILTERS

only list-kr 

https://cdn.jsdelivr.net/gh/List-KR/List-KR@master/filter-AdGuard.txt

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

Please remove video ads

![669028FA-E6EE-4E96-AE94-76F8F8E15DE8](https://user-images.githubusercontent.com/15683789/227234329-d5140070-e303-4873-adab-531b379550bf.jpeg)

**Comment by piquark6046** [comment]
@swbaek81 Please use List-KR filter installed by default because pre-processor directive like `!#include` or `!#if` is not supported yet.
https://github.com/List-KR/List-KR/blob/master/README.md#%EC%82%AC%EC%9A%A9%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95

**Comment by swbaek81** [comment]
Yes, I'm using list-kr by default.
![E2AA1568-F817-4219-891E-2E245950770C](https://user-images.githubusercontent.com/15683789/227558092-dda39947-420b-448b-8188-0cce40521d73.png)
