### ISSUE TITLE
AD: After searching on google.com, an error occurs when clicking on the sponsor item

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#644]
### URL

google.com 

If you search google.com and click the sponsor item, an error occurs.

"safari cannot open that page. Error: A content blocker blocked the URL."

Should list-kr block sponsored items?

### FILTERS

only list-kr

https://cdn.jsdelivr.net/gh/List-KR/List-KR@master/filter-AdGuard.txt

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

![BA37AB8D-3971-47C4-AF2F-2CB3FB98AC44](https://user-images.githubusercontent.com/15683789/227241030-bd7723a0-ce7e-42bf-a120-4f40cac53224.jpeg)
![04F2545B-07EA-4B0B-8514-D251DFE617D8](https://user-images.githubusercontent.com/15683789/227241071-ab5b484b-c457-4496-9a78-ec14316b0c81.png)

**Comment by piquark6046** [comment]
Google is an international website, so that blocking in EasyList or AdGuard Base filter is suited for these filter's purposes.

By the way, did you disable AdGuard Base filter and AdGuard mobile ads filter to get better web browsing performance?

**Comment by swbaek81** [comment]
Yes, I turned off AdGuard Base filter and AdGuard mobile ads filter for faster speed.

**Comment by piquark6046** [comment]
If you disable AdGuard Base filter, you will see advertisement on YouTube.
At least, Please enable these.

**Comment by swbaek81** [comment]
thank you for confirming
If you turn on the Adguard base filter, it will definitely slow down.
i am sad

**Comment by ghost** [comment]
`googleadservices.com`
that's why it's blocked

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/644#issuecomment-1486336305

I know that. But, it is related to Google advertisement service.

**Comment by seia-soto** [comment]
End user should disable the filter manually, the domain is literally marked as a) ad and b) privacy sensitive. There's nothing we can do for you.
