### ISSUE TITLE
AD: iphone nplayer ad

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#645]
### URL

In the iPhone nplayer app, there is a 5-second ad at the start of video. I want you to remove the advertisement.

### FILTERS

adguard dns filter

listkr dns

![6C8EE59C-C19E-48A1-A8AE-E3DEB707D7FD](https://user-images.githubusercontent.com/15683789/227697790-36f90340-b732-473c-937e-415b204b3507.png)
![37001C56-323A-48B0-97B1-3797EB8DD926](https://user-images.githubusercontent.com/15683789/227697793-90f593e8-8c68-4c1b-bdc9-8170e55acb9a.jpeg)
![91CBE9CD-8E41-461F-81E3-B7C1D24D1489](https://user-images.githubusercontent.com/15683789/227697794-8f2c470c-37c9-4edc-9fdb-6d0289530b1d.jpeg)

### Browser

(Other)

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro, AdGuard DNS

**Comment by piquark6046** [comment]
Did you mean [nPlayer Lite](https://apps.apple.com/us/app/nplayer-lite/id1078835991)?

**Comment by swbaek81** [comment]
yes. nplayer lite

**Comment by piquark6046** [comment]
When does the advertisement appear?

**Comment by swbaek81** [comment]
Every time I start a video in the app, an advertisement comes out.

**Comment by piquark6046** [comment]
The popup cannot be resolved by any DNS-level blocking.
