### ISSUE TITLE
IC: spotv now 어플 재생불가

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#649]
### URL

아이폰 spotv now 어플에서 영상재생이 안됩니다

https://www.spotvnow.co.kr/player?type=vod&id=140444

### FILTERS

adguard dns
listkr dns
![A2694B48-AA24-40F0-B71B-1F9A712BC52E](https://user-images.githubusercontent.com/15683789/227716432-3a6b8c70-54c0-41ce-bf01-45feb0774a8b.png)
![Uploading 9A856794-19ED-49D4-ACF3-AFA02F8A229C.png…]()

### Browser

(Other)

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

**Comment by swbaek81** [comment]
![Uploading 1BF41D35-6860-4D43-A00E-21AA1490439C.png…]()

**Comment by swbaek81** [comment]
![612FB8F4-B8C8-4F48-AD52-CA247533C4D5](https://user-images.githubusercontent.com/15683789/227716512-3fb76583-6a73-4c22-a4b2-783c75e249d0.png)

**Comment by piquark6046** [comment]
한번 Safari에서 보실래요?

**Comment by swbaek81** [comment]
사파리 주소창에 붙여넣기 해도 볼수 없습니다. 스포티비 나우 어플로 링크되게 되있네요

![2D4D53F3-B30B-4023-9DA7-540FF99E08E9](https://user-images.githubusercontent.com/15683789/227720021-82cdf1ee-e07a-4236-9b95-656f454600da.png)

**Comment by piquark6046** [comment]
웹 버전의 Spotv now가 `pagead2.googlesyndication.com/pagead/js/adsbygoogle.js`으로 보내서 AdGuard나 uBlock Origin 등을 감지하려고 하는데, 만약 같다면 Apple 정책으로 인해 앱별로 DNS 예외를 할 수 없어 다른 앱에 Google 광고가 나오게끔 하여 해결할 수 밖에 없습니다.

**Comment by swbaek81** [comment]
방법이 없을까요? 볼때마다 애드가드를 끄는건 불편해서요
![9B1CA2DE-AB69-4167-8ABE-9A426F1BA8E8](https://user-images.githubusercontent.com/15683789/227720670-ba3ab515-f8f0-4965-abe9-f3011eb50f0f.png)

**Comment by piquark6046** [comment]
만약 웹 버전과 같다는 가정 및 다른 앱에서 Google 광고가 나옴에 상관 없다는 조건하에 AdGuard 보호 -> DNS 보호 -> DNS 필터링 -> 허용 목록에 `@@||pagead2.googlesyndication.com^`를 추가해보세요.

**Comment by swbaek81** [comment]
네 일단 허용목록으로 사용해 보겠습니다

**Comment by swbaek81** [comment]
스포티비 어플에서 여러영상을 재생시켜봤는데 재생이 안되네요 . 애드가드 오프 하고 볼수밖에 없습니다.

**Comment by piquark6046** [comment]
방금 가입하고 시도해봤는데요. 이전에 알려드린 도메인을 제거하시고 `imasdk.googleapis.com`를 허용 목록에 추가해보세요. 대신에 SPOTV NOW에 광고가 나오며 다른 앱들에서도 광고가 나올 수 있습니다.

**Comment by swbaek81** [comment]
imasdk.googleapis.com를 허용 목록에 추가해서 보고 있었는데, 오늘 부턴 또 아무 영상도 볼수가 없습니다

**Comment by swbaek81** [comment]
제가 실수 했네요 예전처럼 광고 보면서는 볼수 있습니다. 허용목록을 꺼놨어서 안됐던거에요 제 실수 입니다

**Comment by piquark6046** [comment]
확인해주셔서 감사합니다.

**Comment by swbaek81** [comment]
아이폰 spotv now 어플에서 영상재생이 안됩니다

광고없이 잘 보고 있었는데 며칠전부터 재생불가 입니다

listkr dns

https://www.spotvnow.co.kr/player?type=vod&id=162640

![image](https://github.com/List-KR/List-KR/assets/15683789/9e3b622d-0122-4141-86cc-b3a4159d450e)

**Comment by piquark6046** [comment]
AdGuard VPN 같은 실제 VPN 서비스가 실행 중인가요? 그렇다면, 비활성화해보시고 다시 시도해주세요.

**Comment by swbaek81** [comment]
기본 adguard dns 조차 off 상태이고, 오직 listkr dns만 on 상태인데 문제 없었는데 며칠전부터 안되요.

**Comment by swbaek81** [comment]
adguard vpn은 설치되어잇지만 off 상태 입니다

**Comment by piquark6046** [comment]
DNS 보호 설정이 다음과 같나요?
- DNS 구현: AdGuard
- 터널 모드 (로우 레벨 설정): split-tunnel
- 블록 모드 (로우 레벨 설정): 기본값

또한 `imasdk.googleapis.com` 도메인이 허용 목록에 추가되었는지 확인해주세요.

**Comment by swbaek81** [comment]
네 아래사항 4가지 사항 모두 OK 입니다.

아래꺼 한번 해보시면 현상 나올거에요

https://www.spotvnow.co.kr/player?type=vod&id=162640

==========================================

DNS 보호 설정이 다음과 같나요?

DNS 구현: AdGuard
터널 모드 (로우 레벨 설정): split-tunnel
블록 모드 (로우 레벨 설정): 기본값
또한 imasdk.googleapis.com 도메인이 허용 목록에 추가되었는지 확인해주세요.

**Comment by piquark6046** [comment]
https://send.vis.ee/download/de7943f31e9a535e/#0T0m7M_0bGHeG06AsTnXLg
한번 확인해주시겠어요?

**Comment by swbaek81** [comment]
네 영상대로 설정은 되어 있었어요, 

몇시간 전까지는 안됐는데

지금은 잘 되네요 닫아주세요 감사합니다.

그리고 설정영상 보다가 궁금한게 있는데요 

DNS를
오직 Listkr DNS 만 On 한 채로 사용할꺼면 

"DNS서버 - 애드가드 필터링 미사용" 으로 설정해도 되는거죠?

그동안은 ClaudFlare DNS 로 사용하고 있었어요

**Comment by piquark6046** [comment]
상관은 없는데, AdGuard DNS 서버가 Cloudflare보다 DNS 응답 속도가 더 느릴꺼예요.
