### ISSUE TITLE
IC: https://m.tv.nate.com/clip/4687866?ref=mnate can not play video

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#650]
### URL

https://m.tv.nate.com/clip/4687866?ref=mnate

### FILTERS

adguard base 
adguard mobile
list kr

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

Only the advertisement video is played, and the main video doesn't come out. 

safari browser

**Comment by swbaek81** [comment]
![9D20D3BD-0B6A-44EB-93EF-4A8297B0BF5E](https://user-images.githubusercontent.com/15683789/227732461-fa0a4e80-bb1f-480b-86b4-861c5780588c.png)

Only the advertisement video is played, and the main video doesn't come out.

**Comment by piquark6046** [comment]
The PR is not merged yet. Did you apply the javascript rule manually?

**Comment by swbaek81** [comment]
규칙을 수동적용하지 않았습니다. 수정부분이 머지 될때 까지 기다려볼게요. 현재는 광고만 나오고 본 영상을 볼수가 없네요. 에드가드 오프 해야 볼수 있습니다

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/FiltersRegistry/pull/766
병합되었습니다.

**Comment by swbaek81** [comment]
안녕하세요 혹시 이건 언제 반영되는거에요? 필터는 업데이트 했는데 아직도 해결은 안됐어요

![EF8BF4BC-19D9-40F0-8DA5-9782724BDB0D](https://user-images.githubusercontent.com/15683789/227933047-28bccbfe-ff48-4243-bab3-5e980f711c87.jpeg)

**Comment by piquark6046** [comment]
보통은 최대 4시간 정도 보류 시간이 있어요. 그 이후에 업데이트된 필터를 다운로드하시면 됩니다.

**Comment by piquark6046** [comment]
GitHub 서버에 문제가 생겨서 시간이 더 소요될 수 있습니다.
https://www.githubstatus.com/incidents/52z0j6phhnjs

**Comment by piquark6046** [comment]
GitHub 서버의 문제가 해결되었습니다.

**Comment by swbaek81** [comment]
네이트 티비에 모든 영상 이 재생되질 않습니다.

재생할수 없음
https://m.tv.nate.com/clip/4689678?ref=mnate

광고만 나오고 본 영상을 볼수 없음
https://m.tv.nate.com/clip/4689181?ref=mnate

adguard base
adguard mobile 
list kr(2.0.13.90)
