### ISSUE TITLE
AD: m.daum.net

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#651]
### URL

https://m.daum.net/?nil_top=mobile

### FILTERS

adguard base
adguard mobile
listkr

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

광고 제거 부탁드려요

![B7B1E507-1E0A-4413-A17E-00F58257D422](https://user-images.githubusercontent.com/15683789/227755838-80110779-32bc-4cd4-a4c6-d15136d4d088.jpeg)

**Comment by piquark6046** [comment]
그게 카카오 광고라면, 이미지의 우측 상단에 `AD`라는 태그가 있어야 합니다.
그런데, 그 element에는 없습니다.

https://business.kakao.com/info/displayad/
https://kakaobusiness.gitbook.io/main/ad/moment/start/displayad
