### ISSUE TITLE
AD: naver app

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#652]
### URL

naver.com

### FILTERS

adguard dns 
list kr dns

### Browser

(Other)

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

아이폰 네이버 어플에서요 첫화면에 광고가 나왔다 안나왔다 합니다. 뉴스 스포츠 등 상단Tab을 왔다갔다 할때나, 기사를 보고 첫화면 으로 복귀할때 현상이 나타 납니다

![5EFAE1C6-5354-4F33-9CEF-3C0BD48C5C84](https://user-images.githubusercontent.com/15683789/227770783-18175eee-0ba2-41c2-a1ba-680165b8f85e.png)
![8FE90401-81E4-40EF-93F5-91332DDDE7CC](https://user-images.githubusercontent.com/15683789/227770807-900a52cc-d897-46f7-854a-91c924a51f6a.png)
![BA32F0A5-4682-4971-822F-9A67997CB91D](https://user-images.githubusercontent.com/15683789/227770819-ce9f94e2-dbe7-45b2-a93d-39bcb425be3a.jpeg)

**Comment by piquark6046** [comment]
확인은 되었으나 광고와 다른 콘텐츠에서 사용되는 도메인에서 수신되는 것으로 보입니다.
Apple Safari로 보시길 권해드립니다.
