### ISSUE TITLE
AD: https://m.ruliweb.com

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#653]
### URL

https://m.ruliweb.com/community/board/300143/read/60890223

### FILTERS

adguard base
adguard mobile
listkr

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

광고 박스 없애 주세요 

광고제거전
![CECDB126-2E7A-4FDF-8F39-CB5EA6B6C0CB](https://user-images.githubusercontent.com/15683789/227984223-1bccfe78-57e2-4a20-8382-56a2b6bd3092.png)

광고제거후 
![EFC0392A-7175-40B9-B706-BD3B24E7331C](https://user-images.githubusercontent.com/15683789/227984193-b6125090-1674-436a-8f21-0fdf4eb4076d.jpeg)

**Comment by piquark6046** [comment]
비슷한 규칙은 이미 있습니다.

다음과 같이 설정되어 있는지 확인해주세요.
1. AdGuard 보호 -> 고급 보호 활성화
2. iOS 설정 -> Safari -> 확장 프로그램 -> 이 확장 프로그램 허용에서 AdGuard 클릭 -> 켜고 모든 웹 사이트에서 허용으로 설정

**Comment by swbaek81** [comment]
둘다 on되어있는데도 해결되지 않아요

**Comment by piquark6046** [comment]
스크린샷을 주실 수 있으시나요?
다음 스크린샷처럼 보여져야 합니다.

<details><summary>스크린샷</summary>


![0014FF2D-2F88-42E0-93FC-263520B2C9CB](https://user-images.githubusercontent.com/98787049/227993651-65095714-64ef-4c6b-be2a-679787c09c4e.png)


</details>

**Comment by swbaek81** [comment]
네 제 아이폰 에서도 똑같이 보여요 
X 표시 부분을 없애 달라고 요청한거에요

**Comment by piquark6046** [comment]
저건 [이 루리웹 글](https://m.ruliweb.com/community/board/300143/read/59866801)처럼 불만사항이 있어서 https://github.com/List-KR/List-KR/commit/679391693998171271c76c0b2460b6af074af46e 에 패치한 결과이예요.

**Comment by swbaek81** [comment]
![49E3F23F-66F9-4112-95FF-E378B0E30C71](https://user-images.githubusercontent.com/15683789/227996445-cd57feea-6000-47c5-9b60-bb29988fd1d2.png)

x를 포함한 박스를 없애면 되는가 아닌가요?

아
위로 가기 버튼 때문에 일부러 박스를 남긴거 라는 얘기에요?
그렇다면 이해가 되네요

**Comment by piquark6046** [comment]
네. 그럼 닫아도 되나요?

**Comment by swbaek81** [comment]
네 닫으셔도 됩니다
