### ISSUE TITLE
AD: http://m.heraldpop.com

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#658]
### URL

http://m.heraldpop.com/view.php?ud=202303271116190972360_1

### FILTERS

adguard base
adguard mobilie
listkr
사파리 확장프로그램 adguard on

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

광고 깨끗이 없애 주세요

![IMG_2363](https://user-images.githubusercontent.com/15683789/229073046-bf121d70-3267-4fc5-b149-fe74049eb954.jpeg)

**Comment by swbaek81** [comment]
캡처 부분도 제거해주세요

![IMG_2370](https://user-images.githubusercontent.com/15683789/229159519-a0ac1335-71cb-4169-933a-f3afdb74a797.jpeg)

**Comment by piquark6046** [comment]
해결되었습니다.
