### ISSUE TITLE
AD: m.starnewskorea.com

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#659]
### URL

https://m.starnewskorea.com/view.html?no=2023033119311552333&MTT

### FILTERS

adguard base
adguard mobile
listkr

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

전체적으로 광고 정리 해주세요

![IMG_2367](https://user-images.githubusercontent.com/15683789/229126207-e7c70336-d0d9-4eee-a79c-4549e22e9830.jpeg)

**Comment by piquark6046** [comment]
제 iOS에서는 하단에 있는 까만 박스외에는 강조하신 요소가 없습니다.
필터 업데이트를 해주시겠어요?

**Comment by piquark6046** [comment]
그 까만 박스가 패치되었습니다.

**Comment by swbaek81** [comment]
필터최신 업데이트 했어요
adguard 베이스
adguard 모바일
listkr
사파리 확장프로그램 On 

나와야할 사진이 사라지고 정상은 아닙니다 

![IMG_2369](https://user-images.githubusercontent.com/15683789/229130409-8f82494a-b4ba-42f9-b356-442fb6851c4b.png)
![IMG_2368](https://user-images.githubusercontent.com/15683789/229130423-69c60e84-abb1-4f28-978d-7c1cb628c3a9.png)

**Comment by piquark6046** [comment]
오차단도 수정했습니다.

**Comment by swbaek81** [comment]
https://m.starnewskorea.com/view.html?no=2023033119311552333&MTT#_DYAD

이미지 오차단 수정해주세요

![IMG_2371](https://user-images.githubusercontent.com/15683789/229232970-b8a94e0d-ad5d-4643-a5a1-b635d9e0f5ed.jpeg)
