### ISSUE TITLE
IC: m.nate.com

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#660]
### URL

https://m.nate.com/

### FILTERS

adguard base
adguard mobile
list kr

safari 확장프로그램 on

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for Safari

### Comment

사파리 확장프로그램 On하면 좌우 스와이프 가 안됩니다.

다른 탭으로 이동 불가능 입니다(이슈 랭킹 tv 탭)

다른탭 클릭도 불가능해요

**Comment by swbaek81** [comment]
![IMG_2373](https://user-images.githubusercontent.com/15683789/229238662-ddcba10f-c463-474e-9925-f27699c5e8a2.jpeg)

**Comment by piquark6046** [comment]
https://drive.google.com/drive/folders/1YenZ0K3kq_lpIibyLUevLEqtIC0GR2E4?usp=sharing

재구현이 안됩니다.

**Comment by swbaek81** [comment]
뉴스 탭에서 아무기사나 눌러보고 뒤로가기로 첫화면으로 복귀하니까 바로 재구현 되요

**Comment by piquark6046** [comment]
해결했습니다.
