### ISSUE TITLE
AD: mosen.mt.co.kr

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#662]
### URL

http://mosen.mt.co.kr/article/G1112068584

### FILTERS

adguard base
adguard mobile 
listkr

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

광고 빈칸 제거해주세요

![IMG_2395](https://user-images.githubusercontent.com/15683789/229316217-8f8ef541-0891-4407-9b28-334a3868f104.jpeg)

![IMG_2396](https://user-images.githubusercontent.com/15683789/229316242-27f398f5-0762-4b9e-a22b-d1d881d3e79a.jpeg)

**Comment by swbaek81** [comment]
아래 캡처 부분만 문제 입니다

![IMG_2411](https://user-images.githubusercontent.com/15683789/229319032-0aad276b-235e-40d9-9530-b05e2b53ee9f.jpeg)

**Comment by swbaek81** [comment]
닫아도 될거 같습니다. 해당사이트에서 해당기사 외에 다른 기사 클릭시에는 공란이 없이 ok입니다

**Comment by piquark6046** [comment]
알겠습니다. 닫겠습니다.
