### ISSUE TITLE
AD: xportsnews.com

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#663]
### URL

https://www.xportsnews.com/article/1706415

### FILTERS

adguard base
adguard mobile 
listkr

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

광고랑 빈칸 제거해주세요

![IMG_2397](https://user-images.githubusercontent.com/15683789/229316444-ffa221e3-3056-453d-b43d-62b0ab8a3395.png)
![IMG_2398](https://user-images.githubusercontent.com/15683789/229316453-2523c51f-b9a5-46cb-8ab4-1a005c8534c7.jpeg)
![IMG_2399](https://user-images.githubusercontent.com/15683789/229316454-c692807f-f8a2-4970-a8d9-b73db02aa9da.jpeg)
![IMG_2400](https://user-images.githubusercontent.com/15683789/229316456-0df0321f-600a-4188-9af2-0ba39a84c0e1.jpeg)
![IMG_2401](https://user-images.githubusercontent.com/15683789/229316459-e2766cc3-c901-4750-9cbb-ffd5e9a193fa.jpeg)

**Comment by piquark6046** [comment]
Google 광고는 차단이 되어야 합니다.
필터 업데이트 버튼을 누르시고 업데이트 아이콘이 회전을 멈추면 다시 새로고침해보시곘어요?

**Comment by swbaek81** [comment]
네 맞습니다 닫아주세요
