### ISSUE TITLE
IC: search.shopping.naver.com

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#670]
### URL

https://search.shopping.naver.com/search/all?query=%EC%8B%A0%EB%B0%9C

### FILTERS

list-kr

### Browser

Google Chrome

### Operating System

Microsoft Windows 11

### Ad-Blocker

uBlock Origin

### Comment

유블록 오리진과 list-kr 필터를 사용시
네이버 쇼핑에서 검색결과가
초기에 두개정도 밖에 나오지 않고, 스크롤을 해야 그제서야 더 많은 항목이 로딩됩니다.
애드가드 데스크탑 버전과 list kr 사용시에는 이런현상이 없이
곧바로 많은 결과가 나오지만

ublock origin에서는 처음엔 두가지정도 결과밖에 나오지 않습니다.

![화면 캡처 2023-04-04 170231](https://user-images.githubusercontent.com/129815711/229728697-dd1e0fad-0cc5-439e-8e5e-f36414b05c21.png)
![화면 캡처 2023-04-04 170248](https://user-images.githubusercontent.com/129815711/229728714-e94ce152-103c-445d-bd8e-ca4bbaa5fee5.png)

**Comment by piquark6046** [comment]
@Sublease3919 uBlock Origin에서 List-KR 필터 리스트를 제외한 무슨 필터 리스트들이 활성화되어 있나요?
또한, 필터 리스트를 강제로 업데이트하셨나요?

**Comment by ghost** [comment]
> @Sublease3919 uBlock Origin에서 List-KR 필터 리스트를 제외한 무슨 필터 리스트들이 활성화되어 있나요? 또한, 필터 리스트를 강제로 업데이트하셨나요?

ublock origin 기본값으로도 증상이 발생하고
모든필터를 해제하고 list-kr만 활성화해도 증상이 발생하였습니다.
필터는 강제 업데이트 하였으나 동일합니다.

**Comment by ghost** [comment]
adguard 브라우저확장에서도 동일 현상이 나타납니다.
하지만 데스크탑 버전에선 나타나지 않습니다

**Comment by piquark6046** [comment]
제 환경에서는 AdGuard for Windows도 같은 증상을 보이고 있습니다.

이러한 현상은 제 의견으로는 네이버가 1페이지에 들어가는 모든 검색 결과가 포함된 맨 처음의 HTML 수신과 관계없이 네이버 파워링크 관련된 XMLHttpRequest와 JavaScript를 차단하면 2개만 보이게끔 한 것으로 보입니다.

이로 인해 저번에 [관련 issue](https://github.com/AdguardTeam/AdguardFilters/issues/147121)과 [변경 사항](https://github.com/List-KR/List-KR/commit/4c625d550f05c0ad66d47604746d838e7bbcb6d1)을 보시면 네이버 파워링크 광고가 들어오게끔만 수정한 것을 보실 수 있습니다.

혹시 추가적인 수정을 원하시나요?

**Comment by piquark6046** [comment]
CC: @seia-soto

**Comment by ghost** [comment]
네이버가 의도한 사항이라면 추가적인 조치는 원하지 않습니다.
감사합니다.
