### ISSUE TITLE
IC: pay.naver.com/

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#671]
### URL

https://order.pay.naver.com/

### FILTERS

List-KR

### Browser

Google Chrome

### Operating System

Microsoft Windows 11

### Ad-Blocker

uBlock Origin

### Comment

ublock origin과 list-kr 필터를 사용할시
네이버 페이 구매내역에서
주문상세를 누른후 상품판매처로 가는 링크를 누를시 바로 이동하지 않고,
여러번 눌러야 이동합니다.

데스크탑 adguard와 list-kr필터를 사용시에는 즉시 이동합니다.
![화면 캡처 2023-04-04 170949](https://user-images.githubusercontent.com/129815711/229730116-06686d19-11b3-4966-9444-ac25a582d0c3.png)

**Comment by piquark6046** [comment]
제가 네이버 쇼핑을 이용하지 않는데 [연락처](https://github.com/List-KR/List-KR/wiki/contacts)를 참고하여 디버깅을 위한 데이터를 전송해주실 수 있나요?

**Comment by ghost** [comment]
답변이 늦어서 죄송합니다.
현재는 또 한번클릭으로 이동되어 이슈를 닫겠습니다.
