### ISSUE TITLE
 meeco.kr

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#672]
### URL

https://meeco.kr/news/37020056

### FILTERS

adguard dns 또는 
listkr dns

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

adguard dns 또는 
listkr dns 이 켜져있을때만 광고가 나오는데요 제거 할수 있을까요?

![IMG_2456](https://user-images.githubusercontent.com/15683789/230597394-ca6af9c3-3945-4ec6-ace7-02acbad3fc9f.png)

**Comment by piquark6046** [comment]
List-KR 필터를 활성화하시면 해당 안티-애드블록 스크립트가 차단됩니다.

**Comment by swbaek81** [comment]
adguard base
adguard mobile
listkr

adguard dns
listkr dns 

이렇게 켜져있는데요 
광고 제거가 안되네요

**Comment by piquark6046** [comment]
[이 동영상](https://drive.google.com/drive/folders/1SwN3CACQeSZdGOWnIWloXm26D5CDb80n?usp=sharing)을 참고하셔서 아래 항목이 모두 설정이 되었지 확인해주세요:

1. iOS 설정 -> Safari -> 확장 프로그램 장면
2. AdGuard 보호 -> 고급 보호 활성화

**Comment by swbaek81** [comment]
동영상 참고해서 모두 On 해도, 여전히 해결되지 않네요

필터 새로고침도 해보고, 사파리설정, 고급보호 다 둘러봐도 해결은 안되네요

**Comment by piquark6046** [comment]
@swbaek81 Safari의 주소바에 있는 `가가` 버튼에서 AdGuard를 찾아주세요.
그 뒤에 누르시고 meeco.kr에 대해 활성화되어 있는지 확인해주세요.

**Comment by swbaek81** [comment]
활성화 되어 있어요

![IMG_2457](https://user-images.githubusercontent.com/15683789/230752776-116251df-5d29-4934-aad4-68319ce968de.png)

**Comment by piquark6046** [comment]
가끔씩 그러나요? 아니면 자주 그러나요?

**Comment by swbaek81** [comment]
항상 안되요. 제거 된적이 없습니다

**Comment by piquark6046** [comment]
제 iPhone에서도 가끔 그러지만 그런 환경에서는 그러지 않는 것을 보아, 아래 Issue와 관련되어 있어보입니다:
 - https://github.com/AdguardTeam/AdguardForiOS/issues/1930

**Comment by piquark6046** [comment]
제 iPhone에서도 가끔 그러지만 다른 환경에서는 그러지 않는 것을 보아, 아래 Issue와 관련되어 있어보입니다:
 - https://github.com/AdguardTeam/AdguardForiOS/issues/1930

혹시 iPhone외 다른 디바이스를 소지하시고 계시나요?

**Comment by swbaek81** [comment]
아 아이폰만 갖고 있어요 . 지금 새로운 현상을 봤는데요, 사파리를 메모리에서 제거후에(=홈화면 에서 위로 스와이프), 사파리를 최초 실행해서 사이트에 들어가면 광고가 정상제거되는데, 두번째 방문부터는 계속 제거가 안되네요

**Comment by piquark6046** [comment]
AdGuard 보호 -> DNS 보호 -> DNS 필터링 -> 허용 목록에 아래 도메인을 추가해보시고 다시 시도해보시겠어요?
```
pagead2.googlesyndication.com
```

제 생각엔 scriptlet 규칙이 제 시간에 제대로 실행되지 못하고 `@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=meeco.kr`가 이 요청을 허용했지만 DNS 필터링에 광고 도메인으로 등록된 `pagead2.googlesyndication.com`[^1] 가 있기에 문제가 발생하는 것으로 보입니다.

[^1]: Google 광고

**Comment by swbaek81** [comment]
dns 허용도 했습니다. 성공했다 실패했다 하는데 50프로정도는 성공하고 50프로는 실패 되네요

**Comment by piquark6046** [comment]
아, AdGuard Safari 보호에서 List-KR 필터를 활성화 안 하신 이유가 있을까요?

**Comment by swbaek81** [comment]
지금은 사파리 listkr On상태고요, 무거운게 싫어서 사파리에 모든 필터를 오프한채 youslist만 쓰거나 혹은 listkr만 쓰거나 했습니다. 사파리에서 모든필터 끈채로 listkr만 쓰면 구글검색 스폰서 차단이 안되고, 광고공란이 생기는 부분이 있어서  사용자 필터로 해당부분 처리해서 사용중이에요. 결론은 사파리 listkr은 좋은데 단독으로 사용하기에는 youslist대비해서 아쉽다 입니다. 저는 라이트 하게 쓰고 싶은 독특한 사용자 이긴 합니다

**Comment by swbaek81** [comment]
앗 제가 실수했네요 dns필터링 에외허용으로 해결되었습니다. 

허용목록 스위치가 off 되어 있었어요 . 
![IMG_2458](https://user-images.githubusercontent.com/15683789/230754450-f851825f-6942-49ba-8345-e68de9db6d3f.jpeg)

**Comment by piquark6046** [comment]
다른 문제가 있으시나요?
https://github.com/yous/YousList/issues/249#issue-1659746263 여기에서 언급하신 leftover는 제 iPhone에서는 안 보입니다.

**Comment by swbaek81** [comment]
문제 없어요 닫아도 되요. 사파리에서 기본필터 off하고 단독 한국필터로만 사용하려다 보니 (youslist 또는 listkr) 광고 공란이 생기고요 , 베이스필터를 켜고 사용하는 일반사용자들에게는 발생하지 않는 문제 입니다

제가 살짝의 딜레이도 싫어서 베이스필터조차 끄고 써요

**Comment by piquark6046** [comment]
나중에 [AGLint](https://github.com/AdguardTeam/AGLint)가 public 상태로 변경되고 정식으로 릴리즈되면, 라이트 유저를 위한 필터를 만들 생각입니다.

**Comment by swbaek81** [comment]
네 라이트 필터도 꼭 기다리고 있어요 너무 좋을거 같아요
