### ISSUE TITLE
AD: T전화, Between, 날씨날씨, 첫화면날씨

### ISSUE THREAD

**Issue by I0rem1psum** [List-KR/List-KR#679]
### URL

T전화 : https://apps.apple.com/kr/app/t전화/id1150947951
Between : https://apps.apple.com/kr/app/비트윈-between/id458035189

날씨날씨 : https://apps.apple.com/kr/app/날씨날씨-날씨-미세먼지/id1462255869
첫화면날씨 : https://apps.apple.com/kr/app/첫화면-날씨-위젯-미세먼지-날씨/id1526791980

### FILTERS

Adguard Base Filter
Adguard 
Adguard Annoyance Filter
Adguard Japanese Filter
List-KR

List-KR DNS Filter

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

the ad banners on T전화 and Between are not blocked by Adguard.

In addition, 날씨날씨, 첫화면 날씨 shows its blank ad spaces.

**Comment by piquark6046** [comment]
Why did you disable AdGuard DNS filter?

**Comment by I0rem1psum** [comment]
Because I saw your recommendation settings "Don't turn on AdGuard DNS Filters but List-KR DNS if you are on iOS."

And I've tried turn on AdGuard DNS Filter also, but the same happens.

**Comment by piquark6046** [comment]
날씨날씨 - I can see some leftovers that cannot hidden by any adblocker. But, I added some advertisement domains including Apple Ad domain. 
첫화면날씨 - Same as 날씨날씨.
T전화 - Resolved by https://github.com/List-KR/List-KR/commit/8a4cff7856dec8b7d4c5ddb491d58e0b35e0ce16 and https://github.com/AdguardTeam/AdguardFilters/commit/e69f785de7197c918163aadce475db7300f60390.
Betweem - It requires a partner's invite code.

**Comment by piquark6046** [comment]
Timeout.
