### ISSUE TITLE
IC: search.shopping.naver.com

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#681]
### URL

https://search.shopping.naver.com

### FILTERS

ublock origin 기본값 사용중 입니다

### Browser

Google Chrome

### Operating System

Microsoft Windows 11

### Ad-Blocker

uBlock Origin

### Comment

<details><summary>Screenshots</summary>

![웹 캡처_17-4-2023_162838_search shopping naver com](https://user-images.githubusercontent.com/129815711/232415331-75a89ec8-f302-4e15-9441-2956cf8e439f.jpeg)
![웹 캡처_17-4-2023_162741_search shopping naver com](https://user-images.githubusercontent.com/129815711/232415346-96a0a408-3d6c-43c6-b379-de16ba793c6b.jpeg)

</details> 

온라인 쇼핑몰에선 광고로 검색결과에 노출되는 상품이 상당히 많은편이라
광고상품이 아예 노출이 안되니 후기많은 구매후보에 들법한 유명(?) 상품들이
아예 보이지않아 선택의 폭이 너무 좁습니다.
예전처럼 광고인 상품도 노출되는게 좋을것 같습니다.

**Comment by piquark6046** [comment]
그건 목적에 관계없이 유료 광고지 않나요?
https://saedu.naver.com/adbiz/searchad/shoppingSa.naver#product

**Comment by ghost** [comment]
네, 이전에는 동일셋팅에서 광고상품도 보였던거 같아서요
그리고 지금은 광고아닌 상품도 안나오는것처럼 물건이 별로 안나오더라고요
같은 1페이진데도
광고차단 켜고 껏을때 검색된 상품 수량이 다르게 나오네요
분명 광고상품이 아닌데
광고차단을 키면 광고 안붙어 있는 상품까지 안나와서
쇼핑에 어려움이 있습니다

**Comment by piquark6046** [comment]
아래로 드래그하시면 로드되나요?

**Comment by ghost** [comment]
아니요, 첫번째 스크린샷이 광고차단 off,
두번 째 스크린샷이 광고차단on 상태에서 검색후 결과가 두개정도 뿐인걸 
아래로 스크롤해서 그나마 로딩시킨건데 그렇습니다 

분명 광고차단 off 때는 1페이지에서 보이던 상품이(광고 글자 안붙어있는 상품)
광고차단을 키면 2페이지 3페이지에도 없네요

**Comment by piquark6046** [comment]
전에도 그런 비슷한 경우를 봤는데요.
List-KR 필터 리스트 같은 애드블록 필터 리스트의 수정이 없음에도 네이버가 적게 노출시키는 것 같습니다.
