### ISSUE TITLE
AB: v.daum.net

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#682]
### URL

https://v.daum.net/v/20230418204209310

### FILTERS

adguard base
adguard mobile
listkr 

adguard dns
listkr dns

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

동영상을 재생할수 없어요

![IMG_2472](https://user-images.githubusercontent.com/15683789/232829894-0de5d7aa-8797-4c15-acb1-d8994c8dd26e.png)

**Comment by piquark6046** [comment]
왜 안티-애드블록이 AdGuard for iOS에서만 재구현이 되는지 AdGuard Slack에 물어본 상태입니다.
