### ISSUE TITLE
IC: 배달의민족 app

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#684]
### URL

https://apps.apple.com/kr/app/%EB%B0%B0%EB%8B%AC%EC%9D%98%EB%AF%BC%EC%A1%B1/id378084485

### FILTERS

adguard base
adguard mobile 
listkr 

adguard dns
listkr dns

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

아이폰 배달의민족 어플 내에서

일부 이벤트가 공란 처리 되어 볼 수 없습니다.

좌우로 스와이프 하면 일부 이벤트가 공란으로 나와요.

해당 어플은 광고차단하면 안될거 같아요

![IMG_2479](https://user-images.githubusercontent.com/15683789/233575244-2db1120d-604c-410d-87c7-f397aa2efdf9.png)
![IMG_2477](https://user-images.githubusercontent.com/15683789/233575302-3d081b16-274c-4b73-bb12-330afed4e8c2.jpeg)
![IMG_2476](https://user-images.githubusercontent.com/15683789/233575335-a4a4e062-a49c-49f2-a28c-219254255544.jpeg)

**Comment by piquark6046** [comment]
해당 도메인 (`adplatform-cdn.baemin.com`) 은 우아한형제들이 서비스하는 [만화경](https://www.manhwakyung.com/)에서 사용하는 광고 도메인입니다.
그런데, 그게 배달의 민족 앱의 해당 배너에서 사용하는 도메인하고 겹치는 것으로 보이네요.

Android에서는 각 앱 단위로 도메인 허용이 가능한데, iOS에서는 불가능합니다.

**Comment by relaxedbrownie** [comment]
어 이거 저도 마침 제보하려던 참이었는데
![IMG_2665](https://user-images.githubusercontent.com/126370491/233623440-d0486af6-4d79-4ba9-8469-ab3a6bd7a593.jpeg)
![IMG_2664](https://user-images.githubusercontent.com/126370491/233623451-0d2a85f7-ee6e-441e-b734-6dd466b264e7.jpeg)
![IMG_2663](https://user-images.githubusercontent.com/126370491/233623456-f7548acb-3ba8-45a6-8ac1-cde60cb8eff7.jpeg)
이미지가 붙어있어서 보기가 좀 헷갈릴 수도 있는데 총 3개고 각각 왼쪽이 List-KR DNS를 켰을 때, 오른쪽이 껐을 때입니다.
이것들도 같은 이유로 수정하기 어려운 부분인가요?

**Comment by piquark6046** [comment]
DNS 필터 레벨에서는 Android와 iOS 구분 없이 선택적으로 차단할 수 없습니다.
몰론, 이 도메인을 이번에도 사용한가면, DNS 허용 목록에 `@@||adplatform-cdn.baemin.com^$important`를 추가해서 일시적으로 보이게끔 하실 수 있습니다.

**Comment by relaxedbrownie** [comment]
그거 추가하니까 잘 뜨네요. 감사합니다.
