### ISSUE TITLE
빈 공간이 남는 오류 현상

### ISSUE THREAD

**Issue by relaxedbrownie** [List-KR/List-KR#685]
### https://github.com/List-KR/List-KR/issues/685#issuecomment-1517887405 참고해주세요.

**Comment by piquark6046** [comment]
에펨코리아 포텐터짐 최신순이죠? 안 보입니다.
혹시 로그인하셨나요?

**Comment by relaxedbrownie** [comment]
맞아요. 제일 처음 메인 화면이에요.
아뇨. 로그아웃 상태입니다.

**Comment by piquark6046** [comment]
SKT 5G 핫스팟으로 돌려도 안됩니다. 혹시 필터 업데이트를 해보시겠어요?

**Comment by relaxedbrownie** [comment]
윈도우11 엣지에서 개발자 도구를 통해 모바일 화면으로 전환했을 땐 빈 공간이 안 보이네요. 아이폰 사파리에서는 모바일 화면에서도 보이고 데스크탑 모드에서도 보이네요. 필터는 똑같은데 사파리에서만 뜨는 거 같아요. 필터는 최신입니다. 참고로 어제까지는 사파리에서도 안 떴어요.

**Comment by piquark6046** [comment]
DOM 구조를 확인하고 싶은데, macOS 디바이스를 가지고 계신가요?

**Comment by relaxedbrownie** [comment]
아뇨. 디바이스는 아이폰이랑 윈도우 노트북밖에 없어요 ㅠㅠ
실시간으로 뭔가 바뀌고 있는 거 같은데 방금 전부터 광고 자리가 더 뚫고 나오네요.
![IMG_2671](https://user-images.githubusercontent.com/126370491/233648851-02bf96a6-8ad1-4f70-9f05-ad72e3d400d7.png)
딱히 뭐 건드린 거 없었는데 갑자기 이러길래 필터 껐다 켜고 업데이트하고 폰도 껐다 켜봤는데도 마찬가지입니다. 여전히 아이폰에서만 이렇고 윈도우에서는 정상적으로 제거되고 있어요.

**Comment by relaxedbrownie** [comment]
![IMG_2672](https://user-images.githubusercontent.com/126370491/233650089-20b30108-19eb-4962-a96a-eeefc5a42053.png)
글 아무거나 들어가니까 이것도 다시 나타났네요. 옛날에 잠깐 보이다가 없어진 부분인데

**Comment by piquark6046** [comment]
그러면, [Web Inspector](https://apps.apple.com/kr/app/web-inspector/id1584825745)를 설치하시고 iOS 설정 -> Safari -> 확장 프로그램에서 활성화해보시겠어요?
반드시, 모든 웹 사이트에 대한 권한을 허용하시고, 문제가 있는 에펨코리아 페이지에서 Safari의 탭 막대에서 `가가`에 있는 Web Inspector로 찾아주세요.

**Comment by relaxedbrownie** [comment]
네 활성화했어요. 어떤 부분을 보여드리면 될까요?

**Comment by piquark6046** [comment]
그 숨겨지지 않은 빈 공간들(leftover)이요.

**Comment by relaxedbrownie** [comment]
![IMG_2673](https://user-images.githubusercontent.com/126370491/233651802-4320d96d-c5ec-4a51-9870-05e3bf3665e5.png)
![IMG_2674](https://user-images.githubusercontent.com/126370491/233651808-de95808b-49a9-4d6a-a68c-4701aa1e1749.png)

**Comment by piquark6046** [comment]
핵심적인 규칙은 이미 List-KR 필터에 다 있는 상태라 안 보여야하는 빈 공간(leftover)들입니다.
혹시 다른 백그라운드 앱들을 종료해보시겠어요? 아마 메모리 부족 같은데요.

3GiB RAM을 가진 제 iPhone SE2에서는 안 보입니다.

**Comment by relaxedbrownie** [comment]
혹시나 도움이 되실지 모르겠는데 유니콘(Safari 전용) 잠깐 설치해서 테스트해보니까 빈 공간이 다 사라지네요.

**Comment by Maccvc** [comment]
저도 이렇습니다..
방금 필터 수동으로 업데이트 한 이후로 이러네요
찾아보러 왔는데 마침 글이 있길래 댓글 남깁니다

광고영역이 여기저기 뜨는데 
위의 fmkorea도 똑같네요

**Comment by piquark6046** [comment]
혹시 List-KR 필터를 어떻게 활성화하셨나요?

**Comment by relaxedbrownie** [comment]
메모리 문제는 아닌 거 같습니다. 6GB RAM 모델이고 앱 전부 다 끄고 다시 켜봐도 마찬가지네요. 저 같은 분이 또 나타나신 거 보니 뭔가 꼬인 거 같네요. 혹시 모르니 YousList 한 번 켜볼게요.

**Comment by Maccvc** [comment]
> 혹시 List-KR 필터를 어떻게 활성화하셨나요?

adguard 베이스 필터와 list-kr 사용중입니다
https://cdn.jsdelivr.net/gh/List-KR/List-KR@master/filter-AdGuard.txt
이거 말고 
adguard에 내장된 list-kr 필터 사용중입니다
macOS, iOS 둘 다 그러네요

**Comment by Maccvc** [comment]
list-kr을 지우고 youslist를 해봤는데 여전히 그러네요

adguard가 업데이트된거 같지는 않는데 갑자기 무슨 일일까요?

**Comment by piquark6046** [comment]
일단 AdGuard를 재설치해보시곘어요?
AdGuard Slack 채널인 adguard-ios에 남겨볼께요.

**Comment by relaxedbrownie** [comment]
YousList도 소용없네요. 재설치도 한 번 해볼게요.

**Comment by piquark6046** [comment]
답변은 AdGuard의 필터 컴파일을 담당하는 FiltersCompiler의 1.1.82 버전에서 모든 cosmetic 규칙이 삭제되는 현상이 발생해서 버전을 롤백했답니다. https://github.com/AdguardTeam/FiltersRegistry/pull/773
시간이 지나면 해결될 것으로 보입니다.

**Comment by Maccvc** [comment]
> 

필터 문제도 아닌데 문의 남겼네요.. 죄송합니다
정보 감사해요!!

**Comment by relaxedbrownie** [comment]
재설치하고 왔는데 그런 일이 있었군요. 어쩐지 fmkorea.com 말고 다른 사이트에서도 광고 자리가 갑자기 다 나타나더라고요. 그럼 그냥 기다리고 있으면 되겠네요. 감사합니다.

**Comment by piquark6046** [comment]
다른 분들에게 알려주기 위해 이 issue를 해결될 까지 열어두겠습니다.
변경 사항이 있으면 알려드리겠습니다.

**Comment by opeth1990** [comment]
갑자기 네이버도 빈공간이 생겨서 와봤더니 이슈가 있었네요 
![image](https://user-images.githubusercontent.com/55120217/233659698-175746d3-daea-4464-8fe1-66ec20a6b64a.png)

**Comment by piquark6046** [comment]
AdGuard for iOS이 아닌 AdGuard for Windows나 AdGuard Browser Extension이면 기존 Adguard에 포함 되어있던 List-KR를 비활성화하시고 URL로 수동으로 설치하실 수 있습니다:
```
https://cdn.jsdelivr.net/gh/List-KR/List-KR@master/filter-AdGuard.txt
```
@opeth1990

**Comment by relaxedbrownie** [comment]
일단 아이폰에선 고쳐졌어요. 몇 분 전부터 광고 자리 다 사라졌습니다.

**Comment by piquark6046** [comment]
문제가 해결되었으며, 기존에 AdGuard에 설치된 List-KR 필터를 포함해서 모든 AdGuard에 의해 컴파일된 필터가 필터 업데이트하면 해결된다고 합니다.
