### ISSUE TITLE
AD: m.cafe.naver.com

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#686]
### URL

https://m.cafe.naver.com/appleiphone/7890043

### FILTERS

adguard base
adguard mobile 
listkr 

adguard dns
listkr dns

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

아이폰 사파리 브라우저 광고차단 해주세요

![IMG_2481](https://user-images.githubusercontent.com/15683789/233762755-c2c556ef-dd7c-4037-b602-6405ea15d8c5.jpeg)

**Comment by piquark6046** [comment]
게시글이 존재하지 않다고 합니다만 데스크톱에서 해당 광고가 잘 사라진다면, 그건 아사모 카페의 관리자가 설정한 자체 광고이므로 네이버 카페 앱에서는 일반 콘텐츠와 같은 도메인으로 전송되므로 차단할 수 없습니다.

만약, 브라우저에서 방문하신다면, 아사모 자체 광고에 관련된 규칙이 이미 존재해서 숨겨질 수 있습니다.
```adblock
[$path=/ca-fe\\/web\\/cafes\\/(appleiphone|12789486)(\\/|\\?)/]m.cafe.naver.com##.banner_add.bottom
```
그런데, 문제는 AdGuard for iOS와 AdGuard Content Blocker에서는 각 네이버 카페를 구분하기 위해 사용된 `$path`가 지원되지 않아 숨겨지지 않습니다.
만약 모든 네이버 카페 모바일 페이지에 설정된 게시글 하단 배너를 위 플렛폼에서 차단하시라면 아래 규칙을 사용해주세요:
```adblock
m.cafe.naver.com##.banner_add.bottom
```

**Comment by swbaek81** [comment]
알려주신방법으로 일부 해결했지만 사파리내에서 
팝니다 코너에 광고는 여전히 남네요

https://m.cafe.naver.com/appleiphone/7892392

![IMG_2487](https://user-images.githubusercontent.com/15683789/233984018-74e5fef1-1d31-4741-b86e-7228d83ea719.jpeg)

![IMG_2488](https://user-images.githubusercontent.com/15683789/233982900-c206d958-d4fc-43d7-adcc-fada20f21bb4.jpeg)

**Comment by piquark6046** [comment]
```adblock
m.cafe.naver.com##.banner_add.bottom
```
가 아닌 아래 규칙으로 변경해보세요:
```adblock
m.cafe.naver.com##.banner_add
```

**Comment by swbaek81** [comment]
사파리에서 광고가 모두 제거 됐습니다

**Comment by piquark6046** [comment]
그럼, issue를 닫아도 괜찮을까요?

**Comment by swbaek81** [comment]
네 닫아도 됩니다
