### ISSUE TITLE
AD: http://adcr.naver.com

### ISSUE THREAD

**Issue by pese1313** [List-KR/List-KR#688]
### URL

http://adcr.naver.com

### FILTERS

adguard base
list-kr
youslist

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

AdGuard for Windows

### Comment

![image](https://user-images.githubusercontent.com/131527342/233780047-7f34f513-7558-479e-bf44-d487a5bcf265.png)

이런식으로 광고 차단이 제대로 동작하지 않습니다

**Comment by piquark6046** [comment]
필터를 업데이트해보시곘어요?
https://github.com/List-KR/List-KR/issues/685 와 관련되어 있습니다.

**Comment by pese1313** [comment]
해결되었습니다!
