### ISSUE TITLE
IC: send-anywhere.com

### ISSUE THREAD

**Issue by relaxedbrownie** [List-KR/List-KR#689]
### URL

https://sendanywhe.re/41VS7A4G

### FILTERS

AdGuard 베이스 필터

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

브라우저에서 열기(=다운로드) 버튼이 활성화되지 않는 현상

예전엔 광고 5초를 보지 않아도 광고만 차단해줘서 즉시 다운로드할 수 있었는데 언젠가부터 버튼이 먹통됨

**Comment by piquark6046** [comment]
이 문제를 발생시키는 규칙이 AdGuard Base 필터의 기반이 되는 EasyList에 있어 EasyList 관리자에게 수정 요청을 하겠습니다.

**Comment by piquark6046** [comment]
EasyList에서 해결되었다는 코멘트가 있기 전까지 일시적으로 아래 규칙을 사용하실 수 있습니다:
```adblock
-image-ad.$badfilter
```

**Comment by relaxedbrownie** [comment]
일단 알려주신 사용자 규칙 추가해서 사용하고 있을게요. 5초 기다려야 하긴 하네요. 참고로 지금도 pc에서는 바로 사라져서 안 기다려도 되더군요.

**Comment by piquark6046** [comment]
EasyList (`@ryanbr`) 에서 해결되었네요.

1시간 정도 기다리시면 AdGuard Base 필터에도 적용되어서 패치를 다운로드하실 수 있습니다.
그 이후에는 저 규칙을 제거하실 수 있습니다.

---

> 참고로 지금도 pc에서는 바로 사라져서 안 기다려도 되더군요.

저건 모바일에서 바로 안 사라져서 수정했어요.
