### ISSUE TITLE
AD: 쿠팡 앱

### ISSUE THREAD

**Issue by relaxedbrownie** [List-KR/List-KR#691]
### URL

쿠팡 앱

### FILTERS

https://cdn.jsdelivr.net/gh/adguardteam/HostlistsRegistry@main/assets/filter_25.txt

### Browser

(Other)

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

![IMG_2971](https://user-images.githubusercontent.com/126370491/235190585-b535e564-2a36-4959-a716-2337b6cac048.jpeg)
혹시 쿠팡 앱에서는 이런 광고 상품들 못 지우나요?

**Comment by seia-soto** [comment]
안녕하세요? 확인 결과 요청해주신 쿠팡 애플리케이션에서의 광고 섹션 제거는 불가능합니다. 애플리케이션 내 광고는 도메인 단위 차단을 통해 대개 가능하나 `cmapi.coupang.com` 도메인에서 광고 외 일반 검색 데이터 및 배너 데이터 또한 수신하고 있어 차단 시 서비스 이용이 불가능합니다.

감사합니다.

다만 애플리케이션 사용 중 프라이버시가 걱정되신다면 `jslog.coupang.com`, `ljc.coupang.com` 차단을 통해 서비스를 이용하시면서 오류 보고 및 기기 추적을 제한할 수 있습니다.

* iPhone 13 mini (iOS 16)에서 확인하였습니다.

**Comment by relaxedbrownie** [comment]
그렇군요. 이해했어요 설명 감사합니다.
