### ISSUE TITLE
AD: hashnews.cafe24.com

### ISSUE THREAD

**Issue by relaxedbrownie** [List-KR/List-KR#696]
### URL

https://hashnews.cafe24.com/

### FILTERS

AdGuard 베이스 필터
AdGuard 모바일 광고 필터
AdGuard 방해 요소 필터
List-KR

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

![IMG_3119](https://user-images.githubusercontent.com/126370491/236108396-eda78199-8c1b-4959-818f-e61748723dec.jpeg)
화면 중앙에 위와 같은 팝업이 나타남. 5초 지나야 제거 가능

**Comment by relaxedbrownie** [comment]
광고가 차단되기는 되는데 뭔가 좀 이상하네요.

사파리 시크릿 모드에서 테스트했을 때(쿠키 같은 다른 간섭 요인을 완전히 제거하기 위함) 애드가드를 활성화하고 https://hashnews.cafe24.com/ 여기에 처음 들어가면 광고가 그대로 나옵니다. 탭을 종료하고 다시 들어가면 광고가 안 떠요. 근데 웃긴 게 여기서 탭을 종료하고 애드가드를 비활성화하고 다시 사이트에 접속하면 차단 필터가 하나도 없는 상태임에도 광고가 또 안 나타납니다. 다시 탭을 종료하고 페이지에 재접속하면 광고가 나타나요.

어떻게 이런 일이 가능한 건지 제 상식으론 도저히 이해할 수가 없는데 왜 이런 걸까요? 차단 필터 on/off가 해당 페이지에 첫 접속했을 땐 전혀 반영이 안 되다가 두 번째로 재접속해야 반영이 된다는 게 너무 이상하네요. 다른 사이트는 이런 곳이 하나도 없었는데 이 사이트만 그렇습니다. 해결할 수 있나요?

**Comment by piquark6046** [comment]
@relaxedbrownie Safari 스크릿 모드에서 [AdGuard 테스트 페이지](https://adguard.com/ko/test.html)에서 확인해보시겠어요?

**Comment by relaxedbrownie** [comment]
확인해봤는데 adguard 실행 여부는 바로바로 반영되는 걸로 나타납니다. adguard를 껐다 켜서 실행 중이라고 뜬 상태에서 https://hashnews.cafe24.com/ 들어가면 역시 adguard를 켠 뒤 최초 1회 접속이라 그런지 몰라도 광고가 뜨고 시크릿 탭을 다 종료하고 다시 들어가면 광고가 안 뜹니다. 또 여기서 adguard를 끄고 adguard 테스트 페이지에 들어가서 실행 중이 아니라는 문구를 보고 https://hashnews.cafe24.com/ 들어갔는데도 광고가 안 뜹니다. 이것도 탭을 다 종료하고 다시 들어가면 광고가 뜨고요.

아이피 주소도 관련 있는 건가 혹시나 해서 아이피 주소를 바꾸면서 들어가봤는데도 결과는 앞에서 말씀드렸던 거랑 똑같아요. 어떻게 전의 설정 정보를 기억하고 있는지 이해가 안 되네요.

어차피 첫 1회만 그런 거라서 애드가드 필터를 껐다 켜지만 않으면 광고 뜰 일이 없으니까 큰 문제는 안 되는데 상식적으로 너무 납득하기 어려운 경우라 얘기해봤어요. 정 고치기 어렵다면 굳이 안 고쳐주셔도 괜찮습니다.

**Comment by piquark6046** [comment]
아무래도 [이 issue](https://github.com/AdguardTeam/AdguardForiOS/issues/1930)와 관련되어 있는 듯합니다.
