### ISSUE TITLE
안드로이드 POOQ 앱에서 광고 차단&TIVING 오류 문제입니다.

### ISSUE THREAD

**Issue by modu836** [List-KR/List-KR#7]
POOQ의 경우 애드가드 필터링 로그를 보면 ch.dawin.tv에서 동영상 광고를 읽어 와서, 그 도메인을 막았더니 일부 채널들은 오류가 뜨며 볼 수가 없습니다. 그래서 그냥 광고를 보고 있는데 해결 방안이 있을까요?

그리고 TIVING은 광고는 안 뜨지만, 처음 채널 재생할 때 오류 팝업이 뜨고 다시 한 번 재생을 해야 정상적으로 볼 수 있습니다. 큰 오류는 아니긴 하지만, 해결 가능한 문제라면 해결되었으면 하는 생각에 말씀드립니다.

**Comment by ghost** [comment]
안녕하세요, 해당 동작 수행 시 AdGuard 애플리케이션에 기록되는 로그 등 정보가 있다면 기술해주실 수 있으신가요?

**Comment by modu836** [comment]
POOQ은 기본 필터에 없는 광고나 로그 수집에 관련된 주소가 e.crashlytics.com, settings.crashlytics.com, ad.smartmediarep.com, medialog.smartmediarep.com, smrmembers-smr.smartmediarep.com, pooq3-static-json.pooq.co.kr 정도인것 같고, 광고 동영상은 ch.dawin.tv에서 읽어 오는 것 같습니다. 그런데 좀 이상한게 저 주소들을 막으면 어떤 채널은 광고가 안 나오면서 정상 재생되고, 어떤 채널은 안 나옵니다. 그리고 나오던 채널들도 가끔 안 나오기도 하고요. 같은 상황을 만들어도 재생이 되다 안 되다 해서 어떻게 더 설명드려야 할지 애매하네요.

TIVING은 따로 설정한 것 없이 영어 필터에서 adverweb.cjenm.com를 차단하고 있습니다. 이 상태면 광고는 차단되지만 먼저 말씀드린 것처럼 한 번 오류 팝업이 뜨고, 그걸 확인한 이후에 다시 재생해야 정상적으로 보입니다.

**Comment by modu836** [comment]
POOQ에서 다른 주소들은 다 막고 ch.dawin.tv만 열여주니 2개 나오던 광고가 아예 안 나오던가 1개로 줄던가 하네요. ch.dawin.tv에서 광고를 읽을 수 있는가 없는가에 따라 반환값 같은게 정해져서 작동에 영향을 미치는 것 같은데, 그 쪽으로는 아는게 없어서 더 이상은 건들이는 것은 무리네요. TIVING 역시 adverweb.cjenm.com가 반환값을 주는 것 같은데, 오류 팝업을 띄우긴 하지만 재생은 됩니다.
