### ISSUE TITLE
[Status] AB: tgd.kr (via.placeholder.com)

### ISSUE THREAD

**Issue by seia-soto** [List-KR/List-KR#704]
### URL

https://tgd.kr/s/jungtaejune/42698562?category=1262916&page=45

### FILTERS

Fanboy’s Annoyance

```adblock
||placeholder.com^$3p
```

- (3) tgd.kr ⇒ placeholder.com
- image
- https://via.placeholder.com/1

### Browser

(Other)

### Operating System

Apple macOS

### Ad-Blocker

uBlock Origin

### Comment

Possible solutions:

```adblock
||via.placeholder.com/$image,redirect=1x1.gif,domain=tgd.kr
```

```ts
for (const el of document.querySelectorAll('img[src*="via.placeholder.com"]')) {
  el.setAttribute('src', el.getAttribute('data-src'))
}
```

**Comment by seia-soto** [comment]
Ongoing: https://github.com/easylist/easylist/issues/15904

**Comment by piquark6046** [comment]
As far as i know, In EasyList, `$redirect` and javascript filter are not allowed.

**Comment by seia-soto** [comment]
Do you mind adding it to List-Kr?

**Comment by piquark6046** [comment]
Yep.

**Comment by seia-soto** [comment]
AG: `||via.placeholder.com/$image,redirect=1x1-transparent.gif,domain=tgd.kr` would work.

**Comment by piquark6046** [comment]
AdGuard for iOS, AdGuard Content Blocker and AdGuard for Safari do not support `$redirect` syntax.

**Comment by seia-soto** [comment]
Don't know why but the issue is not present on Safari (expecting the lack of functionality)

Investigating

<details><summary>Details</summary>
<p>

![image](https://github.com/List-KR/List-KR/assets/30369714/1169d78e-3b19-44ff-9b9e-2264374d5da5)

</p>
</details>

**Comment by seia-soto** [comment]
iOS clients seem like free of this issue at this time. They're not emitting content blocking as an error.

<details><summary>Details</summary>
<p>

![image](https://github.com/List-KR/List-KR/assets/30369714/009b5ed4-cdf4-4ca3-824c-b40b5429e2d0)

</p>
</details>

**Comment by seia-soto** [comment]
- iOS/macOS Safari (even without AG): unaffected
- AG browser extension: affected / resolvable

I don't know what platform you're currently saying about AdGuard content blocker, can you confirm it, or test it instead?

**Comment by piquark6046** [comment]
AdGuard Content Blocker is an adblocker for Samsung Browser and available in Google Play Store.  
It is not affected.

**Comment by seia-soto** [comment]
Then I'll create a PR.
