### ISSUE TITLE
app : kakaotalk

### ISSUE THREAD

**Issue by bobblun** [List-KR/List-KR#711]
chat list displays ad in the middle

**Comment by bobblun** [comment]
![1fc34c6a931ec](https://github.com/List-KR/List-KR/assets/49634687/f1ee090c-68d9-44dd-8682-7aecfc75a482)

**Comment by piquark6046** [comment]
It seems that Kakao pinned a build-in advertisement in KakaoTalk regardless of your Internet connection. 
They appear even if all networks are disabled, and, no local VPN-based adblocker (including AdGuard and Unicorn Pro) can block them unless KakaoTalk app is modified.
