### ISSUE TITLE
IC: https://danawa.com/

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#712]
### URL

https://danawa.com/

### FILTERS

List-KR 

### Browser

Mozilla Firefox

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

다나와 사이트(https://danawa.com/) 접속이 안 됩니다. 애드가드를 끄면 접속이 잘 됩니다. 
스텔스 모드에 있는 옵션은 퍼스트파티 쿠키 자동 파괴 옵션 제외하고 전부 활성화 했습니다.

**Comment by piquark6046** [comment]
@NoName926 AdGuard의 설정 파일을 내보내신 뒤에 전송해주실 수 있으시나요?

**Comment by Seohare** [comment]
> @NoName926 AdGuard의 설정 파일을 내보내신 뒤에 전송해주실 수 있으시나요?

@piquark6046 

[20230531_201434_adg_settings_7.13.4266.0.zip](https://github.com/List-KR/List-KR/files/11612350/20230531_201434_adg_settings_7.13.4266.0.zip)

**Comment by piquark6046** [comment]
@NoName926 AhnLab V3 같은 안티-바이러스나 금융 보안 프로그램이 설치되어 있나요?

**Comment by Seohare** [comment]
> 

@piquark6046 보안프로그램은 AhnLab V3 365 클리닉, 앱체크 Pro가 설치 되어있습니다.

**Comment by piquark6046** [comment]
@NoName926 AhnLab V3 364 클리닉을 제거 및 재부팅 하신 뒤에는 잘 되나요?
아니면 AdGuard의 설정을 초기화해보시겠어요?

**Comment by Seohare** [comment]
> @NoName926 AhnLab V3 364 클리닉을 제거 및 재부팅 하신 뒤에는 잘 되나요? 아니면 AdGuard의 설정을 초기화해보시겠어요?

@piquark6046  해결 됬습니다. 감사합니다
