### ISSUE TITLE
docs: remove or replace aggressive contents for general customers

### ISSUE THREAD

**Issue by seia-soto** [List-KR/List-KR#717]
# Purpose

I'm writing this issue to remove or replace some aggressive content on the README to help lay people reading the README comfy by using less aggressive expressions or removing potential content that may harm others' reputations, especially for Unicorn Corp.

Also, I want to point out that the Korean term used can be seen as ugly, and replacing the expression can improve the overall readability of documents.

**Before all, I am NOT an official of Unicorn Corp.**

## Overall

> **DO NOT** use any sentence ending with '-해요'. **DO** use '-하십시오.' pattern in Korean of giving trust to visitors.

> **DO NOT** use any sentence implicating 'IF' statements. **DO** use straightforward sentences.

## Listing

The following is a recommended listing of content that may improve overall readability.

> **README.md** List-KR 필터는 AdGuard 광고 차단기와 uBlock Origin에만 함께 사용되는 한국어 웹 사이트용 필터입니다.

List-KR은 AdGuard와 uBlock Origin을 지원하는 한국어 웹 사이트용 광고 차단 필터입니다.

> **README.md** 따라서 List-KR 필터는 AdBlock Plus와 유니콘 Pro 광고차단기가 고급 문법을 지원하지 않기 때문에 그 광고 차단기들에 추가될 수 없습니다.

고급 문법을 지원하지 않는 AdBlock Plus와 유니콘 Pro 광고차단기에서는 일부 필터가 정상적으로 동작하지 않을 수 있습니다.

> **README.md** 게다가, 유니콘 Pro 광고차단기는 디버그에 필요한 필터 편집기를 제공하지 않습니다.

[remove]

> **README.md** 기술적 문제로 인해 일부 웹사이트들의 방문자는 일부 설명을 따라야 합니다. 이 문서를 계속해서 읽어주세요.

[remove]

The above content indicates that List-KR cannot be used in other ad blockers but it is not true. People can add List-KR to their ad blockers and use List-KR in incomplete functionality. Since List-KR is not an exclusive resource or filter to AdGuard and uBlock Origin, the above content should be removed or replaced. Also, some of the content is too aggressive for Unicorn Corp even though they didn't do any harm to List-KR. Since AdGuard is not the standard for handling external contributors, content related to Unicorn Corp should be removed unless List-KR is explicitly owned and operated by AdGuard even if you belong to AdGuard.

> **README.md** 만약 추격기나 우클릭 방지 스크립트를 차단하시고 싶으시면, AdGuard 추적 보호 필터, AdGuard URL 추적 필터나 AdGuard 방해 요소 필터를 활성화하세요.

트래커나 우클릭 방지 스크립트를 차단하시려면 AdGuard 추적 보호 필터, AdGuard URL 추적 필터, 그리고 AdGuard 방해 요소 필터를 활성화하십시오.

The above fixes invalid use of the term: 추격기.

> **README.md** 만약 지원을 받으시거나 각 메인테이너의 이메일 주소를 아시고 싶으시면, 이 위키 문서를 읽어주세요.

이메일을 통한 비공개 지원이 필요하시면 이 위키 문서에 포함 연락처를 참고해주십시오.

The above content has a conflict with the wiki page because it indicates the arbitrary visitor can contact via email but the wiki page indicates that the visitor will be required to check GitHub issues first. Instead, removing the useless steps and making the sentence straightforward will help. Also, you already wrote about how to get help at the head of README.

> **README.md** 프로그램에서 사용하시고 싶으시면, 구독하거나 불러오기 위해 다음 URL을 사용해주세요.
광고 차단기에 다음 URL을 추가해서 List-KR을 사용할 수 있습니다.

The above content includes 'IF' statement harms readability. Also,  just writing the term: 'you can use' is better because lay people don't know what is 'subscribing to the filter'.

> **README.md** 2023년 4월 7일부터 jsDelivr를 활용한 전송 속도 가속으로 인해 기존 /filter.txt와 /filter-uBO.txt을 사용한 구독 방법이 불가능해집니다.

I don't know what the heck is '전송 속도 가속' even I am working as developer. Use easy terms like caching instead.

> **README.md** AdGuard나 uBlock Origin이 아닌 다른 광고 차단기에서 설치하시면, List-KR 필터의 정상적인 작동이 안 될 가능성이 극단적으로 높습니다.

[remove]

You already indicates that this filter works great on AdGuard and ublock Origin. There's no reason to say this twice. If you do so, you're not respecting other ad blockers.

> **README.md** AdGuard for iOS에서 !#include나 #!if 같은 전처리 지시자가 아직 지원되지 않기에 List-KR DNS 필터 설치가 아닌 경우 기본적으로 설치되어 있는 List-KR 필터를 사용해주세요.

iOS용 AdGuard에서는 #!include나 #!if 등의 기능이 지원되지 않으니 URL로 필터를 추가하지 말고 '특정 언어'에 등록된 List-KR 필터를 대신 사용하십시오.

I don't understand what the above content exactly means. Removing DNS filter related content makes sense.

**Comment by seia-soto** [comment]
I am creating the issue before doing PR to discuss first, please add comments for discussion.

**Comment by simnalamburt** [comment]
It generally makes sense to me.

**Comment by piquark6046** [comment]
Can you create new PR to review and discuss easily?
