### ISSUE TITLE
IC: lotteon.com

### ISSUE THREAD

**Issue by relaxedbrownie** [List-KR/List-KR#719]
### URL

https://www.lotteon.com/m/review/myLotte/reviewWriteListTab

https://www.lotteon.com/m/promotion/couponzone/couponReceive

### FILTERS

AdGuard 방해 요소 필터

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

![IMG_5201](https://github.com/List-KR/List-KR/assets/126370491/00398b7c-d1c8-4032-b7d0-7bac5434cd17)
AdGuard 방해 요소 필터 or AdGuard 모바일 앱 배너 필터가 켜져있으면 리뷰쓰기를 눌러도 반응이 없음

![IMG_5202](https://github.com/List-KR/List-KR/assets/126370491/7c7dcbea-5b83-4822-b3a5-30d0a0141bca)
AdGuard 방해 요소 필터 or AdGuard 모바일 앱 배너 필터가 켜져있으면 쿠폰 받기 버튼을 눌러도 반응이 없음

**Comment by piquark6046** [comment]
제휴 서비스 미동의 회원이라고 뜨면서 L.Point 계정을 통한 로그인이 안되서 지연될 수 있습니다.

**Comment by piquark6046** [comment]
지금 작업 중이지만, 제가 롯데온에서 지금 당장 상품을 구입할 일이 없어서 첫번째 문제를 다루기는 어려울 것 같습니다.

**Comment by relaxedbrownie** [comment]
자주 들르는 페이지는 아니라서 당장 급한 건 아니에요. 그때그때 콘텐츠 차단기 끄기 하면 되니까 천천히 하셔도 괜찮아요.
