### ISSUE TITLE
AD: m.mail.daum.net

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#720]
### URL

https://m.mail.daum.net/list/INBOX

### FILTERS

listkr
adguard 베이스
adguard 모바일

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

광고공백제거 부탁드립니다 감사합니다

![IMG_2599](https://github.com/List-KR/List-KR/assets/15683789/dcbaf1ec-b9b6-4979-8b1a-b6309474e634)

**Comment by piquark6046** [comment]
전에 패치했었는데, 안되시나요?
List-KR 필터를 비활성화 하신 뒤에 다시 활성화해보시겠어요? 몰론 이 사이와 과정 끝에 `변환 중`이나 `업데이트 중`이라는 팝업이 사려진 뒤에 후속 과정을 해주세요.

**Comment by swbaek81** [comment]
네 안되요, 아마도 얼마전에 다음 메일이 UI가 변경 되고 나서 부터 안되는거 같습니다
