### ISSUE TITLE
AD: sportalkorea.com

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#722]
### URL

https://www.sportalkorea.com/news/view.php?gisa_uniq=2023060812172428&sp=A&spnk=2023061214075636

### FILTERS

listkr
adguard base

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

광고제거 부탁드립니다 감사합니다

![image](https://github.com/List-KR/List-KR/assets/15683789/98a090a1-d472-41f0-99da-049ba02f4392)

**Comment by piquark6046** [comment]
https://cdn.jsdelivr.net/gh/List-KR/microShield@main/microShield.user.js
위 URL를 클릭하셔서 설치해보시고 새로고침해보세요.

**Comment by swbaek81** [comment]
마이크로쉴드 설치하고 해결되었습니다
