### ISSUE TITLE
AD: instructivehumility.com

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#725]
### URL

https://instructivehumility.com/detail?object_id=64886550f8f50b587865542c&psc=o1l5t3k7S5K4

### FILTERS

List-KR

### Browser

Mozilla Firefox

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![0](https://github.com/List-KR/List-KR/assets/99063049/00a7d313-1f8e-4480-87b5-6a21f4f63240)

**Comment by seia-soto** [comment]
@piquark6046 CSS tweaking works
![image](https://github.com/List-KR/List-KR/assets/30369714/b6b17455-8078-4722-9a6a-004ddaf51508)

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/725#issuecomment-1592873767 Thanks, but i know that.
