### ISSUE TITLE
IC: noonoo.lol

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#726]
### URL

https://noonoo.lol/ani/34

### FILTERS

List-KR

### Browser

Mozilla Firefox

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![1](https://github.com/List-KR/List-KR/assets/99063049/4d2a6d66-cf7e-468a-8d0b-acac8e1a1705)

**Comment by piquark6046** [comment]
AdGuard의 설정을 구체적으로 어떻게 하셨나요?

**Comment by Seohare** [comment]
> AdGuard의 설정을 구체적으로 어떻게 하셨나요?

@piquark6046 
[20230616_224941_adg_settings_7.13.4278.0_Nightly.zip](https://github.com/List-KR/List-KR/files/11770921/20230616_224941_adg_settings_7.13.4278.0_Nightly.zip)

**Comment by piquark6046** [comment]
그 며칠 전에 제가 방문했을 때는 TLS 인증서 기관으로 Let's Encrypt으로 사용하고 DDoS 보호를 안했던데, 지금은 Cloudflare가 설치되어 있네요.
현재 설정으로는 Cloudflare가 방문을 승인해주나요?

제 쪽에서는 주신 스텔스 설정이 너무 엄격해서 승인을 안 해주고 계속 무한 검사합니다.

**Comment by piquark6046** [comment]
누누티비 시즌2가 종료되어 닫습니다.
