### ISSUE TITLE
카카오톡 오픈채팅 광고 제보

### ISSUE THREAD

**Issue by bobblun** [List-KR/List-KR#731]
### URL

![Screenshot_20230622_140300_KakaoTalk](https://github.com/List-KR/List-KR/assets/49634687/12bd3206-d09c-4504-b6ae-5f3872c19079)

카카오톡 오픈채팅방 목록 중간에 생긴 광고가
apk 자체에서 삽입된 방식이라 애드가드로 삭제는 안되지만
광고 갱신이 되지 않는 방법은 있더군요

||talk-pilsner.kakao.com^$app=com.kakao.talk

이 필터를 추가하면 오픈채팅 광고 자체는 갱신되지 않습니다

문제는 위의 필터가 카카오톡 오픈채팅 검색도 막더군요(오픈채팅 전체 주소라서 오픈채팅 관련 설정을 아예 막는듯)

패킷 분석을 통해 오픈채팅 전체 주소에서 광고 갱신만 시키는 상세 주소를 알아내야 할 것 같은데 능력이 안되네요

혹시 알아보실 수 있을까요?

### FILTERS

list-kr

### Browser

(Other)

### Operating System

Android

### Ad-Blocker

AdGuard for Android

**Comment by seia-soto** [comment]
안녕하세요? `talk-plisner.kakao.com` 도메인은 카카오 애플리케이션 내 광범위하게 사용되는 도메인으로 차단 시에는 정상적입 애플리케이션 이용이 불가능합니다. 내부 통신은 JSON을 HTTP와 LOCO 프로토콜 내에 전송 방식으로 이루어지나 SSL Pinning을 시스템 상에서 무력화시켜야 하므로 일반적인 상태의 휴대전화에서는 애드가드 쪽에서 세부적으로 차단이 불가능합니다. 감사합니다.

**Comment by piquark6046** [comment]
APK 분석에는 감사드립니다만, 도메인이 아닌 상세 URL 차단을 진행하시라면 각 사용자의 Android 디바이스가 루팅되어 있어야 하며 루팅 시에는 삼성 녹스가 영구적으로 손상되서 삼성 페이 같은 삼성만의 핵심 기능을 사용하지 못하는 부작용이 있습니다.
