### ISSUE TITLE
AD: 카카오톡

### ISSUE THREAD

**Issue by relaxedbrownie** [List-KR/List-KR#735]
### URL

카카오톡 PC 버전

### FILTERS

AdGuard 베이스 필터
List-KR
List-KR DNS

### Browser

(Other)

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![IMG_5642](https://github.com/List-KR/List-KR/assets/126370491/48e156d7-f530-4483-a232-6bb069c8a29f)
AdGuard DNS filter로는 차단되는데 List-KR DNS로는 광고가 뜨네요.

**Comment by piquark6046** [comment]
![Screenshot from 2023-06-26 19-45-53](https://github.com/List-KR/List-KR/assets/98787049/b1acb776-25e3-4fcb-8f68-7e7f363535a7)

카카오톡 앱을 완전히 끄고 다시 시작해보세요.
참고로, 로그인 이후에는 WPF 드라이버 기반 필터링이 되는 것 같습니다.

**Comment by relaxedbrownie** [comment]
계속 끄고 다시 시작했는데도 뜨더라고요.
그리고 좀 이상한 게 AdGuard DNS filter로 한 번 차단하고 난 뒤에 AdGuard DNS filter를 끄고 List-KR DNS만 켜두면 카카오톡을 재실행했을 때 차단이 정상적으로 유지되더군요? 근데 한참 있다가 껐다 켜보니까 다시 광고가 뜨더라고요. AdGuard DNS filter 켜면 다시 광고 차단되고 또 한동안 List-KR DNS만 켜놔도 차단이 유지되고 시간 지나서 재실행하면 다시 광고 뜨고 무한 반복이었어요.

근데 카카오톡 앱이랑 exe 파일로 설치한 거랑 다른가요? 전 마이크로소프트 스토어에서 설치 안 하고 공홈에서 다운받아서 설치했어요.

**Comment by piquark6046** [comment]
저도 공식 웹 사이트에서 다운로드하고 설치하였습니다.
카카오톡에 대해 계속 이 기기에서 로그인 유지를 설정하셨다면, AdGuard 설정 -> `네트워크` -> `필터링되는 앱`을 클릭하시고 `앱 추가하기`를 통해 카카오톡 앱을 추가하셔서 WPF 드라이버 기반 필터링을 켜보시겠어요?

**Comment by relaxedbrownie** [comment]
![화면 캡처 2023-06-27 001753](https://github.com/List-KR/List-KR/assets/126370491/90362b2a-db34-4f2c-90a7-26e744452319)
거기 카카오톡 추가하면 카카오톡을 껐다 켰을 때 아예 접속 자체가 안 되네요. 자동 로그인 켜놓고 잠금 모드 해제해놔도 로그인 안 돼요. WPF 드라이버 기반 필터링이 되는 것 같다고 하셨는데 그걸 켜면 저는 그냥 애초에 카톡이 안 들어가져요.

첨부해주신 사진 보면 List-KR DNS가 광고 차단하고 있는 걸로 보이는데 신기하네요. WPF 드라이버 기반 필터링에 카카오톡을 추가하신 상태인가요? 추가하면 접속이 안 되는데 어떻게 하신 건지... 

근데 윈도우는 iOS랑 달리 굳이 DNS 보호 안 켜도 브라우저 외에서도 광고 차단되는 거 같은데 그냥 기본 광고 필터들로(AdGuard 베이스 필터, List-KR, 사용자 규칙 등등) 카톡 광고 지우는 방법은 없을까요? 윈도우에선 DNS 보호 켜니까 버그인지 모르겠는데 아무 웹 사이트나 첫 방문 시에 로딩이 엄청나게 오래 걸리네요. 그 다음 방문할 때부턴 시크릿 탭에서 방문해도 정상적으로 바로 로딩되고요.

참고로 DNS 서버는 시스템 기본 설정 씁니다.

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/735#issuecomment-1607810415

저 스크린 샷의 상태는 카카오톡 앱에 대한 WPF 드라이버 기반 필터링을 끈 상태입니다. (전체적인 기능은 켜져있습니다.)
위 스크린 샷처럼 개인정보는 가려진 상태로 필터링 로그를 보여주실 수 있으시나요? 카카오톡 앱을 켜기 전에 필터링 로그 창을 켜셔야 합니다.

더 확인해봐야 알겠지만, 현재 제가 아는 한에서는 DNS 필터링 기반으로 하실 수 밖에 없는 걸로 압니다. 전 Cloudflare DNS 서버를 DNS over HTTPS로 선택해서 테스트했었습니다.

만약, 카카오 비즈니스라고 나오는 요소까지 없애고 싶으시면, [KakaoTalkAdBlock](https://github.com/blurfx/KakaoTalkAdBlock)를 참고해주세요.

**Comment by relaxedbrownie** [comment]
늦은 시간에도 답변 감사합니다. 요청해주신 부분은 나중에 다시 캡처해서 올려볼게요.
아 근데 궁금한 점이 있는데 DNS 서버를 시스템 기본 설정 대신 Cloudflare DNS를 사용하면 어떤 장점이 있나요? 이걸로 하시는 분들 꽤 있는 거 같던데. 일단 광고 차단 기능은 전혀 없는 거 같던데 뭐 때문에 쓰는 서버인지 단순히 궁금해서요.

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/735#issuecomment-1607890116

대한민국에서 가장 가까운 글로벌 거대 DNS 서비스라서 그래요.
대한민국에서 가장 가까운 AdGuard 서버는 일본에 있습니다. Cloudflare는 대한민국에도 서버가 있고요.

**Comment by relaxedbrownie** [comment]
어제는 죽어도 안 되더니 필터링 로그 캡처하려니까 무안하게 갑자기 잘 차단되네요. 다른 설정은 건든 것도 없는데 참 이상하네요...

이 문제는 일단 해결된 거 같고 위에 Cloudflare DNS에 대해 하나만 더 여쭙고 싶은데요. 제가 DNS에 대해 무지해서 이상한 질문일 수도 있는데 Cloudflare가 우리나라에 서버가 있다고 하더라도 그냥 애초에 어떠한 곳도 거치지 않는 시스템 기본 설정(사용 중인 인터넷인 KT, SK, LG 같은 곳에서 제공하는?)이 젤 빠른 거 아니에요? 시스템 기본 설정으로 그대로 놔두는 대신 Cloudflare DNS를 거치면 어떤 점이 좋은 건지 좀 알려주실 수 있나요?
![image](https://github.com/List-KR/List-KR/assets/126370491/73e77252-c1f3-40af-bb1c-53bf244ae7c6)

**Comment by seia-soto** [comment]
일반적인 응답 속도는 CloudFlare보다 통신사 DNS가 빠르나 이후 실제 접속하시는 서버 등 적절한 경로로의 라우팅은 CloudFlare에서 비교적 잘 관리되는 장점이 있습니다. 기존 통신사 DNS를 사용하셔도 무관하며 본래의 취지는 기준이 되는 DNS 서버를 선택하는 것이라 예상됩니다. 감사합니다.

**Comment by relaxedbrownie** [comment]
그렇군요. 답변 감사합니다.

**Comment by piquark6046** [comment]
@relaxedbrownie 닫아도 될까요?

**Comment by relaxedbrownie** [comment]
넵
