### ISSUE TITLE
AD: economist.co.kr

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#747]
### URL

https://economist.co.kr/article/view/ecn202306210016

### FILTERS

listkr 
adguard base
adguard mobile

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

광고제거 부탁드립니다 감사합니다

![image](https://github.com/List-KR/List-KR/assets/15683789/46a99bda-9e67-45f7-83eb-919be7c57e90)

![image](https://github.com/List-KR/List-KR/assets/15683789/305e117a-5b79-467a-9df9-8b21f8c1ec96)

**Comment by piquark6046** [comment]
필터가 맛 간 것 같습니다.
한번 활성화된 모든 필터를 비활성화하시고 변경 사항 적용이 완료되면 다시 활성화해보시겠어요?

**Comment by swbaek81** [comment]
여러번 필터를 재기동해봐도 이 사이트만 광고가 계속 나와요 . 아이폰에서 한번 확인해주세요

**Comment by piquark6046** [comment]
애드쉴드가 설치되어 있네요.
App store에서 [userscripts](https://apps.apple.com/kr/app/userscripts/id1463298887)를 설치하시고 이 유저스크립트 관리자에 [microShield](https://github.com/List-KR/microShield/)를 설치해주세요.

**Comment by swbaek81** [comment]
마이크로쉴드 후에도 광고가 남아서 제거 부탁합니다
![image](https://github.com/List-KR/List-KR/assets/15683789/23be1b05-7a6e-4aed-b226-b94c390a0dcf)

**Comment by swbaek81** [comment]
이 부분도 광고 남네요
https://economist.co.kr/

![image](https://github.com/List-KR/List-KR/assets/15683789/a42b5af2-7ada-489e-bc78-fac0c340682c)

**Comment by piquark6046** [comment]
수정했습니다.
