### ISSUE TITLE
youtube 영상이 무한로딩됩니다.

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#749]
https://github.com/List-KR/List-KR 
를 adguard에서 해제하니 정상적으로 유투브 영상이 보이는데요.
설정을 해두고 새로고침하면 유투브가 차단이 되는것 같습니다.
1주전?까지는 정상적으로 되었었는데 최근에 갑자기 이러네요..

**Comment by piquark6046** [comment]
정확히 무슨 AdGuard 제품이신가요? 브라우저는 무엇인가요?
List-KR 필터에는 그러한 차단에 관련된 규칙이 없습니다.

**Comment by ghost** [comment]
AdGuard Home 제품이고  크롬, 파이어폭스 두개 테스트 해봤는데 둘다 동일한 증상입니다.. 혹시 몰라서 방금 다시 해봐도 동일한 이슈군요..
혹시 의심가는 부분이 있으실까요..?

**Comment by piquark6046** [comment]
AdGuard Home 설정에서 YouTube 웹 사이트가 차단되게끔 설정되어 있는지 확인해주세요.
