### ISSUE TITLE
IC: naver app

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#754]
### URL

https://m.search.naver.com/search.naver?query=%EB%8B%A5%ED%84%B0%ED%94%BC%EC%97%98&where=m&sm=mob_sly.hst&acr=3

### FILTERS

listkr dns
listkr

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

네이버 어플에서 특정 사이트 검색하여 클릭시 광고로 인지하고 listkr dns 에서 차단이 되는데 혹시 해결이 가능한지 문의 드립니다

![IMG_2691](https://github.com/List-KR/List-KR/assets/15683789/0ecfbeac-7c00-453f-9176-f5177226ae68)

![IMG_2692](https://github.com/List-KR/List-KR/assets/15683789/a17923b1-fbe9-44c0-a49f-c0d6a480bec8)

**Comment by piquark6046** [comment]
그 요소는 광고이라서 해당 링크에는 `adcr.naver.com`이라는 네이버의 광고 클릭 검증용 도메인이 사용됩니다.
Safari에서 검색하시거나 해당 광고 링크가 작동되게 원하시면 아래 허용 규칙을 DNS 필터링에 추가해주세요:
```adblock
@@||adcr.naver.com^
```

**Comment by swbaek81** [comment]
해결되었습니다 감사합니다
