### ISSUE TITLE
네이버 사전 광고

### ISSUE THREAD

**Issue by dragonlee64** [List-KR/List-KR#755]
### URL

네이버 사전 앱

### FILTERS

dns.adguard.com

### Browser

(Other)

### Operating System

Android

### Ad-Blocker

AdGuard DNS

### Comment

adguard dns 주소를 프라이빗 DNS 란에 입력하여 네이버 사전 어플의 광고를 차단하며 사용하고 있었는데, 어제부터 갑자기 광고가 뜨기 시작합니다. 인터넷에 검색해보니 저뿐만이 아니라 많은 사람들이 네이버 카페 등 네이버 전반적인 서비스의 광고 차단이 안 된다고 합니다. 네이버 측에서 광고 url을 우회하여 기존 필터를 무력화한 것으로 추정됩니다. 해결 부탁드립니다.

**Comment by piquark6046** [comment]
AdGuard for Android나 List-KR DNS 필터가 추가된 AdGuard for iOS에서는 잘 작동한다고 하나요?

**Comment by piquark6046** [comment]
수정했습니다.

**Comment by dragonlee64** [comment]
@piquark6046 아직도 여전히 광고가 뜹니다. 확인해보니 네이버 사전 내의 광고 url 이 https://g.tivan.naver.com/gfa/~~~~~~~~~~~ 이런 형식으로 되어 있습니다.

**Comment by piquark6046** [comment]
![image](https://github.com/List-KR/List-KR/assets/98787049/351a86c3-d4db-4898-b31f-63b38ffe820a)

확인에 감사드립니다만, AdGuard 공용 DNS 서버를 사용하시면, `tivan.naver.com`가 차단되어 안 표시될 땐데요.

**Comment by dragonlee64** [comment]
@piquark6046 감사합니다, 해결되었습니다.
