### ISSUE TITLE
AB: tenasia.hankyung.com

### ISSUE THREAD

**Issue by kwon0408** [List-KR/List-KR#758]
### URL

한경 텐아시아( https://tenasia.hankyung.com )에 등록된 모든 기사 페이지

### FILTERS

* only-stackoverflow
* AdGuard 베이스 필터
* AdGuard 추적 보호 필터
* AdGuard 소셜미디어 필터
* AdGuard 방해요소 필터
* ListKR

### Browser

Google Chrome

### Operating System

Microsoft Windows 10, Android

### Ad-Blocker

AdGuard for Windows, AdGuard for Android

### Comment

구글 광고를 포함한 `<span>`이 (AdGuard에 의해서든 개발자 도구를 사용해서든) 삭제되는 즉시 특정 스크립트에 의해 재생성됩니다.

광고는 `https://07c225f3.online`에 있는 페이지를 해당 `<span>` 안에 `<iframe>`으로 넣은 형태로 존재하며, 광고 페이지의 주소를 그대로 새 탭에 띄우면 '이 페이지에는 [Ad-Shield](https://www.ad-shield.io/)가 적용되어 있다'는 메시지만 `display: none`인 상태로 존재하도록 변경됩니다.

**Comment by piquark6046** [comment]
[microShield](https://github.com/List-KR/microShield) 유저스크립트를 설치하시면 해결 가능합니다.
지금 당장 해결을 원하시면, 아래 URL를 사용해주세요:
https://github.com/List-KR/microShield/raw/main/microShield.user.js
