### ISSUE TITLE
IC: auction.co.kr

### ISSUE THREAD

**Issue by dofuuz** [List-KR/List-KR#763]
### URL

http://itempage3.auction.co.kr/DetailView.aspx?itemno=D486258069

### FILTERS

List-KR

### Browser

Mozilla Firefox

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Comment

상품 페이지에서 스크롤 내렸을 때, 우측에 표시되는 상품옵션 리스트가 깨집니다.

```
itempage3.auction.co.kr##div[class^="ad_"]
```
위 필터를 해제하면 정상 표시됩니다.

![image](https://github.com/List-KR/List-KR/assets/8174871/e14a68ef-b328-49ea-845c-f986e631962f)
↑ 정상 표시

![image](https://github.com/List-KR/List-KR/assets/8174871/c5c7297a-567d-4d56-ac08-fed302037cc3)
↑ 우측 상품옵션 깨짐

**Comment by piquark6046** [comment]
@dofuuz 

전에는 안 그랬었나요?

**Comment by dofuuz** [comment]
@piquark6046 언제부터 그랬는지는 모르겠습니다.
