### ISSUE TITLE
AD: m.ruliweb.com

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#765]
### URL

https://m.ruliweb.com/community/board/300143/read/62510447

### FILTERS

listkr
listkr dns

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

안녕하세요 노란색부분 제거하려면 사용자 규칙 어떻게 추가하면 되나요?

![IMG_2766](https://github.com/List-KR/List-KR/assets/15683789/58d94476-8ce4-4c52-8d25-760649cfae40)

**Comment by piquark6046** [comment]
AdGuard for iOS에서 보호 탭 -> 고급 보호가 켜져있나요?

**Comment by swbaek81** [comment]
고급보호 off 상태 입니다

**Comment by piquark6046** [comment]
on으로 변경해보시고 규칙 변환이 완료된 뒤에 새로고침해보시겠어요?

**Comment by swbaek81** [comment]
네 그런데 그래도 사용자 규칙으로 없애려고 합니다

![image](https://github.com/List-KR/List-KR/assets/15683789/f7bf894e-85b3-4819-a027-0b6349650916)

**Comment by piquark6046** [comment]
```adblock
m.ruliweb.com##.fixed_ad_wrapper
```

위 규칙을 사용해보세요.

**Comment by swbaek81** [comment]
완료되었습니다 감사합니다
