### ISSUE TITLE
AD: 당근마켓 app

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#766]
### URL

https://apps.apple.com/kr/app/%EB%8B%B9%EA%B7%BC%EB%A7%88%EC%BC%93/id1018769995

### FILTERS

listkr
listkr dns

### Browser

(Other)

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

아이폰 당근마켓 어플에 광고도 제거 가능한지 문의 드립니다. 어플내에서 상품검색을 하면 “동네가게” 광고가 한바닥 가득 나옵니다. 동네가게 광고 제거 가능한가요?

<details><summary>스크린샷</summary>

![IMG_2769](https://github.com/List-KR/List-KR/assets/15683789/79529693-0bb9-4697-a309-680706133271)
![IMG_2771](https://github.com/List-KR/List-KR/assets/15683789/2022300f-0ee9-40de-b6ae-980172285a04)
![IMG_2773](https://github.com/List-KR/List-KR/assets/15683789/c3f31dc5-0aa5-4838-9590-2d719f8171c2)

</details>

**Comment by piquark6046** [comment]
동네가게 자체가 광고라는 말씀이신가요?
아니면 동네가게에 있는 몇 개가 광고라는 말씀이신가요?

**Comment by swbaek81** [comment]
동네가게 자체가 광고 같아요.  제 생각엔
동네가게 모두 통째로 제거해도 될거라고 생각이 됩니다. 
동네가게 밑에 실제 검색 결과가 나옵니다

**Comment by piquark6046** [comment]
제 생각은 다릅니다.
동네가게는 당근 마켓 (당근 서비스)의 서비스 중 하나이고, 여러 피드에 광고가 삽입될 수 있다고 나옵니다:
- https://www.daangn.com/wv/faqs/155

**Comment by swbaek81** [comment]
상품검색을 하면 동네가게가 나오고 밑에 중고거래 가 나와요.   유니콘 프로 에서는 동네가게가 광고처리 되었던 걸로 기억 합니다. 당근마켓 사용목적이 중고거래 인 만큼 동네가게는 광고 아닐지 생각해봅니다. 중고거래 밑에는 당근알바도 나오네요;;
 
동네가게 - 중고거래 - 당근알바

이런 순서로 나오는데 중고거래 외에는 불필요해 보이긴 해요

<details><summary>스크린샷</summary>

![IMG_2774](https://github.com/List-KR/List-KR/assets/15683789/a20d3708-340e-473b-8a81-5118bcefed22)

</details>

**Comment by swbaek81** [comment]
혹시 사용자 규칙으로 광고처리 가능하면 규칙 부탁드려요

**Comment by piquark6046** [comment]
유니콘 프로는 Android 에서 사용하시나요? 아니면, iOS에서 사용하셨었나요?

**Comment by swbaek81** [comment]
아이폰 에서 유니콘 프로 사용했었어요

**Comment by piquark6046** [comment]
아직 유니콘 프로 라이선스를 가지고 계신가요? 지금 제 Android 에서는 당근마켓이 오류가 뜨지 않으면서 광고를 차단할 수 방법이 보이지 않는 것 같습니다.

**Comment by piquark6046** [comment]
현재까지 의심가는 도메인입니다.

```adblock
||dglgdjh8cfwox.cloudfront.net^
||d1unjqcospf8gs.cloudfront.net^
```

**Comment by swbaek81** [comment]
지금은 유니콘 프로 라이선스가 없어서 확인할 수가 없네요 

어제 까지 사용하고 환불했습니다. 당근마켓 이용하면서 "동네가게" 본적이 없는걸 보면 유니콘프로 에선 차단이 됐던게 맞을거 같네요

유니콘 프로 비교해서 DNS가 부족해요

아이폰 유니콘프로 DNS 장점: 당근마켓, Nplayer, SpoTV 3개 어플에 광고 차단 됩니다. 

  당근마켓 : 동네가게 없음
  Nplayer lite : 영상 재생 또는 종료시 창( =5초 딜레이) 없이 시청 가능
  SpoTV now : 스포츠 하이라이트 시청시 광고 없음 

애드가드는 위에 3개가 아쉽네요

**Comment by piquark6046** [comment]
유니콘 프로 라이선스는 있으니까 나중에 제가 직접 다시 해볼께요. (일일 인증 횟수 초과)
나머지도 나중에 확인해볼께요.

**Comment by swbaek81** [comment]
||dglgdjh8cfwox.cloudfront.net^
||d1unjqcospf8gs.cloudfront.net^

DNS 차단목록에 추가 해봤는데 안되네요 

네, 한국 어플리케이션도 처리해주시면 좋겠네요

**Comment by piquark6046** [comment]
다른 문제는 없으시나요?

**Comment by swbaek81** [comment]
위에 3개 어플외에는 다른문제는 없었습니다. 혹시 또 아쉬운 점이 나오면 제보할게요

**Comment by piquark6046** [comment]
유니콘 프로의 DNS 필터링 (VPN 아이콘 있는 풀 터널링와 부분 터널링)이 당근마켓의 광고에 대한 차단은 안되는 것 같습니다.

<details><summary>스크린샷</summary>

![IMG_0034](https://github.com/List-KR/List-KR/assets/98787049/764f3fc0-7df3-46f7-8056-9c8770868ce9)

</details>

**Comment by piquark6046** [comment]
Nplayer lite 문제는 해당 도메인들이 AdGuard 모바일 필터와 베이스 필터에 있지만 List-KR 필터에 없어서 발생하는 문제네요. 곧 추가됩니다.

**Comment by piquark6046** [comment]
SpoTV now 문제는 List-KR 필터, AdGuard 필터에 없던 도메인(`stream.spongead.com`)이 추가되어야겠군요.
곧 추가됩니다.

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/766#issuecomment-1667590178
다른 영역을 테스트하시길 원하시나요?

**Comment by swbaek81** [comment]
스포티비 나우는 ok 되었어요

하지만 , nplayer lite는 dns 필터링 차단목록에 3개 추가해도 아래창은 사라지질 않습니다 . 유니콘 프로는 아래창이 안나오거든요 

||cdn-adn-*.rayjump.com^ 
||net.rayjump.com^ 
||vungle.com^

<details><summary>스크린샷</summary>

![IMG_2777](https://github.com/List-KR/List-KR/assets/15683789/b5f489e4-8b06-4750-8838-a88c017afc0b)

</details>

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/766#issuecomment-1667837375

nPlayer Lite는 유니콘 프로에서 그 구매 요청 팝업이 안 뜨는 것은 말씀 하시기 전에 알고 있었습니다.
DNS 필터링 리스트가 있는 상태에서 DNS 필터링 차단목록에 추가하면 이상한 버그가 생겨서 임시적으로 리스트를 해제하시고 아래 목록으로 다시 해보시겠어요? (검증하게 앱 삭제 후 재설치할 예정)
```adblock
||cdn-adn-https-new.rayjump.com^
||cdn-adn-https.rayjump.com^
||net.rayjump.com^
||vungle.com^
||pagead2.googlesyndication.com^
```

플레이 도중에는 광고가 나오지만 그 팝업은 안 뜹니다. (테스트 목적)

**Comment by swbaek81** [comment]
여전히 플레이 시작과 종료시에 5초 창이 나오네요

아래 dns 차단목록 on 상태 , dns 허용목록 off 

상태인데 
여전히 창은 나옵니다

<details><summary>스크린샷</summary>


![IMG_2779](https://github.com/List-KR/List-KR/assets/15683789/48fc384f-b98d-41fc-84ff-ffaf98cf36ba)
![IMG_2778](https://github.com/List-KR/List-KR/assets/15683789/f966cdef-8396-45cc-9e0f-e57e1060d9b2)
![IMG_2777](https://github.com/List-KR/List-KR/assets/15683789/e009ff74-320a-491d-ba73-94aee2f79e14)


</details>

**Comment by piquark6046** [comment]
제 의미는 List-KR DNS filter와 AdGuard DNS 필터 같은 DNS 필터들을 끄고  DNS 필터링 차단목록에 추가해달라는 의미였습니다.

**Comment by swbaek81** [comment]
> 제 의미는 List-KR DNS filter와 AdGuard DNS 필터 같은 DNS 필터들을 끄고 DNS 필터링 차단목록에 추가해달라는 의미였습니다.

네 아래 처럼 해보니까 5초딜레이 창은 안뜨는데요

대신에 광고가 나오긴 해요.

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/766#issuecomment-1667876394

버그가 맞나봅니다. ~~왜 이런 버그가 나지~~
https://github.com/List-KR/List-KR/commit/29d7127e474d5aa6bdaf1df2130e7082fc79ff56 업데이트는 했으니 아래 URL을 사용하시면 1시간 이내에 업데이트를 수신 하실 수 있습니다:
https://github.com/AdguardTeam/HostlistsRegistry/raw/main/filters/regional/filter_25_KOR_List-KR/filter.txt
기존에 알려진 URL은 12시간 이내에 가능합니다.

**Comment by swbaek81** [comment]
결국에 유니콘프로 처럼 되려면, 광고도 안나오고 딜레이 창도 안나와야 하는데. 그게 안되서 불편합니다. 솔직히 nplayer lite에 대해선 유니콘 프로가 부럽긴 하네요

**Comment by piquark6046** [comment]
오해가 있는 것 같네요. 제가 말한 버그는 DNS 필터링 리스트가 있는 상태에서 DNS 필터링 차단목록에 추가하면 발생하는 버그입니다. DNS 필터만 사용하시면 문제가 없습니다.
따라서, 유니콘 프로처럼 광고도 안나오고 딜레이 창도 안 나올겁니다. 단지, 필터 개발자와 디버깅하는 유저가 힘들어지죠.

**Comment by swbaek81** [comment]
list dns On
DNS 필터링 차단목록 0개 off
DNS 필터링 허용목록 5개 On 

지금 제가 이상태 인데요 

그러면 1시간후에 list dns 필터 업데이트 받으면 OK될까요?

**Comment by piquark6046** [comment]
네네. 아래 URL로 구독하셨다면 가능합니다:
https://github.com/AdguardTeam/HostlistsRegistry/raw/main/filters/regional/filter_25_KOR_List-KR/filter.txt

그래도 문제가 있으면 제가 해볼께요.

**Comment by swbaek81** [comment]
해당 URL로 구독해서 (315개) 해봤는데요, 재생 시작 종료 때 창은 계속 나와요 해결이 안되네요

**Comment by piquark6046** [comment]
@swbaek81 https://meeco.kr/mini/37476007 
nPlayer가 곧 서비스 종료한다는 말이 있네요. 이주하실 예정이시면, 전 VLC 추천합니다.

**Comment by swbaek81** [comment]
VLC도 이미 병행해서 사용중입니다. 엔플레이어 라이트가 UI나 편의성에서 비교적 좋아서 주로 씁니다. 유니콘 프로와 비교해서 아쉬운 부분입니다

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/commit/586d7009926ab251e4558a8318f0c7a9a583ba47
수정했습니댜. 제가 언급했던 버그는 존재하지 않는 것 같으며, 그냥 안티-애드블록 비슷한 매커니즘을 가지고 있던 것 같습니다.

**Comment by swbaek81** [comment]
OK 되었습니다. 광고가 사라져서 너무 좋습니다. 감사합니다
