### ISSUE TITLE
IC: auction.co.kr

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#768]
### URL

https://www.auction.co.kr/

### FILTERS

listkr

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

옥션 첫화면이 차단되어 상품 정보를 볼수 없습니다.

차단되지 않도록 해야 할거 같습니다.

![image](https://github.com/List-KR/List-KR/assets/15683789/e21ecb40-79a6-486a-8f59-75fd02b09830)

**Comment by piquark6046** [comment]
실명이 나와있습니다. 블러해서 수정해드릴까요?

**Comment by piquark6046** [comment]
실명이 나온 그 사진을 GitHub 서버에서 삭제하시라면, 아래 URL로 방문하셔서 그 이미지의 URL와 함께 제출해주세요:
https://support.github.com/contact?flow=asset_removal&subject=Remove%20image&tags=rr-remove-data

**Comment by swbaek81** [comment]
https://github.com/List-KR/List-KR/assets/15683789/dfa0ee0e-a0c7-432b-85e2-a2b6b7d226ca

이미지 URL좀 알려주실수 있나요? 이미지 URL이 틀렸다고 나와서 진행이 안되네요

**Comment by piquark6046** [comment]
그 GitHub 가상 에이전트 말고 실제 GitHub 스테프에게 가는 티켓으로 해보시겠어요?
그거 말고는 모르겠습니다.
URL 없이는 접근하기 어려우니, 티켓을 생성하시고 위 코멘트와 수정 기록을 삭제하시는 것은 어떨까요?

**Comment by piquark6046** [comment]
![Screenshot from 2023-08-05 19-00-26](https://github.com/List-KR/List-KR/assets/98787049/1a9d2d64-f115-4950-a898-b211b33a42a6)

https://github.com/List-KR/List-KR/issues/642

그 요소가 광고 서버에서 로드되고 형식도 다른 광고 요청하고 차이가 없어보입니다.

**Comment by swbaek81** [comment]
네 알겠습니다. 닫아주세요
