### ISSUE TITLE
aagag.com

### ISSUE THREAD

**Issue by piquark6046** [List-KR/List-KR#769]
https://github.com/List-KR/List-KR/discussions/764#discussioncomment-6670540

**Comment by piquark6046** [comment]
이번 안티-애드블록 스크립트는 AdGuard와 uBlock Origin의 scriptlet에 업데이트를 요구하게끔 변경되었습니다.
AdGuard의 리다이렉트 필터가 사용되면, 스크립트가 무력화됩니다.

This time, the anti-adblock script has been modified to require updates related to the scriptlets of AdGuard and uBlock Origin.
If a redirection filter of AdGuard is used, the script will be neutralized.

**Comment by piquark6046** [comment]
AdGuard and uBO
```adblock
aagag.com##+js(no-xhr-if, pagead2.googlesyndication.com/pagead/js/adsbygoogle.js)
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xmlhttprequest,redirect=googlesyndication_adsbygoogle.js
```

```adblock
aagag.com#%#//scriptlet('prevent-xhr', 'pagead2.googlesyndication.com/pagead/js/adsbygoogle.js', 'length:101-200')
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xmlhttprequest,redirect=googlesyndication-adsbygoogle
```

**Comment by zlsmsdnjsqls** [comment]
위에것도 해당 사이트에서 안먹히는데 이것도 또 막힌건가요?

**Comment by piquark6046** [comment]
저건 문제 해결을 위한 규칙이 아닙니다.

**Comment by zlsmsdnjsqls** [comment]
아 그랬군요... 그럼 지금은 해결방법이 없는건가요?
설정 - 필터 들어가서 하나씩 다 눌러봐도 전혀 안되네요...

**Comment by piquark6046** [comment]
아뇨. 해결 가능합니다.

**Comment by zlsmsdnjsqls** [comment]
![qweqwe](https://github.com/List-KR/List-KR/assets/108527954/c746452f-8ea6-4c07-a787-61b9012b831a)

각 파일로 다운받고, 가져오기 했습니다.
이렇게 했는데 전혀 안되는데, 이렇게 쓰는게 아닌가요?
한시간쯤 이런식으로 별짓 다해봤는데 안되서 다시 여쭤봅니다.

개발자가 아닌데 깃허브에서 문의해야 하는게 참 괴롭네요ㅠ
뭘 알려줘도 어떻게 써야 하는지 자체를 모르겠으니...

**Comment by piquark6046** [comment]
AdGuard에 기본 포함된 List-KR 필터를 사용하시면, 최대 4시간 뒤에 수동 업데이트를 하실 수 있습니다.
만약 uBO를 사용하시거나 AdGuard 커스텀 필터로 List-KR 필터를 추가하셨다면, 아래 URL로 기존에 활성화하시던 List-KR 필터 대신에 사용하실 수 있습니다:
AdGuard: https://github.com/List-KR/List-KR/raw/master/filter-AdGuard.txt
uBO: https://github.com/List-KR/List-KR/raw/master/filter-uBlockOrigin.txt

GitHub가 별로시면, 이메일로 하시는 방법도 있습니다.
https://github.com/List-KR/List-KR/wiki/contacts

**Comment by zlsmsdnjsqls** [comment]
![asdasd](https://github.com/List-KR/List-KR/assets/108527954/4fd5b2e6-e046-4939-9436-6a537ee60455)

이렇게 하는거 맞나요?  결국 같게 한거 같은데...
이후 `변경사항 저장` 도 물론 눌렀습니다.

하지만 여전히 막혀있습니다.

https://aagag.com/issue/?idx=1275184

선생님은 위의 링크의 중하단 쯤에 
`광고 차단을 해제해주세요` 가 안나오시나요?

저는 여전히 나오고 있습니다.
제가 잘못 설정한건가요?

**Comment by piquark6046** [comment]
`지역, 언어`에 있는 `kr: List-KR`도 꺼주세요.

**Comment by piquark6046** [comment]
지금 uBlock Origin으로 테스트했는데 `지역, 언어`에 있는 `kr: List-KR`도 잘 해결줍니다.
사용자 지정에 있는 필터 리스트를 전부 삭제해보시고 `모든 캐시 제거` 버튼을 누르신 뒤에 `지금 업데이트` 버튼을 눌러주세요.

**Comment by zlsmsdnjsqls** [comment]
![ewqewqewq](https://github.com/List-KR/List-KR/assets/108527954/019b4e04-0fba-4828-b07e-cba9718299c5)

선생님 이게 제 모든 옵션 상황 입니다.
전부 삭제했고, 캐시 제거 - 업데이트 한 후의 모습입니다.
뭔가 잘못된게 있나요?

**Comment by piquark6046** [comment]
`kr: List-KR`를 다시 활성화해보시고 `지금 업데이트` 버튼을 눌러주세요.

**Comment by piquark6046** [comment]
@taeklims 필터 업데이트를 하셨나요?

https://github.com/List-KR/List-KR/discussions/764#discussioncomment-6680056

**Comment by zlsmsdnjsqls** [comment]
![wweeeewwww](https://github.com/List-KR/List-KR/assets/108527954/49088d2c-5ab3-46f2-99b5-a3ef33882b52)

위의 옵션 상황에서, 
동일 페이지에서 
유블럭 오리진을 켰을때와 껐을때의 차이 입니다.

선생님은 오리진을 켰을때,
광고 차단 해 달라며 저렇게 리플이 안나오는 현상이 없으시다면 
제 설정의 문제일텐데...

어제오늘 5 시간 이상 여기저기 헤메다니며 별짓 다해봤고,
결국 여기까지 왔는데, 다른 분들은 이상 없다면 그냥 포기해야하나 싶어 답답합니다ㅠㅠ
긴 질문에 무척 죄송합니다.

**Comment by zlsmsdnjsqls** [comment]
선생님 지금 갑자기 해결됐습니다!!
너무 답답하고 화나서 새로고침을 한 30 번쯤 연타하고 
검색 좀 하다 다시 가서 새로고침 해보니
갑자기 멀쩡히 나옵니다. 
정말 감사합니다!!! 선생님 덕분입니다.

**Comment by piquark6046** [comment]
알겠습니다. List-KR 필터 리스트에 대한 업데이트가 아닌 scriptlet에 대한 업데이트가 필요해서 열어두겠습니다.

**Comment by taeklims** [comment]
> 

네 애드가드에서 업데이트 했습니다... 안드로이드 입니다.

**Comment by piquark6046** [comment]
@taeklims 아직도 문제를 겪고 계신가요?

**Comment by taeklims** [comment]
> @taeklims 아직도 문제를 겪고 계신가요?

네 안드로이드 애드가드 사용중일땐 여전히 동일증상이네요....🥺

**Comment by piquark6046** [comment]
DNS 모듈에서 DNS 필터를 활성화하셨나요?
필터 업데이트 하셨나요?

**Comment by taeklims** [comment]
> DNS 모듈에서 DNS 필터를 활성화하셨나요? 필터 업데이트 하셨나요?

네 DNS 필터 활성화, 필터업데이트 전부 한 상태에서 동일합니다.

**Comment by piquark6046** [comment]
로우 레벨 설정을 변경해보신 적이 있으시거나 카카오톡 앱에 대한 HTTPS 필터링 또는 사용자 규칙을 설정하신 적이 있으시나요?

**Comment by piquark6046** [comment]
@taeklims 사용하시는 필터들을 알려주시고 HTTPS 필터링을 비활성화하셨나요?

**Comment by taeklims** [comment]
> @taeklims 사용하시는 필터들을 알려주시고 HTTPS 필터링을 비활성화하셨나요?

<details><summary>스크린샷</summary>

![Screenshot_20230810_172730_AdGuard](https://github.com/List-KR/List-KR/assets/141406383/6be1cb82-c2a7-4676-a670-f205ef21a31c)
![Screenshot_20230810_172828_AdGuard](https://github.com/List-KR/List-KR/assets/141406383/4cd9378c-5e8c-4268-9a3f-51f07bbb8aa8)
![Screenshot_20230810_172852_AdGuard](https://github.com/List-KR/List-KR/assets/141406383/c20d094c-1efc-4254-89e1-e5cda5772cd1)
![Screenshot_20230810_172900_AdGuard](https://github.com/List-KR/List-KR/assets/141406383/d9d48d99-67c7-487a-9c6b-e41093a78ddc)
![Screenshot_20230810_172916_AdGuard](https://github.com/List-KR/List-KR/assets/141406383/b45e2cfe-5757-47c7-adc3-ffa70b10b956)
![Screenshot_20230810_172936_AdGuard](https://github.com/List-KR/List-KR/assets/141406383/8419f066-9f3a-44a3-85af-d99e01f31d7b)
![Screenshot_20230810_172957_AdGuard](https://github.com/List-KR/List-KR/assets/141406383/69bf8d4b-5082-4806-bc35-db9edd470401)
![Screenshot_20230810_173034_AdGuard](https://github.com/List-KR/List-KR/assets/141406383/f27f074f-d65b-454c-bb08-9a7b863ca3bb)
![Screenshot_20230810_173115_AdGuard](https://github.com/List-KR/List-KR/assets/141406383/2c26d19a-595d-4fcf-a266-9285fa404fc1)

</details> 

이렇게 적용중입니당.

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/769#issuecomment-1672797712

Android에서는 iOS와는 달리 DNS 필터가 없어도 앱의 DNS 요청은 필터링되므로, 모든 DNS 필터를 비활성화해주세요.
AdGuard 필터와 List-KR 필터에는 안티-애드블록에 대해 대응할 수 있는 규칙이 있으므로, Adblock Removing Removal List가 필요 없습니다.

무슨 브라우저에서 문제가 발생하시나요?

**Comment by taeklims** [comment]
말씀하신대로 dns 필터 및 Adblock Removing Removal List 제외 후 애드가드 다시 실행하니 감쪽같이 잘 됩니다. 감사합니다 👍👍👍

**Comment by yoropico** [comment]
iOS에서는 조금 더 기다려야 할까요?

**Comment by piquark6046** [comment]
@yoropico 현재 `$redirect` 문법이 Apple 정책으로 제한되어서 사용할 수 없어 iOS에서는 DNS를 끄셔야 표시됩니다. 그런데, 이러면 앱에서 광고가 보이게 됩니다.
나중에 위에 링크된 scriptlet 업데이트가 해결되고 AdGuard for iOS에 포함되면 DNS 설정 변경 없이 가능합니다.

**Comment by taeklims** [comment]
9월 7일 현재 또 동일하게 막혔네요....

**Comment by piquark6046** [comment]
@taeklims 
업데이트했습니다.

**Comment by swbaek81** [comment]
아이폰 인데요 댓글 못 보게 막힌거 같습니다
listkr 최신 업데이트 했어요

https://aagag.com/issue/?idx=1290965

![image](https://github.com/List-KR/List-KR/assets/15683789/06f3f3a0-6eb3-4b2b-9220-920b8d6a1522)

**Comment by piquark6046** [comment]
@swbaek81 최근에 iOS 17로 업데이트하셨나요? 그렇다면, AdGuard가 Safari 확장 프로그램(Safari 주소 막대에 있는 가가 버튼)에서 꺼져 있는지 확인해주세요.
경우에 따라 쿠키, 사이트 데이터와 캐시를 삭제해야 할 수 있습니다.

**Comment by swbaek81** [comment]
네 ios17로 업데이트 했어요. 얘기주신부분 다 확인했는데 그래도 안되네요

**Comment by piquark6046** [comment]
List-KR DNS 필터가 `pagead2.googlesyndication.com` 도메인에 대한 예외 없이 켜져있나요?

**Comment by swbaek81** [comment]
디엔에스 허용목록에 

pagead2.googlesyndication.com

이게 On이 어도 NG 구요, 

Off 하고도 NG 입니다

**Comment by piquark6046** [comment]
List-KR 필터 리스트 말고 다른 필터 리스트가 켜져 있나요?
Safari 브라우저를 완전히 닫고 다시 해보셨나요?
iOS 17로 업데이트하신 후에 발생하는 이슈인가요?

**Comment by swbaek81** [comment]
사파리 필터, 디엔에스 필터 모두 listkr만 On상태에요. 기본필터조차 Off 상태 입니다. 사파리 앱닫기 후에도 NG네요. IOs17 이후인지는 정확히는 모르겠어요

**Comment by piquark6046** [comment]
List-KR 필터 리스트를 끈 뒤에 다시 켜보시겠어요? 필터 리스트 업데이트도 해주세요.

**Comment by swbaek81** [comment]
다 해봣는데, 

listkr dns 필터 Off 하면 OK입니다

listkr dns 필터 On시 ng 입니다

**Comment by piquark6046** [comment]
`pagead2.googlesyndication.com` 를 DNS 허용목록에 넣어도 문제가 발생하시나요?

**Comment by swbaek81** [comment]
네 허용목록에 애초에 있었는데도 ng에요

**Comment by piquark6046** [comment]
https://youtu.be/9LN9jxj0Hxw
제 환경에서는 재구현이 그래도 안됩니다.

**Comment by swbaek81** [comment]
저도 애드가드 로그에는
pagead2.googlesyndication.com
이게 "허용" 으로 표기됨에도 불구하고 NG 네요 

IOS17 인거 말곤 차이가 없는거 같습니다. 잘 모르겠네요

**Comment by piquark6046** [comment]
DNS 서버는 어디로 설정되어 있나요?

**Comment by swbaek81** [comment]
adguard DNS로 되어있어요

**Comment by piquark6046** [comment]
일반 서버요? 그럼 논-필터링으로 변경해주세요.

**Comment by swbaek81** [comment]
논-필터링 으로 변경하니까 OK 되었습니다. 

근데 이게 논필터링으로 하니까 

24시간 기준 
애드가드 배터리 소모가 하루에 10프로 이상씩 되더라고요

192.in-addr.arpa 

이게 수시로 발생하는거 같던데요

일단 논필터링으로 아이폰 재부팅 하고 사용해보겠습니다.

**Comment by piquark6046** [comment]
그럼, cloudflare 써보세요.

**Comment by swbaek81** [comment]
cloudflare 요고로 변경하고도 OK 입니다.

일단 이렇게 사용하면 될꺼 같습니다.

**Comment by taeklims** [comment]
> @taeklims 업데이트했습니다.

11월 15일 또 다시 뜨기 시작하네요.

**Comment by taeklims** [comment]
@piquark6046 안드로이드 adguard 및 윈도우 ublock origin 사용 기준 11월 15일 또 다시 뜨기 시작하네요.

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/769#issuecomment-1811954626
수정했습니다.

**Comment by taeklims** [comment]
> [#769 (comment)](https://github.com/List-KR/List-KR/issues/769#issuecomment-1811954626) 수정했습니다.

적용하는데 시간이 걸릴까요~~?
업데이트 했는데 그대로 입니다...

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/769#issuecomment-1812402935
어떤 방식으로 List-KR 필터를 구독하셨나요?

**Comment by taeklims** [comment]
> [#769 (comment)](https://github.com/List-KR/List-KR/issues/769#issuecomment-1812402935) 어떤 방식으로 List-KR 필터를 구독하셨나요?

안드로이드 애드가드 사용자 지정 필터에서
https://cdn.jsdelivr.net/gh/List-KR/List-KR@master/filter-AdGuard.txt
추가 하여 사용중입니다.

**Comment by piquark6046** [comment]
branch로 purge 요청을 넣으면 가끔씩 처리가 되지 않는 오류가 있어서 기능 개선를 요청을 했고 자동화를 위한 [jsdelivr-purge](https://github.com/List-KR/jsdelivr-purge)를 재작성하는 중입니다.

다시 실행했지만, 경우에 따라 일부 규칙들이 최신 상태가 안되는 문제가 발생할 수 있습니다.
https://github.com/List-KR/List-KR/actions/runs/6877029002

**Comment by taeklims** [comment]
또 다시 막힌거 같아요...

**Comment by taeklims** [comment]
> branch로 purge 요청을 넣으면 가끔씩 처리가 되지 않는 오류가 있어서 기능 개선를 요청을 했고 자동화를 위한 [jsdelivr-purge](https://github.com/List-KR/jsdelivr-purge)를 재작성하는 중입니다.
> 
> 다시 실행했지만, 경우에 따라 일부 규칙들이 최신 상태가 안되는 문제가 발생할 수 있습니다. https://github.com/List-KR/List-KR/actions/runs/6877029002

개발자가 이글을 보고 업데이트 바로 하는것인지......

**Comment by piquark6046** [comment]
고쳤습니다.

**Comment by taeklims** [comment]
> 고쳤습니다.

ㅠㅜ 고치시면 또 막네요 이젠 포기해야 되나봐요

**Comment by piquark6046** [comment]
필터를 업데이트해보세요.

**Comment by saioun** [comment]
또 다시 막힌것 같습니다..

**Comment by piquark6046** [comment]
@saioun 필터 리스트를 업데이트하시고 캐시 없이 새로고침( <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>R</kbd> )을 최대 3번 정도 해보세요.

**Comment by taeklims** [comment]
> 고쳤습니다.

안드로이드 애드가드 또 막힌거 같아요...

**Comment by piquark6046** [comment]
AdGuard for Android 프로그램 버그 같은데요.
아마도 QUIC 트레픽을 필터링하지 못하고 있는 것 같습니다.
https://github.com/AdguardTeam/AdguardForWindows/issues/4938

**Comment by piquark6046** [comment]
AdGuard for Android 4.3 안정 채널에서 잘 동작하는 것 같아 닫습니다.

**Comment by yoropico** [comment]
근데 iso에서는 해제 불가능한가요?

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/769#issuecomment-1870833152
@yoropico 
DNS 보호가 켜져있나요?

**Comment by yoropico** [comment]
> [#769 (comment)](https://github.com/List-KR/List-KR/issues/769#issuecomment-1870833152) @yoropico DNS 보호가 켜져있나요?

네.. 현재 adguard 4.5.2 프리미엄 사용하고 있는데 몇달전부터 aagag.com에서는 안되네요.

**Comment by piquark6046** [comment]
아래 규칙을 DNS 허용 목록에 추가해보세요:
```adblock
pagead2.googlesyndication.com
```

다만, 이렇게 되면 브라우저가 아닌 다른 앱에서 Google 광고가 나올 수도 있습니다.
이를 완전히 해결하라면, Apple 정책에서 벗어난 Android로 넘어가시면 DNS 필터링 없이도 앱과 브라우저 별로 차단을 하실 수 있습니다.

**Comment by yoropico** [comment]
> 아래 규칙을 DNS 허용 목록에 추가해보세요:
> 
> ```
> pagead2.googlesyndication.com
> ```
> 
> 다만, 이렇게 되면 브라우저가 아닌 다른 앱에서 Google 광고가 나올 수도 있습니다. 이를 완전히 해결하라면, Apple 정책에서 벗어난 Android로 넘어가시면 DNS 필터링 없이도 앱과 브라우저 별로 차단을 하실 수 있습니다.

적용해 봤는데 동일하게 차단 됩니다 ^^;;;

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/769#issuecomment-1871641921
기존에 추가했던 규칙를 삭제하시고 아래 규칙으로 DNS 허용 목록에 추가해 다시 해보시겠어요? 제가 지금은 집 밖에 있어서 집에 있는 Apple 디바이스에는 접근을 못합니다.
```adblock
@@||pagead2.googlesyndication.com^$important
```

**Comment by yoropico** [comment]
> [#769 (comment)](https://github.com/List-KR/List-KR/issues/769#issuecomment-1871641921) 기존에 추가했던 규칙를 삭제하시고 아래 규칙으로 DNS 허용 목록에 추가해 다시 해보시겠어요? 제가 지금은 집 밖에 있어서 집에 있는 Apple 디바이스에는 접근을 못합니다.
> 
> ```
> @@||pagead2.googlesyndication.com^$important
> ```
동일하게 차단 됩니다 ㅎㅎ.. 제 아이폰이 이상한가 보군요..

**Comment by piquark6046** [comment]
집에 가서 다시 한번 보겠습니다.

**Comment by taeklims** [comment]
> AdGuard for Android 4.3 안정 채널에서 잘 동작하는 것 같아 닫습니다.

애드가드 안드로이드 4.3.199 사용중입니다.
현재 다시 막힌거 같아요...
