### ISSUE TITLE
AB: kyaru.space

### ISSUE THREAD

**Issue by loquenahak** [List-KR/List-KR#770]
### URL

https://kyaru.space/

### FILTERS

Adguard base/mobile/tracking protection/social media/annoyances/list-kr

### Browser

Samsung Internet

### Operating System

Android

### Ad-Blocker

AdGuard Content Blocker

### Comment

![Screenshot_20230811_114626_Samsung Internet](https://github.com/List-KR/List-KR/assets/101969092/2ccf4448-edba-4e31-b948-a47fb2e43eba)

All posts are anti-adblocking.

**Comment by piquark6046** [comment]
@YJethno AdGuard Content Blocker를 사용하시는 이유가 있으시나요?

**Comment by loquenahak** [comment]
별다른 속도 저하 없이 삼성 인터넷 브라우저로 List-KR 필터를 쓸 수 있어서요 :) Adguard DNS 속도 저하 등 문제가 많아 사용하지 않고 있습니다.

**Comment by piquark6046** [comment]
AdGuard DNS 필터 없이 AdGuard for Android에서 앱 광고 차단이 가능합니다.
AdGuard Content Blocker를 사용하시면 반쪽짜리 AdGuard를 사용하시게됩니다.

**Comment by loquenahak** [comment]
말씀주시자마자 냉큼 가서 설치해봤습니다. 꽤 괜찮은걸요? 상주 앱이 가져오는 속도 저하도 체감상 크지 않은 것 같고요. 고맙습니다. 한 동안 써보다가 괜찮으면 구독까지 해봐야겠네요.

**Comment by piquark6046** [comment]
https://stacksocial.com/sales/adguard-personal-plan-lifetime-subscription-2-pack
위 URL에서 9기기 평생권을 가끔 3만원에 구입하실 수 있으니 눈팅을 추천드립니다.
기존에 쓰시던 AdGuard Content Blocker는 삭제하시면 됩니다.

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/wiki 여기도 읽어보세요.

**Comment by loquenahak** [comment]
옙. 생각보다 많이 괜찮아서 패밀리 플랜 할인 나오자마자 구입하려고 이미 맘 먹었습니다ㅎㅎ 고맙습니다.
