### ISSUE TITLE
IC: 택배파인더 앱

### ISSUE THREAD

**Issue by relaxedbrownie** [List-KR/List-KR#778]
### URL

https://apps.apple.com/kr/app/%ED%83%9D%EB%B0%B0%ED%8C%8C%EC%9D%B8%EB%8D%94/id449109603

### FILTERS

KOR: List-KR DNS

### Browser

(Other)

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

무한 로딩
![IMG_3781](https://github.com/List-KR/List-KR/assets/126370491/1d784a27-069c-4dde-bfee-acdb34f7550e)
몇 주 전까지 한 번도 안 이랬는데 최근부터 갑자기 이러네요.
우측 상단에 있는 새로 고침 버튼을 누르면 일시적으로 고쳐지지만 매번 새로 고침을 해야 하고, 택배 목록을 이렇게 강제로 불러오면 읽은 걸로 처리가 안 돼서 택배파인더 앱 내 알림방에서 배지(숫자)가 계속 그대로 남아서 지저분해요.

**Comment by relaxedbrownie** [comment]
실수로 사진 첨부를 안 했네요. 수정하려니까 사진 첨부 버튼이 안 보여서 그냥 댓글에 남길게요.
![IMG_6941](https://github.com/List-KR/List-KR/assets/126370491/387e14a0-803d-413d-ae32-97b4b6e73c64)

**Comment by piquark6046** [comment]
광고 도메인(`screen.buzzvil.com`)에 연결되지 못하면, 페이지를 쉽게 보여주지 않나 봅니다.
아래 도메인을 DNS 허용 목록에 추가해서 일시적으로 해제하실 수 있으나 다른 앱에서 광고가 표시될 수 있습니다:
```adblock
screen.buzzvil.com
```
해당 광고 도메인의 홈페이지입니다: https://www.buzzvil.com/

**Comment by relaxedbrownie** [comment]
해결했어요 감사합니다. 닫으셔도 됩니다.

근데 광고 도메인을 특정 앱에서만 허용되도록 하는 방법은 없죠? 같은 도메인이면 무조건 모든 앱에서 다 허용될 수밖에 없는 건가요?

**Comment by piquark6046** [comment]
네. Apple 정책 때문에 유니콘 Pro를 포함해서 어떤 애드블록도 iOS 에서는 특정 앱에서만 허용하는 방법이 없습니다.
Android에서는 가능하고 해당 Android 앱에서는 그 도메인이 DNS 레벨이 아닌 앱별로 차단했을 때는 그런 문제가 없는 것 같습니다.
