### ISSUE TITLE
AD: inven.co.kr

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#780]
### URL

https://m.inven.co.kr/board/webzine/2097/2127726

### FILTERS

adguard base
adguard mobile 
listkr

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

아이폰 광고제거 부탁드립니다 감사합니다

![image](https://github.com/List-KR/List-KR/assets/15683789/bf0607ab-ee28-4f46-9621-2fb1755764e1)

![image](https://github.com/List-KR/List-KR/assets/15683789/557c3398-5d27-4911-adbf-8ef7ae9febe7)

**Comment by piquark6046** [comment]
https://github.com/List-KR/microShield/issues/34 중복됩니다.
