### ISSUE TITLE
AD: ETF Check 어플

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#781]
### URL

https://apps.apple.com/kr/app/etf-check/id1548228110

### FILTERS

listkr dns

### Browser

(Other)

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

아이폰 어플인데요

혹시 광고배너 제거 가능한지 문의 드립니다 감사합니다

![image](https://github.com/List-KR/List-KR/assets/15683789/301ba88e-2e18-443e-b635-c47c45940c52)

![image](https://github.com/List-KR/List-KR/assets/15683789/297fc148-af88-405a-b10c-522e04e034e4)

**Comment by piquark6046** [comment]
<details><summary>스크린샷</summary>

![image](https://github.com/List-KR/List-KR/assets/98787049/3bba3ccc-9ceb-4898-96c1-e9679ce608a6)
![image](https://github.com/List-KR/List-KR/assets/98787049/b827c601-0b45-4684-984f-82a0d25640b1)


</details> 

앱에서는 불가능하지만 웹에서는 가능합니다.
https://www.etfcheck.co.kr/
