### ISSUE TITLE
AB: m.inven.co.kr

### ISSUE THREAD

**Issue by bobblun** [List-KR/List-KR#782]
### URL

https://m.inven.co.kr/board/maple/5974/1

인벤 접속 후 아무 게시글이나 들어간 후 (위 링크도 가능)

약 20~30초가 지나면 안티 애드블록이 작동하며 사이트가 먹통이 되는 현상이 발생

### FILTERS

list-kr
microshield
adguard extra

### Browser

Google Chrome, Samsung Internet

### Operating System

Microsoft Windows 10, Android

### Ad-Blocker

AdGuard for Windows, AdGuard for Android

**Comment by bobblun** [comment]
![Uploading Screenshot_20230827_135355_Samsung Internet.jpg…]()

**Comment by bobblun** [comment]
![Screenshot_20230827_135355_Samsung Internet](https://github.com/List-KR/List-KR/assets/49634687/97abd062-f962-422d-b22b-53422c227cfe)

**Comment by piquark6046** [comment]
https://github.com/List-KR/microShield/issues/34
중복되어 병합됩니다.
