### ISSUE TITLE
AD: 고급유머 어플

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#783]
### URL

https://apps.apple.com/kr/app/%EA%B3%A0%EA%B8%89%EC%9C%A0%EB%A8%B8/id495871144

### FILTERS

listkr dns

### Browser

(Other)

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

아이폰 어플인데요 
광고공백 제거 가능한지 문의 드립니다 감사합니다

![image](https://github.com/List-KR/List-KR/assets/15683789/f33ce8d1-5326-4e89-a57e-83508d856bb5)

**Comment by piquark6046** [comment]
고정된 영역으로 보입니다.

**Comment by piquark6046** [comment]
<details><summary>스크린샷</summary>

![Screenshot from 2023-08-28 19-15-52](https://github.com/List-KR/List-KR/assets/98787049/e0895cb0-1102-4abd-b8f2-2aab4dff3787)

</details> 

그냥 웹 브라우저를 앱처럼 쓸 수 있게 한 웹 뷰 앱으로 보입니다.
