### ISSUE TITLE
IC: kyobobook.co.kr

### ISSUE THREAD

**Issue by relaxedbrownie** [List-KR/List-KR#785]
### URL

https://www.kyobobook.co.kr/

### FILTERS

List-KR

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

List-KR 필터가 활성화된 상태에서 구매하기가 불가능합니다.
아무 책이나 들어가서 구매하기를 눌러 보면 응답이 없습니다.

**Comment by piquark6046** [comment]
AdGuard 추적 보호 필터를 활성화하셨나요?

**Comment by relaxedbrownie** [comment]
아뇨. List-KR에 의해서만 결과가 달라집니다.

**Comment by piquark6046** [comment]
착각이였고 List-KR 필터 문제였습니다. 수정되었습니다.

**Comment by relaxedbrownie** [comment]
감사합니다.
