### ISSUE TITLE
AD: m.sportschosun.com

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#787]
### URL

https://m.sportschosun.com/news.htm?id=202309010100000320029451&ServiceDate=20230831&f_url=safari&stype=o

### FILTERS

adguard base
adguard mobile
listkr

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

하얀색 Bar 제거 부탁드립니다. 감사합니다

![image](https://github.com/List-KR/List-KR/assets/15683789/0978423f-c712-4200-b05f-c148cce8833e)

**Comment by swbaek81** [comment]
아래 검정부분도 제거 부탁드려요

https://m.sportschosun.com/index.htm

![image](https://github.com/List-KR/List-KR/assets/15683789/9a964ab8-6272-4480-8d0a-0b52b0b89c98)

**Comment by swbaek81** [comment]
https://m.sports.chosun.com/

https://m.sports.chosun.com/entertainment/2023-09-02/202309030100009770001166

다시 광고 bar가 보입니다 
수정 부탁드립니다


![image](https://github.com/List-KR/List-KR/assets/15683789/fd92bee3-863d-4142-9a8c-2b8aa8c970a0)

![image](https://github.com/List-KR/List-KR/assets/15683789/e8459198-764f-4eaf-8009-027d7b5792c0)

**Comment by swbaek81** [comment]
아이폰 사파리 광고공백 제거 부탁드립니다 감사합니다

https://m.sports.chosun.com/entertainment/2023-09-22/202309230100174540022486

![image](https://github.com/List-KR/List-KR/assets/15683789/3d8fe179-b95b-4179-9d2a-f05b8edce638)

![image](https://github.com/List-KR/List-KR/assets/15683789/23a1abf1-4260-4c2b-88b7-c3a0f7c8c6ef)


![image](https://github.com/List-KR/List-KR/assets/15683789/6612ef8e-6308-4b10-8125-8dbd794d088d)

**Comment by piquark6046** [comment]
다음에는 새로운 GitHub issue를 생성해주시기 바랍니다.
