### ISSUE TITLE
[AD] 갤럭시 스토어 광고

### ISSUE THREAD

**Issue by joyfuI** [List-KR/List-KR#79]
[https://www.clien.net/service/board/cm_andro/15418121](https://www.clien.net/service/board/cm_andro/15418121)

갤럭시 스토어가 업데이트 된 이후 대문짝만한 광고가 추가되었다고 합니다. 이와 관련해서 위와 같은 글이 올라왔는데 제 폰에선 아직 갤럭시 스토어가 업데이트 되지 않아서 테스트를 못해봤습니다.  
일단 필터에 없는 규칙인 것 같아 제보합니다.

**Comment by piquark6046** [comment]
Can you email me the filtering log of AdGuard?

Maintainers' email address can be founded at [here](https://github.com/List-KR/List-KR/issues/223).

**Comment by joyfuI** [comment]
I'm closing that ad because it's now gone.
