### ISSUE TITLE
AD: band.us

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#790]
### URL

https://band.us/home

### FILTERS

list-kr

### Browser

Mozilla Firefox

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![3](https://github.com/List-KR/List-KR/assets/99063049/c63e35d5-ec52-4b4c-ae45-47cd706243dd)

**Comment by piquark6046** [comment]
AdGuard 쿠키 필터나 AdGuard 방해 요소 필터를 켜주시고 새로고침해보세요.
