### ISSUE TITLE
AB: m.inven.co.kr

### ISSUE THREAD

**Issue by hankju84** [List-KR/List-KR#791]
### URL

https://m.inven.co.kr/

### FILTERS

List-KR
AdGuard 베이스 필터
AdGuard 모바일 광고 필터
AdGuard URL 추적 필터
AdGuard 추적 보호 필터
Legitimate URL Shortener
AdGuard 소셜미디어 필터
AdGuard 팝업 필터
AdGuard 위젯 필터
AdGuard 기타 방해 요소 필터
AdGuard 쿠키 필터
AdGuard 모바일 앱 배너 필터
AdGuard 일본어 필터
AdGuard 중국어 필터

### Browser

Samsung Internet

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment

페이지를 열고 일정 시간 후에 이런 메시지가 뜹니다.
![Screenshot_20230906-123246_삼성_인터넷_1](https://github.com/List-KR/List-KR/assets/73779442/7efb4781-fc24-45e4-8fc0-23609425aef1)

**Comment by piquark6046** [comment]
microShield를 설치하신 후에 저렇게 뜬다는 말씀이신가요?

**Comment by loquenahak** [comment]
저도 동일한 증상입니다. 마이크로실드 스크립트 설치되어 있습니다.

**Comment by hankju84** [comment]
> microShield를 설치하신 후에 저렇게 뜬다는 말씀이신가요?

네 microShield도 설치되어 있습니다.

**Comment by piquark6046** [comment]
지금 당장 해결하셔야 한다면, 아래 사용자 규칙을 임시로 추가해주세요.
```adblock
m.inven.co.kr#%#//scriptlet('abort-current-inline-script', 'eval', 'decodeURIComponent(escape(')
```

microShield 업데이트가 뜨면, 삭제해주세요.

**Comment by swbaek81** [comment]
liskkr
마이크로쉴드
namulink

m.inven.co.kr#%#//scriptlet('abort-current-inline-script', 'eval', 'decodeURIComponent(escape(')

사용자규칙 사용해도 안해도 모두 ng 상황이 발생해요
마이크로쉴드도 최신 입니다


https://m.inven.co.kr/board/webzine/2097/2136912

<details><summary>스크린샷</summary>

![image](https://github.com/List-KR/List-KR/assets/15683789/6bf3a2d2-70e3-498b-8b35-8d8d0919e6bf)


</details>

**Comment by piquark6046** [comment]
@swbaek81 

가끔 발생하나요? 아니면 자주 그러나요?

**Comment by swbaek81** [comment]
그냥 inven 커뮤니티 글 볼때 매번 그래요. 창열리고 바로 발생하는건 아니구 30초 ~60초 후에 발생합니다

**Comment by piquark6046** [comment]
@swbaek81 고쳤습니다. 최신 버전은 `3.7.3`입니다.
