### ISSUE TITLE
AB: OndemandKorea anti adblcok filter

### ISSUE THREAD

**Issue by kpj205** [List-KR/List-KR#792]
### URL

https://www.ondemandkorea.com/

### FILTERS

List KR,MicroShield, Adguard basefilter

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

AdGuard Browser Extension

### Userscript Manager

Violentmonkey

### USERSCRIPT

MicroShield

### Comment

OnDemand ask unblock adblock filter.

**Comment by piquark6046** [comment]
Please attach a screenshot.
