### ISSUE TITLE
IC: List-KR doesn’t work with Brave Browser

### ISSUE THREAD

**Issue by Dr-Sauce** [List-KR/List-KR#795]
### URL

.

### FILTERS

List-KR doesn’t work with Brave Browser’s default ad blocker. (Tested on iOS and Windows)

![9D7633E3-7B21-4EC9-A0D9-AA31EDF16A92](https://github.com/List-KR/List-KR/assets/82555878/718d6638-b7e3-4fef-af27-204af1ad95d6)
![C2C8B1CF-F9AB-440F-90D3-57084BF8341B](https://github.com/List-KR/List-KR/assets/82555878/a278e73a-c49f-4d3f-9b71-b1904f916760)
![9DAFE704-F3F3-4D69-A627-61F951172310](https://github.com/List-KR/List-KR/assets/82555878/fcda8539-ee97-4418-91d4-0cbb92c1520f)

### Browser

Brave

### Operating System

Apple iOS

### Ad-Blocker

(Other)

**Comment by piquark6046** [comment]
Currently, Brave does not support `!#include` syntax even if I want to support.
 - https://github.com/brave/adblock-resources/issues/104
