### ISSUE TITLE
IC: www.ktmmobile.com

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#796]
### URL

http://www.ktmmobile.com/main.do

### FILTERS

List-KR

스텔스 모드 켰습니다.

### Browser

Mozilla Firefox

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![12](https://github.com/List-KR/List-KR/assets/99063049/5f6945db-1dac-4c90-9d08-52b10cd4246f)

**Comment by piquark6046** [comment]
![image](https://github.com/List-KR/List-KR/assets/98787049/802bae83-65c5-460b-9f13-63545b254803)

재구현이 안됩니다. AdGuard 설정 파일을 이메일이나 GitHub 코멘트로 보내주세요.

**Comment by Seohare** [comment]
> ![image](https://user-images.githubusercontent.com/98787049/268620212-802bae83-65c5-460b-9f13-63545b254803.png)
> 
> 재구현이 안됩니다. AdGuard 설정 파일을 이메일이나 GitHub 코멘트로 보내주세요.

스텔스 모드를 아예 꺼버리면 접속이 됩니다. 스텔스 모드에 있는 옵션 모두 다 켜보시고 테스트 부탁드립니다.

**Comment by piquark6046** [comment]
[Screencast from 2023-09-18 20-45-40.webm](https://github.com/List-KR/List-KR/assets/98787049/10bb3115-dc4c-4ec3-9dc7-b927410e0a37)

첨부된 사진에 있는 IP 주소를 보니까 사설 IP 주소인데 회사용 VPN이 활성화되어 있거나 네트워크/VPN 관련 소프프트웨어이 켜져 있나요?

**Comment by Seohare** [comment]
> Screencast.from.2023-09-18.20-45-40.webm
> 
> 첨부된 사진에 있는 IP 주소를 보니까 사설 IP 주소인데 회사용 VPN이 활성화되어 있거나 네트워크/VPN 관련 소프프트웨어이 켜져 있나요?

@piquark6046  

![image](https://github.com/List-KR/List-KR/assets/99063049/b85a7d34-10db-47b7-94a2-24516675ef67)

**Comment by Seohare** [comment]
@piquark6046 엣지에서 접속하니깐 잘 되네요. 현재 제가 사용하고 있는 브라우저는 파이어폭스입니다.

![114](https://github.com/List-KR/List-KR/assets/99063049/4afb1629-0e6d-423e-bb2e-e6a161ee69cb)

**Comment by piquark6046** [comment]
한국 IP로 연결하시고 계신가요? 여전히 안됩니다.

[Screencast from 2023-09-18 21-16-54.webm](https://github.com/List-KR/List-KR/assets/98787049/e2cac0d7-e7d8-43d0-8720-69d5a51fa9d3)

**Comment by Seohare** [comment]
> 한국 IP로 연결하시고 계신가요? 여전히 안됩니다.
> 
>  Screencast.from.2023-09-18.21-16-54.webm

@piquark6046  현재 한국에서 접속 중이고, 맨 위 사진에 있는 사설IP는 일본 IP입니다.

**Comment by piquark6046** [comment]
AdGuard 설정을 내보내신 후에 AdGuard 고급 설정을 초기화해보시고 다시 시도해주시겠어요?

**Comment by Seohare** [comment]
@piquark6046  고급 설정을 초기화 하니까 사이트가 제대로 열리네요.

![301](https://github.com/List-KR/List-KR/assets/99063049/8b9fe6d0-8860-4462-a698-ee0af28f97dd)

위 사진에 나오는 기능이 문제인 것 같습니다. 위  기능 한번 켜보시고 테스트 부탁드립니다.

**Comment by piquark6046** [comment]
제가 알기로는 고급 설정에 있는 옵션을 예외를 하기 위한 규칙을 만들 수 없는 걸로 압니다.
만약 KT를 사용하신다면, 아래 issue가 반영되기 까지 기다려주세요.
 - https://github.com/AdguardTeam/CoreLibs/issues/1789
 
만약 KT 아닌 LG U+이나 SKT를 사용하신다면, 바로 스텔스 모드에 있는 DPI로 부터 보호를 켜서 적용하실 수 있습니다.

**Comment by Seohare** [comment]
@piquark6046 Anti-DPI for KT가 적용된 코어립스가 나왔다고 하는데. 아직 애드가드 나이틀리 버전에는 패치가 안 된 것 같습니다. 언제 쯤 사용할 수 있을까요?

**Comment by piquark6046** [comment]
아래 issue 처럼 1.13.68 버전 이상의 CoreLibs이 적용되면 될 것 같습니다.
https://github.com/AdguardTeam/AdguardForAndroid/issues/5042
https://github.com/AdguardTeam/AdguardForWindows/issues/4871

Slack DM으로 온 예상 시기와는 다르게 진행된 경우가 있어서 제가 정확하게 말씀드리기 어렵습니다.

**Comment by hsp1020** [comment]
> 아래 issue 처럼 1.13.68 버전 이상의 CoreLibs이 적용되면 될 것 같습니다. [AdguardTeam/AdguardForAndroid#5042](https://github.com/AdguardTeam/AdguardForAndroid/issues/5042) [AdguardTeam/AdguardForWindows#4871](https://github.com/AdguardTeam/AdguardForWindows/issues/4871)
> 
> Slack DM으로 온 예상 시기와는 다르게 진행된 경우가 있어서 제가 정확하게 말씀드리기 어렵습니다.

해당 코어립스가 적용된 안드로이드 애드가드 나이틀리로 업데이트 했음에도 똑같이 안되네요. 수정된게 맞는지 모르겠습니다.

**Comment by piquark6046** [comment]
AdGuard for Android 4.3 Nightly 19로 업데이트하셨나요?
@hsp1020

**Comment by Seohare** [comment]
@piquark6046  AdGuard for Android 4.3 Nightly 19로 업데이트 했는데도, 여전히 똑같습니다.

**Comment by piquark6046** [comment]
AdGuard Slack DM으로 문의했습니다.
