### ISSUE TITLE
AD: sportalkorea.com

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#797]
### URL

https://sportalkorea.com/

### FILTERS

listkr
마이크로쉴드
나무링크

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 10

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

레이아웃이 깨집니다.

수정 부탁드려요

![image](https://github.com/List-KR/List-KR/assets/15683789/d94218b5-6e1d-4c11-b94e-94849b5f7371)

**Comment by piquark6046** [comment]
Duplicate of List-KR/microShield#41
