### ISSUE TITLE
알약 광고가 제대로 차단되지 않습니다.

### ISSUE THREAD

**Issue by giraffebin** [List-KR/List-KR#8]
알약에서 나오는 광고들이 차단 되지 않아요. 
알약 자체에서 나오는 팝업 광고나, 일반 광고가 제대로 차단되지 않습니다.

+ 혹시 애드가드 프로그램이 geforce nvidia랑 충돌할 가능성이 있나요? 

![스크린샷(3)](https://user-images.githubusercontent.com/50972313/63653968-3130d980-c7af-11e9-9cf3-ed36366fbbfb.png)
![스크린샷(2)](https://user-images.githubusercontent.com/50972313/63653969-3130d980-c7af-11e9-8f81-887345004e74.png)

**Comment by L4by** [comment]
안녕하세요, 필터 개발 환경에 알약이 설치되어 있지 않아 재연이 어렵습니다. [이 광고 차단 방법](https://kay79.tistory.com/9)을 사용해 보시는 것을 추천드리나, 이 방법이 작동하지 않는 경우 AdGuard 필터링 로그를 참조해 재회신해주시면 검토 후 차단해보도록 하겠습니다.

+) AdGuard + nVIDIA Geforce Experience 조합이 충돌을 야기할 수 있다는 이야기는 들어본 적이 없지만, 만약 충돌이 발생한다면 AdGuard 지원팀에 문의해보시는 게 좋을 것 같습니다.

List-KR 필터에 관심을 가져 주셔서 감사합니다 :)

**Comment by L4by** [comment]
추가 제보가 없어 종결 처리합니다. 문제가 계속 나타난다면 언제든지 새 이슈로 제보 부탁드립니다.

**Comment by Chocobin** [comment]
안녕하세요, 당시 애드가드 쓴지 얼마 안되서 리포팅하면 이렇게 전부 공개되는지를 몰랐네요. 혹시 스샷을 지워주실 수 있을까요? ㅠ 제가 모르고 제 개인정보를 전혀 가리지 않고 보냈습니다
