### ISSUE TITLE
[AD] map.naver.com

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#80]
## 광고 제보
* **문제가 되는 URL**: https://map.naver.com/v5
* **URL에서 문제가 되는 요소**: 광고 노출
* **확인 가능한 스크린샷 (옵션)**:  ![Screenshot](https://user-images.githubusercontent.com/37463155/94787010-ac31de00-040c-11eb-9f30-c7543787d015.jpg)

## 시스템 환경
* **사용 중인 기기**: `Microsoft Windows 10 2004`
* **사용 중인 브라우저**: `Mozilla Firefox 81.0`
* **구독 중인 필터**: `AdGuard Base Filter, AdGuard Mobile Ads Filter, List-KR, AdGuard Tracking Protection Filter, EasyPrivacy, AdGuard DNS Filter, CommentBlock News`

**Comment by piquark6046** [comment]
`||mapservice-phinf.pstatic.net^$domain=map.naver.com`
`mapservice-phinf.pstatic.net` domain으로부터 광고 이미지를 로드하고 있습니다.

**Comment by ghost** [comment]
https://github.com/List-KR/List-KR/commit/570d9ff7bd19b98dc53276054f6ea2ec4ecfffe3 커밋에서 업데이트 하였습니다.
