### ISSUE TITLE
AD: tiktok.com

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#803]
### URL

https://www.tiktok.com/foryou

### FILTERS

List KR

### Browser

Samsung Internet

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment

![Screenshot_20231009_120213_Samsung Internet](https://github.com/List-KR/List-KR/assets/99063049/1e6aafb5-756e-423d-8e7f-dd9f4338278c)

위 사진 처럼 틱톡 사이트에서 영상 몇 개 넘기면 저런 메시지가 뜹니다. 위 메시지 제거 부탁드립니다.

**Comment by piquark6046** [comment]
제가 이전에 본 issue와 같은 인터페이스인데요. 이전의 분석에 따르면 아래 규칙을 추가하시면 숨길 수는 있으나 보실 수 있는 콘텐츠가 제한됩니다.
```adblock
tiktok.com#?#body > div[class*="-DivModalContainer"]:has(div[class*="DivInfoContainer"] + div[class*="-DivGuideBtnContainer"] > button[class*="-ButtonRefuseOrLogin"])
tiktok.com#$#body { overflow: auto !important; }
```

https://github.com/AdguardTeam/AdguardFilters/issues/161300

**Comment by Seohare** [comment]
> > 제가 이전에 본 issue와 같은 인터페이스인데요. 이전의 분석에 따르면 아래 규칙을 추가하시면 숨길 수는 있으나 보실 수 있는 콘텐츠가 제한됩니다.
> > ```
> > tiktok.com#?#body > div[class*="-DivModalContainer"]:has(div[class*="DivInfoContainer"] + div[class*="-DivGuideBtnContainer"] > button[class*="-ButtonRefuseOrLogin"])
> > tiktok.com#$#body { overflow: auto !important; }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [AdguardTeam/AdguardFilters#161300](https://github.com/AdguardTeam/AdguardFilters/issues/161300)
> 


@piquark6046 위 메시지만 제거하는 건 불가능한가요?

**Comment by piquark6046** [comment]
> 위 메시지만 제거하는 건 불가능한가요?

위에 언급한 규칙으로 메시지**만** 제거하는 건 가능합니다.
