### ISSUE TITLE
AD: 

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#807]
### URL

https://www.goodgag.net/issue/?page=1

### FILTERS

listkr
마이크로쉴드

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

체크한부분 차단하려면 어떻게 해야하는지 궁금합니다 감사합니다

![image](https://github.com/List-KR/List-KR/assets/15683789/c4ee47a6-5091-4aa7-a28b-982318a7cb82)

**Comment by piquark6046** [comment]
```adblock
#$?#meta[name="apple-itunes-app"] { remove: true; }
```
위 규칙을 추가해주세요.
