### ISSUE TITLE
AD: https://m.ruliweb.com

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#810]
### URL

https://m.ruliweb.com/community/board/300143/read/63387673

### FILTERS

listkr 
마이크로쉴드
나무링크

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

체크한 부분 제거하려면 어떻게 해야하는지 문의드립니다 감사합니다

![image](https://github.com/List-KR/List-KR/assets/15683789/4147114a-6124-4aca-ab19-0ebd21f0403f)

**Comment by piquark6046** [comment]
```adblock
#$?#meta[name="apple-itunes-app"] { remove: true; }
```
위 규칙을 추가해주세요.
