### ISSUE TITLE
github.com

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#815]
요 부분 없애려면 어떻게 해야하나요? 감사합니다

listkr 
나무링크
마이크로쉴드

아이폰 사파리

https://github.com/List-KR/List-KR

![image](https://github.com/List-KR/List-KR/assets/15683789/020b05e7-dc46-419a-8c39-3874499bf1dc)

**Comment by piquark6046** [comment]
```adblock
#$?#meta[name="apple-itunes-app"] { remove: true; }
```
https://github.com/List-KR/List-KR/issues/807 와 똑같이 고급 필터링 옵션을 키시고 위 규칙을 추가해주세요.
