### ISSUE TITLE
www.goodgag.net

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#816]
요부분 없애는 법 알려주세요 감사합니다

아이폰 애드가드프로 사파리

listkr 마이크로쉴드 나무링크

https://www.goodgag.net/issue/?page=2

![image](https://github.com/List-KR/List-KR/assets/15683789/ae6117a4-0576-4281-94f6-d07551001a8f)

**Comment by piquark6046** [comment]
```adblock
#$?#meta[name="apple-itunes-app"] { remove: true; }
```
https://github.com/List-KR/List-KR/issues/807 와 똑같이 고급 필터링 옵션을 키시고 위 규칙을 추가해주세요.
