### ISSUE TITLE
AD: fnnews.com

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#819]
### URL

https://www.fnnews.com/news/202310220630511253

https://www.fnnews.com/news/202310181041594524?pg=hot

### FILTERS

리스트케이알
마이크로쉴드
나무링크

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

광고차단 부탁드립니다 감사합니다

![image](https://github.com/List-KR/List-KR/assets/15683789/51de340e-d281-4fe7-bb8e-0a2eec37dfdb)

**Comment by piquark6046** [comment]
재구현할 수 없습니다.
AdGuard 앱에서 List-KR 필터를 끄신 후에 다시 켜보시겠어요? 그런 다음에 새로고침해보세요.

<details><summary>스크린샷</summary>

![IMG_0058](https://github.com/List-KR/List-KR/assets/98787049/06e808ed-9e8e-4e41-95a5-4b7f6022a33c)

</details>

**Comment by swbaek81** [comment]
이제 사라진거 같습니다 닫아주셔도 됩니다
