### ISSUE TITLE
AD: goal.com/kr

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#822]
### URL

https://www.goal.com/kr

### FILTERS

listkr 
마이크로쉴드
listkr dns

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

광고차단 부탁드립니다 감사합니다

![image](https://github.com/List-KR/List-KR/assets/15683789/729d525d-cdd7-46ad-977f-6afc5f97b9b8)

**Comment by piquark6046** [comment]
해당 웹 사이트는 국제 웹 사이트이라서 List-KR 필터에 관련 규칙을 추가할 수 없습니다.
아래 규칙을 사용자 규칙으로 추가해보세요:
```adblock
goal.com##div[data-testid="ad-slot"]
```

**Comment by swbaek81** [comment]
감사합니다
