### ISSUE TITLE
AD: gukjenews.com

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#824]
### URL

https://www.gukjenews.com/news/articleView.html?idxno=2852673

https://www.gukjenews.com/news/articleView.html?idxno=2852396

### FILTERS

listkr 
마이크로쉴드
listkr dns

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

왼쪽밑에 ‘광고삭제’ 란 글씨 제거 부탁드립니다 감사합니다

![image](https://github.com/List-KR/List-KR/assets/15683789/24e2ce24-dd94-4f5d-8f99-9d9a7eee25d6)

**Comment by piquark6046** [comment]
해당 요소가 제 환경에서 보이지 않습니다.
필터 업데이트를 해보시고 브라우저를 완전히 닫은 후 다시 시도해주세요.

**Comment by swbaek81** [comment]
요청주신대로 해봤는데도 NG 에요

**Comment by piquark6046** [comment]
아 뜨네요.
