### ISSUE TITLE
AD: mnews.imaeil.com

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#825]
### URL

https://mnews.imaeil.com/page/view/2023110914535446651

https://mnews.imaeil.com/page/view/2023111111254835053

### FILTERS

listkr 
마이크로쉴드
listkr dns

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

왼쪽밑에 ’광고제거‘ 글자 제거 부탁드립니다 감사합니다

![image](https://github.com/List-KR/List-KR/assets/15683789/e7749992-cf31-4067-af9c-d349ba0d061c)

**Comment by piquark6046** [comment]
해당 요소가 제 환경에서 보이지 않습니다.
필터 업데이트를 해보시고 브라우저를 완전히 닫은 후 다시 시도해주세요.

**Comment by swbaek81** [comment]
요청주신대로 해봐도 NG 에요
