### ISSUE TITLE
AD: m.inven.com

### ISSUE THREAD

**Issue by bobblun** [List-KR/List-KR#835]
### URL

https://m.inven.co.kr/board/maple/5974/2774608

### FILTERS

![Screenshot_20231115_175901_Samsung Internet](https://github.com/List-KR/List-KR/assets/49634687/96228711-1a53-4c66-b1c3-9e774d90e35c)

list-kr

### Browser

Samsung Internet

### Operating System

Android

### Ad-Blocker

AdGuard for Android

**Comment by piquark6046** [comment]
그건 인벤의 자체 배너입니다.
클릭하시면 인벤의 한 파티로 방문하게 됩니다.

**Comment by swbaek81** [comment]
저도 사용자 규칙으로 라도 없앴으면 좋겠습니다

**Comment by piquark6046** [comment]
아래 규칙을 사용해보세요:
```adblock
m.inven.co.kr##.party-banner
```

**Comment by bobblun** [comment]
해결 완료되어 닫아둡니다
