### ISSUE TITLE
aitimes.com

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#836]
### URL

https://www.aitimes.com/

### FILTERS

리스트케이알
마이크로쉴드
나무링크

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 10

### Ad-Blocker

AdGuard for Windows

### Comment

팝업창 차단 부탁드립니다 감사합니다

![image](https://github.com/List-KR/List-KR/assets/15683789/d4960cf8-6893-4ebc-9e52-c465f32ee125)

**Comment by piquark6046** [comment]
광고는 아니라서 List-KR 필터에서는 예외 처리했습니다.
해당 요소를 숨겨지길 원하신다면, 아래 규칙을 사용해보세요:
```adblock
aitimes.com###layer-popups
```
