### ISSUE TITLE
aagag 안티 애드블락이슈

### ISSUE THREAD

**Issue by qprhvms** [List-KR/List-KR#837]
### URL

https://aagag.com/

### FILTERS

 kr: List-KR

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Comment

https://aagag.com

에서 유블락오리진 / KR필터를쓸시

코맨트색션이 안나옵니다 ㅠ 이전 쓰레드도봤찌만 해결은안되있더군요

**Comment by taeklims** [comment]
@piquark6046 안드로이드 애드가드 잘사용중에 오늘부로 또 막힌거 같습니다...

**Comment by piquark6046** [comment]
@taeklims 사용 중이신 DNS 서버와 DNS 필터를 말씀해주세요.
