### ISSUE TITLE
AD: ruliweb.com

### ISSUE THREAD

**Issue by relaxedbrownie** [List-KR/List-KR#838]
### URL

https://m.ruliweb.com/

### FILTERS

AdGuard 베이스 필터
AdGuard 모바일 광고 필터
List-KR

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

![IMG_0492](https://github.com/List-KR/List-KR/assets/126370491/c1c914a9-c471-41b9-9ca0-b2f5cb047e26)

**Comment by piquark6046** [comment]
그 자리에 원래 광고가 있어서 페이지의 맨 위로 가는 버튼을 강제로 확대시킨 상태입니다.
전에 루리웹에서 해당 버튼이 사라져서 문제를 삼는 글쓴이와 해당 버튼이 너무 크기에 문제를 삼는 글쓴이 있어서, 닫기 버튼은 유지했습니다.

추가 요청 사항이나 질문이 있으시나요?

**Comment by relaxedbrownie** [comment]
의도된 거였군요. 닫으셔도 됩니다.
