### ISSUE TITLE
IC: skyscanner.kr

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#839]
### URL

https://www.skyscanner.co.kr/transport/flights/pus/osaa/231220/231227/?adultsv2=2&cabinclass=economy&childrenv2=&ref=home&rtn=1&preferdirects=false&outboundaltsenabled=false&inboundaltsenabled=false#/details/15628-2312200845--32161-0-13068-2312201000|13068-2312271100--32161-0-15628-2312271225/index/2

### FILTERS

List KR
애드가드 베이스 필터
애드가드 모바일 광고 필터
애드가드 URL추적 보호 필터
애드가드 추적 보호 필터
애드가드 방해요소 필터
Fanboy+Easylist-Merged Ultimate List

### Browser

Samsung Internet

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment
![Screenshot_20231125_162708_Samsung Internet](https://github.com/List-KR/List-KR/assets/99063049/3ef0c443-eb34-4861-949d-b2d6ad1ff6c4)

애드가드 버전은 v4.3 나이틀리 35입니다.
위 링크에 들어가서 항공권 '선택하기'를 누르면 화면이 다음 페이지로 넘어가질 않습니다.

**Comment by piquark6046** [comment]
언급하신 필터들(`https://www.fanboy.co.nz/r/fanboy-ultimate.txt` 포함)을 모두 활성화하고 최신 nightly로 업데이트해도 증상이 구현되지 않습니다.
AdGuard for Android v4.3 nightly 38로 다시 해보시겠어요?

**Comment by Seohare** [comment]
@piquark6046  업데이트를 해봐도 안 됩니다.

**Comment by piquark6046** [comment]
삼성 인터넷 말고 다른 웹 브라우저로 해보시겠어요? 그래도 안되면,  Fanboy+Easylist-Merged Ultimate List를 끄고 다시 해보세요.

**Comment by Seohare** [comment]
@piquark6046 Fanboy+Easylist-Merged Ultimate List 끄니깐 웹 사이트가 제대로 작동합니다

**Comment by piquark6046** [comment]
그럼, EasyList 계열 문제겠네요.
