### ISSUE TITLE
IC: m.sports.naver.com

### ISSUE THREAD

**Issue by wiful10** [List-KR/List-KR#843]
### URL

https://m.sports.naver.com/video/1131955

### FILTERS

List-KR
AdGuard 베이스 필터
AdGuard DNS 필터

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

AdGuard Browser Extension

### Comment

List-KR 필터를 적용한 상황에서 네이버 스포츠의 영상을 보면 사이트 상단바가 아예 가려진채 표시됩니다.
![캡처](https://github.com/List-KR/List-KR/assets/102317996/6394a96e-b9dd-4c4d-964e-d92589ed9896)

임의로 list-kr 필터에서 
/^https:\/\/api-gw\.sports\.naver\.com\/cms\/contents\/adContents\/(?!GENERAL)/$domain=m.sports.naver.com
내용을 제거한 뒤 새로고침하니 상단바가 정상적으로 표시됐습니다.

![22](https://github.com/List-KR/List-KR/assets/102317996/fd065f9a-ecc3-4ff7-a3fa-d16245238916)

광고 차단 프로그램을 켜지 않은 상태에서 보이는 화면입니다.
![333](https://github.com/List-KR/List-KR/assets/102317996/accb9bf2-3ed5-44dd-91a8-9c71011de38c)

아무래도 저 광고를 차단하려다 상단바까지 같이 차단된 것 같습니다.

**Comment by piquark6046** [comment]
Related:
 - https://github.com/List-KR/List-KR/issues/821
 - https://github.com/AdguardTeam/AdguardFilters/issues/165214
