### ISSUE TITLE
AD: basketkorea.com

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#847]
### URL

https://basketkorea.com/news/newsview.php?ncode=1065615251402300

### FILTERS

listkr
마이크로쉴드

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 10

### Ad-Blocker

AdGuard for Windows

### Comment

광고차단 부탁드립니다 감사합니다

![image](https://github.com/List-KR/List-KR/assets/15683789/a7362566-4bde-4735-a003-b7d42e703d8b)

**Comment by piquark6046** [comment]
아래 issue와 관련된 문제 같습니다:
 - https://github.com/AdguardTeam/CoreLibs/issues/1833

지금으로써는 7.16 안정 버전을 기다리시거나, 베타 채널을 임시로 사용하시면 될 것 같습니다.

<details><summary>Screenshot</summary>
<p>

![image](https://github.com/List-KR/List-KR/assets/98787049/17b8143b-0108-494d-b58e-08a0fd1eed3c)


</p>
</details>
