### ISSUE TITLE
AD: FMkorea Mobile S

### ISSUE THREAD

**Issue by vpsxhtus** [List-KR/List-KR#851]
### URL

https://m.fmkorea.com

### FILTERS

List-KR
Youslist

### Browser

Mozilla Firefox, (Other)

### Operating System

Android

### Ad-Blocker

uBlock Origin, (Other)

### Userscript Manager

Tampermonkey

### USERSCRIPT

microShield 
NamuLink

### Comment

FMKorea 모바일 웹사이트에서 광고차단을 우회하여 광고 표출을 시도하고 있습니다.
![Uploading 1.png…]()

**Comment by piquark6046** [comment]
새롭게 뜨는 네이버 파워링크를 말씀하시는 거라면 애드쉴드가 아닙니다.

**Comment by piquark6046** [comment]
수정되었습니다. 최대 4시간 이후 부터 필터 업데이트를 하시면 정상적으로 차단이 다시 가능해집니다.

**Comment by vpsxhtus** [comment]
![image](https://github.com/List-KR/List-KR/assets/106915420/2bba63e4-4f70-4f6c-b79d-e916d0f131da)

혹시 이 광고 배너 칸은 차단이 어려운지 여쭈어봅니다.

**Comment by piquark6046** [comment]
그거 이미 했습니다.
https://github.com/List-KR/List-KR/commit/b198daa594ada587ce40386939a1c63b692af756

필터 리스트를 업데이트하셨는데도 동일하다면, jsDelivr CDN Purge API에 보낸 Purge 요청이 이상하게 처리되는 경우라서 그렇습니다.
