### ISSUE TITLE
AD: newtoki.help

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#853]
### URL

https://newtoki.help/

### FILTERS

listkr
마이크로쉴드

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 10

### Ad-Blocker

AdGuard for Windows

### Comment

광고차단 부탁드립니다. 감사합니다

![image](https://github.com/List-KR/List-KR/assets/15683789/ed0f304f-33af-48ec-aa9a-b9fe88007d54)

**Comment by piquark6046** [comment]
정보가 부족합니다. 광고가 있는 부분을 스크린샷으로 찍어서 보내주시겠어요?

**Comment by swbaek81** [comment]
![image](https://github.com/List-KR/List-KR/assets/15683789/459d0c37-60ac-4baf-85fb-6607357ecb0f)

요 정도 크기면 혹시 될까요?

**Comment by piquark6046** [comment]
제 환경에서는 빈 공백만 보입니다. 해당 웹 사이트의 TLS CA가 브라우저를 통해 누구인지 알 수 있을까요?

<details><summary>Screenshot</summary>

![Screenshot from 2023-12-15 21-25-34](https://github.com/List-KR/List-KR/assets/98787049/cefc1e9a-b2bb-4f6a-8296-929195a4ba51)


</details>

**Comment by swbaek81** [comment]
인증서 쪽 얘기 같은데, 혹시 제가 어떻게 도와 드리면 되요?

**Comment by swbaek81** [comment]
CN(일반 이름)	newtoki.help
조직 (O)	<인증서의 일부가 아님>
OU(조직 구성 단위)	<인증서의 일부가 아님>

CN(일반 이름)	Adguard Personal CA
조직 (O)	AdGuard
OU(조직 구성 단위)	<인증서의 일부가 아님>

발급 날짜	2023년 11월 25일 토요일 오후 2:04:10
만료 날짜	2024년 2월 23일 금요일 오후 2:04:09

인증서	74f7a71a0ff8c055aaee0d594fee8124c85f82ff9321d9970c012cbf76baf00d
공개 키	8ee0dc6eadee2ad6f2eb6e0e62dbe657c434393c07ea82b2ecde59fea10e51c6

![image](https://github.com/List-KR/List-KR/assets/15683789/ac025785-eace-44e2-9465-7759b2366d51)

**Comment by piquark6046** [comment]
AdGuard를 키신 상태에서 Google Chrome을 완전히 다시 시작해보시겠어요? (작업 관리자로 확인하시면 좋습니다)

**Comment by swbaek81** [comment]
광고 제거 되었습니다 감사합니다
