### ISSUE TITLE
AD: tvzota87.com

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#856]
### URL

http://tvzota87.com/
https://tvmon.help
https://bontv50.com
https://xn--cm2by8iw5h6xm8pc.com/
https://rmp11.com/
https://nanatv.net/

### FILTERS

List-KR

### Browser

Samsung Internet

### Operating System

Android

### Ad-Blocker

AdGuard for Android

**Comment by piquark6046** [comment]
아래 웹 사이트는 잘 처리됩니다. AdGuard for Android 4.3 안정 채널으로 업데이트하시고 다시 해보세요.
 - https://tvmon.help/

아래 웹 사이트는 연결할 수 없습니다. 연결 되는데 너무 오래 걸립니다.
 -  https://rmp11.com/
