### ISSUE TITLE
IC: cultureland.co.kr

### ISSUE THREAD

**Issue by relaxedbrownie** [List-KR/List-KR#857]
### URL

https://m.cultureland.co.kr/csh/cshGiftCard.do

### FILTERS

List-KR

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

![IMG_1470](https://github.com/List-KR/List-KR/assets/126370491/8cea2896-2af4-4c8c-8cca-ccec38318e3c)
네 번째 칸을 눌렀을 때 이렇게 떠야 정상인데

![IMG_1468](https://github.com/List-KR/List-KR/assets/126370491/e1482098-4b24-4d9b-a38c-a5290a522892)
List-KR을 활성화하면 아이폰 자체 키보드가 올라와요(보안 때문에 캡처 사진에서는 아이폰 키보드가 가려진 상태로 보이는데 실제로는 키보드가 올라와있음). 이렇게 아이폰 키보드가 올라오면 충전이 안 돼요. 충전하기를 눌러도 먹통이에요.

지난주인가? 정확한 시기는 모르겠지만 하여튼 얼마 전까지는 List-KR을 활성화 중인 상태에서도 정상적으로 충전했고 한 번도 문제된 적 없었는데 최근 들어서 갑자기 이러네요. List-KR이 컬쳐랜드의 보안 키패드를 차단하는 것 같습니다.

**Comment by piquark6046** [comment]
테스트하기 위해서 임의의 코드를 넣어도 가상 키보드는 뜨죠?

**Comment by relaxedbrownie** [comment]
임의의 코드라는 게 상품권 번호를 아무거나 입력해본다는 말씀인가요?? 정확히 무슨 뜻인지는 모르겠지만 그게 맞다면 가상 키보드 떠요. 그냥 마지막 칸 터치만 해도 떠야 해요.

**Comment by piquark6046** [comment]
> 임의의 코드라는 게 상품권 번호를 아무거나 입력해본다는 말씀인가요?? 

네.
