### ISSUE TITLE
IC: m.nate.com

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#860]
### URL

https://m.nate.com/

### FILTERS

리스트케이알
마이크로쉴드

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

차단되면 안되는데 이미지가 차단이 됩니다

리스트케이알 온

![image](https://github.com/List-KR/List-KR/assets/15683789/0cd84a99-f0ec-467c-9525-eb9ff6abfd90)

![image](https://github.com/List-KR/List-KR/assets/15683789/67e0a0fa-03f3-4951-a6c0-d5127dec4f9b)

리스트케이알 오프
![image](https://github.com/List-KR/List-KR/assets/15683789/120f21bc-e7ca-498b-a7f4-5557b17904b9)

![image](https://github.com/List-KR/List-KR/assets/15683789/c866381c-62ab-4d3e-8cc2-b05753d21c00)

**Comment by piquark6046** [comment]
으음... 네이트 계정이 필요해보이네요.

**Comment by swbaek81** [comment]
로그아웃 상태에서도 됩니다 제가 지금 해봤어요

**Comment by piquark6046** [comment]
패치가 잘 될지는 모르겠네요. 안되면 comment 남겨주세요.
