### ISSUE TITLE
AD: kr26.topgirl.co

### ISSUE THREAD

**Issue by baserin** [List-KR/List-KR#861]
### URL

https://kr26.topgirl.co/

### FILTERS

없음

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

AdGuard for Windows

### Comment

링크가 된 사이트에 동영상을 보려고 하는데 동영상플레이어 실행 하면 불법도박광고영상이 7초 가량 재생 됩니다. 광고영상이 안 나오게 조치 하여 주세요. 그리고 주위에 보이는 불법도박 광고도 안 보이게 해주세요
![wotndwnd009](https://github.com/List-KR/List-KR/assets/154561966/93c1bcc6-ed95-487b-a17c-517be912c74f)
![rheioewnr32kl234324](https://github.com/List-KR/List-KR/assets/154561966/49fe2b17-15d5-461f-b321-bfff6e330ae1)

**Comment by baserin** [comment]
이거 언제쯤 불법도박 광고동영상 차단이 될까요?

**Comment by piquark6046** [comment]
지금 시작하겠습니다.

**Comment by piquark6046** [comment]
> 그리고 주위에 보이는 불법도박 광고도 안 보이게 해주세요

Google Chrome 웹 브라우저를 완전히 닫고 AdGuard for Windows이 켜진 상태에서 다시 켜보세요.
작업 관리자로 교차검증하시면 좋습니다.

**Comment by baserin** [comment]
오오 됩니다 됩니다!! 처음에는 하라는대로 했는데
얼래? 안 되네 뭐징 했다가 애드가드 정보 옆에 그 업데이트 확인 버튼 누른 후 업데이트 완료 후에
하라는 방법대로 하니깐 짜잔 됐습니다. 불법도박 광고영상이 제거 되었습니다!!

오 다른 광고제거 안 되는 부분 있으면 이제 여기다가 제보 하면 되는군요. 감사합니다

그런데 깃허브 여기는 뭐하는 사이트예요?

**Comment by piquark6046** [comment]
전세계 개발자들이 사용하는 git이라는 버전 관리 시스템을 호스팅해주는 웹 사이트입니다.
그냥 개발자들의 고향이라고 생각하시면 됩니다.
자세한 정보는 Google에 '깃허브'이라고 검색해도 검색 결과가 많이 나올겁니다.
