### ISSUE TITLE
AD: kr.investing.com

### ISSUE THREAD

**Issue by relaxedbrownie** [List-KR/List-KR#862]
### URL

https://m.kr.investing.com/economic-calendar/

### FILTERS

AdGuard 베이스 필터
List-KR

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

![IMG_1593](https://github.com/List-KR/List-KR/assets/126370491/eb31a40d-d704-4ea9-8563-aa8f22dce497)

**Comment by piquark6046** [comment]
AdGuard 모바일 광고 필터를 키시면 해결되나요?

**Comment by relaxedbrownie** [comment]
어 그렇네요. 모바일 광고 필터로 지워져요. 근데 혹시 사용자 규칙으로 지우려면 어떤 규칙을 추가하면 되나요?

**Comment by piquark6046** [comment]
```adblock
m.kr.investing.com##.adDrawer
```
여기 있습니다.

**Comment by relaxedbrownie** [comment]
감사합니다. 추가 문의는 없습니다.
