### ISSUE TITLE
AD: dentalnews.or.kr/mobile/

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#863]
### URL

http://www.dentalnews.or.kr/mobile/

### FILTERS

리스트케이알
마이크로쉴드

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

광고차단 부탁드립니다 감사합니다

![image](https://github.com/List-KR/List-KR/assets/15683789/6e97cf89-bafb-47a8-a84f-093d341beb63)

**Comment by piquark6046** [comment]
패치를 다운로드하신 후에 leftover (빈 공간)이 있으면 말씀해주세요.

**Comment by swbaek81** [comment]
3곳에 빈공간이 생깁니다

![image](https://github.com/List-KR/List-KR/assets/15683789/508e5141-b65e-487d-94b3-b79a36c6a0ee)

![image](https://github.com/List-KR/List-KR/assets/15683789/9445f6e3-6734-4bd0-98ff-75b90d30d4c3)

![image](https://github.com/List-KR/List-KR/assets/15683789/5480ff78-c850-4f53-8b61-49065b2202ea)
