### ISSUE TITLE
AD: https://m.fmkorea.com/ 파워광고를 삭제해 주세요

### ISSUE THREAD

**Issue by baserin** [List-KR/List-KR#866]
### URL

https://m.fmkorea.com/

### FILTERS

없음

### Browser

(Other)

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment

에펨코리아의 파워광고를 삭제해 주세요.
![Screenshot_20231223_155849_One UI Home](https://github.com/List-KR/List-KR/assets/154561966/b507d5c2-12c7-4c79-9dca-ca88663987da)
![Screenshot_20231223_155925_NAVER](https://github.com/List-KR/List-KR/assets/154561966/49bca630-d32a-4561-be17-bbe3131c9e24)
![Screenshot_20231223_155858_NAVER](https://github.com/List-KR/List-KR/assets/154561966/8f91fda5-7c35-4e09-9d31-bf68d225ffe7)

**Comment by baserin** [comment]
링크 된 사이트 사용한 어플은 네이버 어플 입니다.

**Comment by piquark6046** [comment]
네이버 앱으로 하시면 네이버 앱이 HTTPS 필터링을 거부하기 때문에 되지 않습니다. 이는 유니콘 프로도 마찬가지 입니다.
Google Chrome 등 웹 브라우저를 사용해주세요.

**Comment by piquark6046** [comment]
@baserin
