### ISSUE TITLE
www.chosun.com

### ISSUE THREAD

**Issue by lidarbtc** [List-KR/List-KR#867]
### URL

https://www.chosun.com/economy/market_trend/2023/12/23/CLPVEFKWYNG4HE3FVC3W3WW6W4/

### FILTERS

List-KR

### Browser

Mozilla Firefox

### Operating System

Ubuntu

### Ad-Blocker

uBlock Origin

### Comment

![스크린샷 2023-12-23 16-04-57](https://github.com/List-KR/List-KR/assets/97009593/2dfe0fa4-a25a-40f9-a65d-45fa2d5b9c0a)

Ads(subscription offers) in bottom of article.

**Comment by piquark6046** [comment]
Did you mean that '1개월 무료 구독' is an advert?

**Comment by lidarbtc** [comment]
> Did you mean that '1개월 무료 구독' is an advert?

Yes

**Comment by piquark6046** [comment]
It is not an advertisement. It is a newsletter banner.
