### ISSUE TITLE
App store: 1609906813

### ISSUE THREAD

**Issue by rulekak** [List-KR/List-KR#869]
### URL

cashwalk.com

### FILTERS

모바일 다 켜놓고 씀
dns 켜놓고 씀

### Browser

(Other)

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

![1a](https://github.com/List-KR/List-KR/assets/90678061/e1ce5c79-26dd-4763-b6ae-480895dc1d73)
캐시워크앱 처음에 접속할때 팝업창이 뜸

**Comment by lidarbtc** [comment]
해당 팝업 광고 내용은 `https://settings.cashwalk.io/cashwalk/ios/notice/notice2_main`를 통해 전달되며, 이미지는 `https://images.cashwalk.io/0_admin/notice/1702969772231_noticeImage`를 통해 전달됩니다.

두 도메인 `settings.cashwalk.io`와 `images.cashwalk.io` 같은 경우 앱 기능에서 필수적인 역할을 하므로, 도메인 기반 차단인 dns 차단으로는 차단이 어려울것 같습니다.

첫번째 url 응답중 일부입니다.

```json
{
      "state" : 1,
      "id" : "main_1702969772979_ios",
      "position" : "main",
      "url" : "inner:\/\/quiz?id=1702969772231",
      "endDate" : "2999-12-31T14:59:59.000Z",
      "os" : "ios",
      "title" : "이것만으로 불면증을 개선할 수 있다고요?",
      "date" : "2023-12-19T07:09:32.973Z",
      "image" : "https:\/\/images.cashwalk.io\/0_admin\/notice\/1702969772231_noticeImage",
      "startDate" : "2023-12-20T09:30:00.000Z",
      "targetName" : "이것만으로 불면증을 개선할 수 있다고요?",
      "targetId" : "1702969772231"
}
```

해당 광고의 응답을 확인할 수 있습니다.

**Comment by piquark6046** [comment]
하지만, Android 사용자가 본인의 Android 디바이스를 루팅했다면 가능하죠.

**Comment by lidarbtc** [comment]
> 하지만, Android 사용자가 본인의 Android 디바이스를 루팅했다면 가능하죠.

iOS도 트윅을 만들어서 조작 하는 방법으로 가능하겠죠. 다만 말씀주신것과 마찬가지로 out of scope라고 생각됩니다.

**Comment by piquark6046** [comment]
Android에 한해 자동화된 클릭으로 광고를 스킵해보자는 의견은 있습니다. ( https://github.com/AdguardTeam/AdguardForAndroid/issues/5092 )

>  Android 사용자가 본인의 Android 디바이스를 루팅했다면 가능하죠.

제 말은, AdGuard for Android에는 AdGuard TLS 인증서를 시스템 Root CA에 넣어 비-브라우저 앱들에 대해 HTTPS 필터링을 진행할 수 있습니다. 아주 out of scope라고 생각하지는 않습니다.

**Comment by lidarbtc** [comment]
#652
#645
#211

해당 이슈들을 참조하여 [답변](https://github.com/List-KR/List-KR/issues/869#issuecomment-1868493344) 했습니다.

**Comment by piquark6046** [comment]
알겠습니다.
