### ISSUE TITLE
IC: inven.co.kr

### ISSUE THREAD

**Issue by relaxedbrownie** [List-KR/List-KR#870]
### URL

https://www.inven.co.kr/webzine/news/?site=lol

### FILTERS

List-KR

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

![IMG_1946](https://github.com/List-KR/List-KR/assets/126370491/81a00759-944d-4211-8ea4-7af62fc3c767)
iOS뿐만 아니라 다른 기기에서도 PC 페이지로 접속하면 List-KR 필터가 이미지를 오차단함

**Comment by piquark6046** [comment]
이미 2시간 전에 수정했습니다. https://github.com/List-KR/List-KR/commit/2f18e7a2f615f3514a83904d1839ec9d14d42b08
필터를 업데이트해주세요.

**Comment by relaxedbrownie** [comment]
아 그렇군요. 필터 업데이트는 아직 안 되는 거 같아요.

**Comment by relaxedbrownie** [comment]
고쳐진 거 확인했습니다.
