### ISSUE TITLE
AD:  https://www.fmkorea.com/

### ISSUE THREAD

**Issue by baserin** [List-KR/List-KR#872]
### URL

https://www.fmkorea.com/

### FILTERS

![FVJLFXJE](https://github.com/List-KR/List-KR/assets/154561966/aac1a518-58df-46a1-be24-4bbf5e8f40cd)

사진 참조 바래요.

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

AdGuard for Windows

### Comment

에펨코리아 크롬으로 나오는 광고 삭제 부탁 드립니다.
![ADRRRRRRR](https://github.com/List-KR/List-KR/assets/154561966/5b4c68db-9e20-4c47-8b53-4c2ff0d9026a)
![ADRRRR333123](https://github.com/List-KR/List-KR/assets/154561966/ce8a24d9-4577-44dc-8615-99ab6843b99f)

**Comment by baserin** [comment]
![ADRRRR355555555555555](https://github.com/List-KR/List-KR/assets/154561966/75685e23-aa2d-4d93-856a-2e6c525b766a)

이 부분에도 광고가 노출이 됩니다.

**Comment by piquark6046** [comment]
에펨코리아에 연결하셨을 때 웹 브라우저에서는 TLS CA가 뭐라고 하던가요?

**Comment by baserin** [comment]
해결 완료 되었습니다.
애드가드 설정을 다시 하였더니, 광고가 더 이상 나오지를 않습니다. 감사합니다.
