### ISSUE TITLE
AD: CHZZK

### ISSUE THREAD

**Issue by bobblun** [List-KR/List-KR#873]
### URL

https://m.chzzk.naver.com/

### FILTERS

list kr
마이크로쉴드

### Browser

(Other)

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment

![Screenshot_20231231_225026](https://github.com/List-KR/List-KR/assets/49634687/067712d1-3e23-4dad-ae16-c91ad68a82b6)

치지직 어플리케이션에도 광고가 추가되었습니다
모바일 웹에서는 저 광고가 아직 보이지는 않는 것 같은데 앱에서는 보이는군요 (위에 올려둔 사이트)

치지직 앱에서 HTTPS 트래픽 필터링이 아직 가능해서 광고 차단이 가능할 것 같은데 차단 가능할까요

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/commit/6debdc10401183eb65f501092002c408e791d609
4일 전에 이미 했습니다. 그리고 치지직 앱을 보니까 앱에 대한 HTTPS 필터링이 불가능해보입니다.
