### ISSUE TITLE
AD: 네이버 카페 "앱 배너" 광고

### ISSUE THREAD

**Issue by bobblun** [List-KR/List-KR#875]
### URL

https://cafe.naver.com/anycallusershow/4626701

### FILTERS

list kr
마이크로쉴드

### Browser

(Other)

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment

![294757030-1fba38ca-f4d3-4bed-9d8e-e6b9cb3ad561](https://github.com/List-KR/List-KR/assets/49634687/9baf79e5-2fb3-4c1f-8df1-4fe09b5dc960)

네이버 카페 내의 배너 구좌에 설치된 광고는 열매 1 이상 랭킹인 경우에만 차단됩니다. 라고 list kr 설명에는 나와있던데

모바일 웹사이트나 데스크탑 웹사이트는 배너 광고도 차단이 잘 되더군요

하지만 네이버 카페 앱은 광고가 그대로 나오더군요

네이버 카페 앱은 https 필터링 적용도 안되는 것 같고.. 카페 내 자체 배너 광고는 차단할 방법이 없을까요?

||cafeptthumb-phinf.pstatic.net/*_banner

로도 안되더라고요

**Comment by piquark6046** [comment]
없습니다. 네이버 카페 앱이 HTTPS 필터링을 거부해서 안됩니다.

**Comment by piquark6046** [comment]
단, Android 루팅을 통한 방법이 있는 것 같습니다만, 루팅할 때 삼성 갤럭시 스마트폰을 사용하시면 삼성 Knox가 영구 손상되어서 삼성 갤럭시만의 가치를 잃게됩니다.
