### ISSUE TITLE
AD: https://www.inven.co.kr

### ISSUE THREAD

**Issue by Melon394** [List-KR/List-KR#878]
### URL

![Screenshot_20240117_162047_Samsung Internet](https://github.com/List-KR/List-KR/assets/156186083/87f17698-38b4-42d2-98fa-a642ddb982cd)
https://www.inven.co.kr

![Screenshot_20240117_162158_Samsung Internet](https://github.com/List-KR/List-KR/assets/156186083/047c68b2-c334-461a-b99d-73b8f32e8072)
https://m.fmkorea.com/
상단 공지사항 오차단

![Screenshot_20240117_162108_Samsung Internet](https://github.com/List-KR/List-KR/assets/156186083/4af38269-efeb-427b-8e13-f9ff53dfc078)
https://m.ruliweb.com/hobby/board/1002

![Screenshot_20240117_162328_PayboocISP](https://github.com/List-KR/List-KR/assets/156186083/eb0ae3b8-bf49-49af-bfb9-7bdb503325c5)
![Screenshot_20240117_162339_PayboocISP](https://github.com/List-KR/List-KR/assets/156186083/673f9455-24cb-4c42-86d5-a4f5d7df13c4)
https://play.google.com/store/apps/details?id=kvp.jjy.MispAndroid320

혜택-참여적립 탭 안 보임
쇼핑적립 탭에서 경유적립 안됨

### FILTERS

Adguard Base Filter
List-KR
microshield

### Browser

Google Chrome

### Operating System

Android

### Ad-Blocker

AdGuard for Android

**Comment by piquark6046** [comment]
인벤
Duplicate of https://github.com/List-KR/microShield/issues/61

**Comment by piquark6046** [comment]
펨코: 광고나 방해 요소가 아닙니다.
루리웹: 전에 맨 위로 올라가는 버튼이 OLED 디스플레이에서 번인을 일으킨다고 닫기 버튼을 다시 표시해달라는 포스트가 있었습니다.
페이북: 새 issue를 만들어주세요.

**Comment by Melon394** [comment]
펨코는 동그라미 친 부분에 나와야 할 공지사항이 오차단되고 있다고 말씀드린 것입니다.

**Comment by Melon394** [comment]
> 펨코: 광고나 방해 요소가 아닙니다. 루리웹: 전에 맨 위로 올라가는 버튼이 OLED 디스플레이에서 번인을 일으킨다고 닫기 버튼을 다시 표시해달라는 포스트가 있었습니다. 페이북: 새 issue를 만들어주세요.

펨코는 동그라미 친 부분에 나와야 할 공지사항이 오차단되고 있다고 말씀드린 것입니다.

**Comment by piquark6046** [comment]
> 펨코는 동그라미 친 부분에 나와야 할 공지사항이 오차단되고 있다고 말씀드린 것입니다.

AdGuard for Android를 꺼도 공지 사항이 없는데요.

**Comment by piquark6046** [comment]
```adblock
@@||api-ao-list.adison.co^$app=kvp.jjy.MispAndroid320
```
위 규칙으로 페이북 문제가 해결되나요?

**Comment by Melon394** [comment]
> ```
> @@||api-ao-list.adison.co^$app=kvp.jjy.MispAndroid320
> ```
> 
> 위 규칙으로 페이북 문제가 해결되나요?

네 참여적립란 잘 보입니다.



> > 펨코는 동그라미 친 부분에 나와야 할 공지사항이 오차단되고 있다고 말씀드린 것입니다.
> 
> AdGuard for Android를 꺼도 공지 사항이 없는데요.

공지가 있을 때 제보했어야 했는데
지금은 공지가 없는 상태네요.

**Comment by piquark6046** [comment]
수정했습니다.

**Comment by relaxedbrownie** [comment]
> ```
> @@||api-ao-list.adison.co^$app=kvp.jjy.MispAndroid320
> ```
> 
> 위 규칙으로 페이북 문제가 해결되나요?

혹시 이 규칙은 나중에 포함하실 생각이신가요? 아니면 계속 사용자 규칙으로 쓸까요? 저도 불편했던 부분이라 페이북 이용할 때 애드가드를 잠시 끄고 사용했거든요.

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/878#issuecomment-1898493091

https://github.com/List-KR/List-KR/commit/f3ea8c41c8346fbe0ef920d352ec4922f5707286 때 추가했었습니다.
Android 유저라면 패치를 사용하실 수 있습니다. 만약, iOS 유저라면, Apple 정책으로 인해 아래 DNS 규칙을 DNS 허용 리스트에 추가해 모든 앱에 대해 차단을 해제하셔야 합니다.
```adblock
@@||api-ao-list.adison.co^
```
