### ISSUE TITLE
IC: e-himart.co.kr

### ISSUE THREAD

**Issue by relaxedbrownie** [List-KR/List-KR#880]
### URL

http://m.e-himart.co.kr/

### FILTERS

AdGuard 베이스 필터
List-KR

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

![IMG_2645](https://github.com/List-KR/List-KR/assets/126370491/8e100301-cbff-4a79-866f-53d44dc8d8df)
List-KR을 켰을 때

![IMG_2646](https://github.com/List-KR/List-KR/assets/126370491/ae513e06-a03a-4985-b63b-9f660ab313f2)
List-KR을 껐을 때

배너가 통째로 사라집니다. 애초에 태생이 쇼핑몰이라서 저걸 광고로 보긴 어렵지 않나 싶어요.

**Comment by relaxedbrownie** [comment]
![IMG_3776](https://github.com/List-KR/List-KR/assets/126370491/c960874b-0876-4a9a-a2a4-5c79192b74b9)
여전히 배너가 잘려서 화면이 이상하게 표시됩니다.

**Comment by piquark6046** [comment]
고쳤습니다. 다른 문제가 발생하면 새로 열어주세요.
