### ISSUE TITLE
AD: humorpick.com

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#882]
### URL

https://humorpick.com/bbs/board.php?bo_table=humor&wr_id=302452

### FILTERS

리스트케이알
마이크로쉴드

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

광고차단 부탁드립니다 감사합니다

![image](https://github.com/List-KR/List-KR/assets/15683789/b9235aab-5cb7-4f8d-9cd1-bfeb408cb6af)

![image](https://github.com/List-KR/List-KR/assets/15683789/b944d773-3f6b-4fae-a7b2-35bba2cb0dcd)

**Comment by piquark6046** [comment]
구독 URL를 사용하시지 마시고 빌트인되어 있는 List-KR 필터를 사용해보세요.

**Comment by swbaek81** [comment]
빌트인 필터On 상태에서, 캡처한거에요

**Comment by piquark6046** [comment]
잊어버려서 죄송합니다만, 재구현이 안됩니다.
필터를 업데이트하시고 다시 해보시겠어요?

<details><summary>Screenshot</summary>
<p>

![IMG_0072](https://github.com/List-KR/List-KR/assets/98787049/3525813f-50b7-438d-9a15-6f329ed39543)


</p>
</details>

**Comment by swbaek81** [comment]
지금은 잘 됩니다 닫아주세요
