### ISSUE TITLE
AD: namu.wiki

### ISSUE THREAD

**Issue by Melon394** [List-KR/List-KR#883]
### URL

https://www.namu.wiki

### FILTERS

Adguard Base Filter
List-KR
Adguard DNS Filter

microshield
namulink

### Browser

Google Chrome, Naver Whale

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment

광고 있던 자리에 빈 공간이 남습니다
기기해상도에 따라 광고 레이아웃에 차이가 있는 것 같습니다

일반문서의 경우
고해상도 기기 - 상단의 문서 항목명 아래¹ 일반광고 빈공간, 목차 아래²에는 원래 광고 없음
폰 - ¹자리에 파워링크(0.5초쯤 파워링크 보였다가 사라짐, 공백x), ²에 일반광고 빈공간

메인페이지, 분류:, 틀:로 분류되는 문서들에서는 기기해상도 무관하게 ¹에 일반 광고가 있었던 빈공간 남음

그리고 최근변경이랑 나무뉴스란은 광고는 아니지만 거슬리는데 차단규칙을 알 수 있을까요?

**Comment by piquark6046** [comment]
@Melon394 필터 업데이트해보시고 다시 해보세요.

**Comment by Melon394** [comment]
> @Melon394 필터 업데이트해보시고 다시 해보세요.

최신버전이 2.0.17.50 맞나요? 아직 그대로입니다

**Comment by piquark6046** [comment]
그럼, 문제가 되고 있는 부분에 대해 스크린샷들을 보내주세요.

**Comment by Melon394** [comment]
![0005](https://github.com/List-KR/List-KR/assets/156186083/9601d171-32ab-4716-a502-d4d8f9a72707)

![0006](https://github.com/List-KR/List-KR/assets/156186083/fbe69119-6543-47d8-bbe9-c02ad6228d05)

**Comment by Melon394** [comment]
> 그럼, 문제가 되고 있는 부분에 대해 스크린샷들을 보내주세요.

![0005](https://github.com/List-KR/List-KR/assets/156186083/6aca930a-1bd4-489e-a345-c6b66b9c56d8)
![0006](https://github.com/List-KR/List-KR/assets/156186083/0e90b7e1-785b-4484-8045-c6bcabd9505b)
![0007](https://github.com/List-KR/List-KR/assets/156186083/55608dc7-3930-412b-b723-ac48e73ba0d0)

원래 광고 있던 자리입니다

**Comment by piquark6046** [comment]
Google Chrome 데스크톱을 사용하신다면, `chrome://inspect`에 들어가셔서 나무위키가 열린 탭을 inspect해보세요.
그 다음에, 다음 selectors들이 작동하는 지 확인해주세요:
```
article div[class*=" "]:has(> span + ul > li) ~ div div + div[class*=" "]:has(iframe[id^="google_ads_"])
article > div[class]:not([class*=" "]) ~ div[class*=" "]:has(iframe[id^="google_ads_"])
```

**Comment by piquark6046** [comment]
@Melon394

**Comment by Melon394** [comment]
@piquark6046 


나무위키:대문 - 나무위키
https://namu.wiki/w/%EB%82%98%EB%AC%B4%EC%9C%84%ED%82%A4:%EB%8C%80%EB%AC%B8

https://5a8953c16185bf2c75ceb19abb4451b1.safeframe.googlesyndication.com/safeframe/1-0-40/html/conta…
https://5a8953c16185bf2c75ceb19abb4451b1.safeframe.googlesyndication.com/safeframe/1-0-40/html/conta…

https://5a8953c16185bf2c75ceb19abb4451b1.safeframe.googlesyndication.com/safeframe/1-0-40/html/conta…
https://5a8953c16185bf2c75ceb19abb4451b1.safeframe.googlesyndication.com/safeframe/1-0-40/html/conta…

https://gum.criteo.com/syncframe?origin=publishertag&topUrl=namu.wiki#{%22uid%22:{%22origin%22:0},%2…
https://gum.criteo.com/syncframe?origin=publishertag&topUrl=namu.wiki#{%22uid%22:{%22origin%22:0},%2…

https://www.google.com/recaptcha/api2/aframe
https://www.google.com/recaptcha/api2/aframe

https://5a8953c16185bf2c75ceb19abb4451b1.safeframe.googlesyndication.com/safeframe/1-0-40/html/conta…
https://5a8953c16185bf2c75ceb19abb4451b1.safeframe.googlesyndication.com/safeframe/1-0-40/html/conta…

https://gum.criteo.com/syncframe?origin=publishertag&topUrl=namu.wiki#{%22uid%22:{%22origin%22:0},%2…
https://gum.criteo.com/syncframe?origin=publishertag&topUrl=namu.wiki#{%22uid%22:{%22origin%22:0},%2…

https://e09d1487fa5261a94c0e2fc84d73ad60.safeframe.googlesyndication.com/safeframe/1-0-40/html/conta…
https://e09d1487fa5261a94c0e2fc84d73ad60.safeframe.googlesyndication.com/safeframe/1-0-40/html/conta…

https://s.amazon-adsystem.com/iu3?cm3ppd=1&d=dtb-pub&csif=t&dl=n-smaato_n-mediagrid_n-LoopMe_pm-db5_…
https://s.amazon-adsystem.com/iu3?cm3ppd=1&d=dtb-pub&csif=t&dl=n-smaato_n-mediagrid_n-LoopMe_pm-db5_…

https://www.google.com/recaptcha/api2/aframe
https://www.google.com/recaptcha/api2/aframe

https://ads.pubmatic.com/AdServer/js/user_sync.html?kdntuid=1&p=157512
https://ads.pubmatic.com/AdServer/js/user_sync.html?kdntuid=1&p=157512

https://acdn.adnxs.com/dmp/async_usersync.html
https://acdn.adnxs.com/dmp/async_usersync.html

https://acdn.adnxs.com/dmp/async_usersync.html
https://acdn.adnxs.com/dmp/async_usersync.html

https://acdn.adnxs.com/dmp/async_usersync.html
https://acdn.adnxs.com/dmp/async_usersync.html

https://eb2.3lift.com/sync?
https://eb2.3lift.com/sync?

https://eus.rubiconproject.com/usync.html
https://eus.rubiconproject.com/usync.html

https://prebid.a-mo.net/isyn?gdpr_consent=&gdpr=0&us_privacy=&gpp=&gpp_sid=
https://prebid.a-mo.net/isyn?gdpr_consent=&gdpr=0&us_privacy=&gpp=&gpp_sid=

https://ads.pubmatic.com/AdServer/js/user_sync.html?kdntuid=1&p=157512
https://ads.pubmatic.com/AdServer/js/user_sync.html?kdntuid=1&p=157512


inspect 누르고 뭘 봐야하는 건지 모르겠어서 긁어왔는데 작동하는 건가요? pc는 빈공간이 제대로 차단이 되었네요

**Comment by piquark6046** [comment]
아뇨.
먼저, AdGuard for Android를 여시고 설정 -> 일반 -> 고급 -> 로우 레벨 설정 -> scriptlet 디버깅 활성화를 켜주세요.
android debugging bridge를 컴퓨터에 설치하시고 스마트폰에 있는 개발자 설정에서 USB 디버깅을 키신 후에 아래 스크린샷을 참고해보세요.
<details><summary>Screenshot</summary>


![Screenshot from 2024-01-28 21-34-11](https://github.com/List-KR/List-KR/assets/98787049/4c70af0f-abcf-4a2c-8ddb-a9663fe30427)


</details> 

그 다음에, 콘솔 탭에 들어가셔서 `AdGuard content-script`가 있는지 확인해주세요.

**Comment by sssh7710** [comment]
속도도 상당히 느려졌어요
모바일도 마찬가지 입니다.

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/883#issuecomment-1916988064
그건 NamuLink 유저스크립트의 문제 아닌가요?
그 쪽으로 리포트해주세요.

**Comment by piquark6046** [comment]
@Melon394 필터 업데이트가 있으니 업데이트해주세요.
https://github.com/List-KR/List-KR/commit/159630fa1af81b95ee4194a15044f6386d994731
https://github.com/List-KR/List-KR/commit/78e5ee3b505a1fa04bc18feca9b456da0831d779

**Comment by Melon394** [comment]
@piquark6046
2.0.17.56 기준 상기 증상(빈 공간) 그대로입니다

**Comment by piquark6046** [comment]
@Melon394 
2.0.17.57 이상이여야 합니다. 다시 시도 해주세요.

**Comment by Melon394** [comment]
@piquark6046 
2.0.17.57 입니다. 제대로 해결되었습니다. 감사합니다
