### ISSUE TITLE
Bug: meeco.kr

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#884]
### URL

https://meeco.kr/

### FILTERS

애드가드 off + 마이크로쉴드
또는
애드가드 youslist on + 마이크로쉴드

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Userscript Manager

quoid/userscripts

### USERSCRIPT

마이크로쉴드

### Comment

애드가드 off + 마이크로쉴드 = NG
애드가드 youslist on + 마이크로쉴드 = NG
애드가드 listkr on + 마이크로쉴드 = OK

위의 2개 상황에서 아래와같은 NG 가 발생합니다
특히 애드가드를 off 한상태에서 마이크로쉴드만 on해도 NG 입니다

youslist와 마이크로쉴드 조합으로 사용하고 싶은데 NG가 발생합다

![image](https://github.com/List-KR/microShield/assets/15683789/f657606c-c173-4575-9141-27073050cf90)

**Comment by piquark6046** [comment]
@swbaek81 List-KR 필터 끄시고 하신거예요?
그 팝업은 애드쉴드하고 관계가 없는데요.

**Comment by piquark6046** [comment]
@yous
