### ISSUE TITLE
IC: naverpay

### ISSUE THREAD

**Issue by Melon394** [List-KR/List-KR#885]
### URL

https://new-m.pay.naver.com/historybenefit/eventbenefit?category=quickreward

### FILTERS

AdGuard Base Filter
List-KR

### Browser

Google Chrome

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment

![0027](https://github.com/List-KR/List-KR/assets/156186083/a65427ba-043b-4a53-ae0b-f5d85be77097)

**Comment by piquark6046** [comment]
지금 밖에 있어서 지금은 볼 수 없습니다. 곧 보겠습니다.
지금 비활성화하셔야 한다면, 아래 규칙을 사용해보세요:
```adblock
new-m.pay.naver.com#@#div[class*="_banner_"]
```
