### ISSUE TITLE
IC: naverpay, samsung browser translator language pack

### ISSUE THREAD

**Issue by Melon394** [List-KR/List-KR#886]
### URL

https://new-m.pay.naver.com/historybenefit/paymenthistory?page=1

internet-extension://khmmfcceknncifmkiimjnnjldibgajpl/pages/common.html#/option

https://www.totaladblock.com

### FILTERS

Adguard Base, DNS, annoyances Filter
List-KR
microshield
Namulink

### Browser

Samsung Internet

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment

https://new-m.pay.naver.com/historybenefit/paymenthistory?page=1
결제내역에서 주문목록을 누르면 나오는 결제상세정보페이지가 깨집니다

internet-extension://khmmfcceknncifmkiimjnnjldibgajpl/pages/common.html#/option
삼성브라우저-확장기능-번역기 앱의 설정페이지에서 언어팩이 다운로드되지 않습니다

https://www.totaladblock.com
접속이 되지 않습니다

**Comment by piquark6046** [comment]
> https://www.totaladblock.com/

먼저, 답변 드리겠습니다. 해당 앱이 시스템 업데이트이라고 주장하면서 해당 앱을 설치하라고 하는 스팸을 뿌리고 있어서 EasyList에서 차단되었습니다.

**Comment by piquark6046** [comment]
> https://new-m.pay.naver.com/historybenefit/paymenthistory?page=1
결제내역에서 주문목록을 누르면 나오는 결제상세정보페이지가 깨집니다

위 내용이 네이버 페이 -> 결제 내역 -> 각 구매한 상품의 주문 상세 (초록색 글씨)를 눌러서 들어간 페이지가 맞나요?

**Comment by piquark6046** [comment]
@Melon394

**Comment by Melon394** [comment]
@piquark6046 
네 결제상세 버튼 눌러서 나오는 페이지가 맞습니다

**Comment by piquark6046** [comment]
삼성 브라우저 번역기의 언어 패키지 다운로드 오류 문제는 Android의 VPN API 가 사용 중일 때 다운로드가 안되는 것 같습니다.
이 경우에는 다운로드하실 때, AdGuard 같은 Android의 VPN API를 사용하는 모든 앱을 일시적으로 끄셔야 할 것 같습니다.

**Comment by piquark6046** [comment]
네이버 페이 문제에 대해 재구현이 안됩니다.

<details><summary>Screenshot</summary>


![Screenshot_20240131_210724_Chrome](https://github.com/List-KR/List-KR/assets/98787049/6837e7fa-c1ac-4c3a-9d6a-f3870c67e653)


</details>

**Comment by Melon394** [comment]
@piquark6046 
제가 커스텀한 DNS의 문제였네요. 죄송합니다.

덕분에 문제가 모두 해결되었습니다.
