### ISSUE TITLE
AD: laftel.net

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#887]
### URL

https://laftel.net/player/40153/44455

### FILTERS

List-KR
Fanboy+Easylist-Merged Ultimate List
AdGuard base filter

### Browser

Mozilla Firefox, Samsung Internet

### Operating System

Microsoft Windows 11, Android

### Ad-Blocker

AdGuard for Windows, AdGuard for Android

### Comment

라프텔에서 무료로 시청이 가능한 영상 중에 나오는 광고는 잘 차단이 되고 있습니다.
아래 사진에 나오는 방해 요소들 제거 부탁드리고, 중간에 잠깐 나오는 검은색 화면(광고 노출 흔적?)도 제거 부탁드립니다.

![Screenshot_20240205_163227_Samsung Internet](https://github.com/List-KR/List-KR/assets/99063049/352f7b8a-75a2-4123-bc08-0ecac658af61)
![Screenshot_20240205_163452_Samsung Internet](https://github.com/List-KR/List-KR/assets/99063049/06457b16-f6ea-455c-9df5-ba5bfed46861)
![Screenshot_20240205_163502_Samsung Internet](https://github.com/List-KR/List-KR/assets/99063049/505f8323-bdf7-432e-ab7d-7d869b26fc6f)
![Screenshot_20240205_163548_Samsung Internet](https://github.com/List-KR/List-KR/assets/99063049/9cd67002-30f8-49e0-9235-fa7540e06f36)

**Comment by piquark6046** [comment]
`Fanboy+Easylist-Merged Ultimate List` 는 활성화하실 필요가 없어보입니다.

**Comment by Seohare** [comment]
@piquark6046 
문제가 아직 해결이 되지 않은 것 같네요.
![Screenshot_20240303_200612_Samsung Internet](https://github.com/List-KR/List-KR/assets/99063049/d1027968-c8f8-46aa-a877-72f20e639a65)

**Comment by piquark6046** [comment]
늦게 고쳐서 죄송합니다. 생각보다 scriptlet 규칙 레벨로 고치기 어렵게 되어 있어서 지연되었습니다.
