### ISSUE TITLE
IC: 11st.co.kr

### ISSUE THREAD

**Issue by AndyH0ng** [List-KR/List-KR#888]
### URL

https://www.11st.co.kr/products/5820578418

### FILTERS

List-KR

### Browser

Apple Safari

### Operating System

Apple macOS

### Ad-Blocker

AdGuard for Mac

### Comment

List-KR을 켜면 l_product_buy_wrap의 width가 계속 늘어나서 무한 스크롤됩니다

**Comment by piquark6046** [comment]
`.l_product_buy_wrap` element의 `width`가 스크롤해도 `HTMLElement.prototype.style` 로써 존재하지 않습니다.

**Comment by AndyH0ng** [comment]
캐시가 꼬였나봅니다 이제 잘 되네요
