### ISSUE TITLE
AD: bbs.ruliweb.com

### ISSUE THREAD

**Issue by craftingmod** [List-KR/List-KR#889]
### URL

https://bbs.ruliweb.com/community/board/300143

### FILTERS

Adguard Base Filter
AdGuard Tracking Protection filter
AdGuard Annoyances filter
List-KR

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![240209-060535](https://github.com/List-KR/List-KR/assets/9389278/fe3a9c56-88b7-4314-82d2-b36a3c034611)

Twitch AD is on right of BEST header.

This should be removed with this rule.
```
bbs.ruliweb.com###board_top > .row > .border_box
```

**Comment by piquark6046** [comment]
루리웹 커뮤니티 사이트 운영자의 트위치/치치직 스트리밍 아닌가요?

**Comment by craftingmod** [comment]
커뮤니티 사이트 자체 트위치/치지직 스트리밍 광고이긴 합니다만 원래 구글 애드센스 광고가 있었던 위치였으며 위 HTML 요소의 목적(베스트)에 전혀 상관없는 외부 링크를 달아 광고로 제보했습니다.
사이트 운영진이 직접 건 광고는 List-KR에서 제외인가요?

**Comment by piquark6046** [comment]
다시 나타나면 숨기겠습니다.

**Comment by craftingmod** [comment]
이슈 닫아두겠습니다!

**Comment by piquark6046** [comment]
아뇨. 열어 두시고 다시 나타나면 맨션해주세요.
수정을 안했던 이유는 제가 휴가 중이라서 그렇습니다.

**Comment by piquark6046** [comment]
수정되었습니다.
