### ISSUE TITLE
AD: bj.afreecatv.com

### ISSUE THREAD

**Issue by bobblun** [List-KR/List-KR#893]
### URL

https://bj.afreecatv.com/sccha21

### FILTERS

list kr
마이크로쉴드

### Browser

(Other)

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment

afreecaTV 개인방송국 홈페이지에 새로운 광고가 추가되었습니다

브라우저, afreecaTV 앱에서 동시에 광고가 삽입되었습니다

![Screenshot_20240311_013826_AfreecaTV](https://github.com/List-KR/List-KR/assets/49634687/56043f59-13b0-40da-a012-867994e7888d)

**Comment by piquark6046** [comment]
아프리카 앱에서는 어려울 것 같네요. 정확히는 사진만 차단이 가능할 것 같습니다.

**Comment by bobblun** [comment]
> 아프리카 앱에서는 어려울 것 같네요. 정확히는 사진만 차단이 가능할 것 같습니다.

사진 차단이라도 업데이트 부탁드립니다

**Comment by piquark6046** [comment]
수정되었습니다.
