### ISSUE TITLE
IC: anilife.live

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#896]
### URL

https://anilife.live/h/live?p=9b84276e-901c-4951-a4c2-c7a0f559482b&a=none&player=jawcloud

### FILTERS

List-KR

### Browser

Mozilla Firefox, Samsung Internet

### Operating System

Microsoft Windows 11, Android

### Ad-Blocker

AdGuard for Windows, AdGuard for Android

### Comment

스텔스 모드(모든 옵션 활성화)를 키고, 위 링크에서 영상을 재생하면 영상 재생이 안 됩니다.

**Comment by piquark6046** [comment]
AdGuard 베이스 필터를 활성화하셨나요?

**Comment by Seohare** [comment]
@piquark6046  네

**Comment by piquark6046** [comment]
존재하지 않는 URL이라고 뜹니다.
그나저나, AdGuard for Windows를 nightly 채널로 업데이트하신 후에 KT의 DPI로부터 보호 기능도 키셨나요?

<details><summary>Screenshot</summary>
<p>

![image](https://github.com/List-KR/List-KR/assets/98787049/ea2b19a9-31ec-47fa-9e0d-614d7454aa33)


</p>
</details>

**Comment by Seohare** [comment]
@piquark6046 
PC는 KT의 DPI보호 기능도 켰습니다. 하지만 KT의 DPI보호 기능이 문제는 아닌 것 같습니다.
홈에 들어가서 아무 애니메이션이나 재생해 보세요.
영상 제공 회사 서버는 클라우드 비디오로 선택해 주세요.

**Comment by piquark6046** [comment]
> PC는 KT의 DPI보호 기능도 켰습니다. 하지만 KT의 DPI보호 기능이 문제는 아닌 것 같습니다.

KT 통신사를 사용하시며 검열된 웹 사이트에 방문하시는게 아니라면, 안 키시고 nightly로 업데이트를 안하셔서도 괜찮습니다.
nightly 채널은 불안정한 테스트 버전을 배포하는 채널이라서 위 상황이 아니시면, 권장하지 않습니다.

> 홈에 들어가서 아무 애니메이션이나 재생해 보세요.
영상 제공 회사 서버는 클라우드 비디오로 선택해 주세요.

잘 재생이 됩니다. 재생 후 일정 시간이 지나야 되나요?

<details><summary>Screencast</summary>
<p>

[Screencast from 2024-03-15 21-23-10.webm](https://github.com/List-KR/List-KR/assets/98787049/224a00f3-4a95-40b6-989e-19867fff0c8b)


</p>
</details>

**Comment by piquark6046** [comment]
모바일 네트워크인가요?

**Comment by Seohare** [comment]
> 모바일 네트워크인가요?

아니요. WIFI로 연결했습니다.

**Comment by piquark6046** [comment]
Android 폰에서 AdGuard VPN을 포함한 VPN 연결 없이 스텔스 모드 옵션을 모두 키고 삼성 브라우저로 재생했는데 문제가 발생하지 않았습니다.

AdGuard for Android의 설정 파일을 내보셔서 filters@adguard.com 으로 이메일을 보내주시겠어요?
내보내기 항목 중에서 라이선스 정보가 제외되어 있는지 확인해주세요.

**Comment by Seohare** [comment]
보냈습니다

**Comment by piquark6046** [comment]
수정했습니다.

**Comment by piquark6046** [comment]
1시간 뒤에 필터 업데이트를 하셨는데도 안되면, 말씀해주세요.

**Comment by Seohare** [comment]
@piquark6046 
네, 제가 보낸 메일, 파일은 삭제 부탁드립니다.

**Comment by piquark6046** [comment]
삭제했습니다.
