### ISSUE TITLE
AD: www.youtube.com

### ISSUE THREAD

**Issue by bobblun** [List-KR/List-KR#897]
### URL

https://www.youtube.com/watch?v=Cc6ISdIcQ3M

### FILTERS

list-kr
adguard base filter

### Browser

Google Chrome

### Operating System

Microsoft Windows 10

### Ad-Blocker

AdGuard for Windows

### Comment

동영상 재생 광고는 안 나옵니다
동영상 우측의 유튜브 배너 광고가 뚫린것 같네요

![제보](https://github.com/List-KR/List-KR/assets/49634687/74f065cb-d1c4-4522-a985-1a50630282bf)

**Comment by piquark6046** [comment]
```adblock
youtube.com##body > ytd-app > #content.ytd-app.style-scope > ytd-page-manager#page-manager.ytd-app.style-scope > ytd-watch-flexy.ytd-page-manager.style-scope > #columns.ytd-watch-flexy.style-scope > #secondary.ytd-watch-flexy.style-scope > #secondary-inner.ytd-watch-flexy.style-scope > #related.ytd-watch-flexy.style-scope > ytd-watch-next-secondary-results-renderer.ytd-watch-flexy.style-scope > #items.ytd-watch-next-secondary-results-renderer.style-scope > ytd-item-section-renderer > #contents > ytd-ad-slot-renderer
```

위 규칙이 동작하나요?

**Comment by bobblun** [comment]
> ```
> youtube.com##body > ytd-app > #content.ytd-app.style-scope > ytd-page-manager#page-manager.ytd-app.style-scope > ytd-watch-flexy.ytd-page-manager.style-scope > #columns.ytd-watch-flexy.style-scope > #secondary.ytd-watch-flexy.style-scope > #secondary-inner.ytd-watch-flexy.style-scope > #related.ytd-watch-flexy.style-scope > ytd-watch-next-secondary-results-renderer.ytd-watch-flexy.style-scope > #items.ytd-watch-next-secondary-results-renderer.style-scope > ytd-item-section-renderer > #contents > ytd-ad-slot-renderer
> ```
> 
> 위 규칙이 동작하나요?

동작합니다 list-kr엔 없는 규칙인 것 같은데 추가 해주시면 될 것 같습니다

**Comment by piquark6046** [comment]
https://github.com/easylist/easylist/commit/b7d7ad73
EasyList에서 변경사항이 적용되었으며, 최대 1시간 이후에 AdGuard 베이스 필터에 적용될 예정입니다.
1시간 뒤에 필터를 업데이트해주세요.
