### ISSUE TITLE
AB: chmodi.tistory.com

### ISSUE THREAD

**Issue by bobblun** [List-KR/List-KR#899]
### URL

https://chmodi.tistory.com/173

### FILTERS

list kr
adguard 방해요소 필터
Adblock Warning Removal List

### Browser

Samsung Internet

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment

![Screenshot_20240319_223833_Samsung Internet](https://github.com/List-KR/List-KR/assets/49634687/f9ea61fe-b1aa-4b3b-8415-41d6c64bdce7)

Adblock Warning Removal List 필터를 켜둔 상태에서도 상기 사이트 애드블록 차단 해제 창이 활성화 됩니다

**Comment by piquark6046** [comment]
Adblock Warning Removal List은 한국어권 웹 사이트에 있는 안티-애드블록에 대해 처리하지 않는 경우가 대다수라서 필요하지 않아 보입니다.

**Comment by bobblun** [comment]
> Adblock Warning Removal List은 한국어권 웹 사이트에 있는 안티-애드블록에 대해 처리하지 않는 경우가 대다수라서 필요하지 않아 보입니다.

그렇다면 tistory 쪽으로 안티-애드블록 google 애드센스 추가해주셨으면 합니다

**Comment by piquark6046** [comment]
Adblock Warning Removal List 를 비활성화해보세요. 해당 필터가 언급하신 팝업을 트리거하는 것 같습니다.

**Comment by bobblun** [comment]
> Adblock Warning Removal List 를 비활성화해보세요. 해당 필터가 언급하신 팝업을 트리거하는 것 같습니다.

비활성화하니 나오지 않습니다

**Comment by piquark6046** [comment]
자세히 보니까 List-KR 필터가 이미 관련해서 안티-애드블록을 처리하고 있었네요.
닫아도 되겠습니까?

**Comment by bobblun** [comment]
> 자세히 보니까 List-KR 필터가 이미 관련해서 안티-애드블록을 처리하고 있었네요. 닫아도 되겠습니까?

예
