### ISSUE TITLE
https://lover.ne.kr:124/ 이 사이트의 광고가 차단이 되지 않습니다.

### ISSUE THREAD

**Issue by thatembezzler** [List-KR/List-KR#9]
[https://lover.ne.kr:124/bbs/view.php?id=sitelink7&page=1&sn1=&divpage=1&category=1&sn=off&ss=on&sc=on&select_arrange=headnum&desc=asc&no=32541](url)
접속하면 약 5초 정도 기다린 후에 뜨는 "①"을 클릭해서 다른 페이지로 연결되는 방식의 사이트인데요. 애드블럭을 활성화시켜 놓으면 "①"을 클릭해도 아무 반응이 없습니다. 필터 업데이트로 해결해 주실 수 있을까요?

**Comment by ghost** [comment]
안녕하세요, 본 필터에서는 해당 사이트 및 관련 요소에 대해 특별한 차단 규칙을 적용하고 있지 않으나, AdGuard 베이스 필터의 다음과 같은 규칙이 문제가 되는 것으로 보입니다.

`lover.ne.kr#%#//scriptlet("prevent-window-open")`

본 필터의 문제가 아니기 때문에 AdGuard 필터에 직접 이슈를 개설한 상황이며 (https://github.com/AdguardTeam/AdguardFilters/issues/39995) 추후 필터 업데이트 및 문제 해결 여부는 해당 이슈를 확인해주시기 바랍니다.

List-KR 필터 개발에 관심을 가져 주셔서 감사합니다 :)
