### ISSUE TITLE
AD: tvwiki.io

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#900]
### URL

https://tvwiki.io/ott_drama/10939#20010e60b40799e80ff2cb741dd2820cFOAmAVhP

### FILTERS

List-KR

### Browser

Mozilla Firefox, Samsung Internet

### Operating System

Microsoft Windows 11, Android

### Ad-Blocker

AdGuard for Windows, AdGuard for Android

### Comment

![Screenshot_20240321_213611_Samsung Internet](https://github.com/List-KR/List-KR/assets/99063049/087481ff-bc80-4ddd-8741-deb6f04d2bc8)
![Screenshot_20240321_213620_Samsung Internet](https://github.com/List-KR/List-KR/assets/99063049/1a658b2c-04ef-42cb-853d-896f7cf84b6e)

**Comment by piquark6046** [comment]
@haksal732 안되는데요.

<details><summary>Screenshot</summary>
<p>


![image](https://github.com/List-KR/List-KR/assets/98787049/138189c2-2bfc-401c-bfe2-02603cf4f52a)

</p>
</details>

**Comment by Seohare** [comment]
https://tvwiki.io/ 으로도 접속이 안 되나요?

**Comment by piquark6046** [comment]
네. 안됩니다.

**Comment by piquark6046** [comment]
네. 안됩니다.

**Comment by Seohare** [comment]
@piquark6046 
저는 접속이 되네요.
KT망 사용중입니다.
![Screenshot_20240322_114702_Samsung Internet](https://github.com/List-KR/List-KR/assets/99063049/d3493372-1993-4514-980f-505ec20550eb)

**Comment by piquark6046** [comment]
업데이트했습니다.

**Comment by piquark6046** [comment]
안되면, 말씀해주세요.
