### ISSUE TITLE
dcinside.com

### ISSUE THREAD

**Issue by relaxedbrownie** [List-KR/List-KR#902]
### URL

https://m.dcinside.com/board/stockus?s_type=subject_m&serval=%EB%B0%98%EB%8F%84%EC%B2%B4&recommend=&headid=

### FILTERS

[Safari 필터]
AdGuard 베이스 필터
AdGuard 기타 방해 요소 필터
List-KR

[DNS 필터]
KOR: List-KR DNS

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

![IMG_4887](https://github.com/List-KR/List-KR/assets/126370491/eb83cde9-e4a8-4165-b273-66d39bd6f7e7)

**Comment by piquark6046** [comment]
재구현이 안됩니다. iOS 설정에서 AdGuard의 Safari 확장 프로그램이 모두 켜져있는지 확인해주세요.
켜져 있는데 안된다면, 허용 목록을 확인해주세요.
허용 목록에도 없다면, List-KR 필터를 잠시 끄신 후에 다시 켜주세요.

**Comment by relaxedbrownie** [comment]
캐시나 쿠키도 영향이 있는 걸까요? 개인정보 보호 모드에서 접속해보니까 저도 구현 안 되네요. 그래서 dcinside 웹 사이트 데이터를 제거해봤는데 이제 기본 탭에서도 구현 안 되네요. 일단 애드가드 설정 문제는 아니었고 문제도 해결했습니다.

**Comment by piquark6046** [comment]
그럼, 닫겠습니다.

**Comment by piquark6046** [comment]
> 캐시나 쿠키도 영향이 있는 걸까요?

아마 Safari 캐시 문제 같네요. 정확하지는 않습니다.

**Comment by relaxedbrownie** [comment]
이거 광고가 다시 뜨길래 개인정보 보호 모드에서 테스트해봤는데 최초 1회만 안 뜨는 거고 두 번째 검색부턴 바로 광고 뜹니다(새로고침 해도 구현됨). 확인 부탁드립니다.

**Comment by Howu48** [comment]
@piquark6046 
동일 이슈 발생합니다.
- iOS Safari (맥에서 유저 에이전트를 `Safari - iOS 17 - iPhone`으로 바꿔도 동일)
- 사이트 내 검색창에서 검색했을 때
```html
<section class="grid clkhigh">
    <h3 id="view_title" class="power-tit" style="display: block;">파워 링크 광고</h3>
		<ul class="power-lst" id="p53fbb8" style="">
```

**Comment by piquark6046** [comment]
수정했습니다. 최대 4시간 이후에 필터를 업데이트해주세요.

**Comment by Howu48** [comment]
@piquark6046 
현재 동일 이슈 계속 재현됩니다

![image](https://github.com/List-KR/List-KR/assets/75659325/96a00d72-b62e-4d7c-9d17-69823c9d9bf3)


<img width="470" alt="스크린샷 2024-03-29 오후 9 15 19" src="https://github.com/List-KR/List-KR/assets/75659325/42d872e9-8032-434b-9242-511b9cffa82b">

**Comment by relaxedbrownie** [comment]
저도 그렇습니다.

**Comment by piquark6046** [comment]
수정되었습니다.
@relaxedbrownie @Howu48
