### ISSUE TITLE
AD: damoang.net

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#920]
### URL

https://damoang.net/

### FILTERS

listkr
마이크로쉴드
나무링크

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

광고차단 부탁드립니다 감사합니다

![image](https://github.com/List-KR/List-KR/assets/15683789/cd233d9e-7d12-4d74-a560-4a75e41d9997)

**Comment by piquark6046** [comment]
빈 공간이 업데이트 이후에 발생한다면, 알려주세요.

**Comment by swbaek81** [comment]
빈 공간이 남습니다 

![image](https://github.com/List-KR/List-KR/assets/15683789/99d04710-e741-46a8-af8d-f37028f6a4e5)

**Comment by piquark6046** [comment]
수정되었습니다.
