### ISSUE TITLE
IC: fourfourtwo.co.kr

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#922]
### URL

https://www.fourfourtwo.co.kr/news/articleView.html?idxno=51624#_across

### FILTERS

listkr 
마이크로쉴드
나무링크

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

영상을 볼수 없습니다 감사합니다

![image](https://github.com/List-KR/List-KR/assets/15683789/78fda582-659e-4435-88b6-c2ea7ceeffc5)

**Comment by piquark6046** [comment]
네이버 TV iframe입니다. 다음 문제와 동일한 이슈로 보아 닫겠습니다.
https://github.com/AdguardTeam/AdguardForiOS/issues/2315
