### ISSUE TITLE
AD: vietnamguide.co.kr

### ISSUE THREAD

**Issue by swbaek81** [List-KR/List-KR#925]
### URL

https://vietnamguide.co.kr/%EB%B2%A0%ED%8A%B8%EB%82%A8-%EC%97%AC%ED%96%89/

### FILTERS

listkr 
마이크로쉴드
나무링크

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

하단bar 차단 부탁드립니다 감사합니다

![image](https://github.com/List-KR/List-KR/assets/15683789/128356dd-c9df-43d6-a8f6-38679c8ca308)

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/commit/22836019e1f53369e7cf2dae54392f82db110707
