### ISSUE TITLE
IC: m.humoruniv.com

### ISSUE THREAD

**Issue by ted1117** [List-KR/List-KR#927]
### URL

https://m.humoruniv.com/board/read.html?table=pds&number=1307679

### FILTERS

 * Adguard 모바일 광고 필터
 * List-KR

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

제목 아래, 본문 위에 위치한 글 작성자 정보가 아예 안 보입니다.
![IMG_7793](https://github.com/List-KR/List-KR/assets/24566481/35798de1-3c72-48b7-924f-f684921b7983)
![IMG_7794](https://github.com/List-KR/List-KR/assets/24566481/d95894fd-415f-4452-b1ea-3b54023d0043)

**Comment by piquark6046** [comment]
가장 가능성이 높아보이는 규칙을 비활성화했습니다. 나중에 해결되었는지 확인해주세요.

**Comment by ted1117** [comment]
23일 업데이트 했습니다만 여전히 발생합니다.
![IMG_0300](https://github.com/List-KR/List-KR/assets/24566481/62e18fbc-bcd1-4ef5-ab50-46bd84948f60)
Adguard for iOS 기준, List-KR 버전이 2.0.18.45입니다.

**Comment by piquark6046** [comment]
@ted1117 고쳤습니다. 업데이트해주세요.
