### ISSUE TITLE
IC: chzzk.naver.com

### ISSUE THREAD

**Issue by ccxty9** [List-KR/List-KR#928]
### URL

https://chzzk.naver.com/live/abcdef

### FILTERS

ublock origin 기본 필터
list kr

### Browser

Mozilla Firefox, Google Chrome

### Operating System

Microsoft Windows 11

### Ad-Blocker

uBlock Origin

### Comment

치지직 생방송 시청 시 광고 차단은 되지만, 채팅을 치려고 하면 채팅 입력이 되지 않고 오류가 뜸.

![rrwer](https://github.com/List-KR/List-KR/assets/131260360/807e1928-ddbe-4d25-ad67-a52e3995cc5a)

**Comment by piquark6046** [comment]
스크린샷 보내주세요.

**Comment by piquark6046** [comment]
재구현이 안됩니다.

<details><summary>Screencast</summary>
<p>

[Screencast from 2024-05-21 19-18-09.webm](https://github.com/List-KR/List-KR/assets/98787049/9baad1ba-7a77-4191-be2b-eda90a4766fd)


</p>
</details>

**Comment by ccxty9** [comment]
> 재구현이 안됩니다.
> 
> Screencast

![ttt](https://github.com/List-KR/List-KR/assets/131260360/8784cb8f-2804-4d4a-b962-a746d1247541)

참고로 유블럭 오리진을 치지직 사이트에서 예외로 하고, 크롬 확장 프로그램인 치지직 광고 차단을 설치하면 정상적으로 동작.

그리고 채팅을 쳐야(엔터까지) 막혔다고 뜹니다.

**Comment by Countryroad96** [comment]
제 증상으로는 방송 진입 시 간헐적으로 채팅오류 안내가 나오며, 정상적으로 채팅이 보이더라도 몇 초 이후로는 채팅이 더 이상 갱신이 안되는 현상이 일어납니다.

<details>
<summary>Screencast</summary>

[Honeycam 2024-05-21 20-45-42.webm](https://github.com/List-KR/List-KR/assets/70177603/9ae2000c-82c4-4a2d-ad9f-2e2c59aed038)
</details>

**Comment by ccxty9** [comment]
> 제 증상으로는 방송 진입 시 간헐적으로 채팅오류 안내가 나오며, 정상적으로 채팅이 보이더라도 몇 초 이후로는 채팅이 더 이상 갱신이 안되는 현상이 일어납니다.
> 
> Screencast

광고 차단 사용 시 그 상황이 맞습니다. 채팅창은 갱신이 안 되고, 그 상태에서 아무 글 쓰고 엔터치면 오류 어쩌고 메시지 뜨고

**Comment by piquark6046** [comment]
오늘 다시 테스트해보겠습니다만, 최소 1개월 이내로 Brave 브라우저를 제외한 거의 모든 Chromium 계열 브라우저 [^1] 에서 uBlock Origin와 AdGuard 브라우저 확장 프로그램을 포함한 애드블록들의 몇 시간 내로 진행될 수 있는 짧은 기간 필터 리스트 업데이트가 중단되어 추후에 이러한 문제가 발생하여 필터 리스트에서 수정되어도 적용 기간이 몇 주가 지연될 수 있습니다.
따라서, [StackSocial에서 AdGuard 라이선스를 구입](https://www.stacksocial.com/sales/adguard-family-plan-lifetime-subscription)하시거나 Brave 또는 Firefox 브라우저로 이주하셔야 합니다.

[^1]: Google Chrome, Microsoft Edge 와 네이버 웨일 포함

참고로, 저는 AdGuard에 재직 중입니다.

**Comment by tenthousandcoffins** [comment]
It looks like the issue comes from the following commit https://github.com/List-KR/List-KR/commit/3a5ad09194e768918e21781db199faa03d8d6a35

I don't have any issue after removing the following entry.
`chzzk.naver.com##+js(nano-stb, noPingPong||(e.sendPing, *, 0.001)`

**Comment by piquark6046** [comment]
```adblock
 chzzk.naver.com##+js(nano-stb, noPingPong||(e.sendPing, *, 0.001)
```
~~위 필터와 동일하게 표현된 규칙이 AdGuard에도 적용되어 있는데, AdGuard를 사용하시고 계시는 시청자분들이 문제 보고를 안하시는 것을 보아, uBlock Origin의 scriptlet 문제 같습니다.~~
~~일단, 비활성화되었습니다.~~

그냥 필터 이슈 같네요.
