### ISSUE TITLE
AD: www.cvsnet.co.kr

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#934]
### URL

https://www.cvsnet.co.kr/reservation-inquiry/delivery/index.do

### FILTERS

List-KR

### Browser

Mozilla Firefox, Samsung Internet

### Operating System

Microsoft Windows 11, Android

### Ad-Blocker

AdGuard for Windows, AdGuard for Android

### Comment

![Screenshot_20240613_173245_Samsung Internet](https://github.com/List-KR/List-KR/assets/99063049/378f43f4-7b94-4a90-8416-cb8574d61276)

**Comment by Seohare** [comment]
@piquark6046  광고가 다시 노출됩니다. 수정부탁드립니다.

**Comment by piquark6046** [comment]
@haksal732 Android에서요? 스크린샷도 보내주세요.

**Comment by Seohare** [comment]
@piquark6046 네
![Screenshot_20240619_202531_Samsung Internet](https://github.com/List-KR/List-KR/assets/99063049/9ce5ac99-bf0c-44e5-a675-74c66231b3de)

**Comment by piquark6046** [comment]
수정되었습니다. 최대 4시간 뒤에 업데이트를 해주세요.
