### ISSUE TITLE
IC: anilife.app, arca.live

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#946]
### URL

https://arca.live/b/leagueoflegends/110567908?p=1

https://anilife.app/content/101/%EC%9B%90%ED%94%BC%EC%8A%A4

### FILTERS

List-KR

### Browser

Mozilla Firefox, Samsung Internet

### Operating System

Microsoft Windows 11, Android

### Ad-Blocker

AdGuard for Windows, AdGuard for Android

### Comment

스텔스 모드에 있는 리퍼러 숨기기를 활성화 하고 사용자 정의 리퍼러에 값을 넣으면 아래 사진 처럼 이미지가 표시가 안 됩니다. 
![Screenshot_20240706_120809_Samsung
Internet](https://github.com/List-KR/List-KR/assets/99063049/db41b0d7-4fa1-411e-a448-ccf1472fa28e)
![Screenshot_20240706_120845_Samsung Internet](https://github.com/List-KR/List-KR/assets/99063049/114424d9-b5d1-4e23-8a41-78bfb07bbbdf)

`@@||ac-p1.namu.la/$stealth=referrer,image`
`@@||cdn.anilife.live/assets/img/$stealth=referrer,image`
이 두 규칙 필터에 반영 부탁드립니다.

**Comment by piquark6046** [comment]
이미 있는 것으로 알고 있는데 최적화 당해서 리스트에 없나 봅니다.
