### ISSUE TITLE
AB: m.humoruniv.com

### ISSUE THREAD

**Issue by Gray-HM** [List-KR/List-KR#947]
### URL

https://m.humoruniv.com/

### FILTERS

AdGuard 베이스 필터
AdGuard 모바일 광고 필터
List-KR
YousList
AdGuard DNS filter 
List-KR DNS

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for Safari, AdGuard DNS

### Comment

파워링크가 메인 화면이랑 게시글에 다수 나옵니다.

![photo_6104771557558696535_y](https://github.com/user-attachments/assets/511964fe-756c-44c4-bfdb-8d578cb08c54)
![photo_6104771557558696534_y](https://github.com/user-attachments/assets/25316a5d-09ab-4a0e-b141-bc41017cb9e3)
![photo_6104771557558696533_y](https://github.com/user-attachments/assets/5d57846f-3419-4c29-a01d-fab289b16f67)
![photo_6104771557558696532_y](https://github.com/user-attachments/assets/56c55a8a-541c-46a3-a9d8-10e68c4f6728)
![photo_6104771557558696531_y](https://github.com/user-attachments/assets/6c9c9bcd-d35d-4832-95ad-9e74edd2b18e)
![photo_6104771557558696530_y](https://github.com/user-attachments/assets/f8d5b7ce-3429-4bb6-a4fd-03dfee164169)

**Comment by piquark6046** [comment]
재구현이 안됩니다. 지금도 재구현이 가능하신가요?

**Comment by Gray-HM** [comment]
네네 지금도 그러네요

**Comment by piquark6046** [comment]
Safari 탐색 기록을 모두 삭제해보신 뒤에 다시 확인해주세요.

**Comment by Gray-HM** [comment]
동일합니다 ㅠㅠ

**Comment by piquark6046** [comment]
완전히 재구현이 되지 않습니다.

**Comment by Gray-HM** [comment]
AdGuard 추적 보호 필터를 끄니까 해결 되었습니다. 
같이 쓰면 안되나보네요. 
대응 감사합니다.
