### ISSUE TITLE
AD: 통신사 PASS 앱, 금융 앱, 토스 앱의 광고들은 차단이 불가능한가요?

### ISSUE THREAD

**Issue by gminshin** [List-KR/List-KR#951]
### URL

LG U+ Pass, KB국민은행, 하나카드, 토스

### FILTERS

List-KR
List-KR DNS

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

Adguard for IOS 사용중입니다. 불가능한지 궁금하네요.

**Comment by piquark6046** [comment]
HTTPS 패킷 내부에 존재해 도메인으로 차단할 수 없다면 플렛폼 한계상 iOS에서 처리가 불가능합니다.
Android에서는 가능하나 루팅이 필요하나, 루팅을 하게 되면 앞써 언급하신 앱들에서 접근을 제한시키게 될 겁니다.

**Comment by piquark6046** [comment]
토스 앱은 제가 Android에서 사용해서 확인해봤는데 HTTPS 패킷 내부에 있는 것 같아 처리가 힘들어보입니다.

**Comment by fifoqueue** [comment]
stale
