### ISSUE TITLE
AD: m.fmkorea.com 파워링크

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR#953]
### URL

https://m.fmkorea.com/

### FILTERS

List-KR
AdGuard Base filter, AdGuard Mobile Ads filter
AdGuard Tracking Protection filter
AdGuard Social Media filter

### Browser

Apple Safari

### Operating System

Apple iOS

### Ad-Blocker

AdGuard for iOS/iOS Pro

### Comment

iOS에서 Safari 확장기능으로 AdGuard(무료버전, 4.5.5)사용중입니다.
위 사이트에서 파워링크가 차단 되지 않은 지 꽤 된 것 같은데, 관련 issue가 없어 글 작성합니다.

![1](https://github.com/user-attachments/assets/62511cdb-3ecf-4d05-a2e9-32bb3736b292)

**Comment by piquark6046** [comment]
List-KR 필터는 왜 비활성화하셨나요?
무료 버전이라면 Safari 보호 -> 고급 보호를 켜실 수 없으시나요?

**Comment by ghost** [comment]
> List-KR 필터는 왜 비활성화하셨나요? 무료 버전이라면 Safari 보호 -> 고급 보호를 켜실 수 없으시나요?

List-KR 필터 활성화 되어 있습니다.
무료버전에서는 고급 보호 사용을 못하네요.

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR/issues/953#issuecomment-2331281760
안타깝게도 무료 버전에서는 오차단 가능성이 존재하기 때문에 처리할 수 없습니다.
stacksocial 에서 저렴하게 라이선스를 구입해보세요.
