### ISSUE TITLE
AB: chzzk.naver.com

### ISSUE THREAD

**Issue by nagato7** [List-KR/List-KR#961]
### URL

chzzk.naver.com

### FILTERS

uBlock filters
AdGuard - Ads
AdGuard Tracking Protection
Adguard - Annoyances
List-KR

### Browser

Mozilla Firefox

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Comment

![치지직 광고차단 팝업](https://github.com/user-attachments/assets/8215abb1-cf69-47cc-b17b-ab9586350484)

치지직 개별 방송 채널 페이지에 들어가면 광고 차단 솔루션을 사용하고 있다는 경고 메시지가 뜹니다. 경고 메시지 외에 추가적 기능 제한은 현 시점에서 하지 않는 걸로 보입니다만, 일단 이슈에 올려 둡니다. 또한 List-KR 외의 다른 필터와는 반응하지 않는 걸로 보입니다.

**Comment by piquark6046** [comment]
Naver 로그인하셨나요?

**Comment by ccxty9** [comment]
이거 문제가 치지직 사이트에서 광고 차단 쓰고 있다고 인지하면, 저 메시지 뜨고, 기본 화질도 360p로 낮추기 때문에 불편합니다. 확인 누르고, 화질도 수동으로 올려줘야되고. 로그인을 하지 않으면 저 메시지 안 뜹니다

**Comment by piquark6046** [comment]
치지치지직 브라우저 확장 프로그램이 해당 문제를 발생시키고 있다는 말이 있던데 비활성화해보셨나요?

**Comment by ccxty9** [comment]
치직치지직이랑 상관없고 ublock origin 기준 list kr 필터 켜면 저런 창 뜨는 문제 있는 거 맞습니다.

**Comment by piquark6046** [comment]
@ccxty9 

아래 사용자 필터로 잘 숨겨지나요?
```adblock
chzzk.naver.com##div[class^="popup_dimmed__"]:has(p[class^="ad_block_text_"])
```

**Comment by ccxty9** [comment]
저 필터 추가시 기본 해상도가 360p으로 낮아지는 문제는 여전하지만, 광고차단 어쩌고 메시지 자체는 안 뜹니다.

**Comment by fli-ck** [comment]
Unable to reproduce on clean installed WIndows 10 using Edge Browser & uBlock Origin Extension.

**Comment by fli-ck** [comment]
![image](https://github.com/user-attachments/assets/c2d3a75d-9d96-4924-bfa3-6c8f1d3fd1c8)

**Comment by fli-ck** [comment]
![image](https://github.com/user-attachments/assets/11bdff05-c9e6-4142-bafa-3f04d459ed27)

Using SKT DNS.

**Comment by fli-ck** [comment]
Will test using login

**Comment by fli-ck** [comment]
![image](https://github.com/user-attachments/assets/837a95f1-a8f7-4f58-b72d-f0e48ffeb200)
Confirmed that **it is reproducible.**
Seems like the popup condition requires logged in status becuase it wants to send the Ad-blocking user's information report to the Naver's server itself.

@piquark6046 Please check our internal contacts.

**Comment by piquark6046** [comment]
로그인을 헤야 재구현이 된다고 하는 말이 있네요 내일 바로 보겠습니다

**Comment by fli-ck** [comment]
The Anti-adblock popup condition requires logged-in state since it wants Ad-blocking user's UID to be in Anti-adblock notify request mechanism.

TL;DR: Currently Naver records your ad-blocking.

**Comment by piquark6046** [comment]
수정본 올렸습니다

**Comment by ccxty9** [comment]
확인결과 완벽하게 해결되었습니다. 창 안뜨고, 저화질 자동 변경 문제 사라졌습니다.

추가로 치직치지직 이용자의 경우에는 트래커 차단이라는 옵션이 있는데, 이걸 켜면 위의 광고 차단 프로그램 메시지가 여전히 뜨는데, 이거 잘 모르는 사람도 있을 듯하니, 이 부분만 따로 알고 계시면 될 거 같습니다.

**Comment by piquark6046** [comment]
알겠습니다
