### ISSUE TITLE
애드가드앱 필터 업데이트 방법

### ISSUE THREAD

**Issue by dabin8693** [List-KR/List-KR#963]
ios, 크롬익스텐션 애드가드앱 필터 업데이트 방법이 있나요?
찾아봐도 안보여서 삭제하고 다시 까는거 말고는 방법을 모르겠네요.

**Comment by piquark6046** [comment]
AdUGard for iOS에서는 메인 화면에 있는 새로고침 버튼이 업데이트 버튼입니다.
AdGuard 브라우저 확장 프로그램에서도 동일하나, Google의 MV3 강제로 MV3 버전에서는 업데이트가 불가능합니다.

**Comment by fifoqueue** [comment]
Closed due to inactivity.
