### ISSUE TITLE
유니콘Pro에 사용자 필터가 추가 됐는데

### ISSUE THREAD

**Issue by Maccvc** [List-KR/List-KR#965]
다 꺼버리고 List-KR만 쓰고 싶은데

https://cdn.jsdelivr.net/gh/List-KR/List-KR@latest/filter-AdGuard.txt

https://cdn.jsdelivr.net/gh/List-KR/List-KR@latest/filter-uBlockOrigin.txt

둘 중에 뭘 써야할까요?

**Comment by piquark6046** [comment]
유니콘 프로는 안 지원합니다
먼저 README 파일을 읽어주십시오
