### ISSUE TITLE
NekoBox와 AdGuard 동시 사용시 아이피가 숨겨지지 않습니다.

### ISSUE THREAD

**Issue by Seohare** [List-KR/List-KR#966]
제목 그대로 입니다. 
처음에는 제대로 작동을 하다가 어느 순간 부터 갑자기 아이피가 숨겨지지 않습니다.
설정도 제대로 하였고 
ProtonVPN 일본서버에 연결 중입니다.
어디가 문제인지 알 수 있을까요,

**Comment by piquark6046** [comment]
ProtonVPN Wireguard 관리 페이지에서 만료 기간을 연장하셨나요?

**Comment by Seohare** [comment]
> ProtonVPN Wireguard 관리 페이지에서 만료 기간을 연장하셨나요?

@piquark6046 어제 새로 생성했습니다.
이상한 게 아이피가 숨겨질 때도 있고 안 숨겨질 때도 있습니다. 애드가드에서는 다 프록시를 통해 앱 라우팅을 (NekoBox제외) 모두 켰습니다.제 생각에는 버그 같네요.

**Comment by piquark6046** [comment]
> (NekoBox제외)

AdGuard 앱을 통해 라우팅 옵션을 끄셨다는 거죠?

**Comment by Seohare** [comment]
> > (NekoBox제외)
> 
> AdGuard 앱을 통해 라우팅 옵션을 끄셨다는 거죠?

@piquark6046 네, NekoBox는 껏습니다

**Comment by piquark6046** [comment]
NekoBox를 한번 다시 해보시겠어요?

**Comment by Seohare** [comment]
재설치 하라는 말씀이신가요?

**Comment by piquark6046** [comment]
네네

**Comment by Seohare** [comment]
똑같습니다. 애드가드 VPN 통합모드를 사용할 때도 같은 문제가 발생 하였는데, NekoBox도 아이피가 숨겨지지 않는 문제가 생긴걸 보니 애드가드 문제인 것 같습니다.

**Comment by piquark6046** [comment]
직접 https://github.com/AdguardTeam/CoreLibs/issues/ 에 영어로 이슈를 생성해주실 수 있으시나요?
