### ISSUE TITLE
AD: kimpga.com ,theddari.com

### ISSUE THREAD

**Issue by opeth1990** [List-KR/List-KR#969]
### URL

https://kimpga.com/

https://theddari.com/

### FILTERS

List-KR

### Browser

Naver Whale

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![화면 캡처 2024-11-15 051753](https://github.com/user-attachments/assets/1e255e59-1bfc-4663-8e73-30dc5df5a070)
![화면 캡처 2024-11-15 051911](https://github.com/user-attachments/assets/d0e8175a-c84e-4814-ba3e-129c10048c7b)

**Comment by piquark6046** [comment]
https://adguard.com/ko/test.html 에서 HTTPS 필터링이 동작인지 확인해주시겠어요?

**Comment by opeth1990** [comment]
![화면 캡처 2024-11-15 143343](https://github.com/user-attachments/assets/158dd811-b07a-4326-90f6-5e845d5cee60)
이렇게 나오네요

**Comment by piquark6046** [comment]
실제 한국 IP로 하니까 뜨네요. 모두 고쳤습니다
