### ISSUE TITLE
AD: tvroom5.org

### ISSUE THREAD

**Issue by opeth1990** [List-KR/List-KR#970]
### URL

https://tvroom5.org/

### FILTERS

List-KR

### Browser

Microsoft Edge

### Operating System

Microsoft Windows 11

### Ad-Blocker

AdGuard for Windows

### Comment

![화면 캡처 2024-11-16 022436](https://github.com/user-attachments/assets/970970e1-3cc6-40c3-ae1d-f1f184a7353f)
주소 뒷자리숫자 변경되면서 광고차단 안되는 중입니다.

**Comment by fifoqueue** [comment]
Resolved in the commit https://github.com/List-KR/List-KR/commit/70d2cbc1213705757ebdcfedfd4f51e515fa1f12

**Comment by opeth1990** [comment]
여전히 광고가 나오네요
