### ISSUE TITLE
AD: 스토브 인디 어플 홍보광고

### ISSUE THREAD

**Issue by Deathwing1999** [List-KR/List-KR#973]
### URL

https://store.onstove.com/ko

### FILTERS

애드가드 베이스 필터
애드가드 모바일광고 필터
애드가드 URL 추적필터
애드가드 추적보호 필터
애드가드 소셜미디어 필터
애드가드 일본어 필터
List-KR
애드가드 방해요소 필터
애드가드 쿠키알림 필터
애드가드 팝업필터
애드가드 모바일 앱 배너 필터
애드가드 기타방해요소 필터
애드가드 위젯필터

### Browser

Brave

### Operating System

Android

### Ad-Blocker

AdGuard for Android

**Comment by piquark6046** [comment]
스크린샷을 찍어서 보내주세요

**Comment by Deathwing1999** [comment]
![Uploading Screenshot_20241127-171131_Brave.png…]()

**Comment by Deathwing1999** [comment]
![Screenshot_20241127-171131_Brave](https://github.com/user-attachments/assets/eac1effc-4f41-45b3-a15e-3c1511983223)

가장 즐거운발견 스토브앱 저겁니다.
