### ISSUE TITLE
AD: 만개의레시피 사이트 광고

### ISSUE THREAD

**Issue by Flaymore1211** [List-KR/List-KR#974]
### URL

https://m.10000recipe.com/recipe/7039682

### FILTERS

List-KR

### Browser

Brave

### Operating System

Android

### Ad-Blocker

AdGuard for Android

### Comment

![Screenshot_20241214-164408_Brave](https://github.com/user-attachments/assets/2d655de1-e3ad-4c4d-ac76-4a1fb180e40a)
만개의 레시피라는 요리정보사이트입니다. 광고차단이 안되어서 제보드립니다. 사진은 예시입니다.

**Comment by piquark6046** [comment]
@Flaymore1211 Brave 브라우저에서 TLS CA가 누구로 되어 있나요?

**Comment by Flaymore1211** [comment]
Adguard Personal CA로 되어있고요
지금은 광고가 안보이네요
