### ISSUE TITLE
AB: chzzk.naver.com

### ISSUE THREAD

**Issue by nagato7** [List-KR/List-KR#976]
### URL

chzzk.naver.com

### FILTERS

EasyList
EasyPrivacy
Easylist - Cookie Notices
List-KR

### Browser

Mozilla Firefox

### Operating System

Microsoft Windows 10

### Ad-Blocker

uBlock Origin

### Comment

![안티 애드블럭 팝업](https://github.com/user-attachments/assets/2115758f-d248-4a58-b17a-427a495e35bf)

상기한 필터 켜고 라이브 방송 시청시 adblock을 감지한 뒤 영상을 360p로 설정함.

11월 11일자 패치(https://github.com/List-KR/List-KR/commit/f2f78d0288ad388b3f73db5890bb68948a6cfa61) 이후 해당 메시지가 사라졌였는데 추가 감지 수단을 적용한 것으로 보입니다.

**Comment by natic0309** [comment]
오늘 6시경부터  치지직  애드가드 윈도우버전에서도 동일증상있습니다

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/139af909f643a0b49a98368d034ed4c52a7d1111
https://github.com/List-KR/List-KR/commit/b136d10a69470bd4b0fd57aaa93d650ed108f180
고쳤습니다
